Imports BL
Imports DevExpress.XtraGrid.Views.Base
Imports DevExpress.XtraGrid.Views.Grid

Public Class AgencyInvoiceReport
    Dim SALEREGID As Integer
    Dim USERADD, USEREDIT, USERVIEW, USERDELETE As Boolean      'USED FOR RIGHT MANAGEMAENT
    Public multi As Boolean = False
    Public fromno, tono As Integer
    Public PARTYNAME As String
    Public TEMPINVOICENO, TEMPREGNAME As String

    Dim DTMAIL As New DataTable

    Private Sub ToolStripButton2_Click(sender As Object, e As EventArgs) Handles ToolStripButton2.Click
        Try
            Dim PATH As String = Application.StartupPath & "\Invoice Details.XLS"
            Dim opti As New DevExpress.XtraPrinting.XlsExportOptions
            opti.ShowGridLines = True
            opti.SheetName = "Invoice Details"
            gridbill.ExportToXls(PATH, opti)
            EXCELCMPHEADER(PATH, "Invoice Details", gridbill.VisibleColumns.Count + gridbill.GroupCount)
        Catch ex As Exception
            MsgBox("Invoice Details Excel File is Open, Please Close the File first then try to Export", MsgBoxStyle.Critical)
        End Try
    End Sub

    Private Sub TOOLWHATSAPP_Click(sender As Object, e As EventArgs) Handles TOOLWHATSAPP.Click
        Try
            ExportGridToPdf()

        Catch ex As Exception
            Throw ex
        End Try


    End Sub
    Private Sub ExportGridToPdf()
        Try
            Dim filePath As String = Application.StartupPath & "\AgencyInvoiceReport.pdf"
            Dim gridControlObj As DevExpress.XtraGrid.GridControl = gridbill.GridControl

            ' Adjust column widths as before
            Dim pageWidth As Integer = 1122 - 80
            Dim colCount As Integer = gridbill.Columns.Count
            Dim colWidth As Integer = pageWidth \ colCount
            For Each col As DevExpress.XtraGrid.Columns.GridColumn In gridbill.Columns
                col.Width = colWidth
            Next
            gridbill.Columns("DATE").Width = 80
            gridbill.Columns("BUYERNAME").Width = 180
            gridbill.Columns("SELLERNAME").Width = 180
            gridbill.Columns("QUALITY").Width = 100

            gridbill.OptionsPrint.AutoWidth = False
            gridbill.OptionsPrint.PrintHorzLines = True
            gridbill.OptionsPrint.PrintVertLines = True

            Dim ps As New DevExpress.XtraPrinting.PrintingSystem()
            Dim link As New DevExpress.XtraPrinting.PrintableComponentLink(ps)
            link.Component = gridControlObj

            link.Landscape = True
            link.Margins.Left = 30
            link.Margins.Right = 30
            link.Margins.Top = 30
            link.Margins.Bottom = 30
            AddHandler link.CreateDetailArea, Sub(sender As Object, e As DevExpress.XtraPrinting.CreateAreaEventArgs)
                                                  e.Graph.Font = New Font("Verdana", 2)
                                              End Sub

            link.CreateDocument()
            link.ExportToPdf(filePath)

            MessageBox.Show("PDF Exported Successfully: " & filePath)
        Catch ex As Exception
            MessageBox.Show("Export failed: " & ex.Message)
        End Try

    End Sub

    Private Sub cmdcancel_Click(sender As Object, e As EventArgs) Handles cmdcancel.Click
        Me.Close()
    End Sub

    Dim DTWHATSAPP As New DataTable
    Private Sub AgencyInvoiceReport_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Try
        Catch ex As Exception
            Throw ex
        End Try
    End Sub
    Sub fillgrid(ByVal TEMPCONDITION)
        Try
            'If USEREDIT = False And USERVIEW = False Then
            '    MsgBox("Insufficient Rights")
            '    Exit Sub
            'End If

            Dim objclsCMST As New ClsCommonMaster
            'Dim dt As DataTable = objclsCMST.search(" CAST(0 AS BIT) AS CHK, INVOICEMASTER.INVOICE_NO AS SRNO, INVOICEMASTER.INVOICE_DATE AS DATE, ISNULL(INVOICEMASTER.INVOICE_REFNO, '') AS REFNO, ISNULL(LEDGER.Acc_cmpname, '') AS NAME, ISNULL(LEDGER.Acc_add, '') AS ADDRESS, ISNULL(CITYMASTER.city_name, '') AS CITY, ISNULL(LEDGERS.Acc_cmpname, '') AS AGENTNAME,  ISNULL(INVOICE_ACKNO, '') AS ACKNO, INVOICE_ACKDATE AS ACKDATE, ISNULL(LEDGER.Acc_email, '') AS PARTYMAIL, ISNULL(LEDGER.ACC_WHATSAPPNO, '') AS PARTYWHATSAPP, ISNULL(LEDGERS.Acc_email, '')  AS AGENTMAIL, ISNULL(LEDGERS.ACC_WHATSAPPNO, '') AS AGENTWHATSAPP, ISNULL(TRANSNAME.Acc_cmpname, '') AS TRANSNAME, ISNULL(INVOICEMASTER.INVOICE_TOTALPCS, 0) AS TOTALPCS, ISNULL(INVOICEMASTER.INVOICE_TOTALMTRS, 0) AS TOTALMTRS,ISNULL(INVOICEMASTER.INVOICE_TOTALDISCAMT, 0) AS TOTALDISC,ISNULL(INVOICEMASTER.INVOICE_TOTALSPDISCAMT, 0) AS TOTALSPDISCAMT ,ISNULL(INVOICEMASTER.INVOICE_GRANDTOTAL, 0) AS GRANDTOTAL, INVOICEMASTER.INVOICE_DISPUTE AS DISPUTED, INVOICEMASTER.INVOICE_CHECKED AS CHECKED, INVOICEMASTER.INVOICE_REMARKS AS REMARKS, ISNULL(LEDGER.ACC_GSTIN, '') AS GSTIN, ISNULL(STATEMASTER.state_name, '') AS STATENAME, ISNULL(STATEMASTER.state_remark, '') AS STATECODE,ISNULL(INVOICEMASTER.INVOICE_TOTALAMT, 0) AS TOTALAMT , CASE WHEN ISNULL(INVOICEMASTER.INVOICE_SCREENTYPE, 'LINE GST') = 'LINE GST' THEN ISNULL(INVOICEMASTER.INVOICE_TOTALTAXABLEAMT, 0) ELSE ISNULL(INVOICEMASTER.INVOICE_SUBTOTAL, 0) END AS TOTALTAXABLEAMT,ISNULL(INVOICEMASTER.INVOICE_GRANDTOTAL, 0) AS GRANDTOTAL ,ISNULL(INVOICEMASTER.INVOICE_RETURN, 0) AS RETURNAMT ,ISNULL(INVOICEMASTER.INVOICE_BALANCE, 0) AS BALANCEAMT ,ISNULL(INVOICEMASTER.INVOICE_AMTREC, 0) + ISNULL(INVOICEMASTER.INVOICE_EXTRAAMT, 0)   AS RECDAMT,  ISNULL(INVOICEMASTER.INVOICE_TOTALCGSTAMT, 0) AS TOTALCGSTAMT, ISNULL(INVOICEMASTER.INVOICE_TOTALSGSTAMT, 0) AS TOTALSGSTAMT, ISNULL(INVOICEMASTER.INVOICE_TOTALIGSTAMT, 0) AS TOTALIGSTAMT, ISNULL(INVOICEMASTER.INVOICE_GDNNO, '') AS CHALLANNO, ISNULL(INVOICEMASTER.INVOICE_GDNDATE, GETDATE()) AS CHALLANDATE,ISNULL(PACKINGLEDGERS.Acc_cmpname, '') AS PACKING,ISNULL(INVOICEMASTER.INVOICE_EWAYBILLNO, '') AS EWAYBILLNO, ISNULL(TRANSNAME.ACC_CMPNAME,'') AS TRANSNAME, ISNULL(INVOICE_LRNO,'') AS LRNO,INVOICEMASTER.INVOICE_LRDATE AS LRDATE, ISNULL(INVOICE_BALENOFROM,0) AS NOOFBALES, ISNULL(PURLEDGERS.ACC_CMPNAME,'') AS PURNAME , INVOICEMASTER.INVOICE_PONO AS SONO, ISNULL(INVOICEMASTER.INVOICE_CHARGES, 0) AS CHARGES, RECDATE.RECDATE, ISNULL(LOCALTRANSLEDGERS.ACC_CMPNAME,'') AS LOCALTRANSNAME, ISNULL(INVOICEMASTER.INVOICE_APPLYTCS,0) AS APPLYTCS, ISNULL(INVOICEMASTER.INVOICE_TCSPER,0) AS TCSPER, ISNULL(INVOICEMASTER.INVOICE_TCSAMT,0) AS TCSAMT, ISNULL(INVOICE_IRNNO,'') AS IRNNO, ISNULL(INVOICE_DOCKETNO,'') AS DOCKETNO, ISNULL(INVOICE_DOCKETDATE, GETDATE()) AS DOCKETDATE, ISNULL(INVOICE_COURIER,'') AS COURIER, ISNULL(FROMCITYMASTER.city_name, '') AS FROMCITY, ISNULL(TOCITYMASTER.city_name, '') AS TOCITY, ISNULL(USER_NAME,'') AS USERNAME, ISNULL(INVOICEMASTER.INVOICE_INITIALS,'') AS INITIALS, ISNULL(INVOICEMASTER.INVOICE_PRINTINITIALS,'') AS PRINTINITIALS, INVOICE_CREATED AS CREATEDDATE , ISNULL(STUFF((SELECT ', ' + CHGSLEDGERS.ACC_CMPNAME + '  ' + CAST(INVOICE_PER AS VARCHAR(10)) [text()] FROM INVOICEMASTER_CHGS  AS A INNER JOIN LEDGERS AS CHGSLEDGERS ON A.INVOICE_CHARGESID = CHGSLEDGERS.ACC_ID WHERE A.INVOICE_no = INVOICEMASTER.INVOICE_NO AND A.INVOICE_REGISTERID = INVOICEMASTER.INVOICE_REGISTERID AND A.INVOICE_yearid = INVOICEMASTER.INVOICE_YEARID  FOR XML PATH(''), TYPE) .value('.','NVARCHAR(MAX)'),1,2,' '),'') AS CHGSDTLS, ISNULL(INVOICEMASTER.INVOICE_PARTYPONO, 0) AS PARTYPONO  ", " ", " INVOICEMASTER INNER JOIN LEDGERS AS LEDGER ON INVOICEMASTER.INVOICE_LEDGERID = LEDGER.Acc_id INNER JOIN REGISTERMASTER ON INVOICEMASTER.INVOICE_REGISTERID = REGISTERMASTER.register_id LEFT OUTER JOIN LEDGERS AS PACKINGLEDGERS ON INVOICEMASTER.INVOICE_PACKINGID = PACKINGLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS LOCALTRANSLEDGERS ON INVOICEMASTER.INVOICE_LOCALTRANSID = LOCALTRANSLEDGERS.Acc_id LEFT OUTER JOIN STATEMASTER ON LEDGER.Acc_stateid = STATEMASTER.state_id LEFT OUTER JOIN LEDGERS ON INVOICEMASTER.INVOICE_AGENTID = LEDGERS.Acc_id LEFT OUTER JOIN CITYMASTER ON LEDGER.Acc_cityid = CITYMASTER.city_id LEFT OUTER JOIN LEDGERS AS TRANSNAME ON INVOICEMASTER.INVOICE_TRANSID = TRANSNAME.Acc_id LEFT OUTER JOIN LEDGERS AS PURLEDGERS ON INVOICE_PURLEDGERID = PURLEDGERS.ACC_ID LEFT OUTER JOIN (SELECT INVOICEMASTER.INVOICE_INITIALS, REC.receipt_date AS RECDATE, INVOICE_YEARID FROM INVOICEMASTER  CROSS APPLY (SELECT TOP 1 RECEIPTMASTER.receipt_date FROM RECEIPTMASTER_DESC INNER JOIN RECEIPTMASTER ON RECEIPTMASTER_DESC.receipt_no = RECEIPTMASTER.RECEIPT_NO AND RECEIPTMASTER_DESC.receipt_registerid = RECEIPTMASTER.receipt_registerid AND RECEIPTMASTER_DESC.receipt_yearid = RECEIPTMASTER.receipt_yearid WHERE RECEIPTMASTER.RECEIPT_YEARID = " & YearId & " AND INVOICEMASTER.INVOICE_YEARID = " & YearId & " AND receipt_paytype = 'Against Bill' AND INVOICEMASTER.INVOICE_INITIALS = RECEIPT_BILLINITIALS AND INVOICEMASTER.INVOICE_YEARID = RECEIPTMASTER.receipt_yearid ) AS REC) AS RECDATE  ON INVOICEMASTER.INVOICE_INITIALS = RECDATE.INVOICE_INITIALS AND INVOICEMASTER.INVOICE_YEARID = RECDATE.INVOICE_YEARID LEFT OUTER JOIN CITYMASTER AS TOCITYMASTER ON INVOICEMASTER.INVOICE_TOCITYID = TOCITYMASTER.city_id LEFT OUTER JOIN CITYMASTER AS FROMCITYMASTER ON INVOICEMASTER.INVOICE_TRANSCITYID = FROMCITYMASTER.city_id LEFT OUTER JOIN USERMASTER ON INVOICE_USERID = USER_ID", " AND REGISTER_NAME = '" & cmbregister.Text.Trim & "' AND (INVOICEMASTER.INVOICE_YEARID = '" & YearId & "') ORDER BY INVOICEMASTER.INVOICE_NO")
            'Dim dt As DataTable = objclsCMST.search(" CAST(0 AS BIT) AS CHK, AGENCYINVOICEMASTER.AINVOICE_NO AS BILLNO, AGENCYINVOICEMASTER.AINVOICE_PARTYPONO AS PONO, AGENCYINVOICEMASTER.AINVOICE_DATE AS DATE, LEDGERS.Acc_cmpname AS BUYERNAME, SELLERLEDGERS.Acc_cmpname AS SELLERNAME, AGENCYINVOICEMASTER.AINVOICE_CRDAYS AS CRDAYS, AGENCYINVOICEMASTER.AINVOICE_LRNO AS LRNO, AGENCYINVOICEMASTER_DESC.AINVOICE_PCS AS PCS, AGENCYINVOICEMASTER.AINVOICE_TOTALPCS, AGENCYINVOICEMASTER_DESC.AINVOICE_MTRS AS MTRS, AGENCYINVOICEMASTER.AINVOICE_TOTALMTRS, AGENCYINVOICEMASTER_DESC.AINVOICE_AMOUNT AS AMOUNT, AGENCYINVOICEMASTER.AINVOICE_TOTALAMT, AGENCYINVOICEMASTER.AINVOICE_CHARGES, AGENCYINVOICEMASTER.AINVOICE_REMARKS, ITEMMASTER.item_name AS QUALITY, TRANSLEDGERS.Acc_cmpname AS TRANSPORT, AGENCYINVOICEMASTER_DESC.AINVOICE_RATE AS RATE", "", "AGENCYINVOICEMASTER INNER JOIN AGENCYINVOICEMASTER_DESC ON AGENCYINVOICEMASTER.AINVOICE_NO = AGENCYINVOICEMASTER_DESC.AINVOICE_NO INNER JOIN LEDGERS  ON AGENCYINVOICEMASTER.AINVOICE_LEDGERID = LEDGERS.Acc_ID INNER JOIN LEDGERS AS SELLERLEDGERS     ON AGENCYINVOICEMASTER.AINVOICE_PURLEDGERID = SELLERLEDGERS.Acc_ID INNER JOIN ITEMMASTER          ON AGENCYINVOICEMASTER_DESC.AINVOICE_ITEMID = ITEMMASTER.item_id LEFT JOIN LEDGERS AS TRANSLEDGERS ON AGENCYINVOICEMASTER.AINVOICE_TRANSID = TRANSLEDGERS.Acc_ID", " " & TEMPCONDITION & " ORDER BY AGENCYINVOICEMASTER.AINVOICE_NO")
            Dim dt As DataTable = objclsCMST.search(" CAST(0 AS BIT) AS CHK, AGENCYINVOICEMASTER.AINVOICE_NO AS BILLNO, AGENCYINVOICEMASTER.AINVOICE_PARTYPONO AS PONO, AGENCYINVOICEMASTER.AINVOICE_DATE AS DATE, LEDGERS.Acc_cmpname AS BUYERNAME, SELLERLEDGERS.Acc_cmpname AS SELLERNAME, AGENCYINVOICEMASTER.AINVOICE_CRDAYS AS CRDAYS, AGENCYINVOICEMASTER.AINVOICE_LRNO AS LRNO, AGENCYINVOICEMASTER_DESC.AINVOICE_PCS AS PCS, AGENCYINVOICEMASTER.AINVOICE_TOTALPCS, AGENCYINVOICEMASTER_DESC.AINVOICE_MTRS AS MTRS, AGENCYINVOICEMASTER.AINVOICE_TOTALMTRS, AGENCYINVOICEMASTER_DESC.AINVOICE_AMOUNT AS AMT, AGENCYINVOICEMASTER.AINVOICE_TOTALAMT, AGENCYINVOICEMASTER.AINVOICE_CHARGES, AGENCYINVOICEMASTER.AINVOICE_REMARKS, ITEMMASTER.item_name AS QUALITY, TRANSLEDGERS.Acc_cmpname AS TRANSPORT, AGENCYINVOICEMASTER_DESC.AINVOICE_RATE AS RATE ,ISNULL((SELECT TOP 1 AINVOICE_PER FROM AGENCYINVOICEMASTER_CHGS  AS A INNER JOIN LEDGERS AS CHGSLEDGERS ON A.AINVOICE_CHARGESID = CHGSLEDGERS.ACC_ID WHERE A.AINVOICE_no = AGENCYINVOICEMASTER.AINVOICE_NO  AND A.AINVOICE_yearid = AGENCYINVOICEMASTER.AINVOICE_YEARID AND (CHGSLEDGERS.ACC_CMPNAME = 'BROKERAGE' )),0) AS BPER, ISNULL((SELECT SUM(AINVOICE_AMT) AS BAMT FROM AGENCYINVOICEMASTER_CHGS  AS A INNER JOIN LEDGERS AS CHGSLEDGERS ON A.AINVOICE_CHARGESID = CHGSLEDGERS.ACC_ID WHERE A.AINVOICE_no = AGENCYINVOICEMASTER.AINVOICE_NO AND A.AINVOICE_yearid = AGENCYINVOICEMASTER.AINVOICE_YEARID AND (CHGSLEDGERS.ACC_CMPNAME = 'BROKERAGE' )),0) AS BROKERAGE,ISNULL((SELECT TOP 1 AINVOICE_PER AS FLOAT FROM AGENCYINVOICEMASTER_CHGS  AS A INNER JOIN LEDGERS AS CHGSLEDGERS ON A.AINVOICE_CHARGESID = CHGSLEDGERS.ACC_ID WHERE A.AINVOICE_no = AGENCYINVOICEMASTER.AINVOICE_NO  AND A.AINVOICE_yearid = AGENCYINVOICEMASTER.AINVOICE_YEARID AND CHGSLEDGERS.ACC_CMPNAME LIKE '%DISCOUNT%'),0) AS VPER,  ISNULL((SELECT SUM(AINVOICE_AMT) AS CDAMT FROM AGENCYINVOICEMASTER_CHGS  AS A INNER JOIN LEDGERS AS CHGSLEDGERS ON A.AINVOICE_CHARGESID = CHGSLEDGERS.ACC_ID WHERE A.AINVOICE_no = AGENCYINVOICEMASTER.AINVOICE_NO AND A.AINVOICE_yearid = AGENCYINVOICEMASTER.AINVOICE_YEARID AND CHGSLEDGERS.ACC_CMPNAME = 'CASH DISCOUNT'),0) AS CASHDISC , ISNULL( AGENCYINVOICEMASTER_DESC.AINVOICE_FOLDPER,0) AS FOLD ", "", " AGENCYINVOICEMASTER INNER JOIN AGENCYINVOICEMASTER_DESC ON AGENCYINVOICEMASTER.AINVOICE_NO = AGENCYINVOICEMASTER_DESC.AINVOICE_NO AND AGENCYINVOICEMASTER.AINVOICE_YEARID = AGENCYINVOICEMASTER_DESC.AINVOICE_YEARID INNER JOIN LEDGERS  ON AGENCYINVOICEMASTER.AINVOICE_LEDGERID = LEDGERS.Acc_ID AND  AGENCYINVOICEMASTER.AINVOICE_YEARID = LEDGERS.Acc_yearid INNER JOIN LEDGERS AS SELLERLEDGERS     ON AGENCYINVOICEMASTER.AINVOICE_PURLEDGERID = SELLERLEDGERS.Acc_ID INNER JOIN ITEMMASTER          ON AGENCYINVOICEMASTER_DESC.AINVOICE_ITEMID = ITEMMASTER.item_id  AND AGENCYINVOICEMASTER_DESC.AINVOICE_YEARID = ITEMMASTER.item_yearid  LEFT JOIN LEDGERS AS TRANSLEDGERS ON AGENCYINVOICEMASTER.AINVOICE_TRANSID = TRANSLEDGERS.Acc_ID AND AGENCYINVOICEMASTER.AINVOICE_YEARID = TRANSLEDGERS.Acc_yearid", " " & TEMPCONDITION & " ORDER BY AGENCYINVOICEMASTER.AINVOICE_NO")
            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdshow_Click(sender As Object, e As EventArgs) Handles cmdshow.Click
        Try
            If chkdate.Checked = True Then
                fillgrid(" AND (AGENCYINVOICEMASTER.AINVOICE_YEARID = " & YearId & ") AND (AGENCYINVOICEMASTER.AINVOICE_DATE >= '" & Format(dtfrom.Value, "yyyy-MM-dd") & "' AND AGENCYINVOICEMASTER.AINVOICE_DATE <= '" & Format(dtto.Value, "yyyy-MM-dd") & "') ")
            Else
                fillgrid(" AND (AGENCYINVOICEMASTER.AINVOICE_YEARID = " & YearId & ") ")
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_CustomUnboundColumnData(sender As Object, e As DevExpress.XtraGrid.Views.Base.CustomColumnDataEventArgs) Handles gridbill.CustomUnboundColumnData
        If e.Column.FieldName = "SRNO" Then
            ' Assign the row index + 1 as the serial number
            If e.IsGetData Then
                e.Value = e.ListSourceRowIndex + 1 ' ListSourceRowIndex gives the current row index
            End If
        End If
    End Sub
End Class