SELECT     'Outward' AS SUPPLYTYPE, 'Supply' AS SUBTYPE, 'Tax Invoice' AS DOCTYPE, INVOICEMASTER.INVOICE_INITIALS + '/' + RIGHT(CAST(YEAR(year_startdate)  AS VARCHAR(4)),2) + '-' + RIGHT(CAST(YEAR(year_enddate)  AS VARCHAR(4)),2)  AS DOCNO, INVOICEMASTER.INVOICE_DATE AS DOCDATE, 
                      CMPMASTER.cmp_displayedname AS FROMPARTY, CMPMASTER.CMP_GSTIN AS FROMGSTIN, ISNULL(CMPMASTER.cmp_add1, '') AS FROMADDRESS1, ISNULL(CMPMASTER.cmp_add2, '') 
                      AS FROMADDRESS2, ISNULL(CMPCITYMASTER.city_name, '') AS FROMPLACE, ISNULL(CMPMASTER.cmp_zipcode, '') AS FROMPINCODE, CMPSTATEMASTER.state_name AS FROMSTATE, 
                      LEDGERS.Acc_cmpname AS TOPARTY, LEDGERS.ACC_GSTIN AS TOGSTIN, CASE WHEN INVOICE_PACKINGID > 0 THEN ISNULL(SHIPTOLEDGERS.ACC_ADD1,'') ELSE ISNULL(LEDGERS.Acc_add1,'') END AS TOADDRESS1, CASE WHEN INVOICE_PACKINGID > 0 THEN ISNULL(SHIPTOLEDGERS.ACC_ADD2,'') ELSE ISNULL(LEDGERS.Acc_add2,'') END AS TOADDRESS2, 
                      CASE WHEN INVOICE_PACKINGID > 0 THEN ISNULL(SHIPTOCITY.CITY_NAME,'') ELSE ISNULL(CITYMASTER.city_name, '') END AS TOPLACE, 
                      CASE WHEN INVOICE_PACKINGID > 0 THEN ISNULL(SHIPTOLEDGERS.Acc_zipcode,'') ELSE ISNULL(LEDGERS.Acc_zipcode, '') END AS TOPINCODE,
                      CASE WHEN INVOICE_PACKINGID > 0 THEN ISNULL(SHIPTOSTATE.STATE_NAME,'') ELSE ISNULL(STATEMASTER.state_name,'') END AS TOSTATE, 
                      
                      INVDESC.ITEMNAME , INVDESC.[ITEMDESCRIPTION], INVDESC.HSNCODE, INVDESC.UNIT, INVDESC.QTY, INVOICEMASTER.INVOICE_SUBTOTAL AS TAXABLEAMT, (CAST(INVOICE_CGSTPER AS VARCHAR(5))+'+' + CAST(INVOICE_SGSTPER AS VARCHAR(5)) + '+' + CAST(INVOICE_IGSTPER AS VARCHAR(5)) + '+0') AS TAXRATE,
                      
                      INVOICEMASTER.INVOICE_TOTALCGSTAMT AS CGSTAMT, INVOICEMASTER.INVOICE_TOTALSGSTAMT AS SGSTAMT, INVOICEMASTER.INVOICE_TOTALIGSTAMT AS IGSTAMT, 0 AS CESSAMT, 
                      'Road' AS TRANSMODE, 0 AS DISTANCE, ISNULL(TRANSLEDGERS.Acc_cmpname, '') AS TRANSNAME, ISNULL(TRANSLEDGERS.ACC_GSTIN, '') AS TRANSID, 
                      ISNULL(INVOICEMASTER.INVOICE_LRNO, '') AS TRANSDOCNO, INVOICEMASTER.INVOICE_LRDATE AS TRANSDOCDATE, ISNULL(INVOICEMASTER.INVOICE_VEHICLENO, '') AS VEHICLENO
FROM         LEDGERS AS TRANSLEDGERS RIGHT OUTER JOIN
                      CMPMASTER INNER JOIN
                      STATEMASTER INNER JOIN
                      INVOICEMASTER INNER JOIN
                      LEDGERS ON INVOICEMASTER.INVOICE_LEDGERID = LEDGERS.Acc_id INNER JOIN
                      REGISTERMASTER ON INVOICEMASTER.INVOICE_REGISTERID = REGISTERMASTER.register_id ON STATEMASTER.state_id = LEDGERS.Acc_stateid ON 
                      CMPMASTER.cmp_id = INVOICEMASTER.INVOICE_CMPID INNER JOIN 
                      YEARMASTER ON year_id = INVOICE_YEARID  INNER JOIN
                      CITYMASTER AS CMPCITYMASTER ON CMPMASTER.cmp_cityid = CMPCITYMASTER.city_id INNER JOIN
                      STATEMASTER AS CMPSTATEMASTER ON CMPMASTER.cmp_stateid = CMPSTATEMASTER.state_id LEFT OUTER JOIN
                      LEDGERS AS SHIPTOLEDGERS ON SHIPTOLEDGERS.Acc_id = INVOICE_PACKINGID LEFT OUTER JOIN 
                      STATEMASTER AS SHIPTOSTATE ON SHIPTOSTATE.state_id = SHIPTOLEDGERS.Acc_stateid  LEFT OUTER JOIN
                      CITYMASTER AS SHIPTOCITY ON SHIPTOCITY.city_id = SHIPTOLEDGERS.Acc_cityid LEFT OUTER JOIN
                      CITYMASTER ON LEDGERS.Acc_cityid = CITYMASTER.city_id ON TRANSLEDGERS.Acc_id = INVOICEMASTER.INVOICE_TRANSID CROSS APPLY
                      (SELECT  TOP 1 ISNULL(ITEMMASTER.ITEM_NAME, '') AS ITEMNAME, ISNULL(HSN_ITEMDESC,'') as [ITEMDESCRIPTION], ISNULL(HSN_CODE,'') AS HSNCODE, ISNULL(UNIT_NAME, '') AS UNIT, INVOICE_MTRS AS QTY
 FROM          INVOICEMASTER_DESC INNER JOIN ITEMMASTER ON item_id = INVOICE_ITEMID INNER JOIN 
 HSNMASTER ON ITEM_HSNCODEID = HSN_ID LEFT OUTER JOIN UNITMASTER ON item_unitid = unit_id 
WHERE      INVOICEMASTER_DESC.INVOICE_NO = INVOICEMASTER.INVOICE_NO AND INVOICEMASTER_DESC.INVOICE_REGISTERID = INVOICEMASTER.INVOICE_REGISTERID AND 
                                                   INVOICEMASTER_DESC.INVOICE_YEARID = INVOICEMASTER.INVOICE_YEARID) AS INVDESC
	