INSERT INTO TEMPDESIGNUPLOAD 
SELECT DISTINCT ISNULL(ITEMMASTER.ITEM_NAME,'') AS ITEMNAME, DESIGNMASTER.DESIGN_NO AS DESIGNNO, ISNULL(BASECOLORMASTER.COLOR_NAME,'') AS BASECOLOR, ISNULL(PRINTCOLORMASTER.COLOR_NAME,'') AS PRINTCOLOR, ISNULL(COLORMASTER.COLOR_NAME,'') AS COLOR FROM DESIGNMASTER LEFT OUTER JOIN ITEMMASTER ON DESIGNMASTER.DESIGN_ITEMID = ITEMMASTER.ITEM_ID LEFT OUTER JOIN DESIGNMASTER_COLOR ON DESIGNMASTER.DESIGN_id = DESIGNMASTER_COLOR.DESIGN_ID LEFT OUTER JOIN 
COLORMASTER AS BASECOLORMASTER ON DESIGN_BASECOLORID = BASECOLORMASTER.COLOR_ID LEFT OUTER JOIN
COLORMASTER AS PRINTCOLORMASTER ON DESIGN_PRINTCOLORID = PRINTCOLORMASTER.COLOR_ID LEFT OUTER JOIN
COLORMASTER ON DESIGN_COLORID = COLORMASTER.COLOR_ID 
WHERE DESIGNMASTER.DESIGN_yearid = 12