SELECT ITEMNAME, DESIGN, '', 'PCS', '',  CASE WHEN SUM(ACCEPTEDMTRS) > 0 THEN SUM(ACCEPTEDPCS-RECDPCS) ELSE SUM(TOTALPCS-RECDPCS) END AS PCS, CASE WHEN SUM(ACCEPTEDMTRS) > 0 THEN SUM(ACCEPTEDMTRS-RECDMTRS) ELSE SUM(TOTALMTRS-RECDMTRS) END AS MTRS, '5407', PARTYNAME,
'',LOTNO, '', CHALLANNO, '', '', JOBBERNAME 
FROM LOT_VIEW WHERE YEARID = 3 AND LOTCOMPLETED = 0 
GROUP BY ITEMNAME, DESIGN, PARTYNAME, LOTNO, CHALLANNO, JOBBERNAME 
  ORDER BY JOBBERNAME 
