
--EXECUTE THIS QUERY ONCE, THIS WILL REMOVE ALL THE ENTER KEYS 
--UPDATE ACCOUNTSMASTER SET Acc_add  =REPLACE(REPLACE(CAST(Acc_add AS VARCHAR(1000)), CHAR(13),' '), CHAR(10),' '), Acc_add1  =REPLACE(REPLACE(CAST(Acc_add1 AS VARCHAR(1000)), CHAR(13),' '), CHAR(10),' '), Acc_add2  =REPLACE(REPLACE(CAST(Acc_add2 AS VARCHAR(1000)), CHAR(13),' '), CHAR(10),' '), Acc_shippingadd =REPLACE(REPLACE(CAST(Acc_shippingadd AS VARCHAR(1000)), CHAR(13),' '), CHAR(10),' ')


SELECT LEDGERS.ACC_CMPNAME AS CODE, LEDGERS.ACC_CMPNAME AS NAME, ISNULL(LEDGERS.Acc_add1,'') AS ADD1, ISNULL(LEDGERS.Acc_add2,'') AS ADD2,  REPLACE(CAST(ISNULL(LEDGERS.Acc_add,'') AS VARCHAR(1000)), CHAR(10),'') AS [ADRESS], ISNULL(CITYMASTER.CITY_NAME,'') AS CITY,
ISNULL(LEDGERS.Acc_zipcode,'') AS PINCODE, ISNULL(STATEMASTER.STATE_NAME,'') AS STATENAME , ISNULL(COUNTRYMASTER.COUNTRY_NAME,'') AS COUNTRY,
ISNULL(LEDGERS.Acc_phone,'') AS PHONENO, ISNULL(LEDGERS.Acc_mobile,'') AS MOBILENO, ISNULL(LEDGERS.ACC_GSTIN,'') AS GSTIN, ISNULL(GROUPMASTER.GROUP_NAME,'') AS GROUPNAME ,
ISNULL(LEDGERS.Acc_panno,'') AS PANNO, ISNULL(BROKERLEDGERS.ACC_CMPNAME,'') AS AGENT, ISNULL(TRANSLEDGERS.ACC_CMPNAME,'') AS TRANSPORT,
ISNULL(LEDGERS.Acc_email,'') AS EMAILID, ISNULL(LEDGERS.Acc_crdays,0) AS CRDAYS, ISNULL(LEDGERS.ACC_NAME,'') AS CONTACTPERSON,
ISNULL(ACCOUNTSMASTER_TDS.ACC_TDSPER,0) AS TDSPER, ISNULL(ACC_SECTION,'') AS TDSSECTION, ISNULL(LEDGERS.ACC_TDSCOMPANY,'') AS TDSCONMPANY,
ISNULL(LEDGERS.ACC_DISC,0) AS DISCPER, ISNULL(LEDGERS.ACC_CDPER,0) AS CASHDISC , ISNULL(LEDGERS.ACC_AGENTCOMM,0) AS BROKERAGE,
ISNULL(LEDGERS.Acc_shippingadd,'') AS SHIPPINGADD, ISNULL(LEDGERS.Acc_resino,'') AS RESINO, ISNULL(LEDGERS.Acc_altno,'') AS ALTNO,
ISNULL(LEDGERS.Acc_fax,'') AS FAXNO, ISNULL(LEDGERS.Acc_website,'') AS WEBSITE, ISNULL(LEDGERS.Acc_remarks,'') AS REMAEKS, ISNULL(LEDGERS.ACC_INTPER,0) AS INTPER,
ISNULL(DELIVERYATCITY.CITY_NAME,'') AS DELIVERYAT, ISNULL(LEDGERS.ACC_DELIVERYPINCODE,'') AS DELIVERYPINCODE, ISNULL(LEDGERS.ACC_KMS,0) AS KMS,
ISNULL(LEDGERS.ACC_COMMISSION,0) AS BROKERAGECOMM, ISNULL(LEDGERS.ACC_WHATSAPPNO,'') AS WHATSAPPNO, ISNULL(AREAMASTER.AREA_NAME,'') AS AREA,
ISNULL(LEDGERS.ACC_TYPE,'') AS TYPE
FROM LEDGERS LEFT OUTER JOIN CITYMASTER ON LEDGERS.Acc_cityid = CITYMASTER.CITY_ID LEFT OUTER JOIN
STATEMASTER ON LEDGERS.Acc_stateid = STATEMASTER.STATE_ID LEFT OUTER JOIN
COUNTRYMASTER ON LEDGERS.Acc_countryid = COUNTRY_ID INNER JOIN 
GROUPMASTER ON LEDGERS.Acc_groupid = GROUPMASTER.GROUP_ID LEFT OUTER JOIN
LEDGERS AS BROKERLEDGERS ON LEDGERS.ACC_AGENTID = BROKERLEDGERS.ACC_ID LEFT OUTER JOIN
LEDGERS AS TRANSLEDGERS ON LEDGERS.ACC_TRANSID= TRANSLEDGERS.ACC_ID LEFT OUTER JOIN
ACCOUNTSMASTER_TDS ON LEDGERS.ACC_ID = ACCOUNTSMASTER_TDS.ACC_ID LEFT OUTER JOIN
CITYMASTER AS DELIVERYATCITY ON LEDGERS.ACC_DELIVERYATID = DELIVERYATCITY.CITY_ID LEFT OUTER JOIN
AREAMASTER ON LEDGERS.Acc_areaid = AREAMASTER.AREA_ID
WHERE LEDGERS.ACC_TYPE=  'ACCOUNTS' --AND LEDGERS.Acc_yearid = 3 AND GROUPMASTER.group_secondary IN ('SUNDRY CREDITORS', 'SUNDRY DEBTORS')
ORDER BY LEDGERS.ACC_CMPNAME 

