SELECT ITEMNAME, DESIGNNO, COLOR, UNIT, BARCODE, PCS, MTRS, ISNULL(HSN_CODE,'') AS HSNCODE, BARCODESTOCK.PURNAME, QUALITY, LOTNO, BALENO, GRIDREMARKS, GODOWN
FROM BARCODESTOCK INNER JOIN ITEMMASTER ON BARCODESTOCK.ITEMID = ITEMMASTER.ITEM_ID LEFT OUTER JOIN HSNMASTER ON ITEM_HSNCODEID = HSN_ID
WHERE  YEARID = 4 AND UNIT IN (SELECT UNIT_ABBR FROM DEFAULTSTOCKUNIT  )