Imports BL

Public Class SelectAgencySO


    Public BUYERNAME As String = ""
    Public SELLERNAME As String = ""
    Public FRMSTRING As String = ""
    Public GOCNAME As String = ""

    Public DT As New DataTable

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub SelectAgencySO_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Windows.Forms.Keys.Escape Then
            Me.Close()
        ElseIf e.KeyCode = Keys.Enter Then
            SendKeys.Send("{Tab}")
        End If
    End Sub

    Private Sub SelectAgencySO_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        fillgrid("")
    End Sub

    Sub fillgrid(ByVal WHERE As String)
        Try
            Dim OPWHERE As String = ""

            Cursor.Current = Cursors.WaitCursor
            Dim objcls As New ClsCommon()   'GOC
            Dim DT1 As New DataTable             'GOC

            If BUYERNAME <> "" Then
                'WHERE = WHERE & " AND ISNULL(LEDGERS.ACC_CMPNAME,'') = '" & BUYERNAME & "'"
                'OPWHERE = OPWHERE & " AND ISNULL(LEDGERS.ACC_CMPNAME,'') = '" & BUYERNAME & "'"
                WHERE = WHERE & " AND ISNULL(LEDGERS.ACC_CMPNAME,'') = '" & BUYERNAME & "'"
                OPWHERE = OPWHERE & " AND ISNULL(LEDGERS.ACC_CMPNAME,'') = '" & BUYERNAME & "'"

                DT1 = objcls.SEARCH(" LEDGERS.Acc_id, LEDGERS.Acc_cmpname, GROUPOFCOMPANIESMASTER.GOC_NAME AS  GOC ,ISNULL(LEDGERS.ACC_CMPNAME,'') AS NAME ", "", "  LEDGERS LEFT OUTER JOIN GROUPOFCOMPANIESMASTER ON LEDGERS.ACC_GOCID = GROUPOFCOMPANIESMASTER.GOC_ID       ", " AND  (LEDGERS.ACC_GOCID <> '') AND Acc_yearid= " & YearId & "  and ledgers.acc_cmpname = '" & BUYERNAME & "'    ")
                If DT1.Rows.Count > 0 Then
                    GOCNAME = DT1.Rows(0).Item("GOC")
                    If GOCNAME = "" Then
                        WHERE = WHERE = " AND LEDGERS.ACC_CMPNAME = '" & BUYERNAME & "'"
                        OPWHERE = OPWHERE = " AND LEDGERS.ACC_CMPNAME = '" & BUYERNAME & "'"

                    Else
                        WHERE = " AND ISNULL(GOC,'') = '" & GOCNAME & "'"
                        OPWHERE = " AND ISNULL(GOC,'') = '" & GOCNAME & "'"

                    End If
                End If
            End If

            If SELLERNAME <> "" Then
                'WHERE = WHERE & " AND ISNULL(PACKINGLEDGERS.ACC_CMPNAME,'') = '" & SELLERNAME & "'"
                'OPWHERE = OPWHERE & " AND ISNULL(PACKINGLEDGERS.ACC_CMPNAME,'') = '" & SELLERNAME & "'"
                WHERE = WHERE & " AND ISNULL(PACKINGLEDGERS.ACC_CMPNAME,'') = '" & SELLERNAME & "'"
                OPWHERE = OPWHERE & " AND ISNULL(PACKINGLEDGERS.ACC_CMPNAME,'') = '" & SELLERNAME & "'"

                DT1 = objcls.SEARCH(" PACKINGLEDGERS.Acc_id, PACKINGLEDGERS.Acc_cmpname, GROUPOFCOMPANIESMASTER.GOC_NAME AS  GOC ,ISNULL(PACKINGLEDGERS.ACC_CMPNAME,'') AS NAME ", "", "  LEDGERS AS PACKINGLEDGERS LEFT OUTER JOIN GROUPOFCOMPANIESMASTER ON PACKINGLEDGERS.ACC_GOCID = GROUPOFCOMPANIESMASTER.GOC_ID       ", " AND  (PACKINGLEDGERS.ACC_GOCID <> '') AND Acc_yearid= " & YearId & "  and PACKINGLEDGERS.acc_cmpname = '" & SELLERNAME & "'    ")
                If DT1.Rows.Count > 0 Then
                    GOCNAME = DT1.Rows(0).Item("GOC")
                    If GOCNAME = "" Then
                        WHERE = WHERE = " AND PACKINGLEDGERS.ACC_CMPNAME = '" & SELLERNAME & "'"
                        OPWHERE = OPWHERE = " AND PACKINGLEDGERS.ACC_CMPNAME = '" & SELLERNAME & "'"

                    Else
                        WHERE = " AND ISNULL(GROUPOFCOMPANIESMASTER.GOC_NAME, '') = '" & GOCNAME & "'"
                        OPWHERE = " AND ISNULL(GROUPOFCOMPANIESMASTER.GOC_NAME, '') = '" & GOCNAME & "'"

                    End If
                End If
            End If




            Dim objclspreq As New ClsCommon()
            Dim DT As New DataTable
            WHERE = WHERE & " and (CASE WHEN AGENCYSALEORDER.ASO_ORDERON = 'PCS' THEN (AGENCYSALEORDER_DESC.ASO_MTRS - AGENCYSALEORDER_DESC.ASO_RECDQTY) ELSE (AGENCYSALEORDER_DESC.ASO_MTRS - AGENCYSALEORDER_DESC.ASO_RECDMTRS) END) > 0 AND AGENCYSALEORDER_DESC.ASO_CLOSED=0 "
            OPWHERE = OPWHERE & " and  (CASE WHEN OPENINGAGENCYSALEORDER.OPASO_ORDERON = 'PCS' THEN  (OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY) ELSE (OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDMTRS) END) > 0 AND OPENINGAGENCYSALEORDER_DESC.OPASO_CLOSED=0 "
            'DT = objclspreq.SEARCH("CAST (0 AS BIT) AS CHK,*", "", " (SELECT AGENCYSALEORDER.ASO_no AS SONO, AGENCYSALEORDER.ASO_date AS DATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGER.Acc_cmpname, '') AS AGENTNAME, AGENCYSALEORDER.ASO_pono AS [PONO], ISNULL(ITEMMASTER.item_name,'') AS [ITEMNAME], (CASE WHEN AGENCYSALEORDER.ASO_ORDERON = 'PCS' THEN (AGENCYSALEORDER_DESC.ASO_MTRS - AGENCYSALEORDER_DESC.ASO_RECDQTY) ELSE (AGENCYSALEORDER_DESC.ASO_QTY - AGENCYSALEORDER_DESC.ASO_RECDQTY) END) AS [QTY],  (CASE WHEN AGENCYSALEORDER.ASO_ORDERON = 'PCS' THEN (AGENCYSALEORDER_DESC.ASO_MTRS - AGENCYSALEORDER_DESC.ASO_RECDQTY) ELSE (AGENCYSALEORDER_DESC.ASO_MTRS - AGENCYSALEORDER_DESC.ASO_RECDMTRS) END) AS [MTRS], AGENCYSALEORDER.ASO_remarks AS REMARKS, AGENCYSALEORDER_DESC.ASO_GRIDSRNO AS GRIDSRNO, ISNULL(PACKINGLEDGERS.Acc_cmpname, '') AS DELIVERYAT, ISNULL(DESIGN_NO,'') AS DESIGNNO, ISNULL(COLOR_NAME,'') AS COLOR, ISNULL(TRANSLEDGERS.ACC_CMPNAME,'') AS TRANSNAME, ISNULL(AGENCYSALEORDER.ASO_REFNO,'') AS REFNO, AGENCYSALEORDER_DESC.ASO_RATE AS RATE, ISNULL(CITYMASTER.CITY_NAME,'') AS CITYNAME, 'AGENCYSALEORDER' AS TYPE, ISNULL(AGENCYSALEORDER_DESC.ASO_PARTYPONO,'') AS GRIDPARTYPONO, ISNULL(PACKINGTYPEMASTER.PACKINGTYPE_NAME,'') AS PACKINGTYPE, ISNULL(AGENCYSALEORDER_DESC.ASO_GRIDREMARKS, '') AS GRIDDESC, AGENCYSALEORDER_DESC.ASO_QTY AS PERQTY, ISNULL(GROUPOFCOMPANIESMASTER.GOC_NAME, '') AS GOC  FROM AGENCYSALEORDER INNER JOIN LEDGERS ON AGENCYSALEORDER.ASO_ledgerid = LEDGERS.Acc_id INNER JOIN AGENCYSALEORDER_DESC ON AGENCYSALEORDER.ASO_no = AGENCYSALEORDER_DESC.ASO_NO AND AGENCYSALEORDER.ASO_YEARID = AGENCYSALEORDER_DESC.ASO_YEARID LEFT OUTER JOIN PACKINGTYPEMASTER ON AGENCYSALEORDER.ASO_PACKINGTYPEID = PACKINGTYPEMASTER.PACKINGTYPE_ID LEFT OUTER JOIN LEDGERS AS PACKINGLEDGERS ON AGENCYSALEORDER.ASO_PACKINGID = PACKINGLEDGERS.Acc_id LEFT OUTER JOIN ITEMMASTER ON AGENCYSALEORDER_DESC.ASO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGER ON AGENCYSALEORDER.ASO_Agentid = AGENTLEDGER.Acc_id LEFT OUTER JOIN ADDRESSMASTER ON AGENCYSALEORDER.ASO_HASTEID = ADDRESSMASTER.ADDRESS_ID LEFT OUTER JOIN DESIGNMASTER ON AGENCYSALEORDER_DESC.ASO_DESIGNID = DESIGN_ID LEFT OUTER JOIN COLORMASTER ON AGENCYSALEORDER_DESC.ASO_COLORID = COLOR_ID LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON AGENCYSALEORDER.ASO_TRANSID = TRANSLEDGERS.ACC_ID LEFT OUTER JOIN CITYMASTER ON AGENCYSALEORDER.ASO_CITYID = CITYMASTER.CITY_ID LEFT OUTER JOIN GROUPOFCOMPANIESMASTER ON LEDGERS.ACC_GOCID = GROUPOFCOMPANIESMASTER.GOC_ID WHERE  AGENCYSALEORDER.ASO_VERIFIED=1 AND  AGENCYSALEORDER.ASO_YEARID = " & YearId & WHERE & " UNION ALL SELECT OPENINGAGENCYSALEORDER.OPASO_no AS SONO, OPENINGAGENCYSALEORDER.OPASO_date AS DATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGER.Acc_cmpname, '') AS AGENTNAME, OPENINGAGENCYSALEORDER.OPASO_pono AS [PONO], ISNULL(ITEMMASTER.item_name,'') AS [ITEMNAME],  (CASE WHEN OPENINGAGENCYSALEORDER.OPASO_ORDERON = 'PCS' THEN (OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY) ELSE (OPENINGAGENCYSALEORDER_DESC.OPASO_QTY - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY) END) AS [QTY], (CASE WHEN OPENINGAGENCYSALEORDER.OPASO_ORDERON = 'PCS' THEN (OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY) ELSE (OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDMTRS) END) AS [MTRS], OPENINGAGENCYSALEORDER.OPASO_remarks AS REMARKS, OPENINGAGENCYSALEORDER_DESC.OPASO_GRIDSRNO AS GRIDSRNO, ISNULL(PACKINGLEDGERS.Acc_cmpname, '') AS DELIVERYAT, ISNULL(DESIGN_NO,'') AS DESIGNNO, ISNULL(COLOR_NAME,'') AS COLOR, ISNULL(TRANSLEDGERS.ACC_CMPNAME,'') AS TRANSNAME, ISNULL(OPENINGAGENCYSALEORDER.OPASO_REFNO,'') AS REFNO, OPENINGAGENCYSALEORDER_DESC.OPASO_RATE AS RATE, ISNULL(CITYMASTER.CITY_NAME,'') AS CITYNAME, 'OPENING' AS TYPE, ISNULL(OPENINGAGENCYSALEORDER_DESC.OPASO_PARTYPONO,'') AS GRIDPARTYPONO, ISNULL(PACKINGTYPEMASTER.PACKINGTYPE_NAME,'') AS PACKINGTYPE , ISNULL(OPENINGAGENCYSALEORDER_DESC.OPASO_GRIDREMARKS, '') AS GRIDDESC, OPENINGAGENCYSALEORDER_DESC.OPASO_QTY AS PERQTY, GROUPOFCOMPANIESMASTER.GOC_NAME AS  GOC FROM OPENINGAGENCYSALEORDER INNER JOIN LEDGERS ON OPENINGAGENCYSALEORDER.OPASO_ledgerid = LEDGERS.Acc_id INNER JOIN OPENINGAGENCYSALEORDER_DESC ON OPENINGAGENCYSALEORDER.OPASO_no = OPENINGAGENCYSALEORDER_DESC.OPASO_NO AND OPENINGAGENCYSALEORDER.OPASO_YEARID = OPENINGAGENCYSALEORDER_DESC.OPASO_YEARID LEFT OUTER JOIN PACKINGTYPEMASTER ON OPENINGAGENCYSALEORDER.OPASO_PACKINGTYPEID = PACKINGTYPEMASTER.PACKINGTYPE_ID LEFT OUTER JOIN LEDGERS AS PACKINGLEDGERS ON OPENINGAGENCYSALEORDER.OPASO_PACKINGID = PACKINGLEDGERS.Acc_id LEFT OUTER JOIN ITEMMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGER ON OPENINGAGENCYSALEORDER.OPASO_Agentid = AGENTLEDGER.Acc_id LEFT OUTER JOIN ADDRESSMASTER ON OPENINGAGENCYSALEORDER.OPASO_HASTEID = ADDRESSMASTER.ADDRESS_ID LEFT OUTER JOIN DESIGNMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_DESIGNID = DESIGN_ID LEFT OUTER JOIN COLORMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_COLORID = COLOR_ID LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON OPENINGAGENCYSALEORDER.OPASO_TRANSID = TRANSLEDGERS.ACC_ID LEFT OUTER JOIN CITYMASTER ON OPENINGAGENCYSALEORDER.OPASO_CITYID = CITYMASTER.CITY_ID LEFT OUTER JOIN GROUPOFCOMPANIESMASTER ON LEDGERS.ACC_GOCID = GROUPOFCOMPANIESMASTER.GOC_ID WHERE OPENINGAGENCYSALEORDER.OPASO_VERIFIED=1 AND OPENINGAGENCYSALEORDER.OPASO_YEARID = " & YearId & OPWHERE & "  UNION ALL SELECT ALLPURCHASEORDER.PO_no AS SONO, ALLPURCHASEORDER.PO_date AS DATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGER.Acc_cmpname, '') AS AGENTNAME, ALLPURCHASEORDER.PO_REFNO AS [PONO], ISNULL(ITEMMASTER.item_name,'') AS [ITEMNAME], (CASE WHEN ALLPURCHASEORDER.PO_ORDERON = 'PCS' THEN (ALLPURCHASEORDER_DESC.PO_MTRS - ALLPURCHASEORDER_DESC.PO_RECDQTY) ELSE (ALLPURCHASEORDER_DESC.PO_QTY - ALLPURCHASEORDER_DESC.PO_RECDQTY) END) AS [QTY],  (CASE WHEN ALLPURCHASEORDER.PO_ORDERON = 'PCS' THEN (ALLPURCHASEORDER_DESC.PO_MTRS - ALLPURCHASEORDER_DESC.PO_RECDQTY) ELSE (ALLPURCHASEORDER_DESC.PO_MTRS - ALLPURCHASEORDER_DESC.PO_RECDMTRS) END) AS [MTRS], ALLPURCHASEORDER.PO_remarks AS REMARKS, ALLPURCHASEORDER_DESC.PO_GRIDSRNO AS GRIDSRNO, '' AS DELIVERYAT, ISNULL(DESIGN_NO,'') AS DESIGNNO, ISNULL(COLOR_NAME,'') AS COLOR, ISNULL(TRANSLEDGERS.ACC_CMPNAME,'') AS TRANSNAME, ISNULL(ALLPURCHASEORDER.PO_REFNO,'') AS REFNO, ALLPURCHASEORDER_DESC.PO_RATE AS RATE, '' AS CITYNAME, ALLPURCHASEORDER.TYPE, '' AS GRIDPARTYPONO, '' AS PACKINGTYPE, ISNULL(ALLPURCHASEORDER_DESC.PO_GRIDREMARKS, '') AS GRIDDESC, ALLPURCHASEORDER_DESC.PO_QTY AS PERQTY, ISNULL(GROUPOFCOMPANIESMASTER.GOC_NAME, '') AS GOC FROM ALLPURCHASEORDER INNER JOIN LEDGERS ON ALLPURCHASEORDER.PO_ledgerid = LEDGERS.Acc_id INNER JOIN ALLPURCHASEORDER_DESC ON ALLPURCHASEORDER.PO_no = ALLPURCHASEORDER_DESC.PO_NO AND ALLPURCHASEORDER.PO_YEARID = ALLPURCHASEORDER_DESC.PO_YEARID LEFT OUTER JOIN ITEMMASTER ON ALLPURCHASEORDER_DESC.PO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGER ON ALLPURCHASEORDER.PO_BROKERID = AGENTLEDGER.Acc_id LEFT OUTER JOIN DESIGNMASTER ON ALLPURCHASEORDER_DESC.PO_DESIGNID = DESIGN_ID LEFT OUTER JOIN COLORMASTER ON ALLPURCHASEORDER_DESC.PO_COLORID = COLOR_ID LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON ALLPURCHASEORDER.PO_TRANSID = TRANSLEDGERS.ACC_ID LEFT OUTER JOIN GROUPOFCOMPANIESMASTER ON LEDGERS.ACC_GOCID = GROUPOFCOMPANIESMASTER.GOC_ID WHERE  ALLPURCHASEORDER.PO_VERIFIED=1 AND  ALLPURCHASEORDER.PO_YEARID = " & YearId & " AND ISNULL(LEDGERS.ACC_CMPNAME,'') = '" & SELLERNAME & "' and '" & BUYERNAME & "' = 'ABHEE FABRICS LLP [ BUYER ]' And (CASE WHEN ALLPURCHASEORDER.PO_ORDERON = 'PCS' THEN (ALLPURCHASEORDER_DESC.PO_MTRS - ALLPURCHASEORDER_DESC.PO_RECDQTY) ELSE (ALLPURCHASEORDER_DESC.PO_MTRS - ALLPURCHASEORDER_DESC.PO_RECDMTRS) END) > 0 AND ALLPURCHASEORDER_DESC.PO_CLOSED=0  UNION ALL SELECT ALLSALEORDER.SO_no AS SONO, ALLSALEORDER.SO_date AS DATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGER.Acc_cmpname, '') AS AGENTNAME, ALLSALEORDER.SO_pono AS [PONO], ISNULL(ITEMMASTER.item_name,'') AS [ITEMNAME], (CASE WHEN ALLSALEORDER.SO_ORDERON = 'PCS' THEN (ALLSALEORDER_DESC.SO_MTRS - ALLSALEORDER_DESC.SO_RECDQTY) ELSE (ALLSALEORDER_DESC.SO_QTY - ALLSALEORDER_DESC.SO_RECDQTY) END) AS [QTY],  (CASE WHEN ALLSALEORDER.SO_ORDERON = 'PCS' THEN (ALLSALEORDER_DESC.SO_MTRS - ALLSALEORDER_DESC.SO_RECDQTY) ELSE (ALLSALEORDER_DESC.SO_MTRS - ALLSALEORDER_DESC.SO_RECDMTRS) END) AS [MTRS], ALLSALEORDER.SO_remarks AS REMARKS, ALLSALEORDER_DESC.SO_GRIDSRNO AS GRIDSRNO, ISNULL(PACKINGLEDGERS.Acc_cmpname, '') AS DELIVERYAT, ISNULL(DESIGN_NO,'') AS DESIGNNO, ISNULL(COLOR_NAME,'') AS COLOR, ISNULL(TRANSLEDGERS.ACC_CMPNAME,'') AS TRANSNAME, ISNULL(ALLSALEORDER.SO_REFNO,'') AS REFNO, ALLSALEORDER_DESC.SO_RATE AS RATE, ISNULL(CITYMASTER.CITY_NAME,'') AS CITYNAME, ALLSALEORDER.TYPE, '' AS GRIDPARTYPONO, ISNULL(PACKINGTYPEMASTER.PACKINGTYPE_NAME,'') AS PACKINGTYPE, ISNULL(ALLSALEORDER_DESC.SO_GRIDREMARKS, '') AS GRIDDESC, ALLSALEORDER_DESC.SO_QTY AS PERQTY, ISNULL(GROUPOFCOMPANIESMASTER.GOC_NAME, '') AS GOC   FROM ALLSALEORDER INNER JOIN LEDGERS ON ALLSALEORDER.SO_ledgerid = LEDGERS.Acc_id INNER JOIN ALLSALEORDER_DESC ON ALLSALEORDER.SO_no = ALLSALEORDER_DESC.SO_NO AND ALLSALEORDER.SO_YEARID = ALLSALEORDER_DESC.SO_YEARID LEFT OUTER JOIN PACKINGTYPEMASTER ON ALLSALEORDER.SO_PACKINGTYPEID = PACKINGTYPEMASTER.PACKINGTYPE_ID LEFT OUTER JOIN LEDGERS AS PACKINGLEDGERS ON ALLSALEORDER.SO_PACKINGID = PACKINGLEDGERS.Acc_id LEFT OUTER JOIN ITEMMASTER ON ALLSALEORDER_DESC.SO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGER ON ALLSALEORDER.SO_Agentid = AGENTLEDGER.Acc_id LEFT OUTER JOIN ADDRESSMASTER ON ALLSALEORDER.SO_HASTEID = ADDRESSMASTER.ADDRESS_ID LEFT OUTER JOIN DESIGNMASTER ON ALLSALEORDER_DESC.SO_DESIGNID = DESIGN_ID LEFT OUTER JOIN COLORMASTER ON ALLSALEORDER_DESC.SO_COLORID = COLOR_ID LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON ALLSALEORDER.SO_TRANSID = TRANSLEDGERS.ACC_ID LEFT OUTER JOIN CITYMASTER ON ALLSALEORDER.SO_CITYID = CITYMASTER.CITY_ID LEFT OUTER JOIN GROUPOFCOMPANIESMASTER ON LEDGERS.ACC_GOCID = GROUPOFCOMPANIESMASTER.GOC_ID WHERE  ALLSALEORDER.SO_YEARID = " & YearId & " AND ISNULL(LEDGERS.ACC_CMPNAME,'') = '" & BUYERNAME & "' AND '" & SELLERNAME & "' = 'ABHEE FABRICS LLP [ SELLER ]' and (CASE WHEN ALLSALEORDER.SO_ORDERON = 'PCS' THEN (ALLSALEORDER_DESC.SO_MTRS - ALLSALEORDER_DESC.SO_RECDQTY) ELSE (ALLSALEORDER_DESC.SO_MTRS - ALLSALEORDER_DESC.SO_RECDMTRS) END) > 0 AND ALLSALEORDER_DESC.SO_CLOSED=0 ) AS T", " ORDER BY T.DATE, T.SONO, T.GRIDSRNO")
            DT = objclspreq.SEARCH("CAST (0 AS BIT) AS CHK,*", "", " (SELECT AGENCYSALEORDER.ASO_no AS SONO, AGENCYSALEORDER.ASO_date AS DATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGER.Acc_cmpname, '') AS AGENTNAME, AGENCYSALEORDER.ASO_pono AS [PONO], ISNULL(ITEMMASTER.item_name,'') AS [ITEMNAME], (CASE WHEN AGENCYSALEORDER.ASO_ORDERON = 'PCS' THEN (AGENCYSALEORDER_DESC.ASO_MTRS - AGENCYSALEORDER_DESC.ASO_RECDQTY) ELSE (AGENCYSALEORDER_DESC.ASO_QTY - AGENCYSALEORDER_DESC.ASO_RECDQTY) END) AS [QTY],  (CASE WHEN AGENCYSALEORDER.ASO_ORDERON = 'PCS' THEN (AGENCYSALEORDER_DESC.ASO_MTRS - AGENCYSALEORDER_DESC.ASO_RECDQTY) ELSE (AGENCYSALEORDER_DESC.ASO_MTRS - AGENCYSALEORDER_DESC.ASO_RECDMTRS) END) AS [MTRS], AGENCYSALEORDER.ASO_remarks AS REMARKS, AGENCYSALEORDER_DESC.ASO_GRIDSRNO AS GRIDSRNO, ISNULL(PACKINGLEDGERS.Acc_cmpname, '') AS DELIVERYAT, ISNULL(DESIGN_NO,'') AS DESIGNNO, ISNULL(COLOR_NAME,'') AS COLOR, ISNULL(TRANSLEDGERS.ACC_CMPNAME,'') AS TRANSNAME, ISNULL(AGENCYSALEORDER.ASO_REFNO,'') AS REFNO, AGENCYSALEORDER_DESC.ASO_RATE AS RATE, ISNULL(CITYMASTER.CITY_NAME,'') AS CITYNAME, 'AGENCYSALEORDER' AS TYPE, ISNULL(AGENCYSALEORDER_DESC.ASO_PARTYPONO,'') AS GRIDPARTYPONO, ISNULL(PACKINGTYPEMASTER.PACKINGTYPE_NAME,'') AS PACKINGTYPE, ISNULL(AGENCYSALEORDER_DESC.ASO_GRIDREMARKS, '') AS GRIDDESC, AGENCYSALEORDER_DESC.ASO_QTY AS PERQTY, ISNULL(GROUPOFCOMPANIESMASTER.GOC_NAME, '') AS GOC  FROM AGENCYSALEORDER INNER JOIN LEDGERS ON AGENCYSALEORDER.ASO_ledgerid = LEDGERS.Acc_id INNER JOIN AGENCYSALEORDER_DESC ON AGENCYSALEORDER.ASO_no = AGENCYSALEORDER_DESC.ASO_NO AND AGENCYSALEORDER.ASO_YEARID = AGENCYSALEORDER_DESC.ASO_YEARID LEFT OUTER JOIN PACKINGTYPEMASTER ON AGENCYSALEORDER.ASO_PACKINGTYPEID = PACKINGTYPEMASTER.PACKINGTYPE_ID LEFT OUTER JOIN LEDGERS AS PACKINGLEDGERS ON AGENCYSALEORDER.ASO_PACKINGID = PACKINGLEDGERS.Acc_id LEFT OUTER JOIN ITEMMASTER ON AGENCYSALEORDER_DESC.ASO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGER ON AGENCYSALEORDER.ASO_Agentid = AGENTLEDGER.Acc_id LEFT OUTER JOIN ADDRESSMASTER ON AGENCYSALEORDER.ASO_HASTEID = ADDRESSMASTER.ADDRESS_ID LEFT OUTER JOIN DESIGNMASTER ON AGENCYSALEORDER_DESC.ASO_DESIGNID = DESIGN_ID LEFT OUTER JOIN COLORMASTER ON AGENCYSALEORDER_DESC.ASO_COLORID = COLOR_ID LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON AGENCYSALEORDER.ASO_TRANSID = TRANSLEDGERS.ACC_ID LEFT OUTER JOIN CITYMASTER ON AGENCYSALEORDER.ASO_CITYID = CITYMASTER.CITY_ID LEFT OUTER JOIN GROUPOFCOMPANIESMASTER ON LEDGERS.ACC_GOCID = GROUPOFCOMPANIESMASTER.GOC_ID WHERE  AGENCYSALEORDER.ASO_VERIFIED=1 AND  AGENCYSALEORDER.ASO_YEARID = " & YearId & WHERE & " UNION ALL SELECT OPENINGAGENCYSALEORDER.OPASO_no AS SONO, OPENINGAGENCYSALEORDER.OPASO_date AS DATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGER.Acc_cmpname, '') AS AGENTNAME, OPENINGAGENCYSALEORDER.OPASO_pono AS [PONO], ISNULL(ITEMMASTER.item_name,'') AS [ITEMNAME],  (CASE WHEN OPENINGAGENCYSALEORDER.OPASO_ORDERON = 'PCS' THEN (OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY) ELSE (OPENINGAGENCYSALEORDER_DESC.OPASO_QTY - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY) END) AS [QTY], (CASE WHEN OPENINGAGENCYSALEORDER.OPASO_ORDERON = 'PCS' THEN (OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY) ELSE (OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDMTRS) END) AS [MTRS], OPENINGAGENCYSALEORDER.OPASO_remarks AS REMARKS, OPENINGAGENCYSALEORDER_DESC.OPASO_GRIDSRNO AS GRIDSRNO, ISNULL(PACKINGLEDGERS.Acc_cmpname, '') AS DELIVERYAT, ISNULL(DESIGN_NO,'') AS DESIGNNO, ISNULL(COLOR_NAME,'') AS COLOR, ISNULL(TRANSLEDGERS.ACC_CMPNAME,'') AS TRANSNAME, ISNULL(OPENINGAGENCYSALEORDER.OPASO_REFNO,'') AS REFNO, OPENINGAGENCYSALEORDER_DESC.OPASO_RATE AS RATE, ISNULL(CITYMASTER.CITY_NAME,'') AS CITYNAME, 'OPENING' AS TYPE, ISNULL(OPENINGAGENCYSALEORDER_DESC.OPASO_PARTYPONO,'') AS GRIDPARTYPONO, ISNULL(PACKINGTYPEMASTER.PACKINGTYPE_NAME,'') AS PACKINGTYPE , ISNULL(OPENINGAGENCYSALEORDER_DESC.OPASO_GRIDREMARKS, '') AS GRIDDESC, OPENINGAGENCYSALEORDER_DESC.OPASO_QTY AS PERQTY, GROUPOFCOMPANIESMASTER.GOC_NAME AS  GOC FROM OPENINGAGENCYSALEORDER INNER JOIN LEDGERS ON OPENINGAGENCYSALEORDER.OPASO_ledgerid = LEDGERS.Acc_id INNER JOIN OPENINGAGENCYSALEORDER_DESC ON OPENINGAGENCYSALEORDER.OPASO_no = OPENINGAGENCYSALEORDER_DESC.OPASO_NO AND OPENINGAGENCYSALEORDER.OPASO_YEARID = OPENINGAGENCYSALEORDER_DESC.OPASO_YEARID LEFT OUTER JOIN PACKINGTYPEMASTER ON OPENINGAGENCYSALEORDER.OPASO_PACKINGTYPEID = PACKINGTYPEMASTER.PACKINGTYPE_ID LEFT OUTER JOIN LEDGERS AS PACKINGLEDGERS ON OPENINGAGENCYSALEORDER.OPASO_PACKINGID = PACKINGLEDGERS.Acc_id LEFT OUTER JOIN ITEMMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGER ON OPENINGAGENCYSALEORDER.OPASO_Agentid = AGENTLEDGER.Acc_id LEFT OUTER JOIN ADDRESSMASTER ON OPENINGAGENCYSALEORDER.OPASO_HASTEID = ADDRESSMASTER.ADDRESS_ID LEFT OUTER JOIN DESIGNMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_DESIGNID = DESIGN_ID LEFT OUTER JOIN COLORMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_COLORID = COLOR_ID LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON OPENINGAGENCYSALEORDER.OPASO_TRANSID = TRANSLEDGERS.ACC_ID LEFT OUTER JOIN CITYMASTER ON OPENINGAGENCYSALEORDER.OPASO_CITYID = CITYMASTER.CITY_ID LEFT OUTER JOIN GROUPOFCOMPANIESMASTER ON LEDGERS.ACC_GOCID = GROUPOFCOMPANIESMASTER.GOC_ID WHERE OPENINGAGENCYSALEORDER.OPASO_VERIFIED=1 AND OPENINGAGENCYSALEORDER.OPASO_YEARID = " & YearId & OPWHERE & "  UNION ALL SELECT ALLPURCHASEORDER.PO_no AS SONO, ALLPURCHASEORDER.PO_date AS DATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGER.Acc_cmpname, '') AS AGENTNAME, ALLPURCHASEORDER.PO_REFNO AS [PONO], ISNULL(ITEMMASTER.item_name,'') AS [ITEMNAME], (CASE WHEN ALLPURCHASEORDER.PO_ORDERON = 'PCS' THEN (ALLPURCHASEORDER_DESC.PO_MTRS - ALLPURCHASEORDER_DESC.PO_RECDQTY) ELSE (ALLPURCHASEORDER_DESC.PO_QTY - ALLPURCHASEORDER_DESC.PO_RECDQTY) END) AS [QTY],  (CASE WHEN ALLPURCHASEORDER.PO_ORDERON = 'PCS' THEN (ALLPURCHASEORDER_DESC.PO_MTRS - ALLPURCHASEORDER_DESC.PO_RECDQTY) ELSE (ALLPURCHASEORDER_DESC.PO_MTRS - ALLPURCHASEORDER_DESC.PO_RECDMTRS) END) AS [MTRS], ALLPURCHASEORDER.PO_remarks AS REMARKS, ALLPURCHASEORDER_DESC.PO_GRIDSRNO AS GRIDSRNO, '' AS DELIVERYAT, ISNULL(DESIGN_NO,'') AS DESIGNNO, ISNULL(COLOR_NAME,'') AS COLOR, ISNULL(TRANSLEDGERS.ACC_CMPNAME,'') AS TRANSNAME, ISNULL(ALLPURCHASEORDER.PO_REFNO,'') AS REFNO, ALLPURCHASEORDER_DESC.PO_RATE AS RATE, '' AS CITYNAME, ALLPURCHASEORDER.TYPE, '' AS GRIDPARTYPONO, '' AS PACKINGTYPE, ISNULL(ALLPURCHASEORDER_DESC.PO_GRIDREMARKS, '') AS GRIDDESC, ALLPURCHASEORDER_DESC.PO_QTY AS PERQTY, ISNULL(GROUPOFCOMPANIESMASTER.GOC_NAME, '') AS GOC FROM ALLPURCHASEORDER INNER JOIN LEDGERS ON ALLPURCHASEORDER.PO_ledgerid = LEDGERS.Acc_id INNER JOIN ALLPURCHASEORDER_DESC ON ALLPURCHASEORDER.PO_no = ALLPURCHASEORDER_DESC.PO_NO AND ALLPURCHASEORDER.PO_YEARID = ALLPURCHASEORDER_DESC.PO_YEARID LEFT OUTER JOIN ITEMMASTER ON ALLPURCHASEORDER_DESC.PO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGER ON ALLPURCHASEORDER.PO_BROKERID = AGENTLEDGER.Acc_id LEFT OUTER JOIN DESIGNMASTER ON ALLPURCHASEORDER_DESC.PO_DESIGNID = DESIGN_ID LEFT OUTER JOIN COLORMASTER ON ALLPURCHASEORDER_DESC.PO_COLORID = COLOR_ID LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON ALLPURCHASEORDER.PO_TRANSID = TRANSLEDGERS.ACC_ID LEFT OUTER JOIN GROUPOFCOMPANIESMASTER ON LEDGERS.ACC_GOCID = GROUPOFCOMPANIESMASTER.GOC_ID WHERE  ALLPURCHASEORDER.PO_VERIFIED=1 AND  ALLPURCHASEORDER.PO_YEARID = " & YearId & " AND (CASE WHEN '" & GOCNAME & "' = '' THEN ISNULL(LEDGERS.ACC_CMPNAME,'') ELSE ISNULL(GROUPOFCOMPANIESMASTER.GOC_NAME,'') END) = (CASE WHEN '" & GOCNAME & "' = '' THEN '" & SELLERNAME & "' ELSE '" & GOCNAME & "' END) and '" & BUYERNAME & "' = 'ABHEE FABRICS LLP [ BUYER ]' And (CASE WHEN ALLPURCHASEORDER.PO_ORDERON = 'PCS' THEN (ALLPURCHASEORDER_DESC.PO_MTRS - ALLPURCHASEORDER_DESC.PO_RECDQTY) ELSE (ALLPURCHASEORDER_DESC.PO_MTRS - ALLPURCHASEORDER_DESC.PO_RECDMTRS) END) > 0 AND ALLPURCHASEORDER_DESC.PO_CLOSED=0  UNION ALL SELECT ALLSALEORDER.SO_no AS SONO, ALLSALEORDER.SO_date AS DATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGER.Acc_cmpname, '') AS AGENTNAME, ALLSALEORDER.SO_pono AS [PONO], ISNULL(ITEMMASTER.item_name,'') AS [ITEMNAME], (CASE WHEN ALLSALEORDER.SO_ORDERON = 'PCS' THEN (ALLSALEORDER_DESC.SO_MTRS - ALLSALEORDER_DESC.SO_RECDQTY) ELSE (ALLSALEORDER_DESC.SO_QTY - ALLSALEORDER_DESC.SO_RECDQTY) END) AS [QTY],  (CASE WHEN ALLSALEORDER.SO_ORDERON = 'PCS' THEN (ALLSALEORDER_DESC.SO_MTRS - ALLSALEORDER_DESC.SO_RECDQTY) ELSE (ALLSALEORDER_DESC.SO_MTRS - ALLSALEORDER_DESC.SO_RECDMTRS) END) AS [MTRS], ALLSALEORDER.SO_remarks AS REMARKS, ALLSALEORDER_DESC.SO_GRIDSRNO AS GRIDSRNO, ISNULL(PACKINGLEDGERS.Acc_cmpname, '') AS DELIVERYAT, ISNULL(DESIGN_NO,'') AS DESIGNNO, ISNULL(COLOR_NAME,'') AS COLOR, ISNULL(TRANSLEDGERS.ACC_CMPNAME,'') AS TRANSNAME, ISNULL(ALLSALEORDER.SO_REFNO,'') AS REFNO, ALLSALEORDER_DESC.SO_RATE AS RATE, ISNULL(CITYMASTER.CITY_NAME,'') AS CITYNAME, ALLSALEORDER.TYPE, '' AS GRIDPARTYPONO, ISNULL(PACKINGTYPEMASTER.PACKINGTYPE_NAME,'') AS PACKINGTYPE, ISNULL(ALLSALEORDER_DESC.SO_GRIDREMARKS, '') AS GRIDDESC, ALLSALEORDER_DESC.SO_QTY AS PERQTY, ISNULL(GROUPOFCOMPANIESMASTER.GOC_NAME, '') AS GOC   FROM ALLSALEORDER INNER JOIN LEDGERS ON ALLSALEORDER.SO_ledgerid = LEDGERS.Acc_id INNER JOIN ALLSALEORDER_DESC ON ALLSALEORDER.SO_no = ALLSALEORDER_DESC.SO_NO AND ALLSALEORDER.SO_YEARID = ALLSALEORDER_DESC.SO_YEARID LEFT OUTER JOIN PACKINGTYPEMASTER ON ALLSALEORDER.SO_PACKINGTYPEID = PACKINGTYPEMASTER.PACKINGTYPE_ID LEFT OUTER JOIN LEDGERS AS PACKINGLEDGERS ON ALLSALEORDER.SO_PACKINGID = PACKINGLEDGERS.Acc_id LEFT OUTER JOIN ITEMMASTER ON ALLSALEORDER_DESC.SO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGER ON ALLSALEORDER.SO_Agentid = AGENTLEDGER.Acc_id LEFT OUTER JOIN ADDRESSMASTER ON ALLSALEORDER.SO_HASTEID = ADDRESSMASTER.ADDRESS_ID LEFT OUTER JOIN DESIGNMASTER ON ALLSALEORDER_DESC.SO_DESIGNID = DESIGN_ID LEFT OUTER JOIN COLORMASTER ON ALLSALEORDER_DESC.SO_COLORID = COLOR_ID LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON ALLSALEORDER.SO_TRANSID = TRANSLEDGERS.ACC_ID LEFT OUTER JOIN CITYMASTER ON ALLSALEORDER.SO_CITYID = CITYMASTER.CITY_ID LEFT OUTER JOIN GROUPOFCOMPANIESMASTER ON LEDGERS.ACC_GOCID = GROUPOFCOMPANIESMASTER.GOC_ID WHERE  ALLSALEORDER.SO_YEARID = " & YearId & " AND (CASE WHEN '" & GOCNAME & "' = '' THEN ISNULL(LEDGERS.ACC_CMPNAME,'') ELSE ISNULL(GROUPOFCOMPANIESMASTER.GOC_NAME,'') END) = (CASE WHEN '" & GOCNAME & "' = '' THEN '" & BUYERNAME & "' ELSE '" & GOCNAME & "' END) AND '" & SELLERNAME & "' = 'ABHEE FABRICS LLP [ SELLER ]' and (CASE WHEN ALLSALEORDER.SO_ORDERON = 'PCS' THEN (ALLSALEORDER_DESC.SO_MTRS - ALLSALEORDER_DESC.SO_RECDQTY) ELSE (ALLSALEORDER_DESC.SO_MTRS - ALLSALEORDER_DESC.SO_RECDMTRS) END) > 0 AND ALLSALEORDER_DESC.SO_CLOSED=0 ) AS T", " ORDER BY T.DATE, T.SONO, T.GRIDSRNO")

            gridbilldetails.DataSource = DT

            If DT.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If

        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        Finally
            Cursor.Current = Cursors.Default
        End Try
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try
            DT.Columns.Add("DATE")
            DT.Columns.Add("NAME")
            DT.Columns.Add("ITEMNAME")
            DT.Columns.Add("DESIGN")
            DT.Columns.Add("COLOR")
            DT.Columns.Add("QTY")
            DT.Columns.Add("MTRS")
            DT.Columns.Add("PONO")
            DT.Columns.Add("AGENTNAME")
            DT.Columns.Add("TRANSNAME")
            DT.Columns.Add("CITYNAME")
            DT.Columns.Add("DELIVERYAT")
            DT.Columns.Add("REFNO")
            DT.Columns.Add("RATE")
            DT.Columns.Add("SONO")
            DT.Columns.Add("GRIDSRNO")
            DT.Columns.Add("TYPE")
            DT.Columns.Add("GRIDPARTYPONO")
            DT.Columns.Add("PACKINGTYPE")
            DT.Columns.Add("REMARKS")
            DT.Columns.Add("GRIDDESC")
            DT.Columns.Add("PERQTY")


            Dim TEMPDISPATCHTO As String = ""
            Dim TEMPPARTYPONO As String = ""
            Dim TEMPALLOW As Boolean = False

            'for duplication in magic box invoice
            If FRMSTRING = "MAGICBOX" Then
                Dim checkedCount1 As Integer = 0
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    If Convert.ToBoolean(dtrow("CHK")) = True Then
                        checkedCount1 += 1
                    End If
                Next
                If checkedCount1 > 1 Then
                    MsgBox("You cannot select multiple orders")
                    DT.Columns.Clear()
                    Exit Sub
                End If
            End If

            'WE NEED TO INTIMATE IF WE HAVE SELECTED ORDER OF DIFF SHIPTO PARTY

            For i As Integer = 0 To gridbill.RowCount - 1
                Dim dtrow As DataRow = gridbill.GetDataRow(i)
                If Convert.ToBoolean(dtrow("CHK")) = True Then
                    If TEMPDISPATCHTO = "" And dtrow("DELIVERYAT") <> "" Then
                        TEMPDISPATCHTO = dtrow("DELIVERYAT")
                    ElseIf TEMPDISPATCHTO <> "" And dtrow("DELIVERYAT") <> "" And TEMPDISPATCHTO <> dtrow("DELIVERYAT") Then
                        If TEMPALLOW = False Then
                            If MsgBox("You have selected Orders of Different Ship To Party, Wish to Proceed?", MsgBoxStyle.YesNo) = MsgBoxResult.No Then
                                DT.Rows.Clear()
                                Exit For
                            Else
                                TEMPALLOW = True
                            End If
                        End If
                    End If


                    If TEMPPARTYPONO = "" And dtrow("PONO") <> "" Then
                        TEMPPARTYPONO = dtrow("PONO")
                    ElseIf TEMPPARTYPONO <> "" And dtrow("PONO") <> "" And TEMPPARTYPONO <> dtrow("PONO") Then
                        If TEMPALLOW = False Then
                            If MsgBox("You have selected Orders of Different Party PO No, Wish to Proceed?", MsgBoxStyle.YesNo) = MsgBoxResult.No Then
                                DT.Rows.Clear()
                                Exit For
                            Else
                                TEMPALLOW = True
                            End If
                        End If
                    End If


                    DT.Rows.Add(dtrow("DATE"), dtrow("NAME"), dtrow("ITEMNAME"), dtrow("DESIGNNO"), dtrow("COLOR"), Val(dtrow("QTY")), Val(dtrow("MTRS")), dtrow("PONO"), dtrow("AGENTNAME"), dtrow("TRANSNAME"), dtrow("CITYNAME"), dtrow("DELIVERYAT"), dtrow("REFNO"), Val(dtrow("RATE")), Val(dtrow("SONO")), Val(dtrow("GRIDSRNO")), dtrow("TYPE"), dtrow("GRIDPARTYPONO"), dtrow("PACKINGTYPE"), dtrow("REMARKS"), dtrow("GRIDDESC"), Val(dtrow("PERQTY")))
                End If
            Next



            Me.Close()

        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub CHKSELECTALL_CheckedChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CHKSELECTALL.CheckedChanged
        Try
            If gridbilldetails.Visible = True Then
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    dtrow("CHK") = CHKSELECTALL.Checked
                Next
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub SelectAgencySO_Shown(sender As Object, e As EventArgs) Handles Me.Shown
        Try

            If ClientName = "MASHOK" Or ClientName = "ABHEE" Then
                GDESIGNNO.Visible = False
                GCOLOR.Visible = False
                GREFNO.Visible = False
                GGRIDDESC.VisibleIndex = GITEM.VisibleIndex + 1
                GRATE.VisibleIndex = GGRIDDESC.VisibleIndex + 1
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub
End Class


