DECLARE @SUBJECT VARCHAR(100), @ENTRYBODY VARCHAR(MAX), @TOTALMTRS DECIMAL(18,2), @TOTALCANCELLEDMTRS DECIMAL(18,2), @CMPNAME VARCHAR(100), @YEARID INT
SET @CMPNAME = 'SUPRIYA SILK INDUSTRIES'
SET @YEARID=(SELECT TOP 1 YEAR_ID FROM YEARMASTER inner join CMPMASTER ON YEAR_CMPID = CMP_ID WHERE CMP_DISPLAYEDNAME = @CMPNAME  and year_startdate= CASE WHEN MONTH(GETDATE()) > 3 THEN CAST(YEAR(GETDATE()) AS VARCHAR(4)) + '-04-01' ELSE CAST(YEAR(GETDATE())-1 AS VARCHAR(4)) + '-04-01' END ORDER BY YEAR_STARTDATE DESC)

SELECT @TOTALMTRS = SUM(SALEORDER_DESC.SO_MTRS)  FROM  SALEORDER_DESC INNER JOIN SALEORDER ON SALEORDER.SO_NO = SALEORDER_DESC.SO_NO AND SALEORDER.SO_YEARID = SALEORDER_DESC.SO_YEARID WHERE SO_CLOSED = 'FALSE' AND SO_DATE = CAST(GETDATE() AS DATE) AND SALEORDER.SO_YEARID = @YEARID
SELECT @TOTALCANCELLEDMTRS = SUM(SALEORDER_DESC.SO_MTRS)  FROM  SALEORDER_DESC INNER JOIN SALEORDER ON SALEORDER.SO_NO = SALEORDER_DESC.SO_NO AND SALEORDER.SO_YEARID = SALEORDER_DESC.SO_YEARID WHERE SO_CLOSED = 'TRUE' AND SO_CLOSEDDATE = CAST(GETDATE() AS DATE) AND SALEORDER.SO_YEARID = @YEARID
SET @SUBJECT = 'SSI-DAILY ORDER DETAILS REPORT FOR ' + CAST(DAY( GETDATE()) AS VARCHAR(2)) + '-' + CAST(MONTH( GETDATE()) AS VARCHAR(2)) + '-' + CAST(YEAR( GETDATE()) AS VARCHAR(4))


SET @ENTRYBODY = (SELECT  
[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@width]='80px', TD= T.DATE ,'', 
[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@width]='250px', TD= T.NAME ,'', 
[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@align]='right',[TD/@width]='80px', TD=SUM(CAST(T.MTRS AS DECIMAL(18,2))) ,'',
[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@align]='right',[TD/@width]='100px', TD=SUM(CAST(T.CANCELLEDMTRS AS DECIMAL(18,2))) ,''

FROM 
(
select so_date AS DATE, ISNULL(LEDGERS.Acc_cmpname,'') AS NAME,SUM(CAST(SALEORDER_DESC.SO_MTRS AS DECIMAL(18,2))) AS MTRS, 0 AS CANCELLEDMTRS
FROM SALEORDER INNER JOIN LEDGERS ON so_ledgerid = LEDGERS.ACC_ID INNER JOIN 
SALEORDER_DESC ON SALEORDER.SO_NO = SALEORDER_DESC.SO_NO AND SALEORDER.SO_YEARID = SALEORDER_DESC.SO_YEARID
where SO_CLOSED = 'FALSE' AND SO_DATE = CAST(GETDATE() AS DATE) AND SALEORDER.SO_YEARID = @YEARID
GROUP BY SO_DATE, ISNULL(LEDGERS.ACC_CMPNAME,'')

UNION ALL
select SO_CLOSEDDATE, ISNULL(LEDGERS.Acc_cmpname,''),0, SUM(CAST(SALEORDER_DESC.SO_MTRS AS DECIMAL(18,2))) AS CANCELLEDMTRS
FROM SALEORDER INNER JOIN LEDGERS ON so_ledgerid = LEDGERS.ACC_ID INNER JOIN 
SALEORDER_DESC ON SALEORDER.SO_NO = SALEORDER_DESC.SO_NO AND SALEORDER.SO_YEARID = SALEORDER_DESC.SO_YEARID
WHERE SO_CLOSED = 'TRUE' AND SO_CLOSEDDATE = CAST(GETDATE() AS DATE) AND SALEORDER.SO_YEARID = @YEARID
GROUP BY SO_CLOSEDDATE, ISNULL(LEDGERS.ACC_CMPNAME,'')
) AS T
GROUP BY T.DATE, T.NAME


FOR XML PATH ('tr'))



DECLARE @BODY VARCHAR(MAX)
SET @BODY = N'<H1 style="font-family:Tahoma; font-size:11px;">DAILY ORDER DETAILS</H1>' +
				N'<Table Border = "1">' + 
				N'<Tr style="font-family:Tahoma; font-size:11px;"><Th>Date</Th><Th>Name</Th><Th>Mtrs</Th><Th>Cancelled Mtrs</Th></Tr>'+
				+ISNULL(@ENTRYBODY,'')+ N'<tfoot><tr><td colspan="2"; style="font-family:Tahoma; font-size:11px; font-weight:bold; color:black;" bgcolor="yellow">GRAND TOTAL:</td>
				<td style="font-family:Tahoma; font-size:11px; font-weight:bold; color:black;" align="right" bgcolor="yellow">' + CAST(@TOTALMTRS AS VARCHAR) + N'</td>
				<td style="font-family:Tahoma; font-size:11px; font-weight:bold; color:black;" align="right" bgcolor="yellow">' + CAST(@TOTALCANCELLEDMTRS AS VARCHAR) + N'</td>
				</tr></tfoot></Table></html>'



DECLARE @FINALBODY VARCHAR(MAX)
SET @FINALBODY = @BODY 


EXEC msdb.dbo.sp_send_dbmail
@profile_name='TEXTRADE',
@recipients='gulkitjain@gmail.com',	--infoavisindustries@gmail.com;gm@avisindustries.in;
@subject=@SUBJECT,
@body=@FINALBODY,
@body_format = 'HTML'