DECLARE @SUBJECT VARCHAR(100), @ENTRYBODY VARCHAR(MAX), @PENDINGPO DECIMAL(18,2), @PENDINGPOVALUE  DECIMAL(18,2), @NOOFPO INT, @PENDINGSO DECIMAL(18,2), @PENDINGSOVALUE  DECIMAL(18,2), @NOOFSO INT, @TOTALINVAMT DECIMAL(18,2), @TOTALINVMTRS DECIMAL(18,2), @NOOFINV INT, @RECDAMT DECIMAL(18,2), @PAIDAMT DECIMAL(18,2), @BANKBALANCE DECIMAL(18,2), @DYEINGREC DECIMAL(18,2), @JOBIN DECIMAL(18,2), @DYEINGBALANCE DECIMAL(18,2)
SELECT @PENDINGPO =  SUM(PO_MTRS - PO_RECDMTRS), @PENDINGPOVALUE = ROUND(SUM((PO_MTRS - PO_RECDMTRS)*PO_RATE),2) FROM ALLPURCHASEORDER_DESC INNER JOIN ALLPURCHASEORDER ON ALLPURCHASEORDER.PO_NO = ALLPURCHASEORDER_DESC.PO_NO AND ALLPURCHASEORDER.PO_YEARID = ALLPURCHASEORDER_DESC.PO_YEARID WHERE PO_CLOSED = 0 AND (PO_MTRS - PO_RECDMTRS) > 0 
SELECT DISTINCT @NOOFPO = COUNT (PO_NO) FROM ALLPURCHASEORDER_DESC WHERE PO_CLOSED = 0 AND (PO_MTRS - PO_RECDMTRS) > 0 
SELECT @PENDINGSO =  SUM(SO_MTRS - SO_RECDMTRS), @PENDINGSOVALUE = ROUND(SUM((SO_MTRS - SO_RECDMTRS)*SO_RATE),2) FROM ALLSALEORDER_DESC INNER JOIN ALLSALEORDER ON ALLSALEORDER.SO_NO = ALLSALEORDER_DESC.SO_NO AND ALLSALEORDER.SO_YEARID = ALLSALEORDER_DESC.SO_YEARID WHERE SO_CLOSED = 0 AND (SO_MTRS - SO_RECDMTRS) > 0 
SELECT DISTINCT @NOOFSO = COUNT (SO_NO) FROM ALLSALEORDER_DESC WHERE SO_CLOSED = 0 AND (SO_MTRS - SO_RECDMTRS) > 0 
SELECT @TOTALINVAMT =  SUM(INVOICE_SUBTOTAL), @TOTALINVMTRS = SUM(INVOICE_TOTALMTRS), @NOOFINV = COUNT(INVOICE_NO) FROM INVOICEMASTER WHERE INVOICE_DATE = CAST(GETDATE() AS DATE)
SET @SUBJECT = 'MIS SUMMARY REPORT FOR ' + CAST(DAY( GETDATE()) AS VARCHAR(2)) + '-' + CAST(MONTH( GETDATE()) AS VARCHAR(2)) + '-' + CAST(YEAR( GETDATE()) AS VARCHAR(4))


SET @ENTRYBODY = (SELECT  
[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@width]='80px', TD= RECEIPT_DATE ,'', 
[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@width]='250px', TD= ISNULL(LEDGERS.ACC_CMPNAME,'') ,'', 
[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@align]='right',[TD/@width]='80px', TD=SUM(CAST(RECEIPTMASTER.receipt_total AS DECIMAL(18,2))) ,''

FROM RECEIPTMASTER INNER JOIN LEDGERS ON receipt_ledgerid = LEDGERS.ACC_ID 
WHERE RECEIPT_DATE = CAST(GETDATE() AS DATE)
GROUP BY RECEIPT_DATE, ISNULL(LEDGERS.ACC_CMPNAME,'')




FOR XML PATH ('tr'))


DECLARE @BODY VARCHAR(MAX)
SET @BODY = N'<H1 style="font-family:Tahoma; font-size:11px;">DAILY RECEIPT DETAILS</H1>' +
				N'<Table Border = "1">' + 
				N'<Tr style="font-family:Tahoma; font-size:11px;"><Th>Date</Th><Th>Name</Th><Th>Amount</Th></Tr>'+
				+ISNULL(@ENTRYBODY,'')+ N'<tfoot><tr><td colspan="2"; style="font-family:Tahoma; font-size:11px; font-weight:bold; color:black;" bgcolor="yellow">GRAND TOTAL:</td>
				<td style="font-family:Tahoma; font-size:11px; font-weight:bold; color:black;" align="right" bgcolor="yellow">' + CAST(@TOTALAMT AS VARCHAR) + N'</td>
				</tr></tfoot></Table></html>'



DECLARE @FINALBODY VARCHAR(MAX)
SET @FINALBODY = @BODY 


EXEC msdb.dbo.sp_send_dbmail
@profile_name='TEXTRADEMAIL',
@recipients='gulkitjain@gmail.com',	--infoavisindustries@gmail.com;gm@avisindustries.in;
@subject=@SUBJECT,
@body=@FINALBODY,
@body_format = 'HTML'