DECLARE @SUBJECT VARCHAR(100), @ENTRYBODY VARCHAR(MAX), @TOTALMTRS DECIMAL(18,2),  @CMPNAME VARCHAR(100), @YEARID INT, @BODY VARCHAR(MAX)
SET @SUBJECT = 'WEEKLY JOBBER WISE RECEIPT REPORT FROM ' + CAST(DAY(DATEADD(day, -7, GETDATE())) AS VARCHAR(2)) +'-' + CAST(MONTH(DATEADD(day, -7, GETDATE())) AS VARCHAR(2)) + '-' + CAST(YEAR(DATEADD(day, -7, GETDATE())) AS VARCHAR(4))
SET @CMPNAME = 'AVIS INDUSTRIES PVT. LTD.'
SET @YEARID=(SELECT TOP 1 YEAR_ID FROM YEARMASTER inner join CMPMASTER ON YEAR_CMPID = CMP_ID WHERE CMP_DISPLAYEDNAME = @CMPNAME  and year_startdate= CASE WHEN MONTH(GETDATE()) > 3 THEN CAST(YEAR(GETDATE()) AS VARCHAR(4)) + '-04-01' ELSE CAST(YEAR(GETDATE())-1 AS VARCHAR(4)) + '-04-01' END ORDER BY YEAR_STARTDATE DESC)

SET @TOTALMTRS = 0
SELECT @TOTALMTRS =  ISNULL(SUM(MATREC_TOTALRECDMTR),0) FROM MATERIALRECEIPT WHERE MATERIALRECEIPT.MATREC_YEARID = @YEARID  AND CAST(MATREC_DATE AS DATE) > CAST(DATEADD(day, -7, GETDATE()) AS DATE) 


SET @ENTRYBODY = (SELECT
			[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@align]='center',[TD/@width]='60px', TD=CAST(T.RECNO AS INT) ,'',
			[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@align]='center',[TD/@width]='80px', TD= T.DATE,'', 
			[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@width]='250px', TD= T.JOBBERNAME,'', 
			[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@width]='150px', TD= T.DESIGNNO,'', 
			[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@align]='right',[TD/@width]='70px', TD=CAST(T.RECDMTRS AS DECIMAL(18,2)) ,'',
			[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@align]='center',[TD/@width]='80px', TD= T.CARDRECDATE,'', 
			[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@align]='right',[TD/@width]='60px', TD=CAST(T.CARDDAYS AS INT) ,'',
			[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@align]='center',[TD/@width]='80px', TD= T.PROGISSDATE,'', 
			[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@align]='right',[TD/@width]='60px', TD=CAST(T.PROGDAYS AS INT),''
			FROM
			(
			SELECT MATERIALRECEIPT.MATREC_NO AS RECNO, MATERIALRECEIPT.MATREC_DATE AS DATE, LEDGERS.Acc_cmpname AS JOBBERNAME, ISNULL(DESIGNMASTER.DESIGN_NO,'') AS DESIGNNO, MATERIALRECEIPT_PROGDETAILS.MATREC_MTRS AS RECDMTRS,
	CASE WHEN ALLPROGRAMMASTER.PROGRAM_CARDRECDATE <> '' THEN CONVERT(DATE, ALLPROGRAMMASTER.PROGRAM_CARDRECDATE,103 ) ELSE CAST(ALLPROGRAMMASTER.PROGRAM_DATE  AS DATE) END AS CARDRECDATE,
	DATEDIFF(DAY,CASE WHEN ALLPROGRAMMASTER.PROGRAM_CARDRECDATE <> '' THEN CONVERT(DATE, ALLPROGRAMMASTER.PROGRAM_CARDRECDATE,103 ) ELSE CAST(ALLPROGRAMMASTER.PROGRAM_DATE AS DATE) END, MATERIALRECEIPT.MATREC_DATE) AS CARDDAYS,
	CASE WHEN ALLPROGRAMMASTER_DESC.PROGRAM_PROGISSDATE <> '' THEN CONVERT(DATE,ALLPROGRAMMASTER_DESC.PROGRAM_PROGISSDATE ,103) ELSE CAST(ALLPROGRAMMASTER.PROGRAM_DATE AS DATE) END AS PROGISSDATE,
	DATEDIFF(DAY,CASE WHEN ALLPROGRAMMASTER_DESC.PROGRAM_PROGISSDATE <> '' THEN CONVERT(DATE,ALLPROGRAMMASTER_DESC.PROGRAM_PROGISSDATE,103) ELSE CAST(ALLPROGRAMMASTER.PROGRAM_DATE AS DATE) END, MATERIALRECEIPT.MATREC_DATE) AS PROGDAYS
			FROM            MATERIALRECEIPT INNER JOIN
                         LEDGERS ON MATERIALRECEIPT.MATREC_ledgerid = LEDGERS.Acc_id INNER JOIN
                         MATERIALRECEIPT_PROGDETAILS ON MATERIALRECEIPT.MATREC_NO = MATERIALRECEIPT_PROGDETAILS.MATREC_NO AND MATERIALRECEIPT.MATREC_yearid = MATERIALRECEIPT_PROGDETAILS.MATREC_YEARID LEFT OUTER JOIN
						 DESIGNMASTER ON MATERIALRECEIPT_PROGDETAILS.MATREC_DESIGNID = DESIGNMASTER.DESIGN_ID INNER JOIN
						 ALLPROGRAMMASTER_DESC ON MATERIALRECEIPT_PROGDETAILS.MATREC_FROMNO = ALLPROGRAMMASTER_DESC.PROGRAM_NO AND MATERIALRECEIPT_PROGDETAILS.MATREC_FROMSRNO = ALLPROGRAMMASTER_DESC.PROGRAM_GRIDSRNO AND MATERIALRECEIPT_PROGDETAILS.MATREC_FROMTYPE = ALLPROGRAMMASTER_DESC.PROGRAM_TYPE AND MATERIALRECEIPT_PROGDETAILS.MATREC_YEARID = ALLPROGRAMMASTER_DESC.PROGRAM_YEARID INNER JOIN
						 ALLPROGRAMMASTER ON ALLPROGRAMMASTER_DESC.PROGRAM_NO = ALLPROGRAMMASTER.PROGRAM_NO AND ALLPROGRAMMASTER_DESC.PROGRAM_TYPE = ALLPROGRAMMASTER.PROGRAM_TYPE AND ALLPROGRAMMASTER_DESC.PROGRAM_YEARID = ALLPROGRAMMASTER.PROGRAM_YEARID
			WHERE        (MATERIALRECEIPT.MATREC_yearid = @YEARID) AND CAST(MATERIALRECEIPT.MATREC_DATE  AS DATE) > CAST(DATEADD(day, -7, GETDATE()) AS DATE) 
			) AS T
			ORDER BY JOBBERNAME, DESIGNNO 
			FOR XML PATH ('tr'))

			
SET @BODY = ISNULL(@BODY,'') + N'<H1 style="font-family:Tahoma; font-size:11px;">WEEKLY JOBBER WISE RECEIPT REPORT FROM ' + CAST(DAY(DATEADD(day, -7, GETDATE())) AS VARCHAR(2)) +'-' + CAST(MONTH(DATEADD(day, -7, GETDATE())) AS VARCHAR(2)) + '-' + CAST(YEAR(DATEADD(day, -7, GETDATE())) AS VARCHAR(4)) + '</H1>' +
							N'<Table Border = "1">' + 
							N'<Tr style="font-family:Tahoma; font-size:11px;"><Th>Rec No</Th><Th>Date</Th><Th>Jobber Name</Th><Th>Design No</Th><Th>Recd Mtrs</Th><Th>Card Rec Dt</Th><Th>Card Days</Th><Th>Prog Iss Date</Th><Th>Prog Days</Th></Tr>'+
							+ISNULL(@ENTRYBODY,'')+ N'<tfoot><tr><td colspan="5"; style="font-family:Tahoma; font-size:11px; font-weight:bold; color:black;" bgcolor="yellow">TOTAL:</td>
							<td style="font-family:Tahoma; font-size:11px; font-weight:bold; color:black;" align="right" bgcolor="yellow">' + CAST(@TOTALMTRS AS VARCHAR) + N'</td>
							<td colspan="4"; style="font-family:Tahoma; font-size:11px; font-weight:bold; color:black;" bgcolor="yellow"></td>
							</tr></tfoot></Table></html>'

			

DECLARE @FINALBODY VARCHAR(MAX)
SET @FINALBODY = @BODY 


EXEC msdb.dbo.sp_send_dbmail
@profile_name='TEXTRADE',
@recipients='gulkitjain@gmail.com',
@subject=@SUBJECT,
@body=@FINALBODY,
@body_format = 'HTML'








