DECLARE @CMPID INT, @SELECTEDYEARID INT, @YEARID INT, @USERID INT
SET @CMPID = 2
SET @USERID = 1
SET @YEARID = 8
SET @SELECTEDYEARID = 4


-- ************* AGENCYINVOICEMASTER ******************

DELETE FROM AGENCYINVOICEMASTER WHERE AGENCYINVOICEMASTER.AINVOICE_yearid = @YEARID AND AGENCYINVOICEMASTER.AINVOICE_no <= (SELECT MAX(AGENCYINVOICEMASTER.AINVOICE_no) FROM AGENCYINVOICEMASTER WHERE AGENCYINVOICEMASTER.AINVOICE_yearid = @SELECTEDYEARID)


INSERT INTO AGENCYINVOICEMASTER
SELECT AINVOICE_NO, AINVOICE_INITIALS, AINVOICE_SCREENTYPE, NLEDGERS.ACC_ID, AINVOICE_PONO, AINVOICE_PARTYPONO, AINVOICE_PODATE, AINVOICE_BALENOFROM,AINVOICE_BALENOTO,
AINVOICE_DATE, NLOCALTRANSLEDGER.ACC_ID, 0 AS HASTEID, 0 AS AGENTID, AINVOICE_GDNNO, AINVOICE_GDNDATE, AINVOICE_REFNO, 0 AS FORMID, AINVOICE_CRDAYS, AINVOICE_DUEDATE,
PURLEDGER.ACC_ID, TRANSLEDGERS.ACC_ID, AINVOICE_VEHICLENO, AINVOICE_LRNO, AINVOICE_LRDATE, NCITYMASTER.CITY_ID AS TRANSCITYID, NTOCITYMASTER.CITY_ID, NPACKINGLEDGERS.ACC_ID,
AINVOICE_EWAYBILLNO, AINVOICE_GATEPASSNO, AINVOICE_GPDATE,AINVOICE_CHECKED, AINVOICE_DISPUTE, AINVOICE_MANUALGST, AINVOICE_EXPORTGST, AINVOICE_TOTALBALES, AINVOICE_TOTALPCS,
AINVOICE_TOTALMTRS, AINVOICE_TOTALAMT, AINVOICE_TOTALDISCAMT, AINVOICE_TOTALSPDISCAMT, AINVOICE_TOTALOTHERAMT,AINVOICE_TOTALTAXABLEAMT, AINVOICE_CGSTPER, AINVOICE_TOTALCGSTAMT,
AINVOICE_SGSTPER, AINVOICE_TOTALSGSTAMT, AINVOICE_IGSTPER, AINVOICE_TOTALIGSTAMT, AINVOICE_TOTALWITHGST,AINVOICE_APPLYTCS,AINVOICE_TCSPER,AINVOICE_TCSAMT, AINVOICE_AMOUNT,
AINVOICE_CHARGES,AINVOICE_SUBTOTAL,AINVOICE_ROUNDOFF, AINVOICE_GRANDTOTAL,AINVOICE_AMTREC, AINVOICE_EXTRAAMT, AINVOICE_RETURN, AINVOICE_BALANCE,AINVOICE_INWORDS, AINVOICE_REMARKS,
AINVOICE_CHKBARCODE, AINVOICE_DONE, AINVOICE_SONO, AINVOICE_SMSSEND, AINVOICE_PRINT, AINVOICE_TERMID, AINVOICE_PRINTINITIALS,AINVOICE_ROE, AINVOICE_CIF, AINVOICE_EXPTERMS,
AINVOICE_MARKNOS, AINVOICE_EXPINSURANCE, AINVOICE_VESSEL, AINVOICE_LOADINGPORT, AINVOICE_DISCHARGEPORT, AINVOICE_EXPHSN, 0 AS CURRID, AINVOICE_GROSSWT, AINVOICE_NETTWT,
AINVOICE_SQMTRS, AINVOICE_TOTALUSDAMT, AINVOICE_GSTINVRATE, AINVOICE_CUSTOMINVRATE, AINVOICE_EXPDIFF, AINVOICE_INWORDSUSD, AINVOICE_IRNNO, AINVOICE_ACKNO, AINVOICE_ACKDATE,
AINVOICE_QRCODE,AINVOICE_DOCKETNO, AINVOICE_DOCKETDATE, AINVOICE_COURIER, @CMPID, 0 AS LOCATIONID, AINVOICE_USERID, @YEARID, 0 AS [TRANSFER], AINVOICE_CREATED, AINVOICE_MODIFIED, 
AINVOICE_MODIFIEDBY, 0 AS DISPATCHFROMID, AINVOICE_SPECIALREMARKS, AINVOICE_CD, AINVOICE_CHANGEADD, AINVOICE_DELIVERYADD, AINVOICE_SENDWHATSAPP, 0 AS SALESMANID,
AINVOICE_SALETYPE, 0 AS SACCODEID, AINVOICE_MATERIALVALUE, AINVOICE_TOTALWITHMATVALUE, 0 AS COSTCENTRE, 0 AS REFFERID, AINVOICE_TRADINGACC, AINVOICE_COMM, AINVOICE_COMMTPYE,
AINVOICE_COVERNOTEDONE, AINVOICE_MANUALROUNDOFF, AINVOICE_COMPLAINT, AINVOICE_COMPLAINTBY, AINVOICE_COMPLAINTDATE, AINVOICE_HOLDINTCALC
FROM AGENCYINVOICEMASTER INNER JOIN LEDGERS ON AGENCYINVOICEMASTER.AINVOICE_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS LOCALTRANSLEDGER ON AGENCYINVOICEMASTER.AINVOICE_LOCALTRANSID = LOCALTRANSLEDGER.ACC_ID LEFT OUTER JOIN LEDGERS AS NLOCALTRANSLEDGER ON LOCALTRANSLEDGER.ACC_CMPNAME = NLOCALTRANSLEDGER.ACC_CMPNAME AND NLOCALTRANSLEDGER.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS PURLEDGER ON AGENCYINVOICEMASTER.AINVOICE_PURLEDGERID = PURLEDGER.ACC_ID LEFT OUTER JOIN LEDGERS AS NPURLEDGER ON PURLEDGER.ACC_CMPNAME = NPURLEDGER.ACC_CMPNAME AND NPURLEDGER.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS TRANSLEDGERS ON AGENCYINVOICEMASTER.AINVOICE_TRANSID = TRANSLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NTRANSLEDGERS ON TRANSLEDGERS.ACC_CMPNAME = NTRANSLEDGERS.ACC_CMPNAME AND NTRANSLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
CITYMASTER ON AGENCYINVOICEMASTER.AINVOICE_TRANSCITYID = CITYMASTER.CITY_ID LEFT OUTER JOIN CITYMASTER AS NCITYMASTER ON CITYMASTER.CITY_NAME = NCITYMASTER.CITY_NAME AND NCITYMASTER.city_yearid = @YEARID LEFT OUTER JOIN
CITYMASTER AS TOCITYMASTER ON AGENCYINVOICEMASTER.AINVOICE_TOCITYID = TOCITYMASTER.CITY_ID LEFT OUTER JOIN CITYMASTER AS NTOCITYMASTER ON TOCITYMASTER.CITY_NAME = NTOCITYMASTER.CITY_NAME AND NTOCITYMASTER.city_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS PACKINGLEDGERS ON AGENCYINVOICEMASTER.AINVOICE_PACKINGID = PACKINGLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NPACKINGLEDGERS ON PACKINGLEDGERS.ACC_CMPNAME = NPACKINGLEDGERS.ACC_CMPNAME AND NPACKINGLEDGERS.Acc_yearid = @YEARID
WHERE AGENCYINVOICEMASTER.AINVOICE_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND PURLEDGER.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' AND AGENCYINVOICEMASTER.AINVOICE_NO NOT IN (SELECT AINVOICE_NO FROM AGENCYINVOICEMASTER WHERE AINVOICE_YEARID = @YEARID)
ORDER BY AGENCYINVOICEMASTER.AINVOICE_NO DESC


DELETE FROM AGENCYINVOICEMASTER_CHGS WHERE AGENCYINVOICEMASTER_CHGS.AINVOICE_yearid = @YEARID AND AGENCYINVOICEMASTER_CHGS.AINVOICE_no <= (SELECT MAX(AGENCYINVOICEMASTER_CHGS.AINVOICE_no) FROM AGENCYINVOICEMASTER_CHGS WHERE AGENCYINVOICEMASTER_CHGS.AINVOICE_yearid = @SELECTEDYEARID)

INSERT INTO AGENCYINVOICEMASTER_CHGS
SELECT AGENCYINVOICEMASTER.AINVOICE_NO, AGENCYINVOICEMASTER.AINVOICE_INITIALS, AINVOICE_GRIDSRNO, NCHARGESLEDGERS.ACC_ID, AINVOICE_PER, AINVOICE_AMT, AINVOICE_TAXID, @CMPID,
0 AS LOCATIONID, AGENCYINVOICEMASTER.AINVOICE_USERID, @YEARID, 0 AS [TRANSFER]
FROM AGENCYINVOICEMASTER_CHGS INNER JOIN AGENCYINVOICEMASTER ON AGENCYINVOICEMASTER_CHGS.AINVOICE_no = AGENCYINVOICEMASTER.AINVOICE_NO AND AGENCYINVOICEMASTER_CHGS.AINVOICE_yearid = AGENCYINVOICEMASTER.AINVOICE_YEARID INNER JOIN LEDGERS ON AGENCYINVOICEMASTER.AINVOICE_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS CHARGESLEDGERS ON AGENCYINVOICEMASTER_CHGS.AINVOICE_CHARGESID = CHARGESLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NCHARGESLEDGERS ON CHARGESLEDGERS.ACC_CMPNAME = NCHARGESLEDGERS.ACC_CMPNAME AND NCHARGESLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS PURLEDGER ON AGENCYINVOICEMASTER.AINVOICE_PURLEDGERID = PURLEDGER.ACC_ID LEFT OUTER JOIN LEDGERS AS NPURLEDGER ON PURLEDGER.ACC_CMPNAME = NPURLEDGER.ACC_CMPNAME AND NPURLEDGER.Acc_yearid = @YEARID 
WHERE AGENCYINVOICEMASTER.AINVOICE_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND PURLEDGER.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' 
ORDER BY AGENCYINVOICEMASTER.AINVOICE_NO DESC


DELETE FROM AGENCYINVOICEMASTER_DESC WHERE AGENCYINVOICEMASTER_DESC.AINVOICE_yearid = @YEARID AND AGENCYINVOICEMASTER_DESC.AINVOICE_no <= (SELECT MAX(AGENCYINVOICEMASTER_DESC.AINVOICE_no) FROM AGENCYINVOICEMASTER_DESC WHERE AGENCYINVOICEMASTER_DESC.AINVOICE_yearid = @SELECTEDYEARID)

INSERT INTO AGENCYINVOICEMASTER_DESC
SELECT AGENCYINVOICEMASTER.AINVOICE_NO, AGENCYINVOICEMASTER.AINVOICE_INITIALS, AINVOICE_SRNO, NITEMMASTER.ITEM_ID,  NHSNMASTER.HSN_ID, 0 AS QUALITYID, 0 AS DESIGNID, 0 AS COLORID,
AINVOICE_QTY, AINVOICE_FOLDPER, AINVOICE_PRINTDESC, AINVOICE_BALENO, AINVOICE_PCS, AINVOICE_CUT, AINVOICE_MTRS, AINVOICE_RATE, AGENCYINVOICEMASTER_DESC.AINVOICE_PER, AGENCYINVOICEMASTER_DESC.AINVOICE_AMOUNT, 
AINVOICE_GRIDLRNO, NTRANSLEDGERS.ACC_ID, AINVOICE_DISCPER, AINVOICE_DISCAMT, AINVOICE_SPDISCPER, AINVOICE_SPDISCAMT, AINVOICE_OTHERAMT, AGENCYINVOICEMASTER_DESC.AINVOICE_TAXABLEAMT, AGENCYINVOICEMASTER_DESC.AINVOICE_CGSTPER,
AGENCYINVOICEMASTER_DESC.AINVOICE_CGSTAMT, AGENCYINVOICEMASTER_DESC.AINVOICE_SGSTPER, AGENCYINVOICEMASTER_DESC.AINVOICE_SGSTAMT, AGENCYINVOICEMASTER_DESC.AINVOICE_IGSTPER, AGENCYINVOICEMASTER_DESC.AINVOICE_IGSTAMT,
AGENCYINVOICEMASTER_DESC.AINVOICE_GRIDTOTAL, AGENCYINVOICEMASTER_DESC.AINVOICE_BARCODE, AGENCYINVOICEMASTER_DESC.AINVOICE_FROMNO, AGENCYINVOICEMASTER_DESC.AINVOICE_FROMSRNO, AGENCYINVOICEMASTER_DESC.AINVOICE_FROMTYPE,
AGENCYINVOICEMASTER_DESC.AINVOICE_GRIDDONE, AGENCYINVOICEMASTER_DESC.AINVOICE_GRIDPARTYPONO, @CMPID, 0 AS LOCATIONID, AGENCYINVOICEMASTER_DESC.AINVOICE_USERID, @YEARID, 
0 AS [TRANSFER], AGENCYINVOICEMASTER_DESC.AINVOICE_CREATED, AGENCYINVOICEMASTER_DESC.AINVOICE_MODIFIED, AGENCYINVOICEMASTER_DESC.AINVOICE_MODIFIEDBY, NUNITMASTER.UNIT_ID,
AINVOICE_GRIDSONO, AINVOICE_GRIDSOSRNO
FROM AGENCYINVOICEMASTER_DESC INNER JOIN AGENCYINVOICEMASTER ON AGENCYINVOICEMASTER_DESC.AINVOICE_no = AGENCYINVOICEMASTER.AINVOICE_NO AND AGENCYINVOICEMASTER_DESC.AINVOICE_yearid = AGENCYINVOICEMASTER.AINVOICE_YEARID INNER JOIN 
LEDGERS ON AGENCYINVOICEMASTER.AINVOICE_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
ITEMMASTER ON AGENCYINVOICEMASTER_DESC.AINVOICE_ITEMID = ITEMMASTER.ITEM_ID LEFT OUTER JOIN ITEMMASTER AS NITEMMASTER ON ITEMMASTER.ITEM_NAME = NITEMMASTER.ITEM_NAME AND NITEMMASTER.ITEM_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS PURLEDGER ON AGENCYINVOICEMASTER.AINVOICE_PURLEDGERID = PURLEDGER.ACC_ID LEFT OUTER JOIN LEDGERS AS NPURLEDGER ON PURLEDGER.ACC_CMPNAME = NPURLEDGER.ACC_CMPNAME AND NPURLEDGER.Acc_yearid = @YEARID LEFT OUTER JOIN
HSNMASTER ON AGENCYINVOICEMASTER_DESC.AINVOICE_HSNCODEID = HSNMASTER.HSN_ID LEFT OUTER JOIN HSNMASTER AS NHSNMASTER ON HSNMASTER.HSN_CODE = NHSNMASTER.HSN_CODE AND NHSNMASTER.HSN_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS TRANSLEDGERS ON AGENCYINVOICEMASTER_DESC.AINVOICE_GRIDTRANSID = TRANSLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NTRANSLEDGERS ON TRANSLEDGERS.ACC_CMPNAME = NTRANSLEDGERS.ACC_CMPNAME AND NTRANSLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
UNITMASTER ON AGENCYINVOICEMASTER_DESC.AINVOICE_UNITID = UNITMASTER.UNIT_ID LEFT OUTER JOIN UNITMASTER AS NUNITMASTER ON UNITMASTER.UNIT_NAME = NUNITMASTER.UNIT_NAME AND NUNITMASTER.UNIT_yearid = @YEARID
WHERE AGENCYINVOICEMASTER.AINVOICE_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND PURLEDGER.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' 
ORDER BY AGENCYINVOICEMASTER.AINVOICE_NO DESC



DELETE FROM AGENCYINVOICEMASTER_SODETAILS WHERE AGENCYINVOICEMASTER_SODETAILS.AINVOICE_yearid = @YEARID AND AGENCYINVOICEMASTER_SODETAILS.AINVOICE_no <= (SELECT MAX(AGENCYINVOICEMASTER_SODETAILS.AINVOICE_no) FROM AGENCYINVOICEMASTER_SODETAILS WHERE AGENCYINVOICEMASTER_SODETAILS.AINVOICE_yearid = @SELECTEDYEARID)

INSERT INTO AGENCYINVOICEMASTER_SODETAILS
SELECT AGENCYINVOICEMASTER.AINVOICE_NO, AGENCYINVOICEMASTER.AINVOICE_INITIALS, AINVOICE_GRIDSRNO, NITEMMASTER.ITEM_ID,  0 AS DESIGNID, 0 AS COLORID,
AINVOICE_ORDERPCS, AINVOICE_ORDERMTRS, AGENCYINVOICEMASTER_SODETAILS.AINVOICE_FROMNO, AGENCYINVOICEMASTER_SODETAILS.AINVOICE_FROMSRNO, AGENCYINVOICEMASTER_SODETAILS.AINVOICE_FROMTYPE,
AGENCYINVOICEMASTER_SODETAILS.AINVOICE_PCS, AGENCYINVOICEMASTER_SODETAILS.AINVOICE_MTRS, AGENCYINVOICEMASTER_SODETAILS.AINVOICE_RATE, AGENCYINVOICEMASTER_SODETAILS.AINVOICE_PARTYPONO, 
@CMPID, @YEARID
FROM AGENCYINVOICEMASTER_SODETAILS INNER JOIN AGENCYINVOICEMASTER ON AGENCYINVOICEMASTER_SODETAILS.AINVOICE_no = AGENCYINVOICEMASTER.AINVOICE_NO AND AGENCYINVOICEMASTER_SODETAILS.AINVOICE_yearid = AGENCYINVOICEMASTER.AINVOICE_YEARID INNER JOIN 
LEDGERS ON AGENCYINVOICEMASTER.AINVOICE_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
ITEMMASTER ON AGENCYINVOICEMASTER_SODETAILS.AINVOICE_ITEMID = ITEMMASTER.ITEM_ID LEFT OUTER JOIN ITEMMASTER AS NITEMMASTER ON ITEMMASTER.ITEM_NAME = NITEMMASTER.ITEM_NAME AND NITEMMASTER.ITEM_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS PURLEDGER ON AGENCYINVOICEMASTER.AINVOICE_PURLEDGERID = PURLEDGER.ACC_ID LEFT OUTER JOIN LEDGERS AS NPURLEDGER ON PURLEDGER.ACC_CMPNAME = NPURLEDGER.ACC_CMPNAME AND NPURLEDGER.Acc_yearid = @YEARID
WHERE AGENCYINVOICEMASTER.AINVOICE_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND PURLEDGER.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' 
ORDER BY AGENCYINVOICEMASTER.AINVOICE_NO DESC

-- ********************* END OF AGENCYINVOICE ****************************



--************* AGENCYCREDITNOTEMASTER *****************
DELETE FROM AGENCYCREDITNOTEMASTER WHERE AGENCYCREDITNOTEMASTER.ACN_yearid = @YEARID AND AGENCYCREDITNOTEMASTER.ACN_no <= (SELECT MAX(AGENCYCREDITNOTEMASTER.ACN_no) FROM AGENCYCREDITNOTEMASTER WHERE AGENCYCREDITNOTEMASTER.ACN_yearid = @SELECTEDYEARID)


INSERT INTO AGENCYCREDITNOTEMASTER
SELECT ACN_NO, ACN_INITIALS, ACN_DATE, ACN_ACTUALINVDATE, ACN_TYPE, ACN_BILLNO, ACN_INVPRINTINITIALS, ACN_PARTYREFNO, NLEDGERS.ACC_ID, 0 AS AGENTID, NHSNMASTER.HSN_ID,
DEBITLEDGER.ACC_ID, NDELIVERYATLEDGERS.ACC_ID, ACN_TOTALPCS, ACN_TOTALMTRS, ACN_ACTUALINVAMT, ACN_DISCPER, ACN_TOTALAMT, ACN_TOTALTAXAMT, ACN_TOTALOTHERCHGSAMT, ACN_CHARGES,
ACN_RCM, ACN_MANUALGST, ACN_MANUALROUNDOFF, ACN_NOGSTR1, ACN_SUBTOTAL, ACN_CGSTPER, ACN_CGSTAMT, ACN_SGSTPER, ACN_SGSTAMT, ACN_IGSTPER, ACN_IGSTAMT, ACN_TOTALWITHGST, 
ACN_APPLYTCS, ACN_TCSPER, ACN_TCSAMT, ACN_ROUNDOFF, ACN_GTOTAL, ACN_AMTPAID, ACN_EXTRAAMT, ACN_RETURN, ACN_BALANCE, ACN_remarks, ACN_BILLREMARKS, ACN_INWORDS, ACN_DONE,
ACN_PRINTINITIALS, ACN_IRNNO, ACN_ACKNO, ACN_ACKDATE, ACN_QRCODE, @CMPID,0 AS LOCATIONID, ACN_userid, @YEARID, 0 AS [TRANSFER], ACN_created, ACN_MODIFIED, ACN_MODIFIEDBY,
ACN_SPECIALREMARKS, ACN_CD, ACN_SENDWHATSAPP, 0 AS COSTCENTRE, ACN_COMPLAINT, ACN_COMPLAINTBY, ACN_COMPLAINTDATE
FROM AGENCYCREDITNOTEMASTER INNER JOIN LEDGERS ON AGENCYCREDITNOTEMASTER.ACN_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS DEBITLEDGER ON AGENCYCREDITNOTEMASTER.ACN_DEBITLEDGERID = DEBITLEDGER.ACC_ID LEFT OUTER JOIN LEDGERS AS NDEBITLEDGER ON DEBITLEDGER.ACC_CMPNAME = NDEBITLEDGER.ACC_CMPNAME AND NDEBITLEDGER.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS DELIVERYATLEDGERS ON AGENCYCREDITNOTEMASTER.ACN_DELIVERYATID= DELIVERYATLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NDELIVERYATLEDGERS ON DELIVERYATLEDGERS.ACC_CMPNAME = NDELIVERYATLEDGERS.ACC_CMPNAME AND NDELIVERYATLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
HSNMASTER ON AGENCYCREDITNOTEMASTER.ACN_HSNCODEID = HSNMASTER.HSN_ID LEFT OUTER JOIN HSNMASTER AS NHSNMASTER ON HSNMASTER.HSN_CODE = NHSNMASTER.HSN_CODE AND NHSNMASTER.HSN_yearid = @YEARID
WHERE AGENCYCREDITNOTEMASTER.ACN_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND DEBITLEDGER.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' AND AGENCYCREDITNOTEMASTER.ACN_NO NOT IN (SELECT ACN_NO FROM AGENCYCREDITNOTEMASTER WHERE ACN_YEARID = @YEARID)
ORDER BY AGENCYCREDITNOTEMASTER.ACN_NO DESC


DELETE FROM AGENCYCREDITNOTEMASTER_BILLDESC WHERE AGENCYCREDITNOTEMASTER_BILLDESC.ACN_yearid = @YEARID AND AGENCYCREDITNOTEMASTER_BILLDESC.ACN_no <= (SELECT MAX(AGENCYCREDITNOTEMASTER_BILLDESC.ACN_no) FROM AGENCYCREDITNOTEMASTER_BILLDESC WHERE AGENCYCREDITNOTEMASTER_BILLDESC.ACN_yearid = @SELECTEDYEARID)

INSERT INTO AGENCYCREDITNOTEMASTER_BILLDESC
SELECT AGENCYCREDITNOTEMASTER.ACN_NO, ACN_GRIDSRNO, ACN_PAYTYPE, ACN_BILLINITIALS, ACN_GRIDREMARKS, AGENCYCREDITNOTEMASTER_BILLDESC.ACN_AMT, AGENCYCREDITNOTEMASTER_BILLDESC.ACN_AMTPAID, 
AGENCYCREDITNOTEMASTER_BILLDESC.ACN_EXTRAAMT, AGENCYCREDITNOTEMASTER_BILLDESC.ACN_RETURN, AGENCYCREDITNOTEMASTER_BILLDESC.ACN_BALANCE, @CMPID, AGENCYCREDITNOTEMASTER_BILLDESC.ACN_USERID, @YEARID
FROM AGENCYCREDITNOTEMASTER_BILLDESC INNER JOIN AGENCYCREDITNOTEMASTER ON AGENCYCREDITNOTEMASTER_BILLDESC.ACN_no = AGENCYCREDITNOTEMASTER.ACN_NO AND AGENCYCREDITNOTEMASTER_BILLDESC.ACN_yearid = AGENCYCREDITNOTEMASTER.ACN_YEARID INNER JOIN 
LEDGERS ON AGENCYCREDITNOTEMASTER.ACN_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS DEBITLEDGER ON AGENCYCREDITNOTEMASTER.ACN_DEBITLEDGERID = DEBITLEDGER.ACC_ID LEFT OUTER JOIN LEDGERS AS NDEBITLEDGER ON DEBITLEDGER.ACC_CMPNAME = NDEBITLEDGER.ACC_CMPNAME AND NDEBITLEDGER.Acc_yearid = @YEARID
WHERE AGENCYCREDITNOTEMASTER.ACN_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND DEBITLEDGER.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' 
ORDER BY AGENCYCREDITNOTEMASTER.ACN_NO DESC



DELETE FROM AGENCYCREDITNOTEMASTER_CHGS WHERE AGENCYCREDITNOTEMASTER_CHGS.ACN_yearid = @YEARID AND AGENCYCREDITNOTEMASTER_CHGS.ACN_no <= (SELECT MAX(AGENCYCREDITNOTEMASTER_CHGS.ACN_no) FROM AGENCYCREDITNOTEMASTER_CHGS WHERE AGENCYCREDITNOTEMASTER_CHGS.ACN_yearid = @SELECTEDYEARID)

INSERT INTO AGENCYCREDITNOTEMASTER_CHGS
SELECT AGENCYCREDITNOTEMASTER.ACN_NO, AGENCYCREDITNOTEMASTER.ACN_INITIALS, ACN_GRIDSRNO, NCHARGESLEDGERS.ACC_ID, ACN_PER, ACN_AMT, ACN_TAXID, @CMPID,
0 AS LOCATIONID, AGENCYCREDITNOTEMASTER.ACN_USERID, @YEARID, 0 AS [TRANSFER]
FROM AGENCYCREDITNOTEMASTER_CHGS INNER JOIN AGENCYCREDITNOTEMASTER ON AGENCYCREDITNOTEMASTER_CHGS.ACN_no = AGENCYCREDITNOTEMASTER.ACN_NO AND AGENCYCREDITNOTEMASTER_CHGS.ACN_yearid = AGENCYCREDITNOTEMASTER.ACN_YEARID INNER JOIN 
LEDGERS ON AGENCYCREDITNOTEMASTER.ACN_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS CHARGESLEDGERS ON AGENCYCREDITNOTEMASTER_CHGS.ACN_CHARGESID = CHARGESLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NCHARGESLEDGERS ON CHARGESLEDGERS.ACC_CMPNAME = NCHARGESLEDGERS.ACC_CMPNAME AND NCHARGESLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS DEBITLEDGER ON AGENCYCREDITNOTEMASTER.ACN_DEBITLEDGERID = DEBITLEDGER.ACC_ID LEFT OUTER JOIN LEDGERS AS NDEBITLEDGER ON DEBITLEDGER.ACC_CMPNAME = NDEBITLEDGER.ACC_CMPNAME AND NDEBITLEDGER.Acc_yearid = @YEARID 
WHERE AGENCYCREDITNOTEMASTER.ACN_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND DEBITLEDGER.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' 
ORDER BY AGENCYCREDITNOTEMASTER.ACN_NO DESC

-- ********************* END OF AGENCYCREDITNOTE ****************************


-- ************** AGENCYOPENINGBILL ***************
DELETE FROM AGENCYOPENINGBILL WHERE AGENCYOPENINGBILL.ABILL_yearid = @YEARID 

INSERT INTO AGENCYOPENINGBILL
SELECT AGENCYOPENINGBILL.ABILL_NO, ABILL_GRIDSRNO, ABILL_TYPE, ABILL_NO, ABILL_YEAR, ABILL_DATE, ABILL_CRDAYS, ABILL_DUEDATE, 0 AS AGENTID, ABILL_NARRATION, ABILL_DISPUTE, 
NDELIVERYATLEDGERS.ACC_ID, ABILL_PCS, ABILL_MTRS, ABILL_TOTALAMT, ABILL_CHARGES, ABILL_TAXABLEAMT, ABILL_CGSTPER, ABILL_CGSTAMT, ABILL_SGSTPER, ABILL_SGSTAMT, ABILL_IGSTPER, ABILL_IGSTAMT, 
ABILL_GRANDTOTAL, ABILL_AMT, ABILL_INITIALS, ABILL_AMTPAIDREC, ABILL_EXTRAAMT, ABILL_RETURN, ABILL_BALANCE, ABILL_PRINTINITIALS, @CMPID, 0 AS LOCATIONID, AGENCYOPENINGBILL.ABILL_USERID, 
@YEARID, 0 AS [TRANSFER], ABILL_CREATED, ABILL_MODIFIEDBY, ABILL_MODIFIED, ABILL_CD, NITEMMASTER.ITEM_ID, ABILL_RATE, ABILL_LRNO, ABILL_PARTYBILLNO, ABILL_HOLDINTCALC, 
ABILL_COMPLAINT, ABILL_COMPLAINTBY, ABILL_COMPLAINTDATE
FROM AGENCYOPENINGBILL INNER JOIN 
LEDGERS ON AGENCYOPENINGBILL.ABILL_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS DELIVERYATLEDGERS ON AGENCYOPENINGBILL.ABILL_DELIVERYATID= DELIVERYATLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NDELIVERYATLEDGERS ON DELIVERYATLEDGERS.ACC_CMPNAME = NDELIVERYATLEDGERS.ACC_CMPNAME AND NDELIVERYATLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
ITEMMASTER ON AGENCYOPENINGBILL.ABILL_ITEMID = ITEMMASTER.ITEM_ID LEFT OUTER JOIN ITEMMASTER AS NITEMMASTER ON ITEMMASTER.ITEM_NAME = NITEMMASTER.ITEM_NAME AND NITEMMASTER.ITEM_yearid = @YEARID
WHERE AGENCYOPENINGBILL.ABILL_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND DELIVERYATLEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' 
ORDER BY AGENCYOPENINGBILL.ABILL_NO DESC

-- ***************** END OF AGENCYOPENINGBILL ******************



-- **************** AGENCYRECEIPT **********************
DELETE FROM AGENCYRECEIPTMASTER WHERE AGENCYRECEIPTMASTER.ARECEIPT_yearid = @YEARID AND AGENCYRECEIPTMASTER.ARECEIPT_no <= (SELECT MAX(AGENCYRECEIPTMASTER.ARECEIPT_no) FROM AGENCYRECEIPTMASTER WHERE AGENCYRECEIPTMASTER.ARECEIPT_yearid = @SELECTEDYEARID)

INSERT INTO AGENCYRECEIPTMASTER
SELECT AGENCYRECEIPTMASTER.ARECEIPT_NO, NREGISTERMASTER.REGISTER_ID, Areceipt_initials, Areceipt_date, NSELLERLEDGERS.ACC_ID, NLEDGERS.ACC_ID, Areceipt_BANKNAME , 
Areceipt_total, Areceipt_CHQNO, Areceipt_remarks, Areceipt_BILLREMARKS, Areceipt_OURREMARKS, Areceipt_inwords, Areceipt_CHECKPDC, Areceipt_RECODATE, 
Areceipt_SMSSEND, @CMPID, 0 AS LOCATIONID, Areceipt_userid, @YEARID, 0 AS [TRANSFER], Areceipt_created, Areceipt_SPECIALREMARKS, Areceipt_SENDWHATSAPP, Areceipt_CHQDATE, 
ARECEIPT_COMPLAINT, ARECEIPT_COMPLAINTBY, ARECEIPT_COMPLAINTDATE, ARECEIPT_HOLDINTCALC
FROM AGENCYRECEIPTMASTER INNER JOIN 
LEDGERS ON AGENCYRECEIPTMASTER.ARECEIPT_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS SELLERLEDGERS ON AGENCYRECEIPTMASTER.ARECEIPT_SELLERID= SELLERLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NSELLERLEDGERS ON SELLERLEDGERS.ACC_CMPNAME = NSELLERLEDGERS.ACC_CMPNAME AND NSELLERLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
REGISTERMASTER ON AGENCYRECEIPTMASTER.Areceipt_registerid= REGISTERMASTER.REGISTER_ID LEFT OUTER JOIN REGISTERMASTER AS NREGISTERMASTER ON REGISTERMASTER.register_name = NREGISTERMASTER.register_name AND NREGISTERMASTER.register_yearid = @YEARID 
WHERE AGENCYRECEIPTMASTER.ARECEIPT_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND SELLERLEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' 
ORDER BY AGENCYRECEIPTMASTER.ARECEIPT_NO DESC



DELETE FROM AGENCYRECEIPTMASTER_DESC WHERE AGENCYRECEIPTMASTER_DESC.ARECEIPT_yearid = @YEARID AND AGENCYRECEIPTMASTER_DESC.ARECEIPT_no <= (SELECT MAX(AGENCYRECEIPTMASTER_DESC.ARECEIPT_no) FROM AGENCYRECEIPTMASTER_DESC WHERE AGENCYRECEIPTMASTER_DESC.ARECEIPT_yearid = @SELECTEDYEARID)

INSERT INTO AGENCYRECEIPTMASTER_DESC
SELECT AGENCYRECEIPTMASTER.ARECEIPT_NO, NREGISTERMASTER.REGISTER_ID, AGENCYRECEIPTMASTER.Areceipt_initials, ARECEIPT_GRIDSRNO, ARECEIPT_PAYTYPE, ARECEIPT_BILLINITIALS, 
ARECEIPT_GRIDREMARKS, AGENCYRECEIPTMASTER_DESC.ARECEIPT_AMT, AGENCYRECEIPTMASTER_DESC.ARECEIPT_AMTPAID, AGENCYRECEIPTMASTER_DESC.ARECEIPT_EXTRAAMT, AGENCYRECEIPTMASTER_DESC.ARECEIPT_RETURN, 
AGENCYRECEIPTMASTER_DESC.ARECEIPT_BALANCE, @CMPID, 0 AS LOCATIONID, AGENCYRECEIPTMASTER_DESC.ARECEIPT_USERID, @YEARID, 0 AS [TRANSFER], AGENCYRECEIPTMASTER_DESC.Areceipt_created
FROM AGENCYRECEIPTMASTER_DESC INNER JOIN AGENCYRECEIPTMASTER ON AGENCYRECEIPTMASTER_DESC.ARECEIPT_no = AGENCYRECEIPTMASTER.ARECEIPT_NO AND AGENCYRECEIPTMASTER_DESC.ARECEIPT_yearid = AGENCYRECEIPTMASTER.ARECEIPT_YEARID INNER JOIN 
LEDGERS ON AGENCYRECEIPTMASTER.ARECEIPT_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS SELLERLEDGERS ON AGENCYRECEIPTMASTER.Areceipt_sellerid = SELLERLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NSELLERLEDGERS ON SELLERLEDGERS.ACC_CMPNAME = NSELLERLEDGERS.ACC_CMPNAME AND NSELLERLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
REGISTERMASTER ON AGENCYRECEIPTMASTER.Areceipt_registerid= REGISTERMASTER.REGISTER_ID LEFT OUTER JOIN REGISTERMASTER AS NREGISTERMASTER ON REGISTERMASTER.register_name = NREGISTERMASTER.register_name AND NREGISTERMASTER.register_yearid = @YEARID 

WHERE AGENCYRECEIPTMASTER.ARECEIPT_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND SELLERLEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' 
ORDER BY AGENCYRECEIPTMASTER.ARECEIPT_NO DESC



-- **************** END OF AGENCYRECEIPT **********************


-- **************** AGENCYSALEORDER **********************
DELETE FROM AGENCYSALEORDER WHERE AGENCYSALEORDER.ASO_yearid = @YEARID AND AGENCYSALEORDER.ASO_no <= (SELECT MAX(AGENCYSALEORDER.ASO_no) FROM AGENCYSALEORDER WHERE AGENCYSALEORDER.ASO_yearid = @SELECTEDYEARID)


INSERT INTO AGENCYSALEORDER
SELECT ASO_NO, ASO_DATE, NLEDGERS.ACC_ID, 0 AS HASTEID, 0 AS AGENTID, ASO_PONO, ASO_DUEDATE, 0 AS TRANSID, 0 AS TRANSID1, NCITYMASTER.CITY_ID AS CITYID,
ASO_REFNO, ASO_RISK, ASO_CONSIGNOR, ASO_CONSIGNEE, NPACKINGLEDGERS.ACC_ID, 0 AS CURRID, ASO_TOTALQTY, ASO_TOTALMTRS, ASO_TOTALBALES, ASO_TOTALAMT, 
ASO_DISPER, ASO_DISAMT, ASO_PFPER, ASO_PFAMT, ASO_TESTCHGS, ASO_NETT, ASO_EXCISEID, ASO_EXCISEAMT, ASO_EDUCESSAMT, ASO_HSECESSAMT, ASO_SUBTOTAL, 0 AS TAXID, 0 AS TAXAMT, 
0 AS ADDTAXID, 0 AS ADDTAXAMT, 0 AS FRPER, 0 FREIGHT, 0 AS OCTID, 0 AS OCTAMT, 0 AS INSAMT, ASO_ROUNDOFF, ASO_GRANDTOTAL, ASO_INWORDS, ASO_remarks, ASO_NOTE, ASO_TNC,
0 AS MISCPER, ASO_DISCRATE, ASO_DISCLOT, ASO_DISCDEALER, ASO_KATAI, ASO_CD, ASO_ADAT, ASO_DAYS, ASO_INT, ASO_DONE, ASO_ADVANCE, ASO_BALANCE, 0 AS SALESMANID, 0 AS PACKINGTYPEID,
ASO_SMSSEND, ASO_FORWARD, ASO_SAMPLE, @CMPID, 0 AS LOCATIONID, ASO_USERID, @YEARID, 0 AS [TRANSFER], ASO_CREATED, ASO_MODIFIED, ASO_MODIFIEDBY, ASO_SENDWHATSAPP, 
NFROMCITYMASTER.CITY_ID, ASO_VERIFIED, ASO_ORDERON
FROM AGENCYSALEORDER INNER JOIN LEDGERS ON AGENCYSALEORDER.ASO_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
CITYMASTER ON AGENCYSALEORDER.ASO_CITYID = CITYMASTER.CITY_ID LEFT OUTER JOIN CITYMASTER AS NCITYMASTER ON CITYMASTER.CITY_NAME = NCITYMASTER.CITY_NAME AND NCITYMASTER.city_yearid = @YEARID LEFT OUTER JOIN
CITYMASTER AS FROMCITYMASTER ON AGENCYSALEORDER.ASO_FROMCITYID = FROMCITYMASTER.CITY_ID LEFT OUTER JOIN CITYMASTER AS NFROMCITYMASTER ON FROMCITYMASTER.CITY_NAME = NFROMCITYMASTER.CITY_NAME AND NFROMCITYMASTER.city_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS PACKINGLEDGERS ON AGENCYSALEORDER.ASO_PACKINGID = PACKINGLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NPACKINGLEDGERS ON PACKINGLEDGERS.ACC_CMPNAME = NPACKINGLEDGERS.ACC_CMPNAME AND NPACKINGLEDGERS.Acc_yearid = @YEARID
WHERE AGENCYSALEORDER.ASO_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND PACKINGLEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' AND AGENCYSALEORDER.ASO_NO NOT IN (SELECT ASO_NO FROM AGENCYSALEORDER WHERE ASO_YEARID = @YEARID)
ORDER BY AGENCYSALEORDER.ASO_NO DESC



DELETE FROM AGENCYSALEORDER_DESC WHERE AGENCYSALEORDER_DESC.ASO_yearid = @YEARID AND AGENCYSALEORDER_DESC.ASO_no <= (SELECT MAX(AGENCYSALEORDER_DESC.ASO_no) FROM AGENCYSALEORDER_DESC WHERE AGENCYSALEORDER_DESC.ASO_yearid = @SELECTEDYEARID)

INSERT INTO AGENCYSALEORDER_DESC
SELECT AGENCYSALEORDER.ASO_NO, ASO_GRIDSRNO, NITEMMASTER.ITEM_ID,  0 AS QUALITYID, 0 AS DESIGNID, ASO_GRIDREMARKS, 0 AS COLORID,
ASO_PARTYPONO, ASO_QTY, NUNITMASTER.UNIT_ID, ASO_CUT, ASO_MTRS, ASO_RATE, AGENCYSALEORDER_DESC.ASO_PER, AGENCYSALEORDER_DESC.ASO_AMOUNT, 
ASO_RECDQTY, ASO_RECDMTRS, ASO_CLOSED, ASO_CLOSEDDATE, ASO_CLOSEDREASON, AGENCYSALEORDER_DESC.ASO_DONE, AGENCYSALEORDER_DESC.ASO_SAMPLEDONE, @CMPID, 0 AS LOCATIONID, 
AGENCYSALEORDER_DESC.ASO_USERID, @YEARID, 0 AS [TRANSFER], AGENCYSALEORDER_DESC.ASO_CREATED, AGENCYSALEORDER_DESC.ASO_MODIFIED, AGENCYSALEORDER_DESC.ASO_MODIFIEDBY
FROM AGENCYSALEORDER_DESC INNER JOIN AGENCYSALEORDER ON AGENCYSALEORDER_DESC.ASO_no = AGENCYSALEORDER.ASO_NO AND AGENCYSALEORDER_DESC.ASO_yearid = AGENCYSALEORDER.ASO_YEARID INNER JOIN 
LEDGERS ON AGENCYSALEORDER.ASO_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
ITEMMASTER ON AGENCYSALEORDER_DESC.ASO_ITEMID = ITEMMASTER.ITEM_ID LEFT OUTER JOIN ITEMMASTER AS NITEMMASTER ON ITEMMASTER.ITEM_NAME = NITEMMASTER.ITEM_NAME AND NITEMMASTER.ITEM_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS PACKINGLEDGERS ON AGENCYSALEORDER.ASO_PACKINGID = PACKINGLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NPACKINGLEDGERS ON PACKINGLEDGERS.ACC_CMPNAME = NPACKINGLEDGERS.ACC_CMPNAME AND NPACKINGLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
UNITMASTER ON AGENCYSALEORDER_DESC.ASO_UNITID = UNITMASTER.UNIT_ID LEFT OUTER JOIN UNITMASTER AS NUNITMASTER ON UNITMASTER.UNIT_NAME = NUNITMASTER.UNIT_NAME AND NUNITMASTER.UNIT_yearid = @YEARID
WHERE AGENCYSALEORDER.ASO_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND PACKINGLEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' 
ORDER BY AGENCYSALEORDER.ASO_NO DESC

-- **************** END OF AGENCYSALEORDER **********************



-- **************** AGENCYSALERETURN **********************
DELETE FROM AGENCYSALERETURN WHERE AGENCYSALERETURN.ASALRET_yearid = @YEARID AND AGENCYSALERETURN.ASALRET_no <= (SELECT MAX(AGENCYSALERETURN.ASALRET_no) FROM AGENCYSALERETURN WHERE AGENCYSALERETURN.ASALRET_yearid = @SELECTEDYEARID)


INSERT INTO AGENCYSALERETURN
SELECT ASALRET_NO, ASALRET_DATE, NLEDGERS.ACC_ID, NDELIVERYATLEDGERS.ACC_ID, ASALRET_CHALLANNO, ASALRET_CHALLANDATE, ASALRET_ACTUALINVNO, ASALRET_ACTUALINVDATE,
ASALRET_INVOICENO, ASALRET_INVOICEDATE, ASALRET_INVOICETYPE, ASALRET_INVOICEINITIALS, ASALRET_PARTYREFNO, ASALRET_SRCHNO, NTRANSLEDGERS.ACC_ID, ASALRET_LRNO, ASALRET_LRDATE, 
0 AS AGENTID, ASALRET_EWAYBILLNO, ASALRET_TOTALWT, ASALRET_TOTALQTY, ASALRET_TOTALMTRS, ASALRET_TOTALAMT, ASALRET_MANUALGST, ASALRET_CGSTPER, ASALRET_TOTALCGSTAMT, ASALRET_SGSTPER, ASALRET_TOTALSGSTAMT,
ASALRET_IGSTPER, ASALRET_TOTALIGSTAMT, ASALRET_AMOUNT, ASALRET_CHARGES, ASALRET_SUBTOTAL, ASALRET_TOTALWITHGST, ASALRET_APPLYTCS, ASALRET_TCSPER, ASALRET_TCSAMT,
ASALRET_ROUNDOFF, ASALRET_GRANDTOTAL, ASALRET_INWORDS, ASALRET_remarks, ASALRET_BILLREMARKS, ASALRET_DONE, ASALRET_PRINTINITIALS, ASALRET_IRNNO, ASALRET_ACKNO, ASALRET_ACKDATE, 
ASALRET_QRCODE, @CMPID, 0 AS LOCATIONID, ASALRET_USERID, @YEARID, 0 AS [TRANSFER], ASALRET_CREATED, ASALRET_MODIFIED, ASALRET_MODIFIEDBY, ASALRET_SPECIALREMARKS, ASALRET_CD, 
ASALRET_SENDWHATSAPP, ASALRET_NOOFBALES, ASALRET_EXPORTGST, 0 AS COSTCENTRE, ASALRET_MANUALROUNDOFF, NFROMCITYMASTER.CITY_ID, NTOCITYMASTER.CITY_ID, ASALRET_COMPLAINT, ASALRET_COMPLAINTBY, ASALRET_COMPLAINTDATE, ASALRET_HOLDINTCALC
FROM AGENCYSALERETURN INNER JOIN LEDGERS ON AGENCYSALERETURN.ASALRET_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
CITYMASTER AS FROMCITYMASTER ON AGENCYSALERETURN.ASALRET_FROMCITYID = FROMCITYMASTER.CITY_ID LEFT OUTER JOIN CITYMASTER AS NFROMCITYMASTER ON FROMCITYMASTER.CITY_NAME = NFROMCITYMASTER.CITY_NAME AND NFROMCITYMASTER.city_yearid = @YEARID LEFT OUTER JOIN
CITYMASTER AS TOCITYMASTER ON AGENCYSALERETURN.ASALRET_TOCITYID = TOCITYMASTER.CITY_ID LEFT OUTER JOIN CITYMASTER AS NTOCITYMASTER ON TOCITYMASTER.CITY_NAME = NTOCITYMASTER.CITY_NAME AND NTOCITYMASTER.city_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS DELIVERYATLEDGERS ON AGENCYSALERETURN.ASALRET_DELIVERYATID = DELIVERYATLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NDELIVERYATLEDGERS ON DELIVERYATLEDGERS.ACC_CMPNAME = NDELIVERYATLEDGERS.ACC_CMPNAME AND NDELIVERYATLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS TRANSLEDGERS ON AGENCYSALERETURN.ASALRET_TRANSID = TRANSLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NTRANSLEDGERS ON TRANSLEDGERS.ACC_CMPNAME = NTRANSLEDGERS.ACC_CMPNAME AND NTRANSLEDGERS.Acc_yearid = @YEARID
WHERE AGENCYSALERETURN.ASALRET_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND DELIVERYATLEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' AND AGENCYSALERETURN.ASALRET_NO NOT IN (SELECT ASALRET_NO FROM AGENCYSALERETURN WHERE ASALRET_YEARID = @YEARID)
ORDER BY AGENCYSALERETURN.ASALRET_NO DESC


DELETE FROM AGENCYSALERETURN_BILLDESC WHERE AGENCYSALERETURN_BILLDESC.ASALRET_yearid = @YEARID AND AGENCYSALERETURN_BILLDESC.ASALRET_no <= (SELECT MAX(AGENCYSALERETURN_BILLDESC.ASALRET_no) FROM AGENCYSALERETURN_BILLDESC WHERE AGENCYSALERETURN_BILLDESC.ASALRET_yearid = @SELECTEDYEARID)

INSERT INTO AGENCYSALERETURN_BILLDESC
SELECT AGENCYSALERETURN.ASALRET_NO, ASALRET_GRIDSRNO, ASALRET_PAYTYPE, ASALRET_BILLINITIALS, ASALRET_GRIDREMARKS, AGENCYSALERETURN_BILLDESC.ASALRET_AMT, AGENCYSALERETURN_BILLDESC.ASALRET_AMTPAID, 
AGENCYSALERETURN_BILLDESC.ASALRET_EXTRAAMT, AGENCYSALERETURN_BILLDESC.ASALRET_RETURN, AGENCYSALERETURN_BILLDESC.ASALRET_BALANCE, @CMPID, AGENCYSALERETURN_BILLDESC.ASALRET_USERID, @YEARID
FROM AGENCYSALERETURN_BILLDESC INNER JOIN AGENCYSALERETURN ON AGENCYSALERETURN_BILLDESC.ASALRET_no = AGENCYSALERETURN.ASALRET_NO AND AGENCYSALERETURN_BILLDESC.ASALRET_yearid = AGENCYSALERETURN.ASALRET_YEARID INNER JOIN 
LEDGERS ON AGENCYSALERETURN.ASALRET_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS DELIVERYATLEDGERS ON AGENCYSALERETURN.ASALRET_DELIVERYATID = DELIVERYATLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NDELIVERYATLEDGERS ON DELIVERYATLEDGERS.ACC_CMPNAME = NDELIVERYATLEDGERS.ACC_CMPNAME AND NDELIVERYATLEDGERS.Acc_yearid = @YEARID 
WHERE AGENCYSALERETURN.ASALRET_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND DELIVERYATLEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' 
ORDER BY AGENCYSALERETURN.ASALRET_NO DESC



DELETE FROM AGENCYSALERETURN_CHGS WHERE AGENCYSALERETURN_CHGS.ASALRET_yearid = @YEARID AND AGENCYSALERETURN_CHGS.ASALRET_no <= (SELECT MAX(AGENCYSALERETURN_CHGS.ASALRET_no) FROM AGENCYSALERETURN_CHGS WHERE AGENCYSALERETURN_CHGS.ASALRET_yearid = @SELECTEDYEARID)

INSERT INTO AGENCYSALERETURN_CHGS
SELECT AGENCYSALERETURN.ASALRET_NO, ASALRET_GRIDSRNO, NCHARGESLEDGERS.ACC_ID, ASALRET_PER, ASALRET_AMT, ASALRET_TAXID, @CMPID,
0 AS LOCATIONID, AGENCYSALERETURN.ASALRET_USERID, @YEARID, 0 AS [TRANSFER]
FROM AGENCYSALERETURN_CHGS INNER JOIN AGENCYSALERETURN ON AGENCYSALERETURN_CHGS.ASALRET_no = AGENCYSALERETURN.ASALRET_NO AND AGENCYSALERETURN_CHGS.ASALRET_yearid = AGENCYSALERETURN.ASALRET_YEARID INNER JOIN 
LEDGERS ON AGENCYSALERETURN.ASALRET_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS CHARGESLEDGERS ON AGENCYSALERETURN_CHGS.ASALRET_CHARGESID = CHARGESLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NCHARGESLEDGERS ON CHARGESLEDGERS.ACC_CMPNAME = NCHARGESLEDGERS.ACC_CMPNAME AND NCHARGESLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS DELIVERYATLEDGERS ON AGENCYSALERETURN.ASALRET_DELIVERYATID = DELIVERYATLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NDELIVERYATLEDGERS ON DELIVERYATLEDGERS.ACC_CMPNAME = NDELIVERYATLEDGERS.ACC_CMPNAME AND NDELIVERYATLEDGERS.Acc_yearid = @YEARID 
WHERE AGENCYSALERETURN.ASALRET_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND DELIVERYATLEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' 
ORDER BY AGENCYSALERETURN.ASALRET_NO DESC



DELETE FROM AGENCYSALERETURN_DESC WHERE AGENCYSALERETURN_DESC.ASALRET_yearid = @YEARID AND AGENCYSALERETURN_DESC.ASALRET_no <= (SELECT MAX(AGENCYSALERETURN_DESC.ASALRET_no) FROM AGENCYSALERETURN_DESC WHERE AGENCYSALERETURN_DESC.ASALRET_yearid = @SELECTEDYEARID)

INSERT INTO AGENCYSALERETURN_DESC
SELECT AGENCYSALERETURN.ASALRET_NO, ASALRET_GRIDSRNO, NPIECETYPEMASTER.PIECETYPE_id, NITEMMASTER.ITEM_ID, NHSNMASTER.HSN_ID,  0 AS QUALITYID, 0 AS DESIGNID, 0 AS COLORID,
ASALRET_AQTY, ASALRET_AFOLDPER, ASALRET_BALENO, ASALRET_CUT, ASALRET_WT, ASALRET_QTY, NUNITMASTER.UNIT_ID, ASALRET_MTRS, ASALRET_RATE, AGENCYSALERETURN_DESC.ASALRET_PER, AGENCYSALERETURN_DESC.ASALRET_AMT, 
0 AS RACKID, 0 AS SHELFID, ASALRET_BARCODE, ASALRET_GDNBARCODE, AGENCYSALERETURN_DESC.ASALRET_DONE, ASALRET_OUTPCS, AGENCYSALERETURN_DESC.ASALRET_OUTMTRS, AGENCYSALERETURN_DESC.ASALRET_FROMNO, ASALRET_FROMSRNO, 
@CMPID, 0 AS LOCATIONID, AGENCYSALERETURN_DESC.ASALRET_USERID, @YEARID, 0 AS [TRANSFER], AGENCYSALERETURN_DESC.ASALRET_CREATED, AGENCYSALERETURN_DESC.ASALRET_MODIFIED, AGENCYSALERETURN_DESC.ASALRET_MODIFIEDBY
FROM AGENCYSALERETURN_DESC INNER JOIN AGENCYSALERETURN ON AGENCYSALERETURN_DESC.ASALRET_no = AGENCYSALERETURN.ASALRET_NO AND AGENCYSALERETURN_DESC.ASALRET_yearid = AGENCYSALERETURN.ASALRET_YEARID INNER JOIN 
LEDGERS ON AGENCYSALERETURN.ASALRET_LEDGERID = LEDGERS.ACC_ID INNER JOIN LEDGERS AS NLEDGERS ON LEDGERS.ACC_CMPNAME = NLEDGERS.ACC_CMPNAME AND NLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
ITEMMASTER ON AGENCYSALERETURN_DESC.ASALRET_ITEMID = ITEMMASTER.ITEM_ID LEFT OUTER JOIN ITEMMASTER AS NITEMMASTER ON ITEMMASTER.ITEM_NAME = NITEMMASTER.ITEM_NAME AND NITEMMASTER.ITEM_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS DELIVERYATLEDGERS ON AGENCYSALERETURN.ASALRET_DELIVERYATID = DELIVERYATLEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS NDELIVERYATLEDGERS ON DELIVERYATLEDGERS.ACC_CMPNAME = NDELIVERYATLEDGERS.ACC_CMPNAME AND NDELIVERYATLEDGERS.Acc_yearid = @YEARID  LEFT OUTER JOIN
HSNMASTER ON AGENCYSALERETURN_DESC.ASALRET_HSNCODEID = HSNMASTER.HSN_ID LEFT OUTER JOIN HSNMASTER AS NHSNMASTER ON HSNMASTER.HSN_CODE = NHSNMASTER.HSN_CODE AND NHSNMASTER.HSN_yearid = @YEARID LEFT OUTER JOIN
UNITMASTER ON AGENCYSALERETURN_DESC.ASALRET_QTYUNITID = UNITMASTER.UNIT_ID LEFT OUTER JOIN UNITMASTER AS NUNITMASTER ON UNITMASTER.UNIT_NAME = NUNITMASTER.UNIT_NAME AND NUNITMASTER.UNIT_yearid = @YEARID LEFT OUTER JOIN
PIECETYPEMASTER ON AGENCYSALERETURN_DESC.ASALRET_PIECETYPEID = PIECETYPEMASTER.PIECETYPE_id LEFT OUTER JOIN PIECETYPEMASTER AS NPIECETYPEMASTER ON PIECETYPEMASTER.PIECETYPE_name = NPIECETYPEMASTER.PIECETYPE_name AND NPIECETYPEMASTER.PIECETYPE_yearid = @YEARID
WHERE AGENCYSALERETURN.ASALRET_YEARID = @SELECTEDYEARID AND LEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ BUYER ]' AND DELIVERYATLEDGERS.ACC_CMPNAME <> 'ABHEE FABRICS LLP [ SELLER ]' 
ORDER BY AGENCYSALERETURN.ASALRET_NO DESC


-- **************** END OF AGENCYSALERETURN **********************


