DECLARE @CMPYEARID BIGINT
SET @CMPYEARID = 002000000000001
--SET @CMPYEARID = 002000000000002
--SET @CMPYEARID = 002000000000003
--SET @CMPYEARID = 002000000000004


DELETE FROM TEXTRADE.DBO.TEMPAGENCYRECEIPT
DELETE FROM TEXTRADE.DBO.TEMPAGENCYRECEIPT_DESC
DELETE FROM TEXTRADE.DBO.TEMPAGENCYCREDITNOTE

--MASTER RECORDS
INSERT INTO TEXTRADE.DBO.TEMPAGENCYRECEIPT
select RCT_NO AS ENTRYNO, CASH_DATE AS RECDATE , BUYERACCMAS.CASH_ACC AS BUYERNAME, SELLERACCMAS.CASH_ACC AS SELLERNAME, ISNULL(BANKMAS.CASH_ACC,'') AS PARTYBANKNAME, AGSALRCT.CASH_AMT AS CHQAMT,
CHQ_NO AS CHQNO, CHQ_DATE AS CHQDATE, AGSALRCT.CASH_NAR AS REMARKS, REF_NO AS OURREMARKS
FROM AGSALRCT INNER JOIN 
ACCMAS AS BUYERACCMAS ON AGSALRCT.CASH_ACC_ENTITY_UID = BUYERACCMAS.ENTITY_UID INNER JOIN
ACCMAS AS SELLERACCMAS ON AGSALRCT.DEBIT_ACC_ENTITY_UID = SELLERACCMAS.ENTITY_UID LEFT OUTER JOIN
BANKMAS ON AGSALRCT.PARTY_BANK_ENTITY_UID = BANKMAS.ENTITY_UID

WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID 
ORDER BY AUTO_BILL_NO 



--DESCRIPION RECORDS
INSERT INTO TEXTRADE.DBO.TEMPAGENCYRECEIPT_DESC
SELECT * FROM
(
SELECT AGSALRCT.AUTO_BILL_NO AS RECEIPTNO, AGOSSAL.AUTO_BILL_NO AS INVOICENO, AGSALRCTD.RCT_AMT AS AMT,
'Against Bill' AS PAYTYPE, CASE WHEN AGOSSAL.COMPANY_YEAR_ENTITY_UID <> @CMPYEARID THEN 'OPENING' ELSE 'AGENCYINVOICE' END AS FROMTYPE
FROM AGSALRCTD INNER JOIN AGSALRCT ON AGSALRCT.ENTITY_UID = AGSALRCTD.RCT_ENTITY_UID LEFT OUTER JOIN
AGOSSAL ON AGSALRCTD.REF_OSSAL_ENTITY_UID =AGOSSAL.OSSAL_ENTITY_UID  
WHERE AGSALRCT.COMPANY_YEAR_ENTITY_UID =@CMPYEARID 


--WE HAVE REMOVED THIS AS OF NOW
UNION ALL
SELECT AGSALRCT.AUTO_BILL_NO AS RECEIPTNO, 0 AS INVOICENO, (AGSALRCT.CASH_AMT - AGSALRCT.TOT_RCT) AS AMT,
'On Account' AS PAYTYPE, 'AGENCYINVOICE' AS FROMTYPE
FROM AGSALRCT  
WHERE AGSALRCT.COMPANY_YEAR_ENTITY_UID =@CMPYEARID AND AGSALRCT.CASH_AMT - AGSALRCT.TOT_RCT <> 0

) AS T
ORDER BY T.RECEIPTNO, INVOICENO


--WE NEED TO INSERT DEBITNOTE AMT IN AGENCYCREDITNOTE
INSERT INTO TEXTRADE.DBO.TEMPAGENCYCREDITNOTE
SELECT AGSALRCT.AUTO_BILL_NO AS RECEIPTNO, AGSALRCT.CASH_DATE AS DATE, BUYERACCMAS.CASH_ACC AS BUYERNAME, SELLERACCMAS.CASH_ACC AS SELLERNAME, ISNULL(BROKERACCMAS.CASH_ACC,'') AS BROKERNAME,
AGOSSAL.BILL_NO AS PARTYREFNO ,ISNULL(ACCMAS.CASH_ACC,'') AS DEBITNAME,  AGOSSAL.AUTO_BILL_NO AS INVOICENO, AGSALRCTD.LESS_AMT AS AMT,
CASE WHEN AGOSSAL.COMPANY_YEAR_ENTITY_UID <> @CMPYEARID THEN 'OPENING' ELSE 'AGENCYINVOICE' END AS FROMTYPE
FROM AGSALRCT INNER JOIN AGSALRCTD ON AGSALRCT.ENTITY_UID = AGSALRCTD.RCT_ENTITY_UID  LEFT OUTER JOIN 
ACCMAS AS BUYERACCMAS ON AGSALRCT.CASH_ACC_ENTITY_UID = BUYERACCMAS.ENTITY_UID LEFT OUTER JOIN
ACCMAS AS SELLERACCMAS ON AGSALRCT.DEBIT_ACC_ENTITY_UID = SELLERACCMAS.ENTITY_UID LEFT OUTER JOIN 
ACCMAS AS BROKERACCMAS ON AGSALRCT.BROK_ACC_ENTITY_UID = BROKERACCMAS.ENTITY_UID LEFT OUTER JOIN
AGSALRCTDET ON AGSALRCTDET.RCT_ENTITY_UID=AGSALRCTD.RCT_ENTITY_UID LEFT OUTER JOIN 
ACCMAS ON AGSALRCTDET.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID LEFT OUTER JOIN
AGOSSAL ON AGSALRCTD.REF_OSSAL_ENTITY_UID =AGOSSAL.OSSAL_ENTITY_UID 
WHERE AGSALRCT.COMPANY_YEAR_ENTITY_UID =@CMPYEARID AND AGSALRCTD.LESS_AMT>0 
ORDER BY AGSALRCT.AUTO_BILL_NO









