----INSERT DATA FROM TEMPAGENCYMASTER TO AGENCYINVOICEMASTER
DECLARE @CMPID INT, @USERID INT, @YEARID INT
SET @CMPID = 1
SET @USERID = 1
SET @YEARID = 1

----FIRST CHECK WHETHER ALL CHARGESNAME ARE PRESENT IN LEDGERS OR NOT, THEN EXECUTE THE BOTTOM QUERY
--SELECT DISTINCT BUYERNAME FROM  TEMPAGENCYRECEIPT WHERE BUYERNAME NOT IN (SELECT LEDGERS.ACC_CMPNAME FROM LEDGERS WHERE ACC_YEARID = @YEARID)
--SELECT DISTINCT SELLERNAME FROM  TEMPAGENCYRECEIPT WHERE SELLERNAME NOT IN (SELECT LEDGERS.ACC_CMPNAME FROM LEDGERS WHERE ACC_YEARID = @YEARID)
--SELECT DISTINCT BUYERNAME FROM  TEMPAGENCYCREDITNOTE WHERE BUYERNAME NOT IN (SELECT LEDGERS.ACC_CMPNAME FROM LEDGERS WHERE ACC_YEARID = @YEARID)
--SELECT DISTINCT SELLERNAME FROM  TEMPAGENCYCREDITNOTE WHERE SELLERNAME NOT IN (SELECT LEDGERS.ACC_CMPNAME FROM LEDGERS WHERE ACC_YEARID = @YEARID)


--DELETE FROM AGENCYRECEIPTMASTER WHERE ARECEIPT_YEARID = @YEARID
--DELETE FROM AGENCYRECEIPTMASTER_DESC WHERE ARECEIPT_YEARID = @YEARID
--DELETE FROM AGENCYCREDITNOTEMASTER WHERE ACN_yearid = @YEARID
--DELETE FROM AGENCYCREDITNOTEMASTER_BILLDESC WHERE ACN_yearid = @YEARID


--INSERT INTO AGENCYRECEIPTMASTER
--SELECT ENTRYNO, (SELECT REGISTER_ID FROM REGISTERMASTER WHERE register_name = 'RECEIPT' AND register_yearid = @YEARID) AS REGID,
--'REC-' + CAST(ENTRYNO AS VARCHAR(5)) AS INITIALS, TEMPAGENCYRECEIPT.DATE, SELLERLEDGERS.ACC_ID, BUYERLEDGERS.ACC_ID, PARTYBANKNAME, CHQAMT AS TOTAL,
--CHQNO, REMARKS, '' AS BILLREMARKS, OURREMARKS, '', 0,'' AS RECODATE,0, @CMPID,0, @USERID, @YEARID, 0, GETDATE(), '',0, CASE WHEN CHQDATE IS NULL THEN DATE ELSE CHQDATE END 
--FROM TEMPAGENCYRECEIPT INNER JOIN
--LEDGERS AS SELLERLEDGERS ON SELLERLEDGERS.Acc_cmpname = SELLERNAME AND SELLERLEDGERS.Acc_yearid = @YEARID INNER JOIN
--LEDGERS AS BUYERLEDGERS ON BUYERLEDGERS.Acc_cmpname = BUYERNAME AND BUYERLEDGERS.Acc_yearid = @YEARID 



--INSERT INTO AGENCYRECEIPTMASTER_DESC
--SELECT RECEIPTNO, (SELECT REGISTER_ID FROM REGISTERMASTER WHERE register_name = 'RECEIPT' AND register_yearid = @YEARID) AS REGID,
--'REC-' + CAST(RECEIPTNO AS VARCHAR(5)) AS INITIALS, 1, CASE WHEN AGENCYINVNO = 0 THEN 'On Account' ELSE 'Against Bill' END, AGENCYINVOICEMASTER.AINVOICE_INITIALS,
--'', AMT,0,0,0, AMT, @CMPID, 0, @USERID, @YEARID, 0, GETDATE()
--FROM TEMPAGENCYRECEIPT_DESC LEFT OUTER JOIN
--AGENCYINVOICEMASTER ON TEMPAGENCYRECEIPT_DESC.AGENCYINVNO = AGENCYINVOICEMASTER.AINVOICE_NO AND AGENCYINVOICEMASTER.AINVOICE_YEARID = @YEARID




--INSERT INTO AGENCYCREDITNOTEMASTER
--SELECT        TEMPAGENCYCREDITNOTE.ENTRYNO, 'CN-' + CAST(TEMPAGENCYCREDITNOTE.ENTRYNO AS VARCHAR(10)) AS INITIALS, TEMPAGENCYCREDITNOTE.DATE, TEMPAGENCYCREDITNOTE.DATE, '' AS Expr3, '' AS Expr4, 
--                         ISNULL(AGENCYINVOICEMASTER.AINVOICE_PRINTINITIALS, '') AS INVPRINTINITIALS, '' AS PARTYREFNO, BUYERLEDGERS.Acc_id, BROKERLEDGERS.Acc_id AS Expr5, 0 AS Expr6, 
--                         SELLERLEDGERS.Acc_id AS Expr7, 0 AS Expr8, 0 AS Expr9, 0 AS Expr10, 0 AS ACTUALINVAMT, 0 AS Expr11, SUM(TEMPAGENCYCREDITNOTE.AMT) AS Expr40, 0 AS TAXAMT, 0 AS OTHERCHGSAMT, 0 AS CHGS, 0 AS RCM, 
--                         1 AS MANUALGST, 1 AS MANUALROUNDOFF, 1 AS NOGSTR1, SUM(TEMPAGENCYCREDITNOTE.AMT) AS SUBTOTAL, 0 AS CGSTPER, 0 AS Expr12, 0 AS Expr13, 0 AS Expr14, 0 AS Expr15, 0 AS Expr16, 
--                         SUM(TEMPAGENCYCREDITNOTE.AMT) AS TOTALWITHGST, 0 AS Expr17, 0 AS Expr18, 0 AS Expr19, 0 AS Expr20, SUM(TEMPAGENCYCREDITNOTE.AMT) AS GTOTAL, 0 AS AMTPAID, 0 AS Expr21, 0 AS Expr22, 
--                         SUM(TEMPAGENCYCREDITNOTE.AMT) AS BALANCE, TEMPAGENCYCREDITNOTE.DEBITNAME AS REMARKS, '' AS Expr23, '' AS Expr24, 0 AS Expr25, 'CN-' + CAST(TEMPAGENCYCREDITNOTE.ENTRYNO AS VARCHAR(10)) 
--                         AS PRINTINITALS, '' AS Expr26, '' AS Expr27, NULL AS ACKDATE, NULL AS QRCODE, @CMPID AS Expr28, 0 AS Expr29, @USERID AS Expr30, @YEARID AS Expr31, 0 AS Expr32, GETDATE() AS Expr33, GETDATE() AS Expr34, 
--                         @USERID AS Expr35, '' AS Expr36, 0 AS Expr37, 0 AS Expr38, 0 AS Expr39
--FROM            TEMPAGENCYCREDITNOTE LEFT OUTER JOIN
--                         AGENCYINVOICEMASTER ON TEMPAGENCYCREDITNOTE.INVOICENO = AGENCYINVOICEMASTER.AINVOICE_NO AND AGENCYINVOICEMASTER.AINVOICE_YEARID = @YEARID INNER JOIN
--                         LEDGERS AS BUYERLEDGERS ON TEMPAGENCYCREDITNOTE.BUYERNAME = BUYERLEDGERS.Acc_cmpname AND BUYERLEDGERS.Acc_yearid = @YEARID INNER JOIN
--                         LEDGERS AS SELLERLEDGERS ON TEMPAGENCYCREDITNOTE.SELLERNAME = SELLERLEDGERS.Acc_cmpname AND SELLERLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
--                         LEDGERS AS BROKERLEDGERS ON TEMPAGENCYCREDITNOTE.BROKERNAME = BROKERLEDGERS.Acc_cmpname AND BROKERLEDGERS.Acc_yearid = @YEARID
--GROUP BY TEMPAGENCYCREDITNOTE.ENTRYNO, 'CN-' + CAST(TEMPAGENCYCREDITNOTE.ENTRYNO AS VARCHAR(10)), TEMPAGENCYCREDITNOTE.DATE, ISNULL(AGENCYINVOICEMASTER.AINVOICE_PRINTINITIALS, ''), 
--                         BUYERLEDGERS.Acc_id, BROKERLEDGERS.Acc_id, SELLERLEDGERS.Acc_id, TEMPAGENCYCREDITNOTE.DEBITNAME
--ORDER BY TEMPAGENCYCREDITNOTE.ENTRYNO


--INSERT INTO AGENCYCREDITNOTEMASTER_BILLDESC
--SELECT ENTRYNO, 1, 'Against Bill', ISNULL(AGENCYINVOICEMASTER.AINVOICE_INITIALS,'') AS BILLINITIALS, '', AMT, 0, 0, 0, AMT AS BALANCE, @CMPID, @USERID, @YEARID 
--FROM TEMPAGENCYCREDITNOTE LEFT OUTER JOIN
--AGENCYINVOICEMASTER ON TEMPAGENCYCREDITNOTE.INVOICENO = AGENCYINVOICEMASTER.AINVOICE_NO AND AGENCYINVOICEMASTER.AINVOICE_YEARID = @YEARID
--ORDER BY ENTRYNO








