DECLARE @CMPYEARID BIGINT
SET @CMPYEARID = 002000000000001
--SET @CMPYEARID = 002000000000002
--SET @CMPYEARID = 002000000000003
--SET @CMPYEARID = 002000000000004




----CHECK WHETHER LEDGER IS PRESENT IN TEXTRADE OR NOT
--SELECT DISTINCT ACCMAS.CASH_ACC FROM AGDAT INNER JOIN ACCMAS ON AGDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID
--AND ACCMAS.CASH_ACC NOT IN (SELECT TEXTRADE.DBO.LEDGERS.Acc_cmpname FROM TEXTRADE.DBO.LEDGERS WHERE TEXTRADE.DBO.LEDGERS.Acc_yearid = 4)

--SELECT DISTINCT ACCMAS.CASH_ACC FROM AGDAT INNER JOIN ACCMAS ON AGDAT.DEBIT_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID
--AND ACCMAS.CASH_ACC NOT IN (SELECT TEXTRADE.DBO.LEDGERS.Acc_cmpname FROM TEXTRADE.DBO.LEDGERS WHERE TEXTRADE.DBO.LEDGERS.Acc_yearid = 4)



--DELETE FROM TEXTRADE.DBO.TEMPAGENCYMASTER
--DELETE FROM TEXTRADE.DBO.TEMPAGENCYMASTER_DESC
--DELETE FROM TEXTRADE.DBO.TEMPAGENCYMASTER_CHGS
--DELETE FROM TEXTRADE.DBO.TEMPAGENCYSALERETURN



----MASTER RECORDS
--INSERT INTO TEXTRADE.DBO.TEMPAGENCYMASTER
--SELECT       AUTO_BILL_NO AS ENTRYNO, AGDAT.BILL_NO AS PARTYBILLNO, AGDAT.CASH_DATE AS PARTYBILLDATE, ACCMAS.CASH_ACC AS BUYERNAME,
--SELLERACCMAS.CASH_ACC AS SELLERNAME, ISNULL(BROKERACCMAS.CASH_ACC,'') AS BROKERNAME, PAY_DAYS AS CRDAYS, DUE_DATE AS DUEDATE, ISNULL(TRANMAS.CASH_ACC,'') AS TRANSNAME,
--AGDAT.LR_NO AS LRNO, LR_DATE AS LRDATE, AGDAT.TOT_BALES AS NOOFBALES, ISNULL(CITYMAS.CASH_ACC,'') AS FROMCITY, ISNULL(CITYTO.CASH_ACC,'') AS TOCITY, 
--ISNULL(NET_PCS,0) AS TOTALPCS, ISNULL(NET_QTY,0) AS TOTALMTRS, 
--DET.CGSTRATE AS CGSTPER,
--ISNULL(CGSTCHGS.CGST,0) AS CGSTAMT,
--DET.SGSTRATE AS SGSTPER,
--ISNULL(SGSTCHGS.SGST,0) AS SGSTAMT,
--DET.IGSTRATE AS IGSTPER,
--ISNULL(IGSTCHGS.IGST,0) AS IGSTAMT,
--1 AS MANUALGST,
--NET_AMT AS GRANDTOTAL, COURIER_NO AS BROKERAGEON, AGDAT.BROK_RATE AS COMMPER, AGDAT.CASH_NAR AS REMARKS 
--FROM            AGDAT  INNER JOIN ACCMAS ON CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID INNER JOIN
--ACCMAS AS SELLERACCMAS ON DEBIT_ACC_ENTITY_UID = SELLERACCMAS.ENTITY_UID LEFT OUTER JOIN
--ACCMAS AS BROKERACCMAS ON AGDAT.BROK_ACC_ENTITY_UID=BROKERACCMAS.ENTITY_UID LEFT OUTER JOIN
--TRANMAS ON AGDAT.TRAN_ACC_ENTITY_UID = TRANMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS ON AGDAT.DELFROM_ACC_ENTITY_UID = CITYMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS AS CITYTO ON AGDAT.DELTO_ACC_ENTITY_UID = CITYTO.ENTITY_UID CROSS APPLY
--(SELECT TOP 1 AGDET.CGST_RATE AS CGSTRATE, AGDET.SGST_RATE AS SGSTRATE, AGDET.IGST_RATE AS IGSTRATE FROM AGDET WHERE AGDET.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND AGDAT.ENTITY_UID= AGDET.PUR_ENTITY_UID ) AS DET 
--OUTER APPLY
--(SELECT TOP 1 AGCASHDAT.CASH_AMT AS CGST FROM AGCASHDAT INNER JOIN ACCMAS ON AGCASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE AGCASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  AGDAT.ENTITY_UID = AGCASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'CGST') AS CGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 AGCASHDAT.CASH_AMT AS SGST FROM AGCASHDAT INNER JOIN ACCMAS ON AGCASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE AGCASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  AGDAT.ENTITY_UID = AGCASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'SGST') AS SGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 AGCASHDAT.CASH_AMT AS IGST FROM AGCASHDAT INNER JOIN ACCMAS ON AGCASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE AGCASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  AGDAT.ENTITY_UID = AGCASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'IGST') AS IGSTCHGS
--WHERE        (AGDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID)
--ORDER BY AUTO_BILL_NO



----DESC RECORDS
--INSERT INTO TEXTRADE.DBO.TEMPAGENCYMASTER_DESC
--select AGDAT.AUTO_BILL_NO AS ENTRYNO, ITEMMAS.CASH_ACC AS ITEMNAME, BALE_NO AS BALENO, TOT_PCS AS PCS, BILL_MTRS AS AQTY, TOT_FOLD AS FOLDPER, TOT_QTY AS MTRS, AGDET.ITEM_RATE AS RATE,
--'Mtrs' AS PER, CASH_AMT1 AS AMT
--FROM AGDET INNER JOIN ITEMMAS ON ITEM_CODE_ENTITY_UID= ENTITY_UID INNER JOIN
--AGDAT ON AGDET.PUR_ENTITY_UID = AGDAT.ENTITY_UID
--WHERE AGDET.COMPANY_YEAR_ENTITY_UID = @CMPYEARID 
--ORDER BY AGDET.PUR_ENTITY_UID



----EXTRACHGS RECORDS WITHOUT CGST | SGST | IGST, WE NEED TO GET DISCOUNT FROM AGDAT
--INSERT INTO TEXTRADE.DBO.TEMPAGENCYMASTER_CHGS
--SELECT * FROM
--(
--SELECT AGDAT.AUTO_BILL_NO AS ENTRYNO, 'DISCOUNT A/C' AS CHARGESNAME, DISC_RATE*-1 AS DISCPER, DISC_AMT*-1 AS CHARGES
--FROM AGDET  INNER JOIN
--AGDAT ON AGDET.PUR_ENTITY_UID = AGDAT.ENTITY_UID
--WHERE        (AGDET.COMPANY_YEAR_ENTITY_UID = @CMPYEARID)
--AND AGDET.DISC_AMT <> 0


--UNION ALL
--select AGDAT.AUTO_BILL_NO AS ENTRYNO, ACCMAS.CASH_ACC AS CHARGESNAME, 0 AS PER, CASH_AMT AS CHARGES 
--FROM AGCASHDAT INNER JOIN ACCMAS ON AGCASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID
--INNER JOIN AGDAT ON AGDAT.ENTITY_UID = AGCASHDAT.ENTITY_UID
--WHERE AGCASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND SAY_CODE_ENTITY_UID = 'PURCHASE REGISTER' 
--AND ACCMAS.CASH_ACC NOT IN ('CGST', 'SGST', 'IGST')
--) AS T
--ORDER BY T.ENTRYNO, CHARGESNAME





----FOR SALERETURN MASTER
--INSERT INTO TEXTRADE.DBO.TEMPAGENCYSALERETURN
--SELECT AUTO_BILL_NO AS ENTRYNO, CASH_DATE AS DATE, BUYERACCMAS.CASH_ACC AS BUYERNAME, SELLERACCMAS.CASH_ACC AS SELLERNAME, ISNULL(BROKERACCMAS.CASH_ACC,'') AS BROKERNAME,
--ISNULL(TRANMAS.CASH_ACC,'') AS TRANSNAME, LR_NO AS LRNO, LR_DATE AS LRDATE, ISNULL(FROMCITYMAS.CASH_ACC,'') AS FROMCITY, ISNULL(TOCITYMAS.CASH_ACC,'') AS TOCITY,
--NET_QTY AS TOTALQTY,AGSRETDAT.GROSS_AMT AS AMOUNT ,
--CASE WHEN ISNULL(CGSTCHGS.CGST,0) > 0 THEN 2.50 ELSE 0 END AS CGSTPER,
--ISNULL(CGSTCHGS.CGST,0) AS CGSTAMT,
--CASE WHEN ISNULL(SGSTCHGS.SGST,0) > 0 THEN 2.50 ELSE 0 END AS SGSTPER,
--ISNULL(SGSTCHGS.SGST,0) AS SGSTAMT,
--CASE WHEN ISNULL(IGSTCHGS.IGST,0) > 0 THEN 5.00 ELSE 0 END AS IGSTPER,
--ISNULL(IGSTCHGS.IGST,0) AS IGSTAMT,
--AGSRETDAT.NET_AMT AS GRANDTOTAL
--FROM AGSRETDAT	INNER JOIN
--ACCMAS AS BUYERACCMAS ON AGSRETDAT.CASH_ACC_ENTITY_UID = BUYERACCMAS.ENTITY_UID INNER JOIN
--ACCMAS AS SELLERACCMAS ON AGSRETDAT.DEBIT_ACC_ENTITY_UID = SELLERACCMAS.ENTITY_UID LEFT OUTER JOIN
--ACCMAS AS BROKERACCMAS ON AGSRETDAT.BROK_ACC_ENTITY_UID = BROKERACCMAS.ENTITY_UID LEFT OUTER JOIN
--TRANMAS ON AGSRETDAT.TRAN_ACC_ENTITY_UID = TRANMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS AS FROMCITYMAS ON AGSRETDAT.DELFROM_ACC_ENTITY_UID = FROMCITYMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS AS TOCITYMAS ON AGSRETDAT.DELTO_ACC_ENTITY_UID = TOCITYMAS.ENTITY_UID  OUTER APPLY
--(SELECT TOP 1 AGCASHDAT.CASH_AMT AS CGST FROM AGCASHDAT INNER JOIN ACCMAS ON AGCASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE AGCASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  AGSRETDAT.ENTITY_UID = AGCASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'CGST') AS CGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 AGCASHDAT.CASH_AMT AS SGST FROM AGCASHDAT INNER JOIN ACCMAS ON AGCASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE AGCASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  AGSRETDAT.ENTITY_UID = AGCASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'SGST') AS SGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 AGCASHDAT.CASH_AMT AS IGST FROM AGCASHDAT INNER JOIN ACCMAS ON AGCASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE AGCASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  AGSRETDAT.ENTITY_UID = AGCASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'IGST') AS IGSTCHGS
--WHERE AGSRETDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID --AND AGSRETDAT.ENTITY_UID = 203000000000401
--ORDER BY ENTRYNO


