----INSERT DATA FROM TEMPAGENCYMASTER TO AGENCYINVOICEMASTER
DECLARE @CMPID INT, @USERID INT, @YEARID INT
SET @CMPID = 1
SET @USERID = 1
SET @YEARID = 1



----FIRST CHECK WHETHER ALL CHARGESNAME ARE PRESENT IN LEDGERS OR NOT, THEN EXECUTE THE BOTTOM QUERY
--SELECT DISTINCT CHARGESNAME FROM  TEMPAGENCYMASTER_CHGS WHERE CHARGESNAME NOT IN (SELECT LEDGERS.ACC_CMPNAME FROM LEDGERS WHERE ACC_YEARID = @YEARID)



--DELETE FROM AGENCYINVOICEMASTER WHERE AINVOICE_YEARID = @YEARID
--DELETE FROM AGENCYINVOICEMASTER_DESC WHERE AINVOICE_YEARID = @YEARID
--DELETE FROM AGENCYINVOICEMASTER_CHGS WHERE AINVOICE_YEARID = @YEARID



--INSERT INTO AGENCYINVOICEMASTER
--SELECT ENTRYNO, 'S-' + CAST(ENTRYNO AS VARCHAR(5))  AS INITIALS, 'TOTAL GST' AS SCREENTYPE, BUYERLEDGERS.ACC_ID AS BUYERID, 0 AS PONO,PARTYBILLNO AS PARTYPONO,
--PARTYBILLDATE AS PODATE, NOOFBALES AS BALENOFROM, 0 AS BALENOTO, PARTYBILLDATE AS INVDATE, 0 AS LOCALTRANSID, 0 AS HASTEID,
--ISNULL(AGENTLEDGERS.ACC_ID,0) AS AGENTID, 0 AS GDNNO, PARTYBILLDATE AS GDNDATE, '' AS REFNO,0 AS FORMID,CRDAYS , (CASE WHEN DUEDATE IS NULL THEN PARTYBILLDATE ELSE DUEDATE END),
--SELLERLEDGERS.ACC_ID AS SELLERID, ISNULL(TRANSLEDGERS.ACC_ID,0) AS TRANSID, '', LRNO, (CASE WHEN LRDATE IS NULL THEN PARTYBILLDATE ELSE LRDATE END),
--ISNULL(FROMCITYMASTER.CITY_ID,0) AS FROMCITYID, ISNULL(TOCITYMASTER.CITY_ID,0) AS TOCITYID, 0 AS PACKINGID, '' AS EWAYBILLNO, '' AS GPNO, PARTYBILLDATE AS GPDATE,
--0 AS CHECKED, 0 AS DISPUTE, MANUALGST, 0, NOOFBALES, TOTALPCS, TOTALMTRS, 0 AS AMT, 0,0,0,0,CGSTPER,CGSTAMT, SGSTPER,SGSTAMT, IGSTPER,IGSTAMT, 0,0,0,0,0,0 AS  CHARGES,
--0 AS SUBTOTAL,0, GRANDTOTAL, 0,0,0, GRANDTOTAL AS BALANCE,'', REMARKS,0,0,0,0,0,0, 'S-' + CAST(ENTRYNO AS VARCHAR(5))  AS PRINTINITIALS,
--0,'','','','','' AS VESSEL, '','','',0,0,0,0,0 AS TOTALUSDAMT,0,0,0,'','' AS IRNNO,'','1900-01-01' AS ACKDATE,NULL AS QRCODE, '', '1900-01-01' AS DOCKETDATE,
--'',@CMPID,0,@USERID,@YEARID,0, GETDATE(), GETDATE(), @USERID,0,'' AS SPECIALREM, 0,0,'',0,0,'GOODS PURCHASE',0 AS SACCODEID,0,0,0,0,0,COMMPER, TEMPAGENCYMASTER.BROKERAGEON,0, 0
--FROM TEMPAGENCYMASTER INNER JOIN 
--LEDGERS AS BUYERLEDGERS ON TEMPAGENCYMASTER.BUYERNAME = BUYERLEDGERS.Acc_cmpname AND BUYERLEDGERS.Acc_yearid = @YEARID INNER JOIN 
--LEDGERS AS SELLERLEDGERS ON TEMPAGENCYMASTER.SELLERNAME = SELLERLEDGERS.Acc_cmpname AND SELLERLEDGERS.Acc_yearid = @YEARID  LEFT OUTER JOIN
--LEDGERS AS TRANSLEDGERS ON TEMPAGENCYMASTER.TRANSNAME = TRANSLEDGERS.Acc_cmpname AND TRANSLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
--LEDGERS AS AGENTLEDGERS ON TEMPAGENCYMASTER.BROKERNAME = AGENTLEDGERS.Acc_cmpname AND AGENTLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
--CITYMASTER AS FROMCITYMASTER ON TEMPAGENCYMASTER.FROMCITY = FROMCITYMASTER.CITY_NAME AND FROMCITYMASTER.city_yearid = @YEARID LEFT OUTER JOIN
--CITYMASTER AS TOCITYMASTER ON TEMPAGENCYMASTER.TOCITY = TOCITYMASTER.CITY_NAME AND TOCITYMASTER.city_yearid = @YEARID




--INSERT INTO AGENCYINVOICEMASTER_DESC
--SELECT ENTRYNO, 'S-' + CAST(ENTRYNO AS VARCHAR(5))  AS INITIALS, 1, ISNULL(ITEM_ID,0) AS ITEMID, ISNULL(ITEM_HSNCODEID,0) AS HSNCODEID,
--0,0,0,AQTY AS QTY, FOLDPER, '', BALENO, PCS, 0, MTRS, RATE, PER,AMOUNT, AGENCYINVOICEMASTER.AINVOICE_LRNO, AINVOICE_TRANSID,0,0,0,0,0,0,0,0,0,0,0,0,AMOUNT AS GRIDTOTAL,'' AS BARCODE,
--0 AS FROMNO,0 AS FROMSRNO,'',0,0,@CMPID, 0, @USERID,@YEARID,0, GETDATE(), GETDATE(), @USERID,0,0,0
--FROM TEMPAGENCYMASTER_DESC INNER JOIN 
--ITEMMASTER ON TEMPAGENCYMASTER_DESC.ITEMNAME = ITEMMASTER.item_name AND ITEMMASTER.item_yearid = @YEARID INNER JOIN
--AGENCYINVOICEMASTER ON AINVOICE_NO= TEMPAGENCYMASTER_DESC.ENTRYNO




--INSERT INTO AGENCYINVOICEMASTER_CHGS
--SELECT ENTRYNO, 'S-' + CAST(ENTRYNO AS VARCHAR(5))  AS INITIALS, 1, LEDGERS.ACC_ID, PER, TEMPAGENCYMASTER_CHGS.CHARGES,0,@CMPID, 0, @USERID,@YEARID,0
--FROM TEMPAGENCYMASTER_CHGS INNER JOIN 
--LEDGERS ON TEMPAGENCYMASTER_CHGS.CHARGESNAME = LEDGERS.Acc_cmpname AND LEDGERS.Acc_yearid = @YEARID


