----INSERT DATA FROM TEMPAGENCYMASTER TO AGENCYINVOICEMASTER
DECLARE @CMPID INT, @USERID INT, @YEARID INT
SET @CMPID = 1
SET @USERID = 1
SET @YEARID = 1

----FIRST CHECK WHETHER ALL CHARGESNAME ARE PRESENT IN LEDGERS OR NOT, THEN EXECUTE THE BOTTOM QUERY
--SELECT DISTINCT BUYERNAME FROM  TEMPAGENCYRECEIPT WHERE BUYERNAME NOT IN (SELECT LEDGERS.ACC_CMPNAME FROM LEDGERS WHERE ACC_YEARID = @YEARID)
--SELECT DISTINCT SELLERNAME FROM  TEMPAGENCYRECEIPT WHERE SELLERNAME NOT IN (SELECT LEDGERS.ACC_CMPNAME FROM LEDGERS WHERE ACC_YEARID = @YEARID)


--DELETE FROM AGENCYRECEIPTMASTER WHERE ARECEIPT_YEARID = @YEARID
--DELETE FROM AGENCYRECEIPTMASTER_DESC WHERE ARECEIPT_YEARID = @YEARID


--INSERT INTO AGENCYRECEIPTMASTER
--SELECT * FROM TEMPAGENCYRECEIPT





