DECLARE @CMPYEARID BIGINT
SET @CMPYEARID = 002000000000001
--SET @CMPYEARID = 002000000000002
--SET @CMPYEARID = 002000000000003
--SET @CMPYEARID = 002000000000004


--DELETE FROM TEXTRADE.DBO.TEMPAGENCYRECEIPT
--DELETE FROM TEXTRADE.DBO.TEMPAGENCYRECEIPT_DESC

----MASTER RECORDS
--INSERT INTO TEXTRADE.DBO.TEMPAGENCYRECEIPT
--select RCT_NO AS ENTRYNO, CASH_DATE AS RECDATE , BUYERACCMAS.CASH_ACC AS BUYERNAME, SELLERACCMAS.CASH_ACC AS SELLERNAME, ISNULL(BANKMAS.CASH_ACC,'') AS PARTYBANKNAME, AGSALRCT.CASH_AMT AS CHQAMT,
--CHQ_NO AS CHQNO, CHQ_DATE AS CHQDATE, AGSALRCT.CASH_NAR AS REMARKS, REF_NO AS OURREMARKS
--FROM AGSALRCT INNER JOIN 
--ACCMAS AS BUYERACCMAS ON AGSALRCT.CASH_ACC_ENTITY_UID = BUYERACCMAS.ENTITY_UID INNER JOIN
--ACCMAS AS SELLERACCMAS ON AGSALRCT.DEBIT_ACC_ENTITY_UID = SELLERACCMAS.ENTITY_UID LEFT OUTER JOIN
--BANKMAS ON AGSALRCT.PARTY_BANK_ENTITY_UID = BANKMAS.ENTITY_UID

--WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID 
--ORDER BY AUTO_BILL_NO 



----DESCRIPION RECORDS
--INSERT INTO TEXTRADE.DBO.TEMPAGENCYRECEIPT_DESC
--SELECT AGSALRCT.AUTO_BILL_NO AS RECEIPTNO, AGOSSAL.AUTO_BILL_NO AS INVOICENO, AGSALRCTD.RCT_AMT AS AMT 
--FROM AGSALRCTD INNER JOIN AGSALRCT ON AGSALRCT.ENTITY_UID = AGSALRCTD.RCT_ENTITY_UID LEFT OUTER JOIN
--AGOSSAL ON AGSALRCTD.REF_OSSAL_ENTITY_UID =AGOSSAL.OSSAL_ENTITY_UID  
--WHERE AGSALRCT.COMPANY_YEAR_ENTITY_UID =@CMPYEARID 
--ORDER BY AGSALRCT.AUTO_BILL_NO, INVOICENO


----WE NEED TO INSERT DEBITNOTE AMT IN AGENCYCREDITNOTE
--SELECT * FROM AGSALRCTDET WHERE COMPANY_YEAR_ENTITY_UID =002000000000001 --AND RCT_ENTITY_UID = 202000000000275








