----INSERT DATA FROM TEMPAGENCYMASTER TO AGENCYINVOICEMASTER
DECLARE @CMPID INT, @USERID INT, @YEARID INT
SET @CMPID = 1
SET @USERID = 1
SET @YEARID = 1

----FIRST CHECK WHETHER ALL CHARGESNAME ARE PRESENT IN LEDGERS OR NOT, THEN EXECUTE THE BOTTOM QUERY
--SELECT DISTINCT BUYERNAME FROM  TEMPAGENCYRECEIPT WHERE BUYERNAME NOT IN (SELECT LEDGERS.ACC_CMPNAME FROM LEDGERS WHERE ACC_YEARID = @YEARID)
--SELECT DISTINCT SELLERNAME FROM  TEMPAGENCYRECEIPT WHERE SELLERNAME NOT IN (SELECT LEDGERS.ACC_CMPNAME FROM LEDGERS WHERE ACC_YEARID = @YEARID)


--DELETE FROM AGENCYRECEIPTMASTER WHERE ARECEIPT_YEARID = @YEARID
--DELETE FROM AGENCYRECEIPTMASTER_DESC WHERE ARECEIPT_YEARID = @YEARID


--INSERT INTO AGENCYRECEIPTMASTER
--SELECT ENTRYNO, (SELECT REGISTER_ID FROM REGISTERMASTER WHERE register_name = 'RECEIPT' AND register_yearid = @YEARID) AS REGID,
--'REC-' + CAST(ENTRYNO AS VARCHAR(5)) AS INITIALS, TEMPAGENCYRECEIPT.DATE, SELLERLEDGERS.ACC_ID, BUYERLEDGERS.ACC_ID, PARTYBANKNAME, CHQAMT AS TOTAL,
--CHQNO, REMARKS, '' AS BILLREMARKS, OURREMARKS, '', 0,'' AS RECODATE,0, @CMPID,0, @USERID, @YEARID, 0, GETDATE(), '',0, CASE WHEN CHQDATE IS NULL THEN DATE ELSE CHQDATE END 
--FROM TEMPAGENCYRECEIPT INNER JOIN
--LEDGERS AS SELLERLEDGERS ON SELLERLEDGERS.Acc_cmpname = SELLERNAME AND SELLERLEDGERS.Acc_yearid = @YEARID INNER JOIN
--LEDGERS AS BUYERLEDGERS ON BUYERLEDGERS.Acc_cmpname = BUYERNAME AND BUYERLEDGERS.Acc_yearid = @YEARID 



--INSERT INTO AGENCYRECEIPTMASTER_DESC
--SELECT RECEIPTNO, (SELECT REGISTER_ID FROM REGISTERMASTER WHERE register_name = 'RECEIPT' AND register_yearid = @YEARID) AS REGID,
--'REC-' + CAST(RECEIPTNO AS VARCHAR(5)) AS INITIALS, 1, CASE WHEN AGENCYINVNO = 0 THEN 'On Account' ELSE 'Against Bill' END, AGENCYINVOICEMASTER.AINVOICE_INITIALS,
--'', AMT,0,0,0, AMT, @CMPID, 0, @USERID, @YEARID, 0, GETDATE()
--FROM TEMPAGENCYRECEIPT_DESC LEFT OUTER JOIN
--AGENCYINVOICEMASTER ON TEMPAGENCYRECEIPT_DESC.AGENCYINVNO = AGENCYINVOICEMASTER.AINVOICE_NO AND AGENCYINVOICEMASTER.AINVOICE_YEARID = @YEARID








