----INSERT DATA FROM TEMPINVOICEMASTER TO INVOICEMASTER
DECLARE @CMPID INT, @USERID INT, @YEARID INT
SET @CMPID = 2
SET @USERID = 1
SET @YEARID = 5



----FIRST CHECK WHETHER ALL CHARGESNAME ARE PRESENT IN LEDGERS OR NOT, THEN EXECUTE THE BOTTOM QUERY
--SELECT DISTINCT CHARGESNAME FROM  TEMPINVOICEMASTER_CHGS WHERE CHARGESNAME NOT IN (SELECT LEDGERS.ACC_CMPNAME FROM LEDGERS WHERE ACC_YEARID = @YEARID)



------**************************************** START OF INVOICE MASTER ENTRIES *****************************************************

--DELETE FROM INVOICEMASTER WHERE INVOICE_YEARID = @YEARID
--DELETE FROM INVOICEMASTER_DESC WHERE INVOICE_YEARID = @YEARID
--DELETE FROM INVOICEMASTER_CHGS WHERE INVOICE_YEARID = @YEARID


--INSERT INTO INVOICEMASTER
--SELECT ENTRYNO, (SELECT REGISTERMASTER.register_id FROM REGISTERMASTER WHERE register_name = 'SALE REGISTER' AND register_yearid = @YEARID) AS REGID, 
--'S-' + CAST(ENTRYNO AS VARCHAR(5))  AS INITIALS, 'TOTAL GST' AS SCREENTYPE, LEDGERS.ACC_ID AS LEDGERID, 0 AS PONO, '' AS PARTYPONO,
--DATE AS PODATE, NOOFBALES AS BALENOFROM, 0 AS BALENOTO, DATE AS INVDATE, 0 AS LOCALTRANSID, 0 AS HASTEID,
--0 AS AGENTID, 0 AS GDNNO, DATE AS GDNDATE, '' AS REFNO, 0 AS FORMID, CRDAYS , (CASE WHEN DUEDATE IS NULL THEN DATE ELSE DUEDATE END),
--0 AS PURLEDGERID, ISNULL(TRANSLEDGERS.ACC_ID,0) AS TRANSID, '' AS VEHICLENO, LRNO, (CASE WHEN LRDATE IS NULL THEN DATE ELSE LRDATE END),
--ISNULL(FROMCITYMASTER.CITY_ID,0) AS FROMCITYID, ISNULL(TOCITYMASTER.CITY_ID,0) AS TOCITYID, SHIPTOLEDGERS.ACC_ID AS PACKINGID, '' AS EWAYBILLNO, '' AS GPNO, DATE AS GPDATE,
--0 AS CHECKED, 0 AS DISPUTE, MANUALGST, 0, NOOFBALES, TOTALPCS, TOTALMTRS, 0 AS AMT, 0,0,0,0,CGSTPER,CGSTAMT, SGSTPER,SGSTAMT, IGSTPER,IGSTAMT, 0,0,0,0,0,0 AS  CHARGES,
--0 AS SUBTOTAL, TEMPINVOICEMASTER.ROUNDOFF, GRANDTOTAL, 0,0,0, GRANDTOTAL AS BALANCE,'', REMARKS,0,0,0,0,0,0, 'S-' + CAST(ENTRYNO AS VARCHAR(5))  AS PRINTINITIALS,
--0,'','','','','' AS VESSEL, '','','',0,0,0,0,0 AS TOTALUSDAMT,0,0,0,'', IRNNO,ACKNO, DATE  AS ACKDATE,
--NULL AS QRCODE, '', '1900-01-01' AS DOCKETDATE, '',@CMPID,0,@USERID,@YEARID,0, GETDATE(), GETDATE(), @USERID,0,'' AS SPECIALREM, 0,0,'',0,0,
--'GOODS PURCHASE',0 AS SACCODEID,0,0,0,0,0,0, 0,1,0 AS HOLDINTCALC
--FROM TEMPINVOICEMASTER INNER JOIN 
--LEDGERS ON TEMPINVOICEMASTER.NAME = LEDGERS.Acc_cmpname AND LEDGERS.Acc_yearid = @YEARID INNER JOIN 
--LEDGERS AS SHIPTOLEDGERS ON TEMPINVOICEMASTER.SHIPTO = SHIPTOLEDGERS.Acc_cmpname AND SHIPTOLEDGERS.Acc_yearid = @YEARID  LEFT OUTER JOIN
--LEDGERS AS TRANSLEDGERS ON TEMPINVOICEMASTER.TRANSNAME = TRANSLEDGERS.Acc_cmpname AND TRANSLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
--CITYMASTER AS FROMCITYMASTER ON TEMPINVOICEMASTER.FROMCITY = FROMCITYMASTER.CITY_NAME AND FROMCITYMASTER.city_yearid = @YEARID LEFT OUTER JOIN
--CITYMASTER AS TOCITYMASTER ON TEMPINVOICEMASTER.TOCITY = TOCITYMASTER.CITY_NAME AND TOCITYMASTER.city_yearid = @YEARID
--ORDER BY ENTRYNO



--INSERT INTO INVOICEMASTER_DESC
--SELECT ENTRYNO, (SELECT REGISTERMASTER.register_id FROM REGISTERMASTER WHERE register_name = 'SALE REGISTER' AND register_yearid = @YEARID) AS REGID, 
--'S-' + CAST(ENTRYNO AS VARCHAR(5))  AS INITIALS, 1, ISNULL(ITEM_ID,0) AS ITEMID, ISNULL(ITEM_HSNCODEID,0) AS HSNCODEID,
--0,0,0,GROSSQTY AS QTY, FOLD, ITEMDESC, BALENO, PCS, 0, MTRS, RATE, PER, AMOUNT, GRIDLRNO, ISNULL(TRANSLEDGERS.ACC_ID,0) AS GRIDTRANSID,
--0,0,0,0,0,0,0,0,0,0,0,0,AMOUNT AS GRIDTOTAL,'' AS BARCODE,
--0 AS FROMNO,0 AS FROMSRNO,'',0,0,@CMPID, 0, @USERID,@YEARID,0, GETDATE(), GETDATE(), @USERID,0,0,0,0,0,''
--FROM TEMPINVOICEMASTER_DESC INNER JOIN 
--ITEMMASTER ON TEMPINVOICEMASTER_DESC.ITEMNAME = ITEMMASTER.item_name AND ITEMMASTER.item_yearid = @YEARID INNER JOIN
--INVOICEMASTER ON INVOICE_NO= TEMPINVOICEMASTER_DESC.ENTRYNO AND INVOICEMASTER.INVOICE_YEARID = @YEARID LEFT OUTER JOIN
--LEDGERS AS TRANSLEDGERS ON TEMPINVOICEMASTER_DESC.GRIDTRANSPORT = TRANSLEDGERS.Acc_cmpname AND TRANSLEDGERS.Acc_yearid = @YEARID
--ORDER BY ENTRYNO


--INSERT INTO INVOICEMASTER_CHGS
--SELECT ENTRYNO,  (SELECT REGISTERMASTER.register_id FROM REGISTERMASTER WHERE register_name = 'SALE REGISTER' AND register_yearid = @YEARID) AS REGID,
--'S-' + CAST(ENTRYNO AS VARCHAR(5))  AS INITIALS, 1, LEDGERS.ACC_ID, PER, TEMPINVOICEMASTER_CHGS.CHARGES,0,@CMPID, 0, @USERID,@YEARID,0
--FROM TEMPINVOICEMASTER_CHGS INNER JOIN 
--LEDGERS ON TEMPINVOICEMASTER_CHGS.CHARGESNAME = LEDGERS.Acc_cmpname AND LEDGERS.Acc_yearid = @YEARID
--ORDER BY ENTRYNO
------**************************************** END OF INVOICE MASTER ENTRIES *****************************************************




----**************************************** START OF PURCHASE MASTER ENTRIES *****************************************************

--DELETE FROM PURCHASEMASTER WHERE BILL_YEARID = @YEARID
--DELETE FROM PURCHASEMASTER_DESC WHERE BILL_YEARID = @YEARID
--DELETE FROM PURCHASEMASTER_CHGS WHERE BILL_YEARID = @YEARID


--INSERT INTO PURCHASEMASTER
--SELECT ENTRYNO, (SELECT REGISTERMASTER.register_id FROM REGISTERMASTER WHERE register_name = 'PURCHASE REGISTER' AND register_yearid = @YEARID) AS REGID, 
--'P-' + CAST(ENTRYNO AS VARCHAR(5))  AS INITIALS, 'TOTAL GST' AS SCREENTYPE, 0 AS SACCODEID, 0 AS RCM, LEDGERS.ACC_ID AS LEDGERID, DATE, PARTYBILLNO, DATE AS PARTYBILLDATE,
--0 AS AGENTID, 0 AS GDNNO, DATE AS GDNDATE, '' AS REFNO, CRDAYS , (CASE WHEN DUEDATE IS NULL THEN DATE ELSE DUEDATE END),
--ISNULL(TRANSLEDGERS.ACC_ID,0) AS TRANSID, '' AS VEHICLENO, TEMPPDESC.GRIDLRNO, (CASE WHEN LRDATE IS NULL THEN DATE ELSE LRDATE END) AS LRDATE,
--ISNULL(FROMCITYMASTER.CITY_ID,0) AS FROMCITYID, ISNULL(TOCITYMASTER.CITY_ID,0) AS TOCITYID, '' AS EWAYBILLNO, NOOFBALES, 0 AS DEYINGID,
--0 AS CHECKED, 0 AS DISPUTE, MANUALGST, 1 AS MANUALROUNDOFF, REMARKS, 0,0, TOTALPCS, TOTALMTRS, 0 AS AMT, 0,0,0,0,CGSTPER,CGSTAMT, SGSTPER,SGSTAMT, IGSTPER,IGSTAMT, 
--0,1 AS MANUALTCS,1 AS APPLYTCS, 0 AS TCSPER,TCSAMT, '' AS INWORDS, 0 AS BILLAMT, 0,0, 0 AS  CHARGES, 0 AS SUBTOTAL, TEMPPURCHASEMASTER.ROUNDOFF, GRANDTOTAL, 0,0,0, GRANDTOTAL AS BALANCE,
--'GOODS PURCHASE' AS PURTYPE, 0, @CMPID,0,@USERID,@YEARID,0, GETDATE(), @USERID,GETDATE(), '' AS SPECIALREM, 0,0, 0 AS SHIPTOID, 1 AS SOLD, 0 AS HOLDINTCALC
--FROM TEMPPURCHASEMASTER INNER JOIN 
--LEDGERS ON TEMPPURCHASEMASTER.NAME = LEDGERS.Acc_cmpname AND LEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
--LEDGERS AS TRANSLEDGERS ON TEMPPURCHASEMASTER.TRANSNAME = TRANSLEDGERS.Acc_cmpname AND TRANSLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
--CITYMASTER AS FROMCITYMASTER ON TEMPPURCHASEMASTER.FROMCITY = FROMCITYMASTER.CITY_NAME AND FROMCITYMASTER.city_yearid = @YEARID LEFT OUTER JOIN
--CITYMASTER AS TOCITYMASTER ON TEMPPURCHASEMASTER.TOCITY = TOCITYMASTER.CITY_NAME AND TOCITYMASTER.city_yearid = @YEARID OUTER APPLY
--(SELECT TOP 1 GRIDLRNO AS GRIDLRNO FROM TEMPPURCHASEMASTER_DESC WHERE TEMPPURCHASEMASTER_DESC.ENTRYNO = TEMPPURCHASEMASTER.ENTRYNO) AS TEMPPDESC
--ORDER BY TEMPPURCHASEMASTER.ENTRYNO



--INSERT INTO PURCHASEMASTER_DESC
--SELECT ENTRYNO, (SELECT REGISTERMASTER.register_id FROM REGISTERMASTER WHERE register_name = 'PURCHASE REGISTER' AND register_yearid = @YEARID) AS REGID, 
--'P-' + CAST(ENTRYNO AS VARCHAR(5))  AS INITIALS, 1, ISNULL(ITEM_ID,0) AS ITEMID, ISNULL(ITEM_HSNCODEID,0) AS HSNCODEID,
--0,0,0,GROSSQTY AS QTY, FOLD, ITEMDESC, '' AS LOTNO, BALENO, PCS, (SELECT ISNULL(UNITMASTER.UNIT_ID,0) FROM UNITMASTER WHERE UNIT_ABBR ='Pcs' AND unit_yearid = @YEARID ) AS UNITID, 
--0 AS CUT, MTRS, 0 AS WT, RATE, PER, AMOUNT, 0,0,0,0,0,0,0,0,0,0,0,0,AMOUNT AS GRIDTOTAL, 0 AS GRNNO,0 AS FROMSRNO,'',0,0, 0  AS OUTMTRS,
--@CMPID, 0, @USERID,@YEARID,0
--FROM TEMPPURCHASEMASTER_DESC INNER JOIN 
--ITEMMASTER ON TEMPPURCHASEMASTER_DESC.ITEMNAME = ITEMMASTER.item_name AND ITEMMASTER.item_yearid = @YEARID INNER JOIN
--PURCHASEMASTER ON BILL_NO= TEMPPURCHASEMASTER_DESC.ENTRYNO AND PURCHASEMASTER.BILL_YEARID = @YEARID 
--ORDER BY ENTRYNO


--INSERT INTO PURCHASEMASTER_CHGS
--SELECT ENTRYNO,  (SELECT REGISTERMASTER.register_id FROM REGISTERMASTER WHERE register_name = 'PURCHASE REGISTER' AND register_yearid = @YEARID) AS REGID,
--'P-' + CAST(ENTRYNO AS VARCHAR(5))  AS INITIALS, 1, LEDGERS.ACC_ID, PER, TEMPPURCHASEMASTER_CHGS.CHARGES,0,@CMPID, 0, @USERID,@YEARID,0
--FROM TEMPPURCHASEMASTER_CHGS INNER JOIN 
--LEDGERS ON TEMPPURCHASEMASTER_CHGS.CHARGESNAME = LEDGERS.Acc_cmpname AND LEDGERS.Acc_yearid = @YEARID
--ORDER BY ENTRYNO
----**************************************** END OF PURCHASE MASTER ENTRIES *****************************************************



----**************************************** START OF AGENCY SALES RETURN ENTRIES *****************************************************

DELETE FROM SALERETURN WHERE SALRET_YEARID = @YEARID
DELETE FROM SALERETURN_DESC WHERE SALRET_YEARID = @YEARID
DELETE FROM SALERETURN_CHGS WHERE SALRET_YEARID = @YEARID
DELETE FROM SALERETURN_BILLDESC WHERE SALRET_YEARID = @YEARID

INSERT INTO SALERETURN
SELECT ENTRYNO, DATE, 0 as GODOWNID, LEDGERS.ACC_ID AS LEDGERID, (select DEBITLEDGERS.ACC_ID FROM LEDGERS AS DEBITLEDGERS WHERE DEBITLEDGERS.Acc_cmpname = 'SALES RETURN' AND Acc_yearid = @YEARID ) AS SELLERID, 
0,'',DATE as CHALLANDATE, '', DATE, '', DATE AS INVDATE, '', '' AS INVINITIALS,
'','', ISNULL(TRANSLEDGERS.ACC_ID,0) AS TRANSID, LRNO, LRDATE, ISNULL(AGENTLEDGERS.ACC_ID,0) AS AGENTID,'', 0, 0, TOTALQTY AS TOTALMTRS, AMOUNT,1 AS MANUALGST,
CGSTPER,CGSTAMT, SGSTPER,SGSTAMT, IGSTPER,IGSTAMT, AMOUNT,0 AS  CHARGES, 0 AS SUBTOTAL,0,0,0,0,0 AS ROUNDOFF, GRANDTOTAL, '', '', '', 0,ENTRYNO AS PRINTINITIALS, 
'','',DATE AS ACKDATE, NULL AS QRCODE,@CMPID,0,@USERID,@YEARID,0, GETDATE(), GETDATE(), @USERID,'' AS SPECIALREM, 0,0,0 AS NOOFBALES,
0 AS EXPORTGST,0,1, ISNULL(FROMCITYMASTER.city_id,0) AS FROMCITYID, ISNULL(TOCITYMASTER.city_id,0) AS TOCITYID

FROM TEMPSALERETURN INNER JOIN 
LEDGERS AS LEDGERS ON TEMPSALERETURN.BUYERNAME = LEDGERS.Acc_cmpname AND LEDGERS.Acc_yearid = @YEARID  LEFT OUTER JOIN
LEDGERS AS TRANSLEDGERS ON TEMPSALERETURN.TRANSNAME = TRANSLEDGERS.Acc_cmpname AND TRANSLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
LEDGERS AS AGENTLEDGERS ON TEMPSALERETURN.BROKERNAME = AGENTLEDGERS.Acc_cmpname AND AGENTLEDGERS.Acc_yearid = @YEARID LEFT OUTER JOIN
CITYMASTER AS FROMCITYMASTER ON TEMPSALERETURN.FROMCITY = FROMCITYMASTER.CITY_NAME AND FROMCITYMASTER.city_yearid = @YEARID LEFT OUTER JOIN
CITYMASTER AS TOCITYMASTER ON TEMPSALERETURN.TOCITY = TOCITYMASTER.CITY_NAME AND TOCITYMASTER.city_yearid = @YEARID
ORDER BY ENTRYNO




INSERT INTO SALERETURN_DESC
SELECT ENTRYNO, 1, (SELECT PIECETYPEMASTER.PIECETYPE_id FROM PIECETYPEMASTER WHERE PIECETYPEMASTER.PIECETYPE_name = 'FRESH' AND PIECETYPE_yearid = @YEARID), 
ISNULL(ITEM_ID,0) AS ITEMID, ISNULL(ITEM_HSNCODEID,0) AS HSNCODEID,0,0,0,MTRS AS AQTY, 0,  BALENO,0,0, PCS, 
(SELECT UNITMASTER.UNIT_id FROM UNITMASTER WHERE UNITMASTER.unit_abbr = 'Mtrs' AND UNIT_yearid = @YEARID),
MTRS, RATE, PER,AMT,0,0, '' AS BARCODE, '',0,0,0,0,0,@CMPID, 0, @USERID,@YEARID,0, GETDATE(), GETDATE(), @USERID
FROM TEMPSALERETURN_DESC INNER JOIN 
ITEMMASTER ON TEMPSALERETURN_DESC.ITEMNAME = ITEMMASTER.item_name AND ITEMMASTER.item_yearid = @YEARID
ORDER BY ENTRYNO



INSERT INTO SALERETURN_CHGS
SELECT ENTRYNO, 1, LEDGERS.ACC_ID, PER, TEMPSALERETURN_CHGS.CHARGES,0,@CMPID, 0, @USERID,@YEARID,0
FROM TEMPSALERETURN_CHGS INNER JOIN 
LEDGERS ON TEMPSALERETURN_CHGS.CHARGESNAME = LEDGERS.Acc_cmpname AND LEDGERS.Acc_yearid = @YEARID
ORDER BY ENTRYNO



INSERT INTO SALERETURN_BILLDESC
SELECT ENTRYNO, 1, 'Against Bill', INVOICEMASTER.INVOICE_INITIALS, TEMPSALERETURN_BILLDESC.PARTYBILLNO,AMOUNT,0,0,0,AMOUNT,@CMPID, @USERID,@YEARID
FROM TEMPSALERETURN_BILLDESC LEFT OUTER JOIN 
INVOICEMASTER ON TEMPSALERETURN_BILLDESC.AGENCYINVOICENO = INVOICEMASTER.INVOICE_NO AND INVOICEMASTER.INVOICE_YEARID = @YEARID
ORDER BY ENTRYNO
----**************************************** END OF AGENCY SALES RETURN ENTRIES *****************************************************






