DECLARE @CMPYEARID BIGINT
SET @CMPYEARID = 002000000000001
--SET @CMPYEARID = 002000000000003
--SET @CMPYEARID = 002000000000005
--SET @CMPYEARID = 002000000000008




----CHECK WHETHER LEDGER IS PRESENT IN TEXTRADE OR NOT
--SELECT DISTINCT ACCMAS.CASH_ACC FROM SALDAT INNER JOIN ACCMAS ON SALDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID
--AND ACCMAS.CASH_ACC NOT IN (SELECT TEXTRADE.DBO.LEDGERS.Acc_cmpname FROM TEXTRADE.DBO.LEDGERS WHERE TEXTRADE.DBO.LEDGERS.Acc_yearid = 5)

--SELECT DISTINCT ACCMAS.CASH_ACC FROM SALDAT INNER JOIN ACCMAS ON SALDAT.SHIP_TO_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID
--AND ACCMAS.CASH_ACC NOT IN (SELECT TEXTRADE.DBO.LEDGERS.Acc_cmpname FROM TEXTRADE.DBO.LEDGERS WHERE TEXTRADE.DBO.LEDGERS.Acc_yearid = 5)

--SELECT DISTINCT TRANMAS.CASH_ACC FROM SALDAT INNER JOIN TRANMAS ON SALDAT.TRAN_ACC_ENTITY_UID = TRANMAS.ENTITY_UID 
--WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID
--AND TRANMAS.CASH_ACC NOT IN (SELECT TEXTRADE.DBO.LEDGERS.Acc_cmpname FROM TEXTRADE.DBO.LEDGERS WHERE TEXTRADE.DBO.LEDGERS.Acc_yearid = 5)




---- ***************** START OF INVOICE ENTRIES ********************

--DELETE FROM TEXTRADE.DBO.TEMPINVOICEMASTER
DELETE FROM TEXTRADE.DBO.TEMPINVOICEMASTER_DESC
--DELETE FROM TEXTRADE.DBO.TEMPAGENCYMASTER_CHGS

--MASTER RECORDS
--INSERT INTO TEXTRADE.DBO.TEMPINVOICEMASTER 
--SELECT       AUTO_BILL_NO AS ENTRYNO, SALDAT.CASH_DATE AS DATE, ACCMAS.CASH_ACC AS NAME, SHIPTOACCMAS.CASH_ACC AS SHIPTONAME, 
--PAY_DAYS AS CRDAYS, DATEADD(DAY,PAY_DAYS,CAST(SALDAT.CASH_DATE AS DATE)) AS DUEDATE, ISNULL(TRANMAS.CASH_ACC,'') AS TRANSNAME,
--SALDAT.LR_NO AS LRNO, (CASE WHEN LR_DATE IS NULL THEN SALDAT.CASH_DATE ELSE LR_DATE END) AS LRDATE, ISNULL(CITYMAS.CASH_ACC,'') AS FROMCITY, ISNULL(CITYTO.CASH_ACC,'') AS TOCITY, 
--SALDAT.TOT_BALES AS NOOFBALES, ISNULL(NET_PCS,0) AS TOTALPCS, ISNULL(NET_QTY,0) AS TOTALMTRS, 
--0 AS TOTALAMT,
--DET.CGSTRATE AS CGSTPER,
--ISNULL(CGSTCHGS.CGST,0) AS CGSTAMT,
--DET.SGSTRATE AS SGSTPER,
--ISNULL(SGSTCHGS.SGST,0) AS SGSTAMT,
--DET.IGSTRATE AS IGSTPER,
--ISNULL(IGSTCHGS.IGST,0) AS IGSTAMT,
--1 AS MANUALGST, NET_AMT AS GRANDTOTAL, SALDAT.CASH_NAR AS REMARKS, SALDAT.IRN_NO AS IRNNO, SALDAT.ACK_NO AS ACKNO, ACK_DATE AS ACKDATE
--FROM            SALDAT  INNER JOIN ACCMAS ON CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID INNER JOIN
--ACCMAS AS SHIPTOACCMAS ON SHIP_TO_ENTITY_UID = SHIPTOACCMAS.ENTITY_UID LEFT OUTER JOIN
--TRANMAS ON SALDAT.TRAN_ACC_ENTITY_UID = TRANMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS ON SALDAT.DELFROM_ACC_ENTITY_UID = CITYMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS AS CITYTO ON SALDAT.DELTO_ACC_ENTITY_UID = CITYTO.ENTITY_UID  CROSS APPLY
--(SELECT TOP 1 SALDET.CGST_RATE AS CGSTRATE, SALDET.SGST_RATE AS SGSTRATE, SALDET.IGST_RATE AS IGSTRATE FROM SALDET WHERE SALDET.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND SALDAT.ENTITY_UID= SALDET.SAL_ENTITY_UID ) AS DET 
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS CGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  SALDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'CGST') AS CGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS SGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  SALDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'SGST') AS SGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS IGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  SALDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'IGST') AS IGSTCHGS
--WHERE        (SALDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID) AND IS_CANCELED = 'N'
--ORDER BY AUTO_BILL_NO





--DESC RECORDS
INSERT INTO TEXTRADE.DBO.TEMPINVOICEMASTER_DESC
select SALDAT.AUTO_BILL_NO AS ENTRYNO, ITEMMAS.CASH_ACC AS ITEMNAME, SALDET.ITEM_DES1 AS ITEMDESC, SALDET.BALE_NO AS BALENO, SALDET.TOT_PCS AS PCS, GROSS_QTY AS AQTY, TOT_FOLD AS FOLDPER, TOT_QTY AS MTRS, SALDET.ITEM_RATE AS RATE,
'Mtrs' AS PER, SALDET.CASH_AMT AS AMT
FROM SALDAT INNER JOIN 
SALDET ON SALDAT.ENTITY_UID = SALDET.SAL_ENTITY_UID INNER JOIN 
ITEMMAS ON SALDET.ITEM_CODE_ENTITY_UID= ITEMMAS.ENTITY_UID 
WHERE SALDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID 
ORDER BY ENTRYNO



----EXTRACHGS RECORDS WITHOUT CGST | SGST | IGST, WE NEED TO GET DISCOUNT FROM SALDAT
--INSERT INTO TEXTRADE.DBO.TEMPAGENCYMASTER_CHGS
--SELECT * FROM
--(
--SELECT SALDAT.AUTO_BILL_NO AS ENTRYNO, 'DISCOUNT A/C' AS CHARGESNAME, DISC_RATE*-1 AS DISCPER, DISC_AMT*-1 AS CHARGES
--FROM CASHDAT  INNER JOIN
--SALDAT ON CASHDAT.PUR_ENTITY_UID = SALDAT.ENTITY_UID
--WHERE        (CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID)
--AND CASHDAT.DISC_AMT <> 0


--UNION ALL
--select SALDAT.AUTO_BILL_NO AS ENTRYNO, ACCMAS.CASH_ACC AS CHARGESNAME, 0 AS PER, CASH_AMT AS CHARGES 
--FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID
--INNER JOIN SALDAT ON SALDAT.ENTITY_UID = CASHDAT.ENTITY_UID
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND SAY_CODE_ENTITY_UID = 'PURCHASE REGISTER' 
--AND ACCMAS.CASH_ACC NOT IN ('CGST', 'SGST', 'IGST')
--) AS T
--ORDER BY T.ENTRYNO, CHARGESNAME

---- ***************** END OF INVOICE ENTRIES ********************





---- ***************** START OF SALES RETURN ENTRIES ********************

--DELETE FROM TEXTRADE.DBO.TEMPAGENCYSALERETURN
--DELETE FROM TEXTRADE.DBO.TEMPAGENCYSALERETURN_DESC
--DELETE FROM TEXTRADE.DBO.TEMPAGENCYSALERETURN_CHGS
--DELETE FROM TEXTRADE.DBO.TEMPAGENCYSALERETURN_BILLDESC

----FOR SALERETURN MASTER
--INSERT INTO TEXTRADE.DBO.TEMPAGENCYSALERETURN
--SELECT AUTO_BILL_NO AS ENTRYNO, CASH_DATE AS DATE, BUYERACCMAS.CASH_ACC AS BUYERNAME, SELLERACCMAS.CASH_ACC AS SELLERNAME, ISNULL(BROKERACCMAS.CASH_ACC,'') AS BROKERNAME,
--ISNULL(TRANMAS.CASH_ACC,'') AS TRANSNAME, LR_NO AS LRNO, LR_DATE AS LRDATE, ISNULL(FROMCITYMAS.CASH_ACC,'') AS FROMCITY, ISNULL(TOCITYMAS.CASH_ACC,'') AS TOCITY,
--NET_QTY AS TOTALQTY,AGSRETDAT.GROSS_AMT AS AMOUNT ,
--CASE WHEN ISNULL(CGSTCHGS.CGST,0) > 0 THEN 2.50 ELSE 0 END AS CGSTPER,
--ISNULL(CGSTCHGS.CGST,0) AS CGSTAMT,
--CASE WHEN ISNULL(SGSTCHGS.SGST,0) > 0 THEN 2.50 ELSE 0 END AS SGSTPER,
--ISNULL(SGSTCHGS.SGST,0) AS SGSTAMT,
--CASE WHEN ISNULL(IGSTCHGS.IGST,0) > 0 THEN 5.00 ELSE 0 END AS IGSTPER,
--ISNULL(IGSTCHGS.IGST,0) AS IGSTAMT,
--AGSRETDAT.NET_AMT AS GRANDTOTAL
--FROM AGSRETDAT	INNER JOIN
--ACCMAS AS BUYERACCMAS ON AGSRETDAT.CASH_ACC_ENTITY_UID = BUYERACCMAS.ENTITY_UID INNER JOIN
--ACCMAS AS SELLERACCMAS ON AGSRETDAT.DEBIT_ACC_ENTITY_UID = SELLERACCMAS.ENTITY_UID LEFT OUTER JOIN
--ACCMAS AS BROKERACCMAS ON AGSRETDAT.BROK_ACC_ENTITY_UID = BROKERACCMAS.ENTITY_UID LEFT OUTER JOIN
--TRANMAS ON AGSRETDAT.TRAN_ACC_ENTITY_UID = TRANMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS AS FROMCITYMAS ON AGSRETDAT.DELFROM_ACC_ENTITY_UID = FROMCITYMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS AS TOCITYMAS ON AGSRETDAT.DELTO_ACC_ENTITY_UID = TOCITYMAS.ENTITY_UID  OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS CGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  AGSRETDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'CGST') AS CGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS SGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  AGSRETDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'SGST') AS SGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS IGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  AGSRETDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'IGST') AS IGSTCHGS
--WHERE AGSRETDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID --AND AGSRETDAT.ENTITY_UID = 203000000000401
--ORDER BY ENTRYNO



----DESC RECORDS
--INSERT INTO TEXTRADE.DBO.TEMPAGENCYSALERETURN_DESC
--select AGSRETDAT.AUTO_BILL_NO AS ENTRYNO, ITEMMAS.CASH_ACC AS ITEMNAME, AGSRETDET.BALE_NO AS BALENO, TOT_PCS AS PCS, AGSRETDET.TOT_QTY AS MTRS, AGSRETDET.ITEM_RATE AS RATE,
--'Mtrs' AS PER, CASH_AMT1 AS AMT
--FROM AGSRETDET INNER JOIN ITEMMAS ON ITEM_CODE_ENTITY_UID= ENTITY_UID INNER JOIN
--AGSRETDAT ON AGSRETDET.SRET_ENTITY_UID = AGSRETDAT.ENTITY_UID
--WHERE AGSRETDET.COMPANY_YEAR_ENTITY_UID = @CMPYEARID 
--ORDER BY AGSRETDET.SRET_ENTITY_UID





----EXTRACHGS RECORDS WITHOUT CGST | SGST | IGST, WE NEED TO GET DISCOUNT FROM AGSRETDET
--INSERT INTO TEXTRADE.DBO.TEMPAGENCYSALERETURN_CHGS
--SELECT * FROM
--(
--SELECT AGSRETDAT.AUTO_BILL_NO AS ENTRYNO, 'DISCOUNT A/C' AS CHARGESNAME, 0*-1 AS DISCPER, SUM(DISC_AMT)*-1 AS CHARGES
--FROM AGSRETDAT  INNER JOIN
--AGSRETDET ON AGSRETDET.SRET_ENTITY_UID = AGSRETDAT.ENTITY_UID
--WHERE        (AGSRETDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID) 
--GROUP BY AGSRETDAT.AUTO_BILL_NO
--HAVING SUM(AGSRETDET.DISC_AMT) <> 0


--UNION ALL
--select AGSRETDAT.AUTO_BILL_NO AS ENTRYNO, ACCMAS.CASH_ACC AS CHARGESNAME, 0 AS PER, CASH_AMT AS CHARGES
--FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID
--INNER JOIN AGSRETDAT ON AGSRETDAT.ENTITY_UID = CASHDAT.ENTITY_UID
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND SAY_CODE_ENTITY_UID = 'SALES RETURN REGISTER' 
--AND ACCMAS.CASH_ACC NOT IN ('CGST', 'SGST', 'IGST')
--) AS T
--ORDER BY T.ENTRYNO, CHARGESNAME



----BILLDESC RECORDS
--INSERT INTO TEXTRADE.DBO.TEMPAGENCYSALERETURN_BILLDESC
--SELECT AGSRETDAT.AUTO_BILL_NO  AS ENTRYNO, AGOSSAL.AUTO_BILL_NO AS AGENCYINVOICENO , CASH_AMT, AGOSSAL.BILL_NO AS PARTYBILLNO,
--'Against Bill' AS PAYTYPE, CASE WHEN AGOSSAL.COMPANY_YEAR_ENTITY_UID <> @CMPYEARID THEN 'OPENING' ELSE 'AGENCYINVOICE' END AS FROMTYPE
--FROM AGSRETOSDET INNER JOIN AGOSSAL ON AGSRETOSDET.REF_OSSAL_ENTITY_UID = AGOSSAL.OSSAL_ENTITY_UID INNER JOIN
--AGSRETDAT ON AGSRETDAT.ENTITY_UID = AGSRETOSDET.SRET_ENTITY_UID
--WHERE AGSRETOSDET.COMPANY_YEAR_ENTITY_UID = @CMPYEARID --AND AGSRETOSDET.SRET_ENTITY_UID  = 203000000000002
--ORDER BY AGSRETDAT.AUTO_BILL_NO 
------ ***************** END OF SALES RETURN ENTRIES ********************



