DECLARE @CMPYEARID BIGINT
SET @CMPYEARID = 002000000000001
--SET @CMPYEARID = 002000000000003
--SET @CMPYEARID = 002000000000005
--SET @CMPYEARID = 002000000000008




----CHECK WHETHER LEDGER IS PRESENT IN TEXTRADE OR NOT
--SELECT DISTINCT ACCMAS.CASH_ACC FROM SALDAT INNER JOIN ACCMAS ON SALDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID
--AND ACCMAS.CASH_ACC NOT IN (SELECT TEXTRADE.DBO.LEDGERS.Acc_cmpname FROM TEXTRADE.DBO.LEDGERS WHERE TEXTRADE.DBO.LEDGERS.Acc_yearid = 5)

--SELECT DISTINCT ACCMAS.CASH_ACC FROM SALDAT INNER JOIN ACCMAS ON SALDAT.SHIP_TO_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID
--AND ACCMAS.CASH_ACC NOT IN (SELECT TEXTRADE.DBO.LEDGERS.Acc_cmpname FROM TEXTRADE.DBO.LEDGERS WHERE TEXTRADE.DBO.LEDGERS.Acc_yearid = 5)

--SELECT DISTINCT TRANMAS.CASH_ACC FROM SALDAT INNER JOIN TRANMAS ON SALDAT.TRAN_ACC_ENTITY_UID = TRANMAS.ENTITY_UID 
--WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID
--AND TRANMAS.CASH_ACC NOT IN (SELECT TEXTRADE.DBO.LEDGERS.Acc_cmpname FROM TEXTRADE.DBO.LEDGERS WHERE TEXTRADE.DBO.LEDGERS.Acc_yearid = 5)




---- ***************** START OF INVOICE ENTRIES ********************

--DELETE FROM TEXTRADE.DBO.TEMPINVOICEMASTER
--DELETE FROM TEXTRADE.DBO.TEMPINVOICEMASTER_DESC
--DELETE FROM TEXTRADE.DBO.TEMPINVOICEMASTER_CHGS

----MASTER RECORDS
--INSERT INTO TEXTRADE.DBO.TEMPINVOICEMASTER 
--SELECT       AUTO_BILL_NO AS ENTRYNO, SALDAT.CASH_DATE AS DATE, ACCMAS.CASH_ACC AS NAME, SHIPTOACCMAS.CASH_ACC AS SHIPTONAME, 
--PAY_DAYS AS CRDAYS, DATEADD(DAY,PAY_DAYS,CAST(SALDAT.CASH_DATE AS DATE)) AS DUEDATE, ISNULL(TRANMAS.CASH_ACC,'') AS TRANSNAME,
--SALDAT.LR_NO AS LRNO, (CASE WHEN LR_DATE IS NULL THEN SALDAT.CASH_DATE ELSE LR_DATE END) AS LRDATE, ISNULL(CITYMAS.CASH_ACC,'') AS FROMCITY, ISNULL(CITYTO.CASH_ACC,'') AS TOCITY, 
--SALDAT.TOT_BALES AS NOOFBALES, ISNULL(NET_PCS,0) AS TOTALPCS, ISNULL(NET_QTY,0) AS TOTALMTRS, 
--0 AS TOTALAMT,
--DET.CGSTRATE AS CGSTPER,
--ISNULL(CGSTCHGS.CGST,0)*-1 AS CGSTAMT,
--DET.SGSTRATE AS SGSTPER,
--ISNULL(SGSTCHGS.SGST,0)*-1 AS SGSTAMT,
--DET.IGSTRATE AS IGSTPER,
--ISNULL(IGSTCHGS.IGST,0)*-1 AS IGSTAMT,
--ISNULL(ROUNDOFFCHGS.ROUNDOFF,0)*-1 AS ROUNDOFF,
--1 AS MANUALGST, NET_AMT AS GRANDTOTAL, SALDAT.CASH_NAR AS REMARKS, SALDAT.IRN_NO AS IRNNO, SALDAT.ACK_NO AS ACKNO, ACK_DATE AS ACKDATE
--FROM            SALDAT  INNER JOIN ACCMAS ON CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID INNER JOIN
--ACCMAS AS SHIPTOACCMAS ON SHIP_TO_ENTITY_UID = SHIPTOACCMAS.ENTITY_UID LEFT OUTER JOIN
--TRANMAS ON SALDAT.TRAN_ACC_ENTITY_UID = TRANMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS ON SALDAT.DELFROM_ACC_ENTITY_UID = CITYMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS AS CITYTO ON SALDAT.DELTO_ACC_ENTITY_UID = CITYTO.ENTITY_UID  CROSS APPLY
--(SELECT TOP 1 SALDET.CGST_RATE AS CGSTRATE, SALDET.SGST_RATE AS SGSTRATE, SALDET.IGST_RATE AS IGSTRATE FROM SALDET WHERE SALDET.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND SALDAT.ENTITY_UID= SALDET.SAL_ENTITY_UID ) AS DET 
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS CGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  SALDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'CGST') AS CGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS SGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  SALDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'SGST') AS SGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS IGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  SALDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'IGST') AS IGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS ROUNDOFF FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  SALDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'ROUND OFF') AS ROUNDOFFCHGS
--WHERE        (SALDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID) AND IS_CANCELED = 'N'
--ORDER BY AUTO_BILL_NO





----DESC RECORDS
--INSERT INTO TEXTRADE.DBO.TEMPINVOICEMASTER_DESC
--select SALDAT.AUTO_BILL_NO AS ENTRYNO, ITEMMAS.CASH_ACC AS ITEMNAME, SALDET.ITEM_DES1 AS ITEMDESC, SALDET.BALE_NO AS BALENO, SALDET.TOT_PCS AS PCS, GROSS_QTY AS AQTY, TOT_FOLD AS FOLDPER, TOT_QTY AS MTRS, SALDET.ITEM_RATE AS RATE,
--'Mtrs' AS PER, SALDET.CASH_AMT AS AMT, SALDET.LR_NO AS GRIDLRNO, ISNULL(GODOWNMAS.CASH_ACC,'') AS GRIDTRANS
--FROM SALDAT INNER JOIN 
--SALDET ON SALDAT.ENTITY_UID = SALDET.SAL_ENTITY_UID INNER JOIN 
--ITEMMAS ON SALDET.ITEM_CODE_ENTITY_UID= ITEMMAS.ENTITY_UID LEFT OUTER JOIN
--GODOWNMAS ON SALDET.GDN_ENTITY_UID = GODOWNMAS.ENTITY_UID
--WHERE SALDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID 
--ORDER BY ENTRYNO



----EXTRACHGS RECORDS WITHOUT CGST | SGST | IGST, WE NEED TO GET DISCOUNT FROM SALDAT
--INSERT INTO TEXTRADE.DBO.TEMPINVOICEMASTER_CHGS
--SELECT * FROM
--(
--SELECT SALDAT.AUTO_BILL_NO AS ENTRYNO, 'DISCOUNT A/C' AS CHARGESNAME, SALDAT.DISC_RATE*-1 AS DISCPER, SUM(DISC_AMT)*-1 AS CHARGES
--FROM SALDAT INNER JOIN
--SALDET ON SALDAT.ENTITY_UID = SALDET.SAL_ENTITY_UID
--WHERE        (SALDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID) AND SALDET.DISC_AMT <> 0
--GROUP BY SALDAT.AUTO_BILL_NO, SALDAT.DISC_RATE


--UNION ALL
--select SALDAT.AUTO_BILL_NO AS ENTRYNO, ACCMAS.CASH_ACC AS CHARGESNAME, 0 AS PER, CASH_AMT*-1 AS CHARGES 
--FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID
--INNER JOIN SALDAT ON SALDAT.ENTITY_UID = CASHDAT.ENTITY_UID
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND SAY_CODE_ENTITY_UID <> 'SALES ACCOUNT' AND CASHDAT.CASH_ACC_ENTITY_UID <> 'SALES ACCOUNT'
--AND ACCMAS.CASH_ACC NOT IN ('CGST', 'SGST', 'IGST', 'ROUND OFF', 'OUTPUT TCS')
--) AS T
--ORDER BY T.ENTRYNO, CHARGESNAME

---- ***************** END OF INVOICE ENTRIES ********************







---- ***************** START OF PURCHASE ENTRIES ********************

--DELETE FROM TEXTRADE.DBO.TEMPPURCHASEMASTER
--DELETE FROM TEXTRADE.DBO.TEMPPURCHASEMASTER_DESC
--DELETE FROM TEXTRADE.DBO.TEMPPURCHASEMASTER_CHGS

--MASTER RECORDS
--INSERT INTO TEXTRADE.DBO.TEMPPURCHASEMASTER 
--SELECT       AUTO_BILL_NO AS ENTRYNO, PURDAT.CASH_DATE AS DATE, ACCMAS.CASH_ACC AS NAME, BILL_NO AS PARTYBILLNO, 
--PAY_DAYS AS CRDAYS, DUE_DATE, ISNULL(TRANMAS.CASH_ACC,'') AS TRANSNAME,
--PURDAT.LR_NO AS LRNO, (CASE WHEN LR_DATE IS NULL THEN PURDAT.CASH_DATE ELSE LR_DATE END) AS LRDATE, ISNULL(CITYMAS.CASH_ACC,'') AS FROMCITY, ISNULL(CITYTO.CASH_ACC,'') AS TOCITY, 
--PURDAT.TOT_BALES AS NOOFBALES, ISNULL(NET_PCS,0) AS TOTALPCS, ISNULL(NET_QTY,0) AS TOTALMTRS, 
--0 AS TOTALAMT,
--DET.CGSTRATE AS CGSTPER,
--ISNULL(CGSTCHGS.CGST,0) AS CGSTAMT,
--DET.SGSTRATE AS SGSTPER,
--ISNULL(SGSTCHGS.SGST,0) AS SGSTAMT,
--DET.IGSTRATE AS IGSTPER,
--ISNULL(IGSTCHGS.IGST,0) AS IGSTAMT,
--ISNULL(ROUNDOFFCHGS.ROUNDOFF,0) AS ROUNDOFF,
--1 AS MANUALGST, NET_AMT AS GRANDTOTAL, PURDAT.CASH_NAR AS REMARKS, ISNULL(TCSCHGS.TCS,0) AS TCSAMT
--FROM            PURDAT  INNER JOIN ACCMAS ON CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID LEFT OUTER JOIN
--TRANMAS ON PURDAT.TRAN_ACC_ENTITY_UID = TRANMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS ON PURDAT.DELFROM_ACC_ENTITY_UID = CITYMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS AS CITYTO ON PURDAT.DELTO_ACC_ENTITY_UID = CITYTO.ENTITY_UID  CROSS APPLY
--(SELECT TOP 1 PURDET.CGST_RATE AS CGSTRATE, PURDET.SGST_RATE AS SGSTRATE, PURDET.IGST_RATE AS IGSTRATE FROM PURDET WHERE PURDET.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND PURDAT.ENTITY_UID= PURDET.PUR_ENTITY_UID ) AS DET 
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS CGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  PURDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'CGST') AS CGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS SGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  PURDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'SGST') AS SGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS IGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  PURDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'IGST') AS IGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS ROUNDOFF FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  PURDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'ROUND OFF') AS ROUNDOFFCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS TCS FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  PURDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'INPUT TCS') AS TCSCHGS
--WHERE        (PURDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID) 
--ORDER BY AUTO_BILL_NO





--DESC RECORDS
--INSERT INTO TEXTRADE.DBO.TEMPPURCHASEMASTER_DESC
--select PURDAT.AUTO_BILL_NO AS ENTRYNO, ITEMMAS.CASH_ACC AS ITEMNAME, PURDET.ITEM_DES1 AS ITEMDESC, PURDET.BALE_NO AS BALENO, PURDET.TOT_PCS AS PCS, BILL_MTRS AS AQTY, TOT_FOLD AS FOLDPER, TOT_QTY AS MTRS, PURDET.ITEM_RATE AS RATE,
--'Mtrs' AS PER, PURDET.CASH_AMT AS AMT, PURDET.LR_NO AS GRIDLRNO
--FROM PURDAT INNER JOIN 
--PURDET ON PURDAT.ENTITY_UID = PURDET.PUR_ENTITY_UID INNER JOIN 
--ITEMMAS ON PURDET.ITEM_CODE_ENTITY_UID= ITEMMAS.ENTITY_UID 
--WHERE PURDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID 
--ORDER BY ENTRYNO



--EXTRACHGS RECORDS WITHOUT CGST | SGST | IGST, WE NEED TO GET DISCOUNT FROM PURDAT
--INSERT INTO TEXTRADE.DBO.TEMPPURCHASEMASTER_CHGS
--SELECT * FROM
--(
--SELECT PURDAT.AUTO_BILL_NO AS ENTRYNO, 'DISCOUNT A/C' AS CHARGESNAME, PURDAT.DISC_RATE*-1 AS DISCPER, SUM(DISC_AMT)*-1 AS CHARGES
--FROM PURDAT INNER JOIN
--PURDET ON PURDAT.ENTITY_UID = PURDET.PUR_ENTITY_UID
--WHERE        (PURDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID) AND PURDET.DISC_AMT <> 0
--GROUP BY PURDAT.AUTO_BILL_NO, PURDAT.DISC_RATE


--UNION ALL
--select PURDAT.AUTO_BILL_NO AS ENTRYNO, ACCMAS.CASH_ACC AS CHARGESNAME, 0 AS PER, CASH_AMT AS CHARGES 
--FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID
--INNER JOIN PURDAT ON PURDAT.ENTITY_UID = CASHDAT.ENTITY_UID
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND SAY_CODE_ENTITY_UID <> 'PURCHASE ACCOUNT' AND CASHDAT.CASH_ACC_ENTITY_UID <> 'PURCHASE ACCOUNT'
--AND ACCMAS.CASH_ACC NOT IN ('CGST', 'SGST', 'IGST', 'ROUND OFF', 'INPUT TCS')
--) AS T
--ORDER BY T.ENTRYNO, CHARGESNAME

---- ***************** END OF PURCHASE ENTRIES ********************






---- ***************** START OF SALES RETURN ENTRIES ********************

--DELETE FROM TEXTRADE.DBO.TEMPSALERETURN
--DELETE FROM TEXTRADE.DBO.TEMPSALERETURN_DESC
--DELETE FROM TEXTRADE.DBO.TEMPSALERETURN_CHGS
--DELETE FROM TEXTRADE.DBO.TEMPSALERETURN_BILLDESC

----FOR SALERETURN MASTER
--INSERT INTO TEXTRADE.DBO.TEMPSALERETURN
--SELECT AUTO_BILL_NO AS ENTRYNO, CASH_DATE AS DATE, BUYERACCMAS.CASH_ACC AS BUYERNAME, COURIER_NO AS REFNO, 
--ISNULL(TRANMAS.CASH_ACC,'') AS TRANSNAME, LR_NO AS LRNO, LR_DATE AS LRDATE, ISNULL(FROMCITYMAS.CASH_ACC,'') AS FROMCITY, ISNULL(TOCITYMAS.CASH_ACC,'') AS TOCITY,
--NET_QTY AS TOTALQTY,SRETDAT.GROSS_AMT AS AMOUNT ,
--CASE WHEN ISNULL(CGSTCHGS.CGST,0) > 0 THEN 2.50 ELSE 0 END AS CGSTPER,
--ISNULL(CGSTCHGS.CGST,0) AS CGSTAMT,
--CASE WHEN ISNULL(SGSTCHGS.SGST,0) > 0 THEN 2.50 ELSE 0 END AS SGSTPER,
--ISNULL(SGSTCHGS.SGST,0) AS SGSTAMT,
--CASE WHEN ISNULL(IGSTCHGS.IGST,0) > 0 THEN 5.00 ELSE 0 END AS IGSTPER,
--ISNULL(IGSTCHGS.IGST,0) AS IGSTAMT,
--ISNULL(ROUNDOFFCHGS.ROUNDOFF,0) AS ROUNDOFF,
--SRETDAT.NET_AMT AS GRANDTOTAL, IRN_NO AS IRNNO, ACK_NO AS ACKNO, ACK_DATE AS ACKDATE
--FROM SRETDAT	INNER JOIN
--ACCMAS AS BUYERACCMAS ON SRETDAT.CASH_ACC_ENTITY_UID = BUYERACCMAS.ENTITY_UID   LEFT OUTER JOIN
--TRANMAS ON SRETDAT.TRAN_ACC_ENTITY_UID = TRANMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS AS FROMCITYMAS ON SRETDAT.DELFROM_ACC_ENTITY_UID = FROMCITYMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS AS TOCITYMAS ON SRETDAT.DELTO_ACC_ENTITY_UID = TOCITYMAS.ENTITY_UID  OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS CGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  SRETDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'CGST') AS CGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS SGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  SRETDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'SGST') AS SGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS IGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  SRETDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'IGST') AS IGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS ROUNDOFF FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  SRETDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'ROUND OFF') AS ROUNDOFFCHGS

--WHERE SRETDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID --AND SRETDAT.ENTITY_UID = 203000000000401
--ORDER BY ENTRYNO



----DESC RECORDS
--INSERT INTO TEXTRADE.DBO.TEMPSALERETURN_DESC
--select SRETDAT.AUTO_BILL_NO AS ENTRYNO, ITEMMAS.CASH_ACC AS ITEMNAME, SRETDET.BALE_NO AS BALENO, TOT_PCS AS PCS, SRETDET.TOT_QTY AS MTRS, SRETDET.ITEM_RATE AS RATE,
--'Mtrs' AS PER, CASH_AMT1 AS AMT
--FROM SRETDET INNER JOIN ITEMMAS ON ITEM_CODE_ENTITY_UID= ENTITY_UID INNER JOIN
--SRETDAT ON SRETDET.SRET_ENTITY_UID = SRETDAT.ENTITY_UID
--WHERE SRETDET.COMPANY_YEAR_ENTITY_UID = @CMPYEARID 
--ORDER BY SRETDET.SRET_ENTITY_UID





----EXTRACHGS RECORDS WITHOUT CGST | SGST | IGST, WE NEED TO GET DISCOUNT FROM SRETDET
--INSERT INTO TEXTRADE.DBO.TEMPSALERETURN_CHGS
--SELECT * FROM
--(
--SELECT SRETDAT.AUTO_BILL_NO AS ENTRYNO, 'DISCOUNT A/C' AS CHARGESNAME, 0*-1 AS DISCPER, SUM(DISC_AMT)*-1 AS CHARGES
--FROM SRETDAT  INNER JOIN
--SRETDET ON SRETDET.SRET_ENTITY_UID = SRETDAT.ENTITY_UID
--WHERE        (SRETDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID) 
--GROUP BY SRETDAT.AUTO_BILL_NO
--HAVING SUM(SRETDET.DISC_AMT) <> 0


--UNION ALL
--select SRETDAT.AUTO_BILL_NO AS ENTRYNO, ACCMAS.CASH_ACC AS CHARGESNAME, 0 AS PER, CASH_AMT AS CHARGES
--FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID
--INNER JOIN SRETDAT ON SRETDAT.ENTITY_UID = CASHDAT.ENTITY_UID
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND SAY_CODE_ENTITY_UID = 'SALES RETURN REGISTER' 
--AND ACCMAS.CASH_ACC NOT IN ('CGST', 'SGST', 'IGST', 'ROUND OFF')
--) AS T
--ORDER BY T.ENTRYNO, CHARGESNAME



----BILLDESC RECORDS
--INSERT INTO TEXTRADE.DBO.TEMPSALERETURN_BILLDESC
--SELECT SRETDAT.AUTO_BILL_NO  AS ENTRYNO, OSSAL.AUTO_BILL_NO AS AGENCYINVOICENO , CASH_AMT, OSSAL.BILL_NO AS PARTYBILLNO,
--'Against Bill' AS PAYTYPE, CASE WHEN OSSAL.COMPANY_YEAR_ENTITY_UID <> @CMPYEARID THEN 'OPENING' ELSE 'INVOICE' END AS FROMTYPE
--FROM SRETOSDET INNER JOIN OSSAL ON SRETOSDET.REF_OSSAL_ENTITY_UID = OSSAL.OSSAL_ENTITY_UID INNER JOIN
--SRETDAT ON SRETDAT.ENTITY_UID = SRETOSDET.SRET_ENTITY_UID
--WHERE SRETOSDET.COMPANY_YEAR_ENTITY_UID = @CMPYEARID --AND SRETOSDET.SRET_ENTITY_UID  = 203000000000002
--ORDER BY SRETDAT.AUTO_BILL_NO 
------ ***************** END OF SALES RETURN ENTRIES ********************




---- ***************** START OF PURCHASE RETURN ENTRIES ********************

--DELETE FROM TEXTRADE.DBO.TEMPPURCHASERETURN
--DELETE FROM TEXTRADE.DBO.TEMPPURCHASERETURN_DESC
--DELETE FROM TEXTRADE.DBO.TEMPPURCHASERETURN_CHGS
--DELETE FROM TEXTRADE.DBO.TEMPPURCHASERETURN_BILLDESC

----FOR PURCHASERETURN MASTER
--INSERT INTO TEXTRADE.DBO.TEMPPURCHASERETURN
--SELECT AUTO_BILL_NO AS ENTRYNO, CASH_DATE AS DATE, BUYERACCMAS.CASH_ACC AS BUYERNAME, COURIER_NO AS REFNO, 
--ISNULL(TRANMAS.CASH_ACC,'') AS TRANSNAME, LR_NO AS LRNO, LR_DATE AS LRDATE, ISNULL(FROMCITYMAS.CASH_ACC,'') AS FROMCITY, ISNULL(TOCITYMAS.CASH_ACC,'') AS TOCITY,
--NET_PCS AS TOTALQTY, NET_QTY AS TOTALMTRS,PRETDAT.GROSS_AMT AS AMOUNT ,
--CASE WHEN ISNULL(CGSTCHGS.CGST,0) > 0 THEN 2.50 ELSE 0 END AS CGSTPER,
--ISNULL(CGSTCHGS.CGST,0) AS CGSTAMT,
--CASE WHEN ISNULL(SGSTCHGS.SGST,0) > 0 THEN 2.50 ELSE 0 END AS SGSTPER,
--ISNULL(SGSTCHGS.SGST,0) AS SGSTAMT,
--CASE WHEN ISNULL(IGSTCHGS.IGST,0) > 0 THEN 5.00 ELSE 0 END AS IGSTPER,
--ISNULL(IGSTCHGS.IGST,0) AS IGSTAMT,
--ISNULL(ROUNDOFFCHGS.ROUNDOFF,0) AS ROUNDOFF,
--PRETDAT.NET_AMT AS GRANDTOTAL
--FROM PRETDAT	INNER JOIN
--ACCMAS AS BUYERACCMAS ON PRETDAT.CASH_ACC_ENTITY_UID = BUYERACCMAS.ENTITY_UID   LEFT OUTER JOIN
--TRANMAS ON PRETDAT.TRAN_ACC_ENTITY_UID = TRANMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS AS FROMCITYMAS ON PRETDAT.DELFROM_ACC_ENTITY_UID = FROMCITYMAS.ENTITY_UID LEFT OUTER JOIN
--CITYMAS AS TOCITYMAS ON PRETDAT.DELTO_ACC_ENTITY_UID = TOCITYMAS.ENTITY_UID  OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS CGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  PRETDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'CGST') AS CGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS SGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  PRETDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'SGST') AS SGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS IGST FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  PRETDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'IGST') AS IGSTCHGS
--OUTER APPLY
--(SELECT TOP 1 CASHDAT.CASH_AMT AS ROUNDOFF FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID 
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND  PRETDAT.ENTITY_UID = CASHDAT.ENTITY_UID  AND ACCMAS.CASH_ACC  = 'ROUND OFF') AS ROUNDOFFCHGS

--WHERE PRETDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID --AND PRETDAT.ENTITY_UID = 203000000000401
--ORDER BY ENTRYNO



----DESC RECORDS
--INSERT INTO TEXTRADE.DBO.TEMPPURCHASERETURN_DESC
--select PRETDAT.AUTO_BILL_NO AS ENTRYNO, ITEMMAS.CASH_ACC AS ITEMNAME, PRETDET.BALE_NO AS BALENO, TOT_PCS AS PCS, PRETDET.TOT_QTY AS MTRS, PRETDET.ITEM_RATE AS RATE,
--'Mtrs' AS PER, CASH_AMT1 AS AMT
--FROM PRETDET INNER JOIN ITEMMAS ON ITEM_CODE_ENTITY_UID= ENTITY_UID INNER JOIN
--PRETDAT ON PRETDET.PRET_ENTITY_UID = PRETDAT.ENTITY_UID
--WHERE PRETDET.COMPANY_YEAR_ENTITY_UID = @CMPYEARID 
--ORDER BY PRETDET.PRET_ENTITY_UID





----EXTRACHGS RECORDS WITHOUT CGST | SGST | IGST, WE NEED TO GET DISCOUNT FROM PRETDET
--INSERT INTO TEXTRADE.DBO.TEMPPURCHASERETURN_CHGS
--SELECT * FROM
--(
--SELECT PRETDAT.AUTO_BILL_NO AS ENTRYNO, 'DISCOUNT A/C' AS CHARGESNAME, 0*-1 AS DISCPER, SUM(DISC_AMT)*-1 AS CHARGES
--FROM PRETDAT  INNER JOIN
--PRETDET ON PRETDET.PRET_ENTITY_UID = PRETDAT.ENTITY_UID
--WHERE        (PRETDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID) 
--GROUP BY PRETDAT.AUTO_BILL_NO
--HAVING SUM(PRETDET.DISC_AMT) <> 0


--UNION ALL
--select PRETDAT.AUTO_BILL_NO AS ENTRYNO, ACCMAS.CASH_ACC AS CHARGESNAME, 0 AS PER, CASH_AMT AS CHARGES
--FROM CASHDAT INNER JOIN ACCMAS ON CASHDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID
--INNER JOIN PRETDAT ON PRETDAT.ENTITY_UID = CASHDAT.ENTITY_UID
--WHERE CASHDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND SAY_CODE_ENTITY_UID = 'PURCHASE RETURN REGISTER' 
--AND ACCMAS.CASH_ACC NOT IN ('CGST', 'SGST', 'IGST', 'ROUND OFF')
--) AS T
--ORDER BY T.ENTRYNO, CHARGESNAME



----BILLDESC RECORDS
--INSERT INTO TEXTRADE.DBO.TEMPPURCHASERETURN_BILLDESC
--SELECT PRETDAT.AUTO_BILL_NO  AS ENTRYNO, OSSAL.AUTO_BILL_NO AS AGENCYINVOICENO , CASH_AMT, OSSAL.BILL_NO AS PARTYBILLNO,
--'Against Bill' AS PAYTYPE, CASE WHEN OSSAL.COMPANY_YEAR_ENTITY_UID <> @CMPYEARID THEN 'OPENING' ELSE 'PURCHASE' END AS FROMTYPE
--FROM SRETOSDET INNER JOIN OSSAL ON SRETOSDET.REF_OSSAL_ENTITY_UID = OSSAL.OSSAL_ENTITY_UID INNER JOIN
--PRETDAT ON PRETDAT.ENTITY_UID = SRETOSDET.SRET_ENTITY_UID
--WHERE SRETOSDET.COMPANY_YEAR_ENTITY_UID = @CMPYEARID --AND SRETOSDET.SRET_ENTITY_UID  = 203000000000002
--ORDER BY PRETDAT.AUTO_BILL_NO 
------ ***************** END OF PURCHASE RETURN ENTRIES ********************




------ ***************** START OF RECEIPT ENTRIES ********************
DELETE FROM TEXTRADE.DBO.TEMPRECEIPT
DELETE FROM TEXTRADE.DBO.TEMPRECEIPT_DESC

--MASTER RECORDS
INSERT INTO TEXTRADE.DBO.TEMPRECEIPT
select RCT_NO AS ENTRYNO, CASH_DATE AS RECDATE , PARTYNAME.CASH_ACC AS NAME, BANKNAME.CASH_ACC AS BANKNAME, ISNULL(BANKMAS.CASH_ACC,'') AS PARTYBANKNAME, SALRCT.CASH_AMT AS CHQAMT,
CHQ_NO AS CHQNO, CHQ_DATE AS CHQDATE, SALRCT.CASH_NAR AS REMARKS, '' AS OURREM
FROM SALRCT INNER JOIN 
ACCMAS AS PARTYNAME ON SALRCT.CASH_ACC_ENTITY_UID = PARTYNAME.ENTITY_UID INNER JOIN
ACCMAS AS BANKNAME ON SALRCT.DEBIT_ACC_ENTITY_UID = BANKNAME.ENTITY_UID LEFT OUTER JOIN
BANKMAS ON SALRCT.PARTY_BANK_ENTITY_UID = BANKMAS.ENTITY_UID

WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID 
ORDER BY AUTO_BILL_NO 



--DESCRIPION RECORDS
INSERT INTO TEXTRADE.DBO.TEMPRECEIPT_DESC
SELECT * FROM
(
SELECT SALRCT.AUTO_BILL_NO AS RECEIPTNO, OSSAL.BILL_NO AS INVOICENO, SALRCTD.RCT_AMT AS AMT,
(CASE WHEN OSSAL.BILL_NO IS NULL THEN 'On Account' ELSE 'Against Bill' END) AS PAYTYPE, 
CASE WHEN OSSAL.COMPANY_YEAR_ENTITY_UID <> @CMPYEARID  THEN 'OPENING' ELSE 'INVOICE' END AS FROMTYPE
FROM SALRCTD INNER JOIN SALRCT ON SALRCT.ENTITY_UID = SALRCTD.RCT_ENTITY_UID LEFT OUTER JOIN
OSSAL ON SALRCTD.REF_OSSAL_ENTITY_UID =OSSAL.OSSAL_ENTITY_UID  
WHERE SALRCT.COMPANY_YEAR_ENTITY_UID =@CMPYEARID 


--WE HAVE REMOVED THIS AS OF NOW
--UNION ALL
--SELECT SALRCT.AUTO_BILL_NO AS RECEIPTNO, 0 AS INVOICENO, (SALRCT.CASH_AMT - SALRCT.TOT_RCT) AS AMT,
--'On Account' AS PAYTYPE, 'AGENCYINVOICE' AS FROMTYPE
--FROM SALRCT  
--WHERE SALRCT.COMPANY_YEAR_ENTITY_UID =@CMPYEARID AND SALRCT.CASH_AMT - SALRCT.TOT_RCT <> 0

) AS T
ORDER BY T.RECEIPTNO, INVOICENO


------ ***************** END OF RECEIPT ENTRIES ********************






