DECLARE @CMPID INT, @USERID INT, @YEARID INT
declare CUR_MAIN cursor for SELECT year_cmpid AS CMPID, year_userid AS USERID, YEAR_ID AS YEARID FROM TEXTRADE.dbo.YEARMASTER WHERE year_cmpid = 2
open CUR_MAIN
	fetch next from CUR_MAIN into @CMPID, @USERID, @YEARID
	while @@Fetch_STATUS = 0
	BEGIN


--FOR CITYMASTER
INSERT INTO TEXTRADE.dbo.CITYMASTER
SELECT CITYMAS.CASH_ACC AS CITYNAME, '' AS REMARKS, @CMPID, 0, @USERID, @YEARID, 0 , GETDATE() FROM CITYMAS
WHERE CITYMAS.CASH_ACC NOT IN (SELECT TEXTRADE.DBO.CITYMASTER.CITY_NAME FROM TEXTRADE.DBO.CITYMASTER WHERE TEXTRADE.DBO.CITYMASTER.city_yearid = @YEARID)


--FOR STATEMASTER
INSERT INTO TEXTRADE.dbo.STATEMASTER
SELECT  STATEMAS.CASH_ACC AS STATENAME, STATE_CODE AS REMARKS, @CMPID, 0, @USERID, @YEARID, 0 , GETDATE() FROM STATEMAS
WHERE STATEMAS.CASH_ACC NOT IN (SELECT TEXTRADE.DBO.STATEMASTER.STATE_NAME FROM TEXTRADE.DBO.STATEMASTER WHERE TEXTRADE.DBO.STATEMASTER.state_yearid = @YEARID)


--FOR PARTYBANKMASTER
INSERT INTO TEXTRADE.dbo.PARTYBANKMASTER
SELECT  BANKMAS.CASH_ACC AS PARTYBANKNAME, '' AS REMARKS, @CMPID, 0, @USERID, @YEARID, 0 , GETDATE() FROM BANKMAS
WHERE BANKMAS.CASH_ACC NOT IN (SELECT TEXTRADE.DBO.PARTYBANKMASTER.PARTYBANK_name FROM TEXTRADE.DBO.PARTYBANKMASTER WHERE TEXTRADE.DBO.PARTYBANKMASTER.PARTYBANK_yearid = @YEARID)


--FOR HSNMASTER
INSERT INTO TEXTRADE.dbo.HSNMASTER
SELECT 'Goods', HSNMAS.CASH_ACC AS HSNCODE, HSNMAS.ACC_TITLE AS HSNDESC, '' AS [DESC], 0 AS RATE, 0 AS CGST, 0 AS SGST, 0 AS IGST, 0 AS RATE1, 0 AS CGST1, 0 AS SGST1, 0 AS IGST1,
0 AS EXPCGST, 0 AS EXPSGT, 0 AS EXPIGST, @CMPID, @USERID, @YEARID, GETDATE(), GETDATE(), @USERID FROM HSNMAS 
WHERE HSNMAS.CASH_ACC NOT IN (SELECT TEXTRADE.DBO.HSNMASTER.HSN_CODE FROM TEXTRADE.DBO.HSNMASTER WHERE TEXTRADE.DBO.HSNMASTER.HSN_YEARID = @YEARID)


--FOR HSNMASTERDESC
INSERT INTO TEXTRADE.dbo.HSNMASTER_DESC
SELECT TEXTRADE.dbo.HSNMASTER.HSN_ID, '2018-04-01', 0 AS RATE, HSNMASDET.[CGST_RATE] AS CGST ,HSNMASDET.[SGST_RATE] AS SGST, HSNMASDET.[GST_RATE] AS IGST, 0,0,0,0,0,0,0, @CMPID, @YEARID
FROM HSNMASDET INNER JOIN  HSNMAS ON HSNMASDET.HSN_ENTITY_UID = HSNMAS.ENTITY_UID INNER JOIN TEXTRADE.dbo.HSNMASTER ON TEXTRADE.dbo.HSNMASTER.HSN_CODE = HSNMAS.CASH_ACC AND TEXTRADE.dbo.HSNMASTER.HSN_YEARID = @YEARID
WHERE HSNMAS.CASH_ACC NOT IN (SELECT TEXTRADE.DBO.HSNMASTER.HSN_CODE FROM TEXTRADE.DBO.HSNMASTER INNER JOIN TEXTRADE.dbo.HSNMASTER_DESC ON TEXTRADE.dbo.HSNMASTER.HSN_ID = TEXTRADE.dbo.HSNMASTER_DESC.HSN_ID WHERE TEXTRADE.DBO.HSNMASTER.HSN_YEARID = @YEARID)


--FOR ITEMMASTER
INSERT INTO TEXTRADE.dbo.ITEMMASTER
SELECT (SELECT TEXTRADE.DBO.MATERIALTYPEMASTER.material_id FROM TEXTRADE.DBO.MATERIALTYPEMASTER WHERE material_name = 'Finished Goods' AND material_yearid = @YEARID ) AS MATERIALTYPEID,
0 AS CATEGORYID, 0, ITEMMAS.[CASH_ACC], ITEMMAS.[CASH_ACC], ITEMMAS.[CASH_ACC] AS CODE, 0 AS UNITID, '' AS FOLD, 0, 0, 0,0,0,0 AS DESIGNRATE, 0 AS REORDER,
0,0 AS LOWERLIMIT,TEXTRADE.DBO.HSNMASTER.HSN_ID AS HSNID, 0,0,'' AS WIDTH,'',0,0,'','' AS REMARKS, 'MERCHANT' AS FRMSTRING, NULL AS PHOTO,'','',0,0,0,0,0,0,0,0,
'' AS WEAVE, @CMPID,0, @USERID, @YEARID, 0, GETDATE(),0,0,0,0,0,0,0 AS WASTAGEAMT, 0,0,0,0 AS GSTAMT,0,0,0 AS TOTALAMT,0,0,0,0,0 AS GSM,0,0 AS GARMENT
FROM [ITEMMAS] INNER JOIN HSNMAS ON ITEMMAS.HSN_ENTITY_UID = HSNMAS.ENTITY_UID INNER JOIN TEXTRADE.DBO.HSNMASTER ON HSNMAS.CASH_ACC = TEXTRADE.DBO.HSNMASTER.HSN_CODE AND TEXTRADE.DBO.HSNMASTER.HSN_YEARID = @YEARID
WHERE ITEMMAS.CASH_ACC NOT IN (SELECT TEXTRADE.DBO.ITEMMASTER.ITEM_NAME FROM TEXTRADE.DBO.ITEMMASTER WHERE TEXTRADE.DBO.ITEMMASTER.item_yearid = @YEARID)


--FOR NARRATIONMASTER
INSERT INTO TEXTRADE.dbo.NARRATIONMASTER
SELECT  NARMAS.CASH_ACC AS NARRATION, '' AS REMARKS, @CMPID, 0, @USERID, @YEARID, 0 , GETDATE() FROM NARMAS
WHERE NARMAS.CASH_ACC NOT IN (SELECT TEXTRADE.DBO.NARRATIONMASTER.NARRATION_name FROM TEXTRADE.DBO.NARRATIONMASTER WHERE TEXTRADE.DBO.NARRATIONMASTER.NARRATION_yearid = @YEARID)




--FOR BROKERS
INSERT INTO TEXTRADE.dbo.ACCOUNTSMASTER
SELECT DISTINCT BROKERACCMAS.CASH_ACC AS CMPNAME, BROKERACCMAS.CASH_ACC AS NAME, 
(SELECT ISNULL(TEXTRADE.dbo.GROUPMASTER.GROUP_ID,0) FROM TEXTRADE.dbo.GROUPMASTER WHERE group_name = 'SUNDRY CREDITORS' AND GROUPMASTER.GROUP_yearid = @YEARID) AS GROUPID, 
0 AS OPBAL, '' AS DRCR, BROKERACCMAS.INT_RATE AS INTPER, 0, BROKERACCMAS.ACC_ADD1 AS ADD1 , 
BROKERACCMAS.ACC_ADD2 + ' ' + BROKERACCMAS.ACC_ADD3 AS ADD2, '' AS AREA, '', (SELECT ISNULL(TEXTRADE.dbo.CITYMASTER.city_id,0) FROM TEXTRADE.dbo.CITYMASTER WHERE city_name = CITYMAS.CASH_ACC AND CITYMASTER.city_yearid = @YEARID) AS CITYID,
BROKERACCMAS.PIN_CODE AS PINCODE,
(SELECT ISNULL(TEXTRADE.dbo.STATEMASTER.state_id,0) FROM TEXTRADE.dbo.STATEMASTER WHERE state_name = STATEMAS.CASH_ACC AND STATEMASTER.state_yearid = @YEARID) AS STATEID,
0 AS COUNTRYID, BROKERACCMAS.GRACE_DAYS AS CRDAYS, BROKERACCMAS.CR_LIMIT AS CRLIMIT, BROKERACCMAS.RESI_PH1 AS RESINO,BROKERACCMAS.OFF_PH2 AS ALTNO,BROKERACCMAS.OFF_PH1 AS PHONENO,BROKERACCMAS.MOB_2 AS MOBILENO,
0 AS FAXNO, BROKERACCMAS.WEB_SITE AS WEBSITE, BROKERACCMAS.E_MAIL AS EMAIL, 
0 AS TRANSID, 0 AS AGENTID,
0, BROKERACCMAS.DISC_RATE AS DISCPER, BROKERACCMAS.CD_RATE AS CDPER, 0 AS KMS, BROKERACCMAS.PAN_NO AS PANNO, '','','', '' AS CSTNO, '', '',  '' AS VATNO,
BROKERACCMAS.GST_NO AS GSTIN, 0 AS REGID, BROKERACCMAS.ACC_ADD1 + ' ' + BROKERACCMAS.ACC_ADD2 + ' ' + BROKERACCMAS.ACC_ADD3 AS [ADDRESS], '', CAST(BROKERACCMAS.REM_ACC AS VARCHAR(2000)) AS REMARKS, 0 AS BANKID, '','','' AS IFSC,
'',0,0,0 AS BLOCKED,0 ,0,0,0,'' AS TDSCMP,'',0, @CMPID,0,@USERID,@YEARID,0,GETDATE(), BROKERACCMAS.CASH_ACC AS CODE, 'AGENT' AS [TYPE], 0, '','',0 AS PACKINGTYPEID,
0,0, (SELECT TEXTRADE.dbo.CITYMASTER.city_id FROM TEXTRADE.dbo.CITYMASTER WHERE city_name = CITYMAS.CASH_ACC AND CITYMASTER.city_yearid = @YEARID) AS DELIVERYATID,
0,BROKERACCMAS.PIN_CODE AS DELPINCODE, '', '', 0 AS TCS, '', BROKERACCMAS.MOB_1 AS WHATSAPPNO, 0,0,0,'' AS WARNING, 0,0,0,'' AS MSMETYPE,0,0,0 AS LOCKDAYS
FROM ACCMAS INNER JOIN ACCMAS AS BROKERACCMAS ON ACCMAS.BROK_ACC_ENTITY_UID = BROKERACCMAS.ENTITY_UID LEFT OUTER JOIN 
CITYMAS ON BROKERACCMAS.CITY_ACC_ENTITY_UID = CITYMAS.ENTITY_UID LEFT OUTER JOIN
STATEMAS ON CITYMAS.STATE_ENTITY_UID = STATEMAS.ENTITY_UID  LEFT OUTER JOIN
ACCMAS AS TRANSACCMAS ON BROKERACCMAS.TRAN_ACC_ENTITY_UID = TRANSACCMAS.ENTITY_UID
WHERE BROKERACCMAS.LEVL_CODE_ENTITY_UID IN ('BROKER ACCOUNT')
AND BROKERACCMAS.CASH_ACC NOT IN (SELECT TEXTRADE.dbo.LEDGERS.ACC_CMPNAME FROM TEXTRADE.dbo.LEDGERS WHERE TEXTRADE.dbo.LEDGERS.Acc_yearid = @YEARID)



--FOR TRANSPORT
INSERT INTO TEXTRADE.dbo.ACCOUNTSMASTER
SELECT DISTINCT TRANMAS.CASH_ACC AS CMPNAME, TRANMAS.CASH_ACC AS NAME, 
(SELECT ISNULL(TEXTRADE.dbo.GROUPMASTER.GROUP_ID,0) FROM TEXTRADE.dbo.GROUPMASTER WHERE group_name = 'SUNDRY CREDITORS' AND GROUPMASTER.GROUP_yearid = @YEARID) AS GROUPID, 
0 AS OPBAL, '' AS DRCR, 0 AS INTPER, 0, TRANMAS.ACC_ADD1 AS ADD1 , 
TRANMAS.ACC_ADD2 + ' ' + TRANMAS.ACC_ADD3 AS ADD2, '' AS AREA, '', 0 AS CITYID,
'' AS PINCODE, 0 AS STATEID,
0 AS COUNTRYID, 0 AS CRDAYS, 0 AS CRLIMIT, TRANMAS.CONTACT_PERSON_PH_1 AS RESINO, TRANMAS.OFF_PH2 AS ALTNO,TRANMAS.OFF_PH1 AS PHONENO,TRANMAS.MOB_1 AS MOBILENO,
TRANMAS.MOB_2 AS FAXNO, '' AS WEBSITE, '' AS EMAIL,  0 AS TRANSID, 0 AS AGENTID,
0, 0 AS DISCPER, 0 AS CDPER, 0 AS KMS, '' AS PANNO, '','','', '' AS CSTNO, '', '',  '' AS VATNO,
TRANMAS.TRANS_ID AS GSTIN, 0 AS REGID, TRANMAS.ACC_ADD1 + ' ' + TRANMAS.ACC_ADD2 + ' ' + TRANMAS.ACC_ADD3 AS [ADDRESS], '', '' AS REMARKS, 0 AS BANKID, '','','' AS IFSC,
'',0,0,0 AS BLOCKED,0 ,0,0,0,'' AS TDSCMP,'',0, @CMPID,0,@USERID,@YEARID,0,GETDATE(), TRANMAS.CASH_ACC AS CODE, 'TRANSPORT' AS [TYPE], 0, '','',0 AS PACKINGTYPEID,
0,0, 0 AS DELIVERYATID, 0,'' AS DELPINCODE, '', '', 0 AS TCS, '', TRANMAS.MOB_1 AS WHATSAPPNO, 0,0,0,'' AS WARNING, 0,0,0,'' AS MSMETYPE,0,0,0 AS LOCKDAYS
FROM TRANMAS
WHERE TRANMAS.CASH_ACC NOT IN (SELECT TEXTRADE.dbo.LEDGERS.ACC_CMPNAME FROM TEXTRADE.dbo.LEDGERS WHERE TEXTRADE.dbo.LEDGERS.Acc_yearid = @YEARID)


--FOR TRANSPORT (GET DATA FROM GODOWNMASTER ALSO)
INSERT INTO TEXTRADE.dbo.ACCOUNTSMASTER
SELECT DISTINCT GODOWNMAS.CASH_ACC AS CMPNAME, GODOWNMAS.CASH_ACC AS NAME, 
(SELECT ISNULL(TEXTRADE.dbo.GROUPMASTER.GROUP_ID,0) FROM TEXTRADE.dbo.GROUPMASTER WHERE group_name = 'SUNDRY CREDITORS' AND GROUPMASTER.GROUP_yearid = @YEARID) AS GROUPID, 
0 AS OPBAL, '' AS DRCR, 0 AS INTPER, 0, GODOWNMAS.ACC_ADD1 AS ADD1 , 
GODOWNMAS.ACC_ADD2 + ' ' + GODOWNMAS.ACC_ADD3 AS ADD2, '' AS AREA, '', 0 AS CITYID,
'' AS PINCODE, 0 AS STATEID,
0 AS COUNTRYID, 0 AS CRDAYS, 0 AS CRLIMIT, '' AS RESINO, '' AS ALTNO, '' AS PHONENO, '' AS MOBILENO,
'' AS FAXNO, '' AS WEBSITE, '' AS EMAIL,  0 AS TRANSID, 0 AS AGENTID,
0, 0 AS DISCPER, 0 AS CDPER, 0 AS KMS, '' AS PANNO, '','','', '' AS CSTNO, '', '',  '' AS VATNO,
'' AS GSTIN, 0 AS REGID, GODOWNMAS.ACC_ADD1 + ' ' + GODOWNMAS.ACC_ADD2 + ' ' + GODOWNMAS.ACC_ADD3 AS [ADDRESS], '', '' AS REMARKS, 0 AS BANKID, '','','' AS IFSC,
'',0,0,0 AS BLOCKED,0 ,0,0,0,'' AS TDSCMP,'',0, @CMPID,0,@USERID,@YEARID,0,GETDATE(), GODOWNMAS.CASH_ACC AS CODE, 'TRANSPORT' AS [TYPE], 0, '','',0 AS PACKINGTYPEID,
0,0, 0 AS DELIVERYATID, 0,'' AS DELPINCODE, '', '', 0 AS TCS, '', '' AS WHATSAPPNO, 0,0,0,'' AS WARNING, 0,0,0,'' AS MSMETYPE,0,0,0 AS LOCKDAYS
FROM GODOWNMAS
WHERE GODOWNMAS.CASH_ACC NOT IN (SELECT TEXTRADE.dbo.LEDGERS.ACC_CMPNAME FROM TEXTRADE.dbo.LEDGERS WHERE TEXTRADE.dbo.LEDGERS.Acc_yearid = @YEARID)



--FOR ACCOUNTSMASTER (ACCOUNTS)
INSERT INTO TEXTRADE.dbo.ACCOUNTSMASTER
SELECT ACCMAS.CASH_ACC AS CMPNAME, ACCMAS.CASH_ACC AS NAME, TEXTRADE.dbo.GROUPMASTER.group_id AS GROUPID, 0 AS OPBAL, '' AS DRCR, ACCMAS.INT_RATE AS INTPER, 0,
ACCMAS.ACC_ADD1 AS ADD1 , 
ACCMAS.ACC_ADD2 + ' ' + ACCMAS.ACC_ADD3 AS ADD2, '' AS AREA, '', (SELECT ISNULL(TEXTRADE.dbo.CITYMASTER.city_id,0) FROM TEXTRADE.dbo.CITYMASTER WHERE city_name = CITYMAS.CASH_ACC AND CITYMASTER.city_yearid = @YEARID) AS CITYID,
ACCMAS.PIN_CODE AS PINCODE,
(SELECT ISNULL(TEXTRADE.dbo.STATEMASTER.state_id,0) FROM TEXTRADE.dbo.STATEMASTER WHERE state_name = STATEMAS.CASH_ACC AND STATEMASTER.state_yearid = @YEARID) AS STATEID,
0 AS COUNTRYID, ACCMAS.GRACE_DAYS AS CRDAYS, ACCMAS.CR_LIMIT AS CRLIMIT, ACCMAS.RESI_PH1 AS RESINO,ACCMAS.OFF_PH2 AS ALTNO,ACCMAS.OFF_PH1 AS PHONENO,ACCMAS.MOB_2 AS MOBILENO,
0 AS FAXNO, ACCMAS.WEB_SITE AS WEBSITE, ACCMAS.E_MAIL AS EMAIL, 
(SELECT ISNULL(TEXTRADE.dbo.LEDGERS.ACC_ID,0) FROM TEXTRADE.dbo.LEDGERS WHERE Acc_cmpname = TRANSACCMAS.CASH_ACC AND LEDGERS.ACC_yearid = @YEARID) AS TRANSID,
(SELECT ISNULL(TEXTRADE.dbo.LEDGERS.ACC_ID,0) FROM TEXTRADE.dbo.LEDGERS WHERE Acc_cmpname = BROKERACCMAS.CASH_ACC AND LEDGERS.ACC_yearid = @YEARID) AS AGENTID,
0, ACCMAS.DISC_RATE AS DISCPER, ACCMAS.CD_RATE AS CDPER, 0 AS KMS, ACCMAS.PAN_NO AS PANNO, '','','', '' AS CSTNO, '', '',  '' AS VATNO,
ACCMAS.GST_NO AS GSTIN, 0 AS REGID, ACCMAS.ACC_ADD1 + ' ' + ACCMAS.ACC_ADD2 + ' ' + ACCMAS.ACC_ADD3 AS [ADDRESS], '', CAST(ACCMAS.REM_ACC AS VARCHAR(2000)) AS REMARKS, 0 AS BANKID, '','','' AS IFSC,
'',0,0,0 AS BLOCKED,0 ,0,0,0,'' AS TDSCMP,'',0, @CMPID,0,@USERID,@YEARID,0,GETDATE(), ACCMAS.CASH_ACC AS CODE, 'ACCOUNTS' AS [TYPE], 0, '','',0 AS PACKINGTYPEID,
0,0, (SELECT TEXTRADE.dbo.CITYMASTER.city_id FROM TEXTRADE.dbo.CITYMASTER WHERE city_name = CITYMAS.CASH_ACC AND CITYMASTER.city_yearid = @YEARID) AS DELIVERYATID,
0,ACCMAS.PIN_CODE AS DELPINCODE, '', '', 0 AS TCS, '', ACCMAS.MOB_1 AS WHATSAPPNO, 0,0,0,'' AS WARNING, 0,0,0,'' AS MSMETYPE,0,0,0 AS LOCKDAYS
FROM ACCMAS LEFT OUTER JOIN CITYMAS ON ACCMAS.CITY_ACC_ENTITY_UID = CITYMAS.ENTITY_UID LEFT OUTER JOIN
STATEMAS ON CITYMAS.STATE_ENTITY_UID = STATEMAS.ENTITY_UID LEFT OUTER JOIN
ACCMAS AS BROKERACCMAS ON ACCMAS.BROK_ACC_ENTITY_UID = BROKERACCMAS.ENTITY_UID LEFT OUTER JOIN
TRANMAS AS TRANSACCMAS ON ACCMAS.TRAN_ACC_ENTITY_UID = TRANSACCMAS.ENTITY_UID
INNER JOIN TEXTRADE.dbo.GROUPMASTER ON ACCMAS.LEVL_CODE_ENTITY_UID = TEXTRADE.dbo.GROUPMASTER.group_name AND TEXTRADE.dbo.GROUPMASTER.group_yearid = @YEARID
WHERE ACCMAS.LEVL_CODE_ENTITY_UID IN ('SUNDRY CREDITORS','SUNDRY DEBTORS')
AND ACCMAS.CASH_ACC NOT IN (SELECT TEXTRADE.dbo.LEDGERS.ACC_CMPNAME FROM TEXTRADE.dbo.LEDGERS WHERE TEXTRADE.dbo.LEDGERS.Acc_yearid = @YEARID)







	fetch next from CUR_MAIN into @CMPID, @USERID, @YEARID
	end
close CUR_MAIN
deallocate CUR_MAIN







