DECLARE @CMPYEARID BIGINT
SET @CMPYEARID = 002000000000001

--FOR OPENING BALANCE
--SELECT DISTINCT ACCMAS.CASH_ACC AS NAME, OSSALDAT.ACC_OPBL AS OPBAL FROM OSSALDAT  INNER JOIN
--ACCMAS ON OSSALDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID
--WHERE OSSALDAT.COMPANY_CODE_ENTITY_UID = 001000000000001
--ORDER BY NAME


--SELECT ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS ENTRYNO, TDSDAT.CASH_DATE AS DATE, TDSDAT.TOT_TDS AS AMT, ACCMAS.CASH_ACC AS DEBITNAME, TDSLEDGER.CASH_ACC AS CREDITNAME, TDSDAT.BILL_NO AS PARTYBILLNO, 
--TDSDAT.VOU_ACC_ENTITY_UID AS FORMTYPE
--FROM TDSDAT INNER JOIN
--ACCMAS  ON TDSDAT.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID INNER JOIN
--ACCMAS AS TDSLEDGER ON TDSDAT.TDS_ACC_ENTITY_UID = TDSLEDGER.ENTITY_UID
--WHERE TDSDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID 







--SELECT * FROM GENEXPDET WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND GEN_ENTITY_UID = 113000000000036

--SELECT * FROM JVDETS WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND JV_ENTITY_UID = 114000000000060
--SELECT * FROM OSSAL WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID and  OSSAL_ENTITY_UID IN (SELECT REF_OSSAL_ENTITY_UID FROM JVDETS 
--WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND JVDETS.JV_ENTITY_UID = 114000000000092 )

--SELECT JVDAT.AUTO_BILL_NO AS ENTRYNO, JVDAT.CASH_DATE AS DATE, ACCMAS.CASH_ACC AS NAME,  
--(CASE WHEN JVDETS.OS_IND = 'C' OR JVDETS.OS_IND IS NULL THEN COALESCE(JVDETS.CASH_AMT, JVDET.DR_AMT) ELSE 0 END) AS DEBITAMT, 
--(CASE WHEN JVDETS.OS_IND = 'D' OR JVDETS.OS_IND IS NULL THEN COALESCE(JVDETS.CASH_AMT, JVDET.CR_AMT) ELSE 0 END) AS CREDITAMT, JV_NAR AS REMARKS, 
--ISNULL(OSSAL.BILL_NO,'') AS BILLNOS
--FROM JVDAT INNER JOIN
--JVDET ON JVDAT.ENTITY_UID = JVDET.JV_ENTITY_UID INNER JOIN
--ACCMAS  ON JVDET.CASH_ACC_ENTITY_UID = ACCMAS.ENTITY_UID  LEFT OUTER JOIN
--JVDETS ON JVDAT.ENTITY_UID = JVDETS.JV_ENTITY_UID AND JVDET.UNIQUE_ID = JVDETS.UNIQUE_ID LEFT OUTER JOIN
--OSSAL ON REF_OSSAL_ENTITY_UID = OSSAL_ENTITY_UID  

--WHERE JVDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID --AND JVDAT.AUTO_BILL_NO = 1
--ORDER BY ENTRYNO

------SELECT * FROM PURPAYDET WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND PAY_ENTITY_UID = 118000000000968
----SELECT * FROM OSSAL WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND OSSAL_ENTITY_UID = '718DFEC6-9A9D-47F5-BAE5-32BEC30D574B'
----SELECT * FROM CASHDAT WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND SAY_CODE_ENTITY_UID <> 'RECEIPT REGISTER' AND CASH_CODE_ENTITY_UID <> 'RECEIPT REGISTER' AND ENTITY_UID = 116000000000004

--SELECT * FROM TDSDAT WHERE VOU_ACC_ENTITY_UID = 'CREDIT NOTE'
--SELECT * FROM CRNOTE WHERE ENTITY_UID =  112000000000186

--SELECT * FROM DRNOTEOSDET WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND REF_OSSAL_ENTITY_UID = '113000000000020'
--SELECT DRNOTE.AUTO_BILL_NO AS ENTRYNO, '' AS INVOICENO, DRNOTE.NET_AMT AS AMT,
--'On Account' AS PAYTYPE, '' AS FROMTYPE
--FROM DRNOTE LEFT OUTER JOIN DRNOTEOSDET ON DRNOTE.ENTITY_UID = DRNOTEOSDET.DR_ENTITY_UID
--WHERE DRNOTE.COMPANY_YEAR_ENTITY_UID =@CMPYEARID AND DRNOTEOSDET.DR_ENTITY_UID IS NULL


--SELECT * FROM OSSAL WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID and   VOU_ACC_ENTITY_UID = 'CREDIT NOTE' ORDER BY BILL_NO

--select RCT_NO AS ENTRYNO, CASH_DATE AS RECDATE , PARTYNAME.CASH_ACC AS NAME, BANKNAME.CASH_ACC AS BANKNAME, ISNULL(BANKMAS.CASH_ACC,'') AS PARTYBANKNAME, SALRCT.CASH_AMT AS CHQAMT,
--CHQ_NO AS CHQNO, CHQ_DATE AS CHQDATE, SALRCT.CASH_NAR AS REMARKS, '' AS OURREM
--FROM SALRCT INNER JOIN 
--ACCMAS AS PARTYNAME ON SALRCT.CASH_ACC_ENTITY_UID = PARTYNAME.ENTITY_UID INNER JOIN
--ACCMAS AS BANKNAME ON SALRCT.DEBIT_ACC_ENTITY_UID = BANKNAME.ENTITY_UID LEFT OUTER JOIN
--BANKMAS ON SALRCT.PARTY_BANK_ENTITY_UID = BANKMAS.ENTITY_UID

--WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND SALRCT.VOU_ACC_ENTITY_UID = 'BANK RECEIPT' AND AUTO_BILL_NO = 403
--ORDER BY AUTO_BILL_NO 

--SELECT * FROM
--(
--SELECT SALRCT.AUTO_BILL_NO AS RECEIPTNO, ISNULL(OSSAL.BILL_NO,0) AS INVOICENO, SALRCTD.RCT_AMT AS AMT,
--(CASE WHEN OSSAL.BILL_NO IS NULL THEN 'On Account' ELSE 'Against Bill' END) AS PAYTYPE, 
--CASE WHEN OSSAL.COMPANY_YEAR_ENTITY_UID <> @CMPYEARID  THEN 'OPENING' ELSE 'INVOICE' END AS FROMTYPE
--FROM SALRCTD INNER JOIN SALRCT ON SALRCT.ENTITY_UID = SALRCTD.RCT_ENTITY_UID LEFT OUTER JOIN
--OSSAL ON SALRCTD.REF_OSSAL_ENTITY_UID =OSSAL.OSSAL_ENTITY_UID  
--WHERE SALRCT.COMPANY_YEAR_ENTITY_UID =@CMPYEARID  AND SALRCT.VOU_ACC_ENTITY_UID = 'CASH RECEIPT'


--UNION ALL
--SELECT SALRCT.AUTO_BILL_NO AS RECEIPTNO, 0 AS INVOICENO, (SALRCT.CASH_AMT - SALRCT.TOT_RCT) AS AMT,
--'On Account' AS PAYTYPE, '' AS FROMTYPE
--FROM SALRCT  
--WHERE SALRCT.COMPANY_YEAR_ENTITY_UID =@CMPYEARID AND SALRCT.CASH_AMT - SALRCT.TOT_RCT <> 0  AND SALRCT.VOU_ACC_ENTITY_UID = 'CASH RECEIPT'

--) AS T
--ORDER BY T.RECEIPTNO, INVOICENO



-- ****************** SALE INVOICE QUERIES **************************

--SELECT * FROM SALDAT WHERE SALDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND AUTO_BILL_NO = 35

--SELECT * FROM SALDET WHERE SALDET.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND SAL_ENTITY_UID = 105000000000039
--SELECT SALDAT.AUTO_BILL_NO AS ENTRYNO, 'DISCOUNT A/C' AS CHARGESNAME, SALDAT.DISC_RATE*-1 AS DISCPER, SUM(DISC_AMT)*-1 AS CHARGES
--FROM SALDAT INNER JOIN
--SALDET ON SALDAT.ENTITY_UID = SALDET.SAL_ENTITY_UID
--WHERE        (SALDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID) AND SAL_ENTITY_UID = 105000000000039
--AND SALDET.DISC_AMT <> 0
--GROUP BY SALDAT.AUTO_BILL_NO, SALDAT.DISC_RATE



--SELECT * FROM CASHDAT WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND ENTITY_UID = 105000000000039 AND SAY_CODE_ENTITY_UID <> 'SALES ACCOUNT' AND CASH_ACC_ENTITY_UID <> 'SALES ACCOUNT'


