DECLARE @CMPYEARID BIGINT
SET @CMPYEARID = 002000000000001

SELECT * FROM SRETDAT WHERE SRETDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND AUTO_BILL_NO = 40
SELECT * FROM SRETDET WHERE SRETDET.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND SRET_ENTITY_UID = 110000000000083
SELECT * FROM CASHDAT WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND SAY_CODE_ENTITY_UID <> 'SALES RETURN ACCOUNT' AND CASH_ACC_ENTITY_UID <> 'SALES RETURN ACCOUNT' AND ENTITY_UID = 110000000000083






-- ****************** SALE INVOICE QUERIES **************************

--SELECT * FROM SALDAT WHERE SALDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND AUTO_BILL_NO = 35

--SELECT * FROM SALDET WHERE SALDET.COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND SAL_ENTITY_UID = 105000000000039
--SELECT SALDAT.AUTO_BILL_NO AS ENTRYNO, 'DISCOUNT A/C' AS CHARGESNAME, SALDAT.DISC_RATE*-1 AS DISCPER, SUM(DISC_AMT)*-1 AS CHARGES
--FROM SALDAT INNER JOIN
--SALDET ON SALDAT.ENTITY_UID = SALDET.SAL_ENTITY_UID
--WHERE        (SALDAT.COMPANY_YEAR_ENTITY_UID = @CMPYEARID) AND SAL_ENTITY_UID = 105000000000039
--AND SALDET.DISC_AMT <> 0
--GROUP BY SALDAT.AUTO_BILL_NO, SALDAT.DISC_RATE



--SELECT * FROM CASHDAT WHERE COMPANY_YEAR_ENTITY_UID = @CMPYEARID AND ENTITY_UID = 105000000000039 AND SAY_CODE_ENTITY_UID <> 'SALES ACCOUNT' AND CASH_ACC_ENTITY_UID <> 'SALES ACCOUNT'


