
Imports BL

Public Class OrderGridReport

    Public SOCLAUSE As String = ""
    Public ORDERTYPE As String = ""

    Private Sub OrderGridReport_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Try
            If ORDERTYPE = "YARNSO" Or ORDERTYPE = "YARNPO" Then GMILLNAME.Visible = True Else GMILLNAME.Visible = False
            FILLGRID()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdexit_Click(sender As Object, e As EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub CMDREFRESH_Click(sender As Object, e As EventArgs) Handles CMDREFRESH.Click
        Try
            FILLGRID()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLGRID()
        Try
            GRIDSO.RowCount = 0
            Dim OBJCMN As New ClsCommon
            Dim LASTITEMNAME As String = ""
            Dim TOTALPCS, TOTALDELPCS, TOTALBALPCS As Double
            Dim GTOTALPCS, GTOTALDELPCS, GTOTALBALPCS As Double
            Dim COMPLETIONDAYS As Integer = 0
            Dim DT As New DataTable

            If SALEORDERONMTRS = True Then
                If ORDERTYPE = "SO" Then
                    DT = OBJCMN.SEARCH(" ITEMMASTER.item_name AS ITEMNAME, '' AS MILLNAME, ALLSALEORDER.so_no AS SONO, ALLSALEORDER.so_date AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.Acc_cmpname,'') AS AGENTNAME, ALLSALEORDER.so_NOTE AS NOTE, ALLSALEORDER_DESC.SO_MTRS AS PCS, ALLSALEORDER_DESC.SO_RECDMTRS AS OUTPCS, ALLSALEORDER_DESC.BALANCE AS BALPCS, ALLSALEORDER_DESC.SO_RATE AS RATE, SO_DAYS AS [DAYS], ISNULL(ITEMMASTER.ITEM_REORDER,0) AS PERDAYPROD ", "", " ALLSALEORDER INNER JOIN ALLSALEORDER_DESC ON ALLSALEORDER.so_no = ALLSALEORDER_DESC.SO_NO AND ALLSALEORDER.TYPE = ALLSALEORDER_DESC.TYPE AND ALLSALEORDER.SO_YEARID = ALLSALEORDER_DESC.SO_YEARID INNER JOIN ITEMMASTER ON ALLSALEORDER_DESC.SO_ITEMID = ITEMMASTER.item_id INNER JOIN LEDGERS ON ALLSALEORDER.so_ledgerid = LEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON ALLSALEORDER.so_Agentid = AGENTLEDGERS.Acc_id LEFT OUTER JOIN DESIGNMASTER ON ALLSALEORDER_DESC.SO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN COLORMASTER ON ALLSALEORDER_DESC.SO_COLORID = COLORMASTER.COLOR_ID", " AND ALLSALEORDER.SO_YEARID =" & YearId & SOCLAUSE & " ORDER BY ITEMMASTER.item_name, ALLSALEORDER.SO_DATE, ALLSALEORDER.SO_NO")
                ElseIf ORDERTYPE = "YARNSO" Then
                    DT = OBJCMN.SEARCH(" YARNQUALITYMASTER.YARN_NAME AS ITEMNAME, ISNULL(MILLMASTER.MILL_NAME,'') AS MILLNAME, ALLYARNSALEORDER.YSO_NO AS SONO, ALLYARNSALEORDER.YSO_DATE AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.ACC_CMPNAME,'') AS AGENTNAME, ALLYARNSALEORDER.YSO_NOTE AS NOTE, ALLYARNSALEORDER_DESC.YSO_WT AS PCS, ALLYARNSALEORDER_DESC.YSO_RECDWT AS OUTPCS, ALLYARNSALEORDER_DESC.BALANCE AS BALPCS, ALLYARNSALEORDER_DESC.YSO_RATE AS RATE, ALLYARNSALEORDER.YSO_CRDAYS AS DAYS, 0 AS PERDAYPROD   ", "", " ALLYARNSALEORDER INNER JOIN ALLYARNSALEORDER_DESC ON ALLYARNSALEORDER.YSO_NO = ALLYARNSALEORDER_DESC.YSO_NO AND ALLYARNSALEORDER.YSO_YEARID = ALLYARNSALEORDER_DESC.YSO_YEARID INNER JOIN YARNQUALITYMASTER ON ALLYARNSALEORDER_DESC.YSO_YARNQUALITYID = YARNQUALITYMASTER.YARN_ID LEFT OUTER JOIN MILLMASTER ON ALLYARNSALEORDER_DESC.YSO_MILLID = MILLMASTER.MILL_ID INNER JOIN LEDGERS ON ALLYARNSALEORDER.YSO_LEDGERID = LEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON ALLYARNSALEORDER.YSO_BROKERID = AGENTLEDGERS.ACC_ID ", " AND ALLYARNSALEORDER.YSO_YEARID =" & YearId & SOCLAUSE & " ORDER BY YARNQUALITYMASTER.YARN_NAME, ALLYARNSALEORDER.YSO_DATE, ALLYARNSALEORDER.YSO_NO")
                ElseIf ORDERTYPE = "PO" Then
                    DT = OBJCMN.SEARCH(" ITEMMASTER.item_name AS ITEMNAME, '' AS MILLNAME, ALLPURCHASEORDER.PO_no AS SONO, ALLPURCHASEORDER.PO_date AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.Acc_cmpname,'') AS AGENTNAME, ALLPURCHASEORDER.PO_REMARKS AS NOTE, ALLPURCHASEORDER_DESC.PO_MTRS AS PCS, ALLPURCHASEORDER_DESC.PO_RECDMTRS AS OUTPCS, ALLPURCHASEORDER_DESC.BALANCE AS BALPCS, ALLPURCHASEORDER_DESC.PO_RATE AS RATE, PO_CRDAYS AS [DAYS], ISNULL(ITEMMASTER.ITEM_REORDER,0) AS PERDAYPROD ", "", " ALLPURCHASEORDER INNER JOIN ALLPURCHASEORDER_DESC ON ALLPURCHASEORDER.PO_no = ALLPURCHASEORDER_DESC.PO_NO AND ALLPURCHASEORDER.TYPE = ALLPURCHASEORDER_DESC.TYPE AND ALLPURCHASEORDER.PO_YEARID = ALLPURCHASEORDER_DESC.PO_YEARID INNER JOIN ITEMMASTER ON ALLPURCHASEORDER_DESC.PO_ITEMID = ITEMMASTER.item_id INNER JOIN LEDGERS ON ALLPURCHASEORDER.PO_ledgerid = LEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON ALLPURCHASEORDER.PO_BROKERID = AGENTLEDGERS.Acc_id LEFT OUTER JOIN DESIGNMASTER ON ALLPURCHASEORDER_DESC.PO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN COLORMASTER ON ALLPURCHASEORDER_DESC.PO_COLORID = COLORMASTER.COLOR_ID", " AND ALLPURCHASEORDER.PO_YEARID =" & YearId & SOCLAUSE & " ORDER BY ITEMMASTER.item_name, ALLPURCHASEORDER.PO_DATE, ALLPURCHASEORDER.PO_NO")
                ElseIf ORDERTYPE = "YARNPO" Then
                    DT = OBJCMN.SEARCH(" YARNQUALITYMASTER.YARN_NAME AS ITEMNAME, ISNULL(MILLMASTER.MILL_NAME,'') AS MILLNAME, ALLYARNPURCHASEORDER.YPO_NO AS SONO, ALLYARNPURCHASEORDER.YPO_DATE AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.ACC_CMPNAME,'') AS AGENTNAME, ALLYARNPURCHASEORDER.YPO_REMARKS AS NOTE, ALLYARNPURCHASEORDER_DESC.YPO_WT AS PCS, ALLYARNPURCHASEORDER_DESC.YPO_RECDWT AS OUTPCS, ALLYARNPURCHASEORDER_DESC.BALANCE AS BALPCS, ALLYARNPURCHASEORDER_DESC.YPO_RATE AS RATE, ALLYARNPURCHASEORDER.YPO_CRDAYS AS DAYS, 0 AS PERDAYPROD ", "", " ALLYARNPURCHASEORDER INNER JOIN ALLYARNPURCHASEORDER_DESC ON ALLYARNPURCHASEORDER.YPO_NO = ALLYARNPURCHASEORDER_DESC.YPO_NO AND ALLYARNPURCHASEORDER.YPO_YEARID = ALLYARNPURCHASEORDER_DESC.YPO_YEARID INNER JOIN YARNQUALITYMASTER ON ALLYARNPURCHASEORDER_DESC.YPO_YARNQUALITYID = YARNQUALITYMASTER.YARN_ID LEFT OUTER JOIN MILLMASTER ON ALLYARNPURCHASEORDER_DESC.YPO_MILLID = MILLMASTER.MILL_ID INNER JOIN LEDGERS ON ALLYARNPURCHASEORDER.YPO_LEDGERID = LEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON ALLYARNPURCHASEORDER.YPO_BROKERID = AGENTLEDGERS.ACC_ID  ", " AND ALLYARNPURCHASEORDER.YPO_YEARID =" & YearId & SOCLAUSE & " ORDER BY YARNQUALITYMASTER.YARN_NAME, ALLYARNPURCHASEORDER.YPO_DATE, ALLYARNPURCHASEORDER.YPO_NO")
                End If
            Else
                If ORDERTYPE = "SO" Then
                    DT = OBJCMN.SEARCH(" ITEMMASTER.item_name AS ITEMNAME, '' AS MILLNAME, ALLSALEORDER.so_no AS SONO, ALLSALEORDER.so_date AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.Acc_cmpname,'') AS AGENTNAME, ALLSALEORDER.so_NOTE AS NOTE, ALLSALEORDER_DESC.SO_QTY AS PCS, ALLSALEORDER_DESC.SO_RECDQTY AS OUTPCS, ALLSALEORDER_DESC.BALANCE AS BALPCS, ALLSALEORDER_DESC.SO_RATE AS RATE, SO_DAYS AS [DAYS], ISNULL(ITEMMASTER.ITEM_REORDER,0) AS PERDAYPROD ", "", " ALLSALEORDER INNER JOIN ALLSALEORDER_DESC ON ALLSALEORDER.so_no = ALLSALEORDER_DESC.SO_NO AND ALLSALEORDER.TYPE = ALLSALEORDER_DESC.TYPE AND ALLSALEORDER.SO_YEARID = ALLSALEORDER_DESC.SO_YEARID INNER JOIN ITEMMASTER ON ALLSALEORDER_DESC.SO_ITEMID = ITEMMASTER.item_id INNER JOIN LEDGERS ON ALLSALEORDER.so_ledgerid = LEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON ALLSALEORDER.so_Agentid = AGENTLEDGERS.Acc_id LEFT OUTER JOIN DESIGNMASTER ON ALLSALEORDER_DESC.SO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN COLORMASTER ON ALLSALEORDER_DESC.SO_COLORID = COLORMASTER.COLOR_ID", " AND ALLSALEORDER.SO_YEARID =" & YearId & SOCLAUSE & " ORDER BY ITEMMASTER.item_name, ALLSALEORDER.SO_DATE, ALLSALEORDER.SO_NO")
                ElseIf ORDERTYPE = "YARNSO" Then
                    DT = OBJCMN.SEARCH(" YARNQUALITYMASTER.YARN_NAME AS ITEMNAME, ISNULL(MILLMASTER.MILL_NAME,'') AS MILLNAME, ALLYARNSALEORDER.YSO_NO AS SONO, ALLYARNSALEORDER.YSO_DATE AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.ACC_CMPNAME,'') AS AGENTNAME, ALLYARNSALEORDER.YSO_NOTE AS NOTE, ALLYARNSALEORDER_DESC.YSO_BAGS AS PCS, ALLYARNSALEORDER_DESC.YSO_RECDBAGS AS OUTPCS, ALLYARNSALEORDER_DESC.BALANCE AS BALPCS, ALLYARNSALEORDER_DESC.YSO_RATE AS RATE, ALLYARNSALEORDER.YSO_CRDAYS AS DAYS, 0 AS PERDAYPROD   ", "", " ALLYARNSALEORDER INNER JOIN ALLYARNSALEORDER_DESC ON ALLYARNSALEORDER.YSO_NO = ALLYARNSALEORDER_DESC.YSO_NO AND ALLYARNSALEORDER.YSO_YEARID = ALLYARNSALEORDER_DESC.YSO_YEARID INNER JOIN YARNQUALITYMASTER ON ALLYARNSALEORDER_DESC.YSO_YARNQUALITYID = YARNQUALITYMASTER.YARN_ID LEFT OUTER JOIN MILLMASTER ON ALLYARNSALEORDER_DESC.YSO_MILLID = MILLMASTER.MILL_ID INNER JOIN LEDGERS ON ALLYARNSALEORDER.YSO_LEDGERID = LEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON ALLYARNSALEORDER.YSO_BROKERID = AGENTLEDGERS.ACC_ID ", " AND ALLYARNSALEORDER.YSO_YEARID =" & YearId & SOCLAUSE & " ORDER BY YARNQUALITYMASTER.YARN_NAME, ALLYARNSALEORDER.YSO_DATE, ALLYARNSALEORDER.YSO_NO")
                ElseIf ORDERTYPE = "PO" Then
                    DT = OBJCMN.SEARCH(" ITEMMASTER.item_name AS ITEMNAME, '' AS MILLNAME, ALLPURCHASEORDER.PO_no AS SONO, ALLPURCHASEORDER.PO_date AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.Acc_cmpname,'') AS AGENTNAME, ALLPURCHASEORDER.PO_REMARKS AS NOTE, ALLPURCHASEORDER_DESC.PO_QTY AS PCS, ALLPURCHASEORDER_DESC.PO_RECDQTY AS OUTPCS, ALLPURCHASEORDER_DESC.BALANCE AS BALPCS, ALLPURCHASEORDER_DESC.PO_RATE AS RATE, PO_CRDAYS AS [DAYS], ISNULL(ITEMMASTER.ITEM_REORDER,0) AS PERDAYPROD ", "", " ALLPURCHASEORDER INNER JOIN ALLPURCHASEORDER_DESC ON ALLPURCHASEORDER.PO_no = ALLPURCHASEORDER_DESC.PO_NO AND ALLPURCHASEORDER.TYPE = ALLPURCHASEORDER_DESC.TYPE AND ALLPURCHASEORDER.PO_YEARID = ALLPURCHASEORDER_DESC.PO_YEARID INNER JOIN ITEMMASTER ON ALLPURCHASEORDER_DESC.PO_ITEMID = ITEMMASTER.item_id INNER JOIN LEDGERS ON ALLPURCHASEORDER.PO_ledgerid = LEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON ALLPURCHASEORDER.PO_BROKERID = AGENTLEDGERS.Acc_id LEFT OUTER JOIN DESIGNMASTER ON ALLPURCHASEORDER_DESC.PO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN COLORMASTER ON ALLPURCHASEORDER_DESC.PO_COLORID = COLORMASTER.COLOR_ID", " AND ALLPURCHASEORDER.PO_YEARID =" & YearId & SOCLAUSE & " ORDER BY ITEMMASTER.item_name, ALLPURCHASEORDER.PO_DATE, ALLPURCHASEORDER.PO_NO")
                ElseIf ORDERTYPE = "YARNPO" Then
                    DT = OBJCMN.SEARCH(" YARNQUALITYMASTER.YARN_NAME AS ITEMNAME, ISNULL(MILLMASTER.MILL_NAME,'') AS MILLNAME, ALLYARNPURCHASEORDER.YPO_NO AS SONO, ALLYARNPURCHASEORDER.YPO_DATE AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.ACC_CMPNAME,'') AS AGENTNAME, ALLYARNPURCHASEORDER.YPO_REMARKS AS NOTE, ALLYARNPURCHASEORDER_DESC.YPO_BAGS AS PCS, ALLYARNPURCHASEORDER_DESC.YPO_RECDBAGS AS OUTPCS, ALLYARNPURCHASEORDER_DESC.BALANCE AS BALPCS, ALLYARNPURCHASEORDER_DESC.YPO_RATE AS RATE, ALLYARNPURCHASEORDER.YPO_CRDAYS AS DAYS, 0 AS PERDAYPROD ", "", " ALLYARNPURCHASEORDER INNER JOIN ALLYARNPURCHASEORDER_DESC ON ALLYARNPURCHASEORDER.YPO_NO = ALLYARNPURCHASEORDER_DESC.YPO_NO AND ALLYARNPURCHASEORDER.YPO_YEARID = ALLYARNPURCHASEORDER_DESC.YPO_YEARID INNER JOIN YARNQUALITYMASTER ON ALLYARNPURCHASEORDER_DESC.YPO_YARNQUALITYID = YARNQUALITYMASTER.YARN_ID LEFT OUTER JOIN MILLMASTER ON ALLYARNPURCHASEORDER_DESC.YPO_MILLID = MILLMASTER.MILL_ID INNER JOIN LEDGERS ON ALLYARNPURCHASEORDER.YPO_LEDGERID = LEDGERS.ACC_ID LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON ALLYARNPURCHASEORDER.YPO_BROKERID = AGENTLEDGERS.ACC_ID  ", " AND ALLYARNPURCHASEORDER.YPO_YEARID =" & YearId & SOCLAUSE & " ORDER BY YARNQUALITYMASTER.YARN_NAME, ALLYARNPURCHASEORDER.YPO_DATE, ALLYARNPURCHASEORDER.YPO_NO")
                End If
            End If

            For Each DTROW As DataRow In DT.Rows
                If LASTITEMNAME <> DTROW("ITEMNAME") Then
                    LASTITEMNAME = DTROW("ITEMNAME")
                    If GRIDSO.RowCount > 0 Then
                        GRIDSO.Rows.Add("", "", "", "COMPLETION DAYS - " & Val(COMPLETIONDAYS), "", "TOTAL", "", Val(TOTALPCS), Val(TOTALDELPCS), Val(TOTALBALPCS), "", "")
                        GRIDSO.Rows(GRIDSO.RowCount - 1).DefaultCellStyle.ForeColor = Color.Maroon
                        GRIDSO.Rows(GRIDSO.RowCount - 1).DefaultCellStyle.Font = New Font("Calibri", 10, FontStyle.Bold)
                        GRIDSO.Rows.Add("", "", "", "", "", "", "", "", "", "", "", "")

                        TOTALPCS = 0
                        TOTALDELPCS = 0
                        TOTALBALPCS = 0
                        COMPLETIONDAYS = 0
                    End If
                    GRIDSO.Rows.Add(DTROW("ITEMNAME"), "", "", "PER DAY PROD - " & Val(DTROW("PERDAYPROD")), "", "", "", "", "", "", "", "")
                    GRIDSO.Rows(GRIDSO.RowCount - 1).DefaultCellStyle.Font = New Font("Calibri", 10, FontStyle.Bold)
                End If
                GRIDSO.Rows.Add("", Val(DTROW("SONO")), Format(DTROW("SODATE"), "dd/MM/yyyy"), DTROW("NAME"), DTROW("AGENTNAME"), DTROW("NOTE"), DTROW("MILLNAME"), Val(DTROW("PCS")), Val(DTROW("OUTPCS")), Val(DTROW("BALPCS")), Format(Val(DTROW("RATE")), "0.00"), Val(DTROW("DAYS")))
                TOTALPCS += Val(DTROW("PCS"))
                GTOTALPCS += Val(DTROW("PCS"))
                TOTALDELPCS += Val(DTROW("OUTPCS"))
                GTOTALDELPCS += Val(DTROW("OUTPCS"))
                TOTALBALPCS += Val(DTROW("BALPCS"))
                GTOTALBALPCS += Val(DTROW("BALPCS"))
                If Val(TOTALBALPCS) > 0 And Val(DTROW("PERDAYPROD")) > 0 Then COMPLETIONDAYS = Format(Val(TOTALBALPCS) / Val(DTROW("PERDAYPROD")), "0")
            Next

            'FOR TOTAL AND GRANDTOTAL ON LAST LINE
            If GRIDSO.RowCount > 0 Then
                GRIDSO.Rows.Add("", "", "", "COMPLETION DAYS - " & Val(COMPLETIONDAYS), "", "TOTAL", "", Val(TOTALPCS), Val(TOTALDELPCS), Val(TOTALBALPCS), "", "")
                GRIDSO.Rows(GRIDSO.RowCount - 1).DefaultCellStyle.ForeColor = Color.Maroon
                GRIDSO.Rows(GRIDSO.RowCount - 1).DefaultCellStyle.Font = New Font("Calibri", 10, FontStyle.Bold)


                GRIDSO.Rows.Add("", "", "", "", "", "GRAND TOTAL", "", Val(GTOTALPCS), Val(GTOTALDELPCS), Val(GTOTALBALPCS), "", "")
                GRIDSO.Rows(GRIDSO.RowCount - 1).DefaultCellStyle.ForeColor = Color.DarkGreen
                GRIDSO.Rows(GRIDSO.RowCount - 1).DefaultCellStyle.Font = New Font("Calibri", 10, FontStyle.Bold)
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub OrderGridReport_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode = Keys.Escape Then Me.Close()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CMDEXPORT_Click(sender As Object, e As EventArgs) Handles CMDEXPORT.Click
        Try
            Dim xlapp As Excel.Application
            Dim xlWorkBook As Excel.Workbook
            Dim xlWorkSheet As Excel.Worksheet
            Dim misValue As Object = System.Reflection.Missing.Value
            Dim i As Integer
            Dim j As Integer

            xlapp = New Excel.Application
            xlWorkBook = xlapp.Workbooks.Add(misValue)
            xlWorkSheet = CType(xlWorkBook.Sheets("Sheet1"), Excel.Worksheet)

            For k = 0 To GRIDSO.ColumnCount - 1
                xlWorkSheet.Cells(1, k + 1).HorizontalAlignment = Microsoft.Office.Interop.Excel.XlHAlign.xlHAlignCenter
                xlWorkSheet.Cells(1, k + 1) = GRIDSO.Columns(k).HeaderText
                xlWorkSheet.Rows.Item(1).EntireColumn.AutoFit()
            Next
            For i = 0 To GRIDSO.RowCount - 1
                For j = 0 To GRIDSO.ColumnCount - 1
                    xlWorkSheet.Cells(i + 2, j + 1).HorizontalAlignment = Microsoft.Office.Interop.Excel.XlHAlign.xlHAlignCenter
                    xlWorkSheet.Cells(i + 2, j + 1) = GRIDSO(j, i).Value.ToString()
                Next
                xlWorkSheet.Rows.Item(i + 2).EntireColumn.AutoFit()
            Next


            Dim SaveFileDialog1 As New SaveFileDialog()
            SaveFileDialog1.Filter = "Execl files (*.xlsx)|*.xlsx"
            SaveFileDialog1.FilterIndex = 2
            SaveFileDialog1.RestoreDirectory = True
            If SaveFileDialog1.ShowDialog() = DialogResult.OK Then
                xlWorkSheet.SaveAs(SaveFileDialog1.FileName)
                MsgBox("Save file success")
            Else
                Return
            End If
            xlWorkBook.Close()
            xlapp.Quit()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub OrderGridReport_Shown(sender As Object, e As EventArgs) Handles Me.Shown
        Try
            If ClientName = "ABHEE" Then GAGENTNAME.Visible = False
        Catch ex As Exception
            Throw ex
        End Try
    End Sub
End Class