Imports BL

Public Class DesignCardMasterDetails

    Dim USERADD, USEREDIT, USERVIEW, USERDELETE As Boolean

    Private Sub CMDEXIT_Click(sender As Object, e As EventArgs)
        Me.Close()
    End Sub

    Public FRMSTRING As String
    Private Sub DesignCardMasterDetails_Load(sender As Object, e As EventArgs) Handles MyBase.Load
         Try
            Dim DTROW() As DataRow
            DTROW = USERRIGHTS.Select("FormName = 'DESIGN MASTER'")
            USERADD = DTROW(0).Item(1)
            USEREDIT = DTROW(0).Item(2)
            USERVIEW = DTROW(0).Item(3)
            USERDELETE = DTROW(0).Item(4)

            fillgrid()
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub
    Sub fillgrid()
        Try
            If USEREDIT = False And USERVIEW = False Then
                MsgBox("Insufficient Rights")
                Exit Sub
            End If
            Dim objClsCommon As New ClsCommonMaster
            Dim dttable As DataTable = objClsCommon.search("   DESIGNCARD.DESIGN_CARDNO AS CARDNO, ISNULL(DESIGNCARD.DESIGN_FEPI, 0) AS FEPI, ISNULL(DESIGNCARD.DESIGN_FWIDTH, 0) AS FWIDTH, ISNULL(DESIGNCARD.DESIGN_FPPI, 0) AS FPPI, ISNULL(DESIGNCARD.DESIGN_FWT, 0) AS FWT, ISNULL(DESIGNCARD.DESIGN_DENTS, 0) AS DENTS, ISNULL(DESIGNCARD.DESIGN_TOTALDENTSMAIN, 0) AS TOTALDENTSMAIN, ISNULL(DESIGNCARD.DESIGN_TOTALSELVEDGEDENTS, 0) AS TOTALSELVEDGEDENTS, ISNULL(DESIGNCARD.DESIGN_TOTALDENTS, 0) AS TOTALDENTS, ISNULL(DESIGNCARD.DESIGN_WARPTTL, 0) AS WARPTTL, ISNULL(DESIGNCARD.DESIGN_WEFTTTL, 0) AS WEFTTTL, ISNULL(DESIGNCARD.DESIGN_GSM, 0) AS GSM, ISNULL(DESIGNCARD.DESIGN_SHAFTS, 0) AS SHAFTS, ISNULL(DESIGNCARD.DESIGN_TOTALWT, 0) AS TOTALWT, ISNULL(DESIGNCARD.DESIGN_LEFTSELVEDGE, 0) AS LEFTSELVEDGE, ISNULL(DESIGNCARD.DESIGN_RIGHTSELVEDGE, 0) AS RIGHTSELVEDGE, ISNULL(DESIGNCARD.DESIGN_LEFTSELVEDGEEND, 0) AS LEFTSELVEDGEEND, ISNULL(DESIGNCARD.DESIGN_RIGHTSELVEDGEEND, 0) AS RIGHTSELVEDGEEND, ISNULL(DESIGNCARD.DESIGN_LEFTSELVEDGEDENTS, 0) AS LEFTSELVEDGEDENTS, ISNULL(DESIGNCARD.DESIGN_RIGHTSELVEDGEDENTS, 0) AS RIGHTSELVEDGEDENTS, ISNULL(DESIGNCARD.DESIGN_LEFTSELVEDGETOTALEND, 0) AS LEFTSELVEDGETOTALEND, ISNULL(DESIGNCARD.DESIGN_RIGHTSELVEDGETOTALEND, 0) AS RIGHTSELVEDGETOTALEND, ISNULL(DESIGNCARD.DESIGN_TOTALSELVEDGEENDS, 0) AS TOTALSELVEDGEENDS, ISNULL(DESIGNCARD.DESIGN_REFNO, '') AS REFNO, ISNULL(DESIGNCARD.DESIGN_GREY, '') AS GREY, ISNULL(DESIGNCARD.DESIGN_ORDERNO, 0) AS ORDERNO, ISNULL(DESIGNCARD.DESIGN_DELDATE, '') AS DELDATE, ISNULL(DESIGNCARD.DESIGN_ORDERDATE, '') AS ORDERDATE, ISNULL(DESIGNCARD.DESIGN_MTRS, 0) AS MTRS, ISNULL(DESIGNCARD.DESIGN_NOOFPCS, 0) AS NOOFPCS, ISNULL(DESIGNCARD.DESIGN_LOOM, '') AS LOOM, ISNULL(DESIGNCARD.DESIGN_BEAMMTRS, 0) AS BEAMMTRS, ISNULL(DESIGNCARD.DESIGN_COVERFACTOR, '') AS COVERFACTOR, ISNULL(DESIGNCARD.DESIGN_EFFICIENCY, '') AS EFFICIENCY, ISNULL(DESIGNCARD.DESIGN_LOOMPROD, 0) AS LOOMPROD, ISNULL(DESIGNCARD.DESIGN_RPM, '') AS RPM, ISNULL(DESIGNCARD.DESIGN_GREYDELDATE, '') AS GREYDELDATE, ISNULL(DESIGNCARD.DESIGN_TOTALWARPPE, 0) AS TOTALWARPPE, ISNULL(DESIGNCARD.DESIGN_TOTALWARPBE, 0) AS TOTALWARPBE, ISNULL(DESIGNCARD.DESIGN_TOTALWARPTE, 0) AS TOTALWARPTE, ISNULL(DESIGNCARD.DESIGN_TOTALWARPWT, 0) AS TOTALWARPWT, ISNULL(DESIGNCARD.DESIGN_TOTALWARPCONS, 0) AS TOTALWARPCONS, ISNULL(DESIGNCARD.DESIGN_TOTALWARPRATE, 0) AS TOTALWARPRATE, ISNULL(DESIGNCARD.DESIGN_TOTALWARPCOST, 0) AS TOTALWARPCOST, ISNULL(DESIGNCARD.DESIGN_TOTALWARPGRIDPE, 0) AS TOTALWARPGRIDPE, ISNULL(DESIGNCARD.DESIGN_TOTALSELVEDGEPE, 0) AS TOTALSELVEDGEPE, ISNULL(DESIGNCARD.DESIGN_TOTALSELVEDGEBE, 0) AS TOTALSELVEDGEBE, ISNULL(DESIGNCARD.DESIGN_TOTALSELVEDGETE, 0) AS TOTALSELVEDGETE, ISNULL(DESIGNCARD.DESIGN_TOTALSELVEDGEWT, 0) AS TOTALSELVEDGEWT, ISNULL(DESIGNCARD.DESIGN_TOTALSELVEDGECONS, 0) AS TOTALSELVEDGECONS, ISNULL(DESIGNCARD.DESIGN_TOTALSELVEDGERATE, 0) AS TOTALSELVEDGERATE, ISNULL(DESIGNCARD.DESIGN_TOTALSELVEDGECOST, 0) AS TOTALSELVEDGECOST, ISNULL(DESIGNCARD.DESIGN_TOTALSELVEDGEGRIDPE, 0) AS TOTALSELVEDGEGRIDPE, ISNULL(DESIGNCARD.DESIGN_TOTALWEFTPE, 0) AS TOTALWEFTPE, ISNULL(DESIGNCARD.DESIGN_TOTALWEFTBE, 0) AS TOTALWEFTBE, ISNULL(DESIGNCARD.DESIGN_TOTALWEFTTE, 0) AS TOTALWEFTTE, ISNULL(DESIGNCARD.DESIGN_TOTALWEFTWT, 0) AS TOTALWEFTWT, ISNULL(DESIGNCARD.DESIGN_TOTALWEFTCONS, 0) AS TOTALWEFTCONS, ISNULL(DESIGNCARD.DESIGN_TOTALWEFTRATE, 0) AS TOTALWEFTRATE, ISNULL(DESIGNCARD.DESIGN_TOTALWEFTCOST, 0) AS TOTALWEFTCOST, ISNULL(DESIGNCARD.DESIGN_TOTALWEFTGRIDPE, 0) AS TOTALWEFTGRIDPE, ISNULL(DESIGNCARD.DESIGN_TOTALDRAWENDS, 0) AS TOTALDRAWENDS, ISNULL(DESIGNCARD.DESIGN_TOTALDRAWDENTS, 0) AS TOTALDRAWDENTS, ISNULL(DESIGNMASTER.DESIGN_NO, 0) AS DESIGNNO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(AGENTLEDGERS.Acc_cmpname, '') AS AGENTNAME, ISNULL(DELATLEDGERS.Acc_cmpname, '') AS DELIVERYAT, ISNULL(GDELATLEDGERS.Acc_cmpname, '') AS GREYDELIVERYAT, DESIGNCARD.DESIGN_DATE AS DATE, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, ISNULL(DESIGNCARD.DESIGN_REED, 0) AS REED, ISNULL(DESIGNCARD.DESIGN_REEDSPACE, 0) AS REEDSPACE, ISNULL(DESIGNCARD.DESIGN_PICKS, 0) AS PICKS, ISNULL(DESIGNCARD.DESIGN_MAINRS, 0) AS MAINRS, ISNULL(DESIGNCARD.DESIGN_THREADPERDENT, 0) AS THREADPERDENT, ISNULL(WEAVEMASTER.WEAVE_name, '') AS WEAVE, ISNULL(DESIGNCARD.DESIGN_TOTALFINISHWT, 0) AS TOTALFINISHWT, ISNULL(DESIGNCARD.DESIGN_GREYWIDTH, 0) AS GREYWIDTH, ISNULL(DESIGNCARD.DESIGN_GREYWIDTHCM,0) AS GREYWIDTHCM, ISNULL(DESIGNCARD.DESIGN_FINISHWIDTHCM,0) AS FINISHWIDTHCM, ISNULL(DESIGNCARD.DESIGN_GREYLOOMMTR,0) AS GREYLOOMMTR, ISNULL(DESIGNCARD.DESIGN_BLENDPERCENTAGE,0) AS BLENDPER, ISNULL(DESIGNCARD.DESIGN_FINISHMETHOD,'') AS FINISHMETHOD, ISNULL(DESIGNCARD.DESIGN_QUALITIES,'') AS QUALITY, ISNULL(DESIGNCARD.DESIGN_QUALITYTYPE,'') AS QUALITYTYPE, ISNULL(DESIGNCARD.DESIGN_WARPWASTAGE,0) AS WARPWASTAGE, ISNULL(DESIGNCARD.DESIGN_WASTAGEPERCENTAGE,0) AS WASTAGEPER, ISNULL(DESIGNCARD.DESIGN_SHRINKAGEPERCENTAGE,0) AS SHRINKAGEPER, ISNULL(DESIGNCARD.DESIGN_WPP,0) AS WPP, ISNULL(DESIGNCARD.DESIGN_WEAVECOST,0) AS WEAVECOST, ISNULL(DESIGNCARD.DESIGN_GREYFABRICCOST,0) AS GREYFABCOST, ISNULL(DESIGNCARD.DESIGN_FINISHFABRICCOST,0) AS FINISHFABCOST, ISNULL(DESIGNCARD.DESIGN_PRODUCTIONPERDAY,0) AS PRODDAY, ISNULL(DESIGNCARD.DESIGN_PCSL,0) AS PCSL, ISNULL(DESIGNCARD.DESIGN_REEDSPACECM,0) AS REEDSPACECM,ISNULL(DESIGNCARD.DESIGN_TOTALENDS,0) AS TOTALENDS,ISNULL(DESIGNCARD.DESIGN_ENDPERINCH,0) AS ENDPERINCH, ISNULL(DESIGNCARD.DESIGN_TOTALPEG,0) AS TOTALPEG", "", " DESIGNCARD LEFT OUTER JOIN WEAVEMASTER ON DESIGNCARD.DESIGN_YEARID = WEAVEMASTER.WEAVE_yearid AND DESIGNCARD.DESIGN_WEAVEID = WEAVEMASTER.WEAVE_id LEFT OUTER JOIN LEDGERS AS GDELATLEDGERS ON DESIGNCARD.DESIGN_YEARID = GDELATLEDGERS.Acc_yearid AND DESIGNCARD.DESIGN_GREYDELATID = GDELATLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS DELATLEDGERS ON DESIGNCARD.DESIGN_YEARID = DELATLEDGERS.Acc_yearid AND DESIGNCARD.DESIGN_DELIVERYATID = DELATLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON DESIGNCARD.DESIGN_YEARID = AGENTLEDGERS.Acc_yearid AND DESIGNCARD.DESIGN_AGENTID = AGENTLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS ON DESIGNCARD.DESIGN_YEARID = LEDGERS.Acc_yearid AND DESIGNCARD.DESIGN_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN ITEMMASTER ON DESIGNCARD.DESIGN_YEARID = ITEMMASTER.item_yearid AND DESIGNCARD.DESIGN_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN DESIGNMASTER ON DESIGNCARD.DESIGN_YEARID = DESIGNMASTER.DESIGN_yearid AND DESIGNCARD.DESIGN_ID = DESIGNMASTER.DESIGN_id ", " and DESIGNMASTER.design_yearid = " & YearId)
            GRIDBILLDETAILS.DataSource = dttable
            If dttable.Rows.Count > 0 Then
                GRIDBILL.FocusedRowHandle = GRIDBILL.RowCount - 1
                GRIDBILL.TopRowIndex = GRIDBILL.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try

    End Sub

End Class