DECLARE @SUBJECT VARCHAR(100), @ENTRYBODY VARCHAR(MAX), @TOTALMTRS DECIMAL(18,2), @TOTALRETURNMTRS DECIMAL(18,2), @CMPNAME AS VARCHAR(100)
SET @CMPNAME = 'SUPRIYA SILK INDUSTRIES'
SET @SUBJECT = 'SSI-DAILY DISPATH DETAILS REPORT FOR ' + CAST(DAY( GETDATE()) AS VARCHAR(2)) + '-' + CAST(MONTH( GETDATE()) AS VARCHAR(2)) + '-' + CAST(YEAR( GETDATE()) AS VARCHAR(4))
SELECT @TOTALMTRS = SUM(GDN_DESC.GDN_MTRS)  FROM  GDN_DESC INNER JOIN GDN ON GDN.GDN_NO = GDN_DESC.GDN_NO AND GDN.GDN_YEARID = GDN_DESC.GDN_YEARID WHERE GDN_DATE = CAST(GETDATE() AS DATE) AND GDN.GDN_YEARID = (SELECT TOP 1 YEAR_ID FROM YEARMASTER inner join CMPMASTER ON YEAR_CMPID = CMP_ID WHERE CMP_DISPLAYEDNAME = @CMPNAME  and year_startdate= CASE WHEN MONTH(GETDATE()) > 3 THEN CAST(YEAR(GETDATE()) AS VARCHAR(4)) + '-04-01' ELSE CAST(YEAR(GETDATE())-1 AS VARCHAR(4)) + '-04-01' END ORDER BY YEAR_STARTDATE DESC) 
SELECT @TOTALRETURNMTRS = ISNULL(SUM(SALERETURN_DESC.SALRET_MTRS),0)  FROM  SALERETURN_DESC INNER JOIN SALERETURN ON SALERETURN.SALRET_NO = SALERETURN_DESC.SALRET_NO AND SALERETURN.SALRET_YEARID = SALERETURN_DESC.SALRET_YEARID WHERE SALRET_DATE = CAST(GETDATE() AS DATE) AND SALERETURN.SALRET_YEARID = (SELECT TOP 1 YEAR_ID FROM YEARMASTER inner join CMPMASTER ON YEAR_CMPID = CMP_ID WHERE CMP_DISPLAYEDNAME = @CMPNAME  and year_startdate= CASE WHEN MONTH(GETDATE()) > 3 THEN CAST(YEAR(GETDATE()) AS VARCHAR(4)) + '-04-01' ELSE CAST(YEAR(GETDATE())-1 AS VARCHAR(4)) + '-04-01' END ORDER BY YEAR_STARTDATE DESC) 



SET @ENTRYBODY = (SELECT  
[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@width]='80px', TD= GDN_DATE ,'', 
[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@width]='250px', TD= ISNULL(LEDGERS.Acc_cmpname,'') ,'', 
[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@align]='right',[TD/@width]='80px', TD=SUM(CAST(GDN_DESC.GDN_MTRS AS DECIMAL(18,2))) ,'',
[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@align]='right',[TD/@width]='100px', TD=CAST(ISNULL(T.MTRS,0) AS DECIMAL(18,2)) ,''

FROM GDN INNER JOIN LEDGERS ON GDN_ledgerid = LEDGERS.ACC_ID INNER JOIN 
GDN_DESC ON GDN.GDN_NO = GDN_DESC.GDN_NO AND GDN.GDN_YEARID = GDN_DESC.GDN_YEARID
LEFT OUTER JOIN 

(SELECT SALRET_DATE AS DATE, ISNULL(LEDGERS.ACC_CMPNAME,'') AS NAME, SUM(SALERETURN_DESC.SALRET_MTRS) AS MTRS  FROM SALERETURN INNER JOIN LEDGERS ON SALRET_ledgerid = LEDGERS.ACC_ID INNER JOIN SALERETURN_DESC ON SALERETURN.SALRET_NO = SALERETURN_DESC.SALRET_NO AND SALERETURN.SALRET_YEARID = SALERETURN_DESC.SALRET_YEARID 
WHERE SALRET_DATE = CAST(GETDATE() AS DATE) AND SALERETURN.SALRET_YEARID = (SELECT TOP 1 YEAR_ID FROM YEARMASTER inner join CMPMASTER ON YEAR_CMPID = CMP_ID WHERE CMP_DISPLAYEDNAME = @CMPNAME  and year_startdate= CASE WHEN MONTH(GETDATE()) > 3 THEN CAST(YEAR(GETDATE()) AS VARCHAR(4)) + '-04-01' ELSE CAST(YEAR(GETDATE())-1 AS VARCHAR(4)) + '-04-01' END ORDER BY YEAR_STARTDATE DESC) 
GROUP BY SALRET_DATE, ISNULL(LEDGERS.ACC_CMPNAME,'')
) AS T

ON T.DATE = GDN_date AND T.NAME = LEDGERS.ACC_CMPNAME

WHERE GDN_DATE = CAST(GETDATE() AS DATE) AND GDN.GDN_YEARID = (SELECT TOP 1 YEAR_ID FROM YEARMASTER inner join CMPMASTER ON YEAR_CMPID = CMP_ID WHERE CMP_DISPLAYEDNAME = @CMPNAME  and year_startdate= CASE WHEN MONTH(GETDATE()) > 3 THEN CAST(YEAR(GETDATE()) AS VARCHAR(4)) + '-04-01' ELSE CAST(YEAR(GETDATE())-1 AS VARCHAR(4)) + '-04-01' END ORDER BY YEAR_STARTDATE DESC) 
GROUP BY GDN_DATE, T.MTRS, ISNULL(LEDGERS.ACC_CMPNAME,'')




FOR XML PATH ('tr'))


DECLARE @BODY VARCHAR(MAX)
SET @BODY = N'<H1 style="font-family:Tahoma; font-size:11px;">DAILY DISPATCH DETAILS</H1>' +
				N'<Table Border = "1">' + 
				N'<Tr style="font-family:Tahoma; font-size:11px;"><Th>Date</Th><Th>Name</Th><Th>Mtrs</Th><Th>Return Mtrs</Th></Tr>'+
				+ISNULL(@ENTRYBODY,'')+ N'<tfoot><tr><td colspan="2"; style="font-family:Tahoma; font-size:11px; font-weight:bold; color:black;" bgcolor="yellow">GRAND TOTAL:</td>
				<td style="font-family:Tahoma; font-size:11px; font-weight:bold; color:black;" align="right" bgcolor="yellow">' + CAST(@TOTALMTRS AS VARCHAR) + N'</td>
				<td style="font-family:Tahoma; font-size:11px; font-weight:bold; color:black;" align="right" bgcolor="yellow">' + CAST(@TOTALRETURNMTRS AS VARCHAR) + N'</td>
				</tr></tfoot></Table></html>'



DECLARE @FINALBODY VARCHAR(MAX)
SET @FINALBODY = @BODY 


EXEC msdb.dbo.sp_send_dbmail
@profile_name='TEXTRADE',
@recipients='royaltexfabrics@yahoo.co.in;',
@subject=@SUBJECT,
@body=@FINALBODY,
@body_format = 'HTML'