
Imports BL
Imports DevExpress.XtraGrid.Views.Grid

Public Class SelectBillsforITC
    Public DT As New DataTable

    Private Sub SelectBillsforITC_Load(sender As Object, e As EventArgs) Handles Me.Load
        Try
            DTTILLDATE.Value = Now.Date
            FILLGRID()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLGRID()
        Try
            Dim OBJCMN As New ClsCommon
            'Dim dt As DataTable = OBJCMN.search(" *, (CASE WHEN T.INVNOBOOKS = '' THEN 'ONLY IN PORTAL' ELSE (CASE WHEN T.INVNOPORTAL = '' THEN 'ONLY IN BOOKS' ELSE (CASE WHEN (T.TAXABLEAMTBOOKS - T.TAXABLEAMTPORTAL) <> 0 THEN 'VALUE MISMATCH' ELSE 'EXACT MATCH' END) END)END) AS RECOSTATUS ", "", "(SELECT ISNULL(GSTR2BILLS.BILLNO,0) AS BILLNO, ISNULL(GSTR2BILLS.TYPE,'') AS TYPE, COALESCE (GSTR2B2B.MONTH, UPPER(DATENAME(M, GSTR2BILLS.PARTYBILLDATE))) AS [MONTH], COALESCE(GSTR2B2B.GSTIN,  GSTR2BILLS.GSTIN) AS GSTIN, (CASE WHEN ISNULL(GSTR2B2B.NAME,'') <> '' THEN ISNULL(GSTR2B2B.NAME,'') ELSE GSTR2BILLS.NAME END) AS NAME, ISNULL(GSTR2BILLS.PARTYBILLNO,'') AS INVNOBOOKS, COALESCE(GSTR2BILLS.PARTYBILLDATE,GSTR2B2B.INVDATE) AS INVDATEBOOKS, ISNULL(GSTR2B2B.INVNO,'') AS INVNOPORTAL,   COALESCE(GSTR2B2B.INVDATE, GSTR2BILLS.PARTYBILLDATE) AS INVDATEPORTAL,  ISNULL(GSTR2BILLS.TAXABLEAMT,0) AS TAXABLEAMTBOOKS, ISNULL(GSTR2BILLS.CGSTAMT,0) AS CGSTAMTBOOKS, ISNULL(GSTR2BILLS.SGSTAMT,0) AS SGSTAMTBOOKS, ISNULL(GSTR2BILLS.IGSTAMT,0) AS IGSTAMTBOOKS, ISNULL(GSTR2BILLS.GRANDTOTAL,0) AS GRANDTOTALBOOKS, ISNULL(GSTR2B2B.TAXABLEAMT,0) AS TAXABLEAMTPORTAL, ISNULL(GSTR2B2B.CGSTAMT,0) AS CGSTAMTPORTAL, ISNULL(GSTR2B2B.SGSTAMT,0) AS SGSTAMTPORTAL, ISNULL(GSTR2B2B.IGSTAMT,0) AS IGSTAMTPORTAL, ISNULL(GSTR2B2B.GRANDTOTAL,0) AS GRANDTOTALPORTAL , COALESCE( GSTR2B2B.YEARID, GSTR2BILLS.YEARID) AS YEARID FROM GSTR2B2B FULL OUTER JOIN (SELECT * FROM GSTR2BILLS WHERE [TYPE] IN ('PURCHASE', 'NONPURCHASE')) AS GSTR2BILLS ON GSTR2B2B.YEARID = GSTR2BILLS.YEARID AND GSTR2B2B.INVNO = GSTR2BILLS.PARTYBILLNO AND GSTR2B2B.GSTIN = GSTR2BILLS.GSTIN UNION ALL SELECT ISNULL(GSTR2BILLS.BILLNO,0) AS BILLNO, ISNULL(GSTR2BILLS.TYPE,'') AS TYPE, COALESCE (GSTR2CNDN.MONTH, UPPER(DATENAME(M, GSTR2BILLS.PARTYBILLDATE))) AS [MONTH], COALESCE(GSTR2CNDN.GSTIN,  GSTR2BILLS.GSTIN) AS GSTIN, (CASE WHEN ISNULL(GSTR2CNDN.NAME,'') <> '' THEN ISNULL(GSTR2CNDN.NAME,'') ELSE GSTR2BILLS.NAME END) AS NAME, ISNULL(GSTR2BILLS.PARTYBILLNO,'') AS INVNOBOOKS, COALESCE(GSTR2BILLS.PARTYBILLDATE,GSTR2CNDN.INVDATE) AS INVDATEBOOKS, ISNULL(GSTR2CNDN.INVNO,'') AS INVNOPORTAL, COALESCE(GSTR2CNDN.INVDATE, GSTR2BILLS.PARTYBILLDATE) AS INVDATEPORTAL, ISNULL(GSTR2BILLS.TAXABLEAMT,0) AS TAXABLEAMTBOOKS, ISNULL(GSTR2BILLS.CGSTAMT,0) AS CGSTAMTBOOKS, ISNULL(GSTR2BILLS.SGSTAMT,0) AS SGSTAMTBOOKS, ISNULL(GSTR2BILLS.IGSTAMT,0) AS IGSTAMTBOOKS, ISNULL(GSTR2BILLS.GRANDTOTAL,0) AS GRANDTOTALBOOKS, ISNULL(GSTR2CNDN.TAXABLEAMT,0) AS TAXABLEAMTPORTAL, ISNULL(GSTR2CNDN.CGSTAMT,0) AS CGSTAMTPORTAL, ISNULL(GSTR2CNDN.SGSTAMT,0) AS SGSTAMTPORTAL, ISNULL(GSTR2CNDN.IGSTAMT,0) AS IGSTAMTPORTAL, ISNULL(GSTR2CNDN.GRANDTOTAL,0) AS GRANDTOTALPORTAL, COALESCE( GSTR2CNDN.YEARID, GSTR2BILLS.YEARID) AS YEARID FROM GSTR2CNDN FULL OUTER JOIN (SELECT * FROM GSTR2BILLS WHERE [TYPE] IN ('CREDITNOTE', 'DEBITNOTE', 'PURCHASERETURN')) AS GSTR2BILLS ON GSTR2CNDN.YEARID = GSTR2BILLS.YEARID AND GSTR2CNDN.INVNO = GSTR2BILLS.PARTYBILLNO AND GSTR2CNDN.GSTIN = GSTR2BILLS.GSTIN ) AS T", " AND T.YEARID = " & YearId & " AND T.INVDATEBOOKS <= '" & Format(DTTILLDATE.Value.Date, "MM/dd/yyyy") & "'" & " AND NOT EXISTS (SELECT * FROM PURCHASEITCENTRY_DESC AS P WHERE ISNULL(T.BILLNO,0) = ISNULL(P.PURITC_BILLNO,0) AND T.GSTIN = P.PURITC_GSTIN AND T.YEARID = P.PURITC_YEARID AND ISNULL(T.INVNOPORTAL,'') = ISNULL(P.PURITC_INVOICENOPORTAL,'')) ORDER BY T.GSTIN,T.INVDATEBOOKS ")
            Dim dt As DataTable = OBJCMN.SEARCH(" *, (CASE WHEN T.INVNOBOOKS = '' THEN 'ONLY IN PORTAL' ELSE (CASE WHEN T.INVNOPORTAL = '' THEN 'ONLY IN BOOKS' ELSE (CASE WHEN (T.TAXABLEAMTBOOKS - T.TAXABLEAMTPORTAL) <> 0 THEN 'VALUE MISMATCH' ELSE 'EXACT MATCH' END) END)END) AS RECOSTATUS ", "", "(SELECT ISNULL(GSTR2BILLS.BILLNO,0) AS BILLNO, ISNULL(GSTR2BILLS.TYPE,'') AS TYPE, COALESCE (GSTR2B2B.MONTH, UPPER(DATENAME(M, GSTR2BILLS.PARTYBILLDATE))) AS [MONTH], COALESCE(GSTR2B2B.GSTIN,  GSTR2BILLS.GSTIN) AS GSTIN, (CASE WHEN ISNULL(GSTR2B2B.NAME,'') <> '' THEN ISNULL(GSTR2B2B.NAME,'') ELSE GSTR2BILLS.NAME END) AS NAME, ISNULL(GSTR2BILLS.PARTYBILLNO,'') AS INVNOBOOKS, COALESCE(GSTR2BILLS.PARTYBILLDATE,GSTR2B2B.INVDATE) AS INVDATEBOOKS, ISNULL(GSTR2B2B.INVNO,'') AS INVNOPORTAL,  COALESCE(GSTR2B2B.INVDATE, GSTR2BILLS.PARTYBILLDATE) AS INVDATEPORTAL,  ISNULL(GSTR2BILLS.TAXABLEAMT,0) AS TAXABLEAMTBOOKS, ISNULL(GSTR2BILLS.CGSTAMT,0) AS CGSTAMTBOOKS, ISNULL(GSTR2BILLS.SGSTAMT,0) AS SGSTAMTBOOKS, ISNULL(GSTR2BILLS.IGSTAMT,0) AS IGSTAMTBOOKS, ISNULL(GSTR2BILLS.GRANDTOTAL,0) AS GRANDTOTALBOOKS, ISNULL(GSTR2B2B.TAXABLEAMT,0) AS TAXABLEAMTPORTAL, ISNULL(GSTR2B2B.CGSTAMT,0) AS CGSTAMTPORTAL, ISNULL(GSTR2B2B.SGSTAMT,0) AS SGSTAMTPORTAL, ISNULL(GSTR2B2B.IGSTAMT,0) AS IGSTAMTPORTAL, ISNULL(GSTR2B2B.GRANDTOTAL,0) AS GRANDTOTALPORTAL , COALESCE( GSTR2B2B.YEARID, GSTR2BILLS.YEARID) AS YEARID FROM GSTR2B2B FULL OUTER JOIN (SELECT * FROM GSTR2BILLS WHERE [TYPE] IN ('PURCHASE', 'NONPURCHASE')) AS GSTR2BILLS ON GSTR2B2B.YEARID = GSTR2BILLS.YEARID AND GSTR2B2B.INVNO = GSTR2BILLS.PARTYBILLNO AND GSTR2B2B.GSTIN = GSTR2BILLS.GSTIN UNION ALL SELECT ISNULL(GSTR2BILLS.BILLNO,0) AS BILLNO, ISNULL(GSTR2BILLS.TYPE,'') AS TYPE, COALESCE (GSTR2CNDN.MONTH, UPPER(DATENAME(M, GSTR2BILLS.PARTYBILLDATE))) AS [MONTH], COALESCE(GSTR2CNDN.GSTIN,  GSTR2BILLS.GSTIN) AS GSTIN, (CASE WHEN ISNULL(GSTR2CNDN.NAME,'') <> '' THEN ISNULL(GSTR2CNDN.NAME,'') ELSE GSTR2BILLS.NAME END) AS NAME, ISNULL(GSTR2BILLS.PARTYBILLNO,'') AS INVNOBOOKS, COALESCE(GSTR2BILLS.PARTYBILLDATE,GSTR2CNDN.INVDATE) AS INVDATEBOOKS, ISNULL(GSTR2CNDN.INVNO,'') AS INVNOPORTAL, COALESCE(GSTR2CNDN.INVDATE, GSTR2BILLS.PARTYBILLDATE) AS INVDATEPORTAL, ISNULL(GSTR2BILLS.TAXABLEAMT,0) AS TAXABLEAMTBOOKS, ISNULL(GSTR2BILLS.CGSTAMT,0) AS CGSTAMTBOOKS, ISNULL(GSTR2BILLS.SGSTAMT,0) AS SGSTAMTBOOKS, ISNULL(GSTR2BILLS.IGSTAMT,0) AS IGSTAMTBOOKS, ISNULL(GSTR2BILLS.GRANDTOTAL,0) AS GRANDTOTALBOOKS, ISNULL(GSTR2CNDN.TAXABLEAMT,0) AS TAXABLEAMTPORTAL, ISNULL(GSTR2CNDN.CGSTAMT,0) AS CGSTAMTPORTAL, ISNULL(GSTR2CNDN.SGSTAMT,0) AS SGSTAMTPORTAL, ISNULL(GSTR2CNDN.IGSTAMT,0) AS IGSTAMTPORTAL, ISNULL(GSTR2CNDN.GRANDTOTAL,0) AS GRANDTOTALPORTAL, COALESCE( GSTR2CNDN.YEARID, GSTR2BILLS.YEARID) AS YEARID FROM GSTR2CNDN FULL OUTER JOIN (SELECT * FROM GSTR2BILLS WHERE [TYPE] IN ('CREDITNOTE', 'DEBITNOTE', 'PURCHASERETURN')) AS GSTR2BILLS ON GSTR2CNDN.YEARID = GSTR2BILLS.YEARID AND GSTR2CNDN.INVNO = GSTR2BILLS.PARTYBILLNO AND GSTR2CNDN.GSTIN = GSTR2BILLS.GSTIN) AS T", " AND T.YEARID = " & YearId & " AND T.INVDATEBOOKS <= '" & Format(DTTILLDATE.Value.Date, "MM/dd/yyyy") & "'" & " AND NOT EXISTS (SELECT * FROM PURCHASEITCENTRY_DESC AS P WHERE ISNULL(T.BILLNO,0) = ISNULL(P.PURITC_BILLNO,0) AND T.GSTIN = P.PURITC_GSTIN AND T.YEARID = P.PURITC_YEARID AND ISNULL(T.INVNOPORTAL,'') = ISNULL(P.PURITC_INVOICENOPORTAL,'')) ORDER BY T.GSTIN,T.INVDATEBOOKS ")
            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_RowStyle(ByVal sender As Object, ByVal e As DevExpress.XtraGrid.Views.Grid.RowStyleEventArgs) Handles gridbill.RowStyle
        Try
            If e.RowHandle >= 0 Then
                Dim View As GridView = sender
                If View.GetRowCellDisplayText(e.RowHandle, View.Columns("RECOSTATUS")) = "ONLY IN BOOKS" Then
                    e.Appearance.BackColor = Color.Yellow
                ElseIf View.GetRowCellDisplayText(e.RowHandle, View.Columns("RECOSTATUS")) = "ONLY IN PORTAL" Then
                    e.Appearance.BackColor = Color.LightGreen
                ElseIf View.GetRowCellDisplayText(e.RowHandle, View.Columns("RECOSTATUS")) = "VALUE MISMATCH" Then
                    e.Appearance.BackColor = Color.LightBlue
                ElseIf View.GetRowCellDisplayText(e.RowHandle, View.Columns("RECOSTATUS")) = "EXACT MATCH" Then
                    e.Appearance.BackColor = Color.White
                End If
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CMDREFRESH_Click(sender As Object, e As EventArgs) Handles CMDREFRESH.Click
        Try
            FILLGRID()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdexit_Click(sender As Object, e As EventArgs) Handles cmdexit.Click
        Try
            Me.Close()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CMDOK_Click(sender As Object, e As EventArgs) Handles CMDOK.Click
        Try
            DT.Columns.Add("BILLNO")
            DT.Columns.Add("TYPE")
            DT.Columns.Add("GSTIN")
            DT.Columns.Add("NAME")
            DT.Columns.Add("INVNOBOOKS")
            DT.Columns.Add("INVDATEBOOKS")
            DT.Columns.Add("INVNOPORTAL")
            DT.Columns.Add("INVDATEPORTAL")
            DT.Columns.Add("TAXABLEAMTBOOKS")
            DT.Columns.Add("CGSTAMTBOOKS")
            DT.Columns.Add("SGSTAMTBOOKS")
            DT.Columns.Add("IGSTAMTBOOKS")
            DT.Columns.Add("GRANDTOTALBOOKS")
            DT.Columns.Add("TAXABLEAMTPORTAL")
            DT.Columns.Add("CGSTAMTPORTAL")
            DT.Columns.Add("SGSTAMTPORTAL")
            DT.Columns.Add("IGSTAMTPORTAL")
            DT.Columns.Add("GRANDTOTALPORTAL")
            DT.Columns.Add("GSTRATE")
            DT.Columns.Add("GRIDREMARKS")
            DT.Columns.Add("ITCRECD")
            DT.Columns.Add("ITCREVERSED")

            Dim SELECTEDROWS As Int32() = gridbill.GetSelectedRows()
            For I As Integer = 0 To Val(SELECTEDROWS.Length - 1)
                Dim dtrow As DataRow = gridbill.GetDataRow(SELECTEDROWS(I))
                DT.Rows.Add(dtrow("BILLNO"), dtrow("TYPE"), dtrow("GSTIN"), dtrow("NAME"), dtrow("INVNOBOOKS"), dtrow("INVDATEBOOKS"), dtrow("INVNOPORTAL"), dtrow("INVDATEPORTAL"), Val(dtrow("TAXABLEAMTBOOKS")), Val(dtrow("CGSTAMTBOOKS")), Val(dtrow("SGSTAMTBOOKS")), Val(dtrow("IGSTAMTBOOKS")), Val(dtrow("GRANDTOTALBOOKS")), Val(dtrow("TAXABLEAMTPORTAL")), Val(dtrow("CGSTAMTPORTAL")), Val(dtrow("SGSTAMTPORTAL")), Val(dtrow("IGSTAMTPORTAL")), Val(dtrow("GRANDTOTALPORTAL")), 0, "", False, False)
            Next
            Me.Close()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CMDEXPORT_Click(sender As Object, e As EventArgs) Handles CMDEXPORT.Click
        Try
            Dim PATH As String = Application.StartupPath & "\Purchase ITC Details.XLS"
            Dim opti As New DevExpress.XtraPrinting.XlsExportOptions
            opti.ShowGridLines = True
            opti.SheetName = "Purchase ITC Details"
            gridbill.ExportToXls(PATH, opti)
            EXCELCMPHEADER(PATH, "Purchase ITC Details", gridbill.VisibleColumns.Count + gridbill.GroupCount)
        Catch ex As Exception
            MsgBox("Purchase ITC Details Excel File is Open, Please Close the File first then try to Export", MsgBoxStyle.Critical)
        End Try
    End Sub
End Class