SELECT        LEDGERS.Acc_cmpname AS NAME, GROUPMASTER.group_name AS GROUPNAME, GROUPMASTER.group_secondary AS SECONDARY, ISNULL(CITYMASTER.CITY_NAME,'') AS CITYNAME, ISNULL(AGENTLEDGERS.Acc_cmpname,'') AS AGENTNAME, 
                         REGISTERMASTER.register_name AS REGISTER, INVOICEMASTER.INVOICE_SUBTOTAL AS TAXABLEAMT, INVOICEMASTER.INVOICE_NO AS INVOICENO, INVOICEMASTER.INVOICE_INITIALS AS INVOICEINITIALS, 
                         INVOICEMASTER.INVOICE_DATE AS DATE, INVDESC.ITEMNAME, INVDESC.CATEGORY, INVOICE_TOTALPCS AS TOTALPCS, INVOICE_TOTALMTRS AS TOTALMTRS, UPPER(DATENAME(MONTH,INVOICE_DATE)) AS [MONTHNAME]
FROM            INVOICEMASTER INNER JOIN
                         LEDGERS ON INVOICEMASTER.INVOICE_LEDGERID = LEDGERS.Acc_id INNER JOIN
                         REGISTERMASTER ON INVOICEMASTER.INVOICE_REGISTERID = REGISTERMASTER.register_id INNER JOIN
                         GROUPMASTER ON LEDGERS.Acc_groupid = GROUPMASTER.group_id LEFT OUTER JOIN
                         LEDGERS AS AGENTLEDGERS ON INVOICEMASTER.INVOICE_AGENTID = AGENTLEDGERS.Acc_id LEFT OUTER JOIN
						 CITYMASTER ON LEDGERS.ACC_CITYID = CITYMASTER.CITY_ID CROSS APPLY
						 (SELECT TOP 1 ITEMMASTER.ITEM_NAME AS ITEMNAME, ISNULL(CATEGORY_NAME,'') AS CATEGORY FROM INVOICEMASTER_DESC INNER JOIN ITEMMASTER ON INVOICEMASTER_DESC.INVOICE_ITEMID = ITEMMASTER.ITEM_ID LEFT OUTER JOIN
						 CATEGORYMASTER ON ITEMMASTER.item_categoryid = CATEGORY_ID
						 WHERE        INVOICEMASTER_DESC.INVOICE_NO = INVOICEMASTER.INVOICE_NO AND INVOICEMASTER_DESC.INVOICE_REGISTERID = INVOICEMASTER.INVOICE_REGISTERID AND 
                                                         INVOICEMASTER_DESC.INVOICE_YEARID = INVOICEMASTER.INVOICE_YEARID ) AS INVDESC 