SELECT  NAME, ISNULL(APRIL,2) AS APR, ISNULL(MAY,0) AS MAY, ISNULL(JUNE,0) AS JUN, ISNULL(JULY,0) AS JUL, ISNULL(AUGUST,0) AS AUG, ISNULL(SEPTEMBER,0) AS SEP, ISNULL(OCTOBER,0) AS OCT, ISNULL(NOVEMBER,0) AS NOV, ISNULL(DECEMBER,0) AS DEC, ISNULL(JANUARY,0) AS JAN, ISNULL(FEBRUARY,0) AS FEB, ISNULL(MARCH,0) AS MAR, ROUND((ISNULL(APRIL,0) + ISNULL(MAY,0)+ ISNULL(JUNE,0)+ISNULL(JULY,0)+ISNULL(AUGUST,0)+ISNULL(SEPTEMBER,0)+ISNULL(OCTOBER,0)+ISNULL(NOVEMBER,0)+ISNULL(DECEMBER,0)+ISNULL(JANUARY,0)+ISNULL(FEBRUARY,0)+ISNULL(MARCH,0)),2) AS TOTALMTRS 
FROM
 (
 SELECT LEDGERS.Acc_cmpname AS NAME, UPPER(DATENAME(MONTH,INVOICE_DATE)) AS [MONTHNAME] , INVOICE_TOTALMTRS AS TOTALMTRS 
 FROM INVOICEMASTER INNER JOIN LEDGERS ON INVOICEMASTER.INVOICE_LEDGERID = LEDGERS.Acc_id INNER JOIN REGISTERMASTER ON INVOICEMASTER.INVOICE_REGISTERID = REGISTERMASTER.register_id INNER JOIN GROUPMASTER ON LEDGERS.Acc_groupid = GROUPMASTER.group_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON INVOICEMASTER.INVOICE_AGENTID = AGENTLEDGERS.Acc_id LEFT OUTER JOIN CITYMASTER ON LEDGERS.ACC_CITYID = CITYMASTER.CITY_ID CROSS APPLY (SELECT TOP 1 ITEMMASTER.ITEM_NAME AS ITEMNAME, ISNULL(CATEGORY_NAME,'') AS CATEGORY FROM INVOICEMASTER_DESC INNER JOIN ITEMMASTER ON INVOICEMASTER_DESC.INVOICE_ITEMID = ITEMMASTER.ITEM_ID LEFT OUTER JOIN CATEGORYMASTER ON ITEMMASTER.item_categoryid = CATEGORY_ID WHERE INVOICEMASTER_DESC.INVOICE_NO = INVOICEMASTER.INVOICE_NO AND INVOICEMASTER_DESC.INVOICE_REGISTERID = INVOICEMASTER.INVOICE_REGISTERID AND INVOICEMASTER_DESC.INVOICE_YEARID = INVOICEMASTER.INVOICE_YEARID ) AS INVDESC 
 WHERE 1=1  AND INVOICEMASTER.INVOICE_YEARID = 2 
 UNION ALL 
 SELECT 'PARTY TOTAL' AS CATEGORY, UPPER(DATENAME(MONTH,INVOICE_DATE)) AS [MONTHNAME], ROUND(SUM(INVOICEMASTER.INVOICE_TOTALMTRS) ,2)AS TOTALMTRS 
 FROM INVOICEMASTER WHERE 1=1  AND INVOICEMASTER.INVOICE_YEARID = 2 
 GROUP BY UPPER(DATENAME(MONTH,INVOICE_DATE))) AS INVOICEDATA PIVOT (SUM(TOTALMTRS) FOR  [MONTHNAME] IN (APRIL, MAY, JUNE, JULY, AUGUST, SEPTEMBER, OCTOBER, NOVEMBER, DECEMBER, JANUARY, FEBRUARY, MARCH)) AS PIV ORDER BY CASE NAME WHEN '' THEN 0 WHEN 'PARTY TOTAL' THEN 2 ELSE 1 END 


