Imports BL
Imports System.Windows.Forms
Imports DevExpress.XtraGrid.Views.Grid

Public Class AgencySaleOrderClose


    Dim USERADD, USEREDIT, USERVIEW, USERDELETE As Boolean      'USED FOR RIGHT MANAGEMAENT

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub AgencySaleOrderClose_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode = Windows.Forms.Keys.Escape Then
                Me.Close()
            ElseIf e.KeyCode = Keys.Space And e.Control = True Then
                'SELECT ALL DATA
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    dtrow("CLOSED") = Not Convert.ToBoolean(dtrow("CLOSED"))
                Next
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub AgencySaleOrderClose_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            Dim DTROW() As DataRow
            DTROW = USERRIGHTS.Select("FormName = 'SALE ORDER'")
            USERADD = DTROW(0).Item(1)
            USEREDIT = DTROW(0).Item(2)
            USERVIEW = DTROW(0).Item(3)
            USERDELETE = DTROW(0).Item(4)

            If USEREDIT = False And USERVIEW = False Then
                MsgBox("Insufficient Rights")
                Exit Sub
            End If

            'GET REASON
            Dim OBJCMN As New ClsCommon
            Dim DT As DataTable = OBJCMN.SEARCH("ISNULL(REASON_NAME,'') AS REASON", "", "REASONMASTER", " AND REASON_YEARID = " & YearId)
            For Each ROW As DataRow In DT.Rows
                CMBREASON.Items.Add(ROW("REASON"))
                CMBMAINREASON.Items.Add(ROW("REASON"))
            Next


            FILLGRID()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLGRID()
        Try
            Dim OBJCMN As New ClsCommonMaster
            Dim dt As New DataTable
            If RBPENDING.Checked = True Then

                Dim TEMPCONDITION As String = " WHERE YEARID = " & YearId
                Dim DTUNIT As DataTable = OBJCMN.search("UNIT_ABBR", "", "DEFAULTSTOCKUNIT", "")
                If DTUNIT.Rows.Count > 0 Then TEMPCONDITION = TEMPCONDITION & " AND UNIT IN (SELECT UNIT_ABBR FROM DEFAULTSTOCKUNIT)"

                If SALEORDERONMTRS = True Then
                    dt = OBJCMN.search("T.*, '' AS CLOSEDDATE, '' AS REASON, ISNULL(SUM(BARCODESTOCK.MTRS),0) AS STOCKMTRS, ISNULL(SUM(BARCODESTOCK.PCS),0) AS STOCKPCS", "", " (SELECT AGENCYSALEORDER.ASO_no AS SONO, AGENCYSALEORDER_DESC.ASO_GRIDSRNO AS GRIDSRNO, AGENCYSALEORDER.ASO_date AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.Acc_cmpname,'') AS AGENTNAME, ISNULL(DISPATCHLEDGERS.Acc_cmpname,'') AS DISPATCHTO, AGENCYSALEORDER.ASO_pono AS PARTYPONO, AGENCYSALEORDER.ASO_DUEDATE AS DELDATE, ITEMMASTER.item_name AS ITEMNAME, ISNULL(DESIGNMASTER.DESIGN_NO,'') AS DESIGNNO, ISNULL(COLORMASTER.COLOR_name,'') AS COLOR, ISNULL(AGENCYSALEORDER_DESC.ASO_PARTYPONO,'') AS GRIDPARTYPONO, AGENCYSALEORDER_DESC.ASO_QTY AS PCS, AGENCYSALEORDER_DESC.ASO_CUT AS CUT, AGENCYSALEORDER_DESC.ASO_MTRS AS MTRS, AGENCYSALEORDER_DESC.ASO_RATE AS RATE, AGENCYSALEORDER_DESC.ASO_RECDQTY AS OUTPCS, AGENCYSALEORDER_DESC.ASO_RECDMTRS AS OUTMTRS, (AGENCYSALEORDER_DESC.ASO_QTY - AGENCYSALEORDER_DESC.ASO_RECDQTY) AS BALPCS, ISNULL((AGENCYSALEORDER_DESC.ASO_MTRS - AGENCYSALEORDER_DESC.ASO_RECDMTRS),0) AS BALMTRS, ASO_REMARKS AS REMARKS, ISNULL(ASO_CLOSED,0) AS CLOSED ,ISNULL(CITYMASTER.city_name, '') AS CITY, ISNULL(QUALITYMASTER.QUALITY_name, '') AS QUALITY, 'AGENCYSALEORDER' AS TYPE, ISNULL(ASO_FORWARD,'') AS FORWARD, (ROUND((ISNULL((AGENCYSALEORDER_DESC.ASO_MTRS - AGENCYSALEORDER_DESC.ASO_RECDMTRS),0)/AGENCYSALEORDER_DESC.ASO_MTRS)*100,2)) AS BALPER, AGENCYSALEORDER.ASO_YEARID AS YEARID , ISNULL(AGENCYSALEORDER.ASO_REFNO,'') AS REFNO  FROM AGENCYSALEORDER_DESC INNER JOIN AGENCYSALEORDER ON AGENCYSALEORDER_DESC.ASO_NO = AGENCYSALEORDER.ASO_no AND AGENCYSALEORDER_DESC.ASO_YEARID = AGENCYSALEORDER.ASO_YEARID INNER JOIN LEDGERS ON AGENCYSALEORDER.ASO_ledgerid = LEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS DISPATCHLEDGERS ON AGENCYSALEORDER.ASO_PACKINGID = DISPATCHLEDGERS.ACC_ID INNER JOIN ITEMMASTER ON AGENCYSALEORDER_DESC.ASO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN COLORMASTER ON AGENCYSALEORDER_DESC.ASO_COLORID = COLORMASTER.COLOR_id LEFT OUTER JOIN DESIGNMASTER ON AGENCYSALEORDER_DESC.ASO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON AGENCYSALEORDER.ASO_Agentid = AGENTLEDGERS.Acc_id LEFT OUTER JOIN QUALITYMASTER ON AGENCYSALEORDER_DESC.ASO_QUALITYID = QUALITYMASTER.QUALITY_id LEFT OUTER JOIN CITYMASTER ON LEDGERS.Acc_cityid = CITYMASTER.city_id WHERE AGENCYSALEORDER_DESC.ASO_CLOSED = 'FALSE' and (AGENCYSALEORDER_DESC.ASO_MTRS-AGENCYSALEORDER_DESC.ASO_RECDMTRS)>0 AND dbo.AGENCYSALEORDER.ASO_yearid=" & YearId & " UNION ALL  SELECT OPENINGAGENCYSALEORDER.OPASO_no AS SONO, OPENINGAGENCYSALEORDER_DESC.OPASO_GRIDSRNO AS GRIDSRNO, OPENINGAGENCYSALEORDER.OPASO_date AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.Acc_cmpname,'') AS AGENTNAME, ISNULL(DISPATCHLEDGERS.Acc_cmpname,'') AS DISPATCHTO, OPENINGAGENCYSALEORDER.OPASO_pono AS PARTYPONO, OPENINGAGENCYSALEORDER.OPASO_DUEDATE AS DELDATE, ITEMMASTER.item_name AS ITEMNAME, ISNULL(DESIGNMASTER.DESIGN_NO,'') AS DESIGNNO, ISNULL(COLORMASTER.COLOR_name,'') AS COLOR, ISNULL(OPENINGAGENCYSALEORDER_DESC.OPASO_PARTYPONO,'') AS GRIDPARTYPONO, OPENINGAGENCYSALEORDER_DESC.OPASO_QTY AS PCS, OPENINGAGENCYSALEORDER_DESC.OPASO_CUT AS CUT, OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS AS MTRS, OPENINGAGENCYSALEORDER_DESC.OPASO_RATE AS RATE, OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY AS OUTPCS, OPENINGAGENCYSALEORDER_DESC.OPASO_RECDMTRS AS OUTMTRS, (OPENINGAGENCYSALEORDER_DESC.OPASO_QTY - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY) AS BALPCS, ISNULL((OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDMTRS),0) AS BALMTRS, OPASO_REMARKS AS REMARKS, ISNULL(OPASO_CLOSED,0) AS CLOSED ,ISNULL(CITYMASTER.city_name, '') AS CITY, ISNULL(QUALITYMASTER.QUALITY_name, '') AS QUALITY, 'OPENING' AS TYPE, ISNULL(OPASO_FORWARD,'') AS FORWARD, (ROUND((ISNULL((OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDMTRS),0)/OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS)*100,2)) AS BALPER, OPENINGAGENCYSALEORDER.OPASO_YEARID AS YEARID , ISNULL(OPENINGAGENCYSALEORDER.OPASO_REFNO,'') AS REFNO FROM OPENINGAGENCYSALEORDER_DESC INNER JOIN OPENINGAGENCYSALEORDER ON OPENINGAGENCYSALEORDER_DESC.OPASO_NO = OPENINGAGENCYSALEORDER.OPASO_no AND OPENINGAGENCYSALEORDER_DESC.OPASO_YEARID = OPENINGAGENCYSALEORDER.OPASO_YEARID INNER JOIN LEDGERS ON OPENINGAGENCYSALEORDER.OPASO_ledgerid = LEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS DISPATCHLEDGERS ON OPENINGAGENCYSALEORDER.OPASO_PACKINGID = DISPATCHLEDGERS.ACC_ID  INNER JOIN ITEMMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN COLORMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_COLORID = COLORMASTER.COLOR_id LEFT OUTER JOIN DESIGNMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON OPENINGAGENCYSALEORDER.OPASO_Agentid = AGENTLEDGERS.Acc_id LEFT OUTER JOIN QUALITYMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_QUALITYID = QUALITYMASTER.QUALITY_id LEFT OUTER JOIN CITYMASTER ON LEDGERS.Acc_cityid = CITYMASTER.city_id WHERE OPENINGAGENCYSALEORDER_DESC.OPASO_CLOSED = 'FALSE' and (OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS-OPENINGAGENCYSALEORDER_DESC.OPASO_RECDMTRS)>0 AND dbo.OPENINGAGENCYSALEORDER.OPASO_yearid=" & YearId & ") AS T LEFT OUTER JOIN (SELECT * FROM BARCODESTOCK " & TEMPCONDITION & ") AS BARCODESTOCK ON T.ITEMNAME = BARCODESTOCK.ITEMNAME AND T.DESIGNNO = BARCODESTOCK.DESIGNNO AND T.COLOR = BARCODESTOCK.COLOR AND T.YEARID = BARCODESTOCK.YEARID ", " GROUP BY  T.SONO , T.REFNO ,T.GRIDSRNO, T.SODATE, T.NAME, T.AGENTNAME, T.DISPATCHTO, T.PARTYPONO, T.DELDATE, T.ITEMNAME, T.DESIGNNO, T.COLOR, T.GRIDPARTYPONO, T.PCS, T.CUT, T.MTRS, T.RATE, T.OUTPCS, T.OUTMTRS, T.BALPCS, T.BALMTRS, T.REMARKS, T.CLOSED, T.CITY, T.QUALITY, T.TYPE, T.FORWARD, T.BALPER, T.YEARID ORDER BY SONO, GRIDSRNO")
                Else
                    dt = OBJCMN.search("T.*, '' AS CLOSEDDATE, '' AS REASON, ISNULL(SUM(BARCODESTOCK.MTRS),0) AS STOCKMTRS, ISNULL(SUM(BARCODESTOCK.PCS),0) AS STOCKPCS", "", " (SELECT AGENCYSALEORDER.ASO_no AS SONO, AGENCYSALEORDER_DESC.ASO_GRIDSRNO AS GRIDSRNO, AGENCYSALEORDER.ASO_date AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.Acc_cmpname,'') AS AGENTNAME, ISNULL(DISPATCHLEDGERS.Acc_cmpname,'') AS DISPATCHTO, AGENCYSALEORDER.ASO_pono AS PARTYPONO, AGENCYSALEORDER.ASO_DUEDATE AS DELDATE, ITEMMASTER.item_name AS ITEMNAME, ISNULL(DESIGNMASTER.DESIGN_NO,'') AS DESIGNNO, ISNULL(COLORMASTER.COLOR_name,'') AS COLOR, ISNULL(AGENCYSALEORDER_DESC.ASO_PARTYPONO,'') AS GRIDPARTYPONO, AGENCYSALEORDER_DESC.ASO_QTY AS PCS, AGENCYSALEORDER_DESC.ASO_CUT AS CUT, AGENCYSALEORDER_DESC.ASO_MTRS AS MTRS, AGENCYSALEORDER_DESC.ASO_RATE AS RATE, AGENCYSALEORDER_DESC.ASO_RECDQTY AS OUTPCS, AGENCYSALEORDER_DESC.ASO_RECDMTRS AS OUTMTRS, (AGENCYSALEORDER_DESC.ASO_QTY - AGENCYSALEORDER_DESC.ASO_RECDQTY) AS BALPCS, ISNULL((AGENCYSALEORDER_DESC.ASO_MTRS - AGENCYSALEORDER_DESC.ASO_RECDMTRS),0) AS BALMTRS, ASO_REMARKS AS REMARKS, ISNULL(ASO_CLOSED,0) AS CLOSED ,ISNULL(CITYMASTER.city_name, '') AS CITY, ISNULL(QUALITYMASTER.QUALITY_name, '') AS QUALITY, 'AGENCYSALEORDER' AS TYPE, ISNULL(ASO_FORWARD,'') AS FORWARD, (ROUND((ISNULL((AGENCYSALEORDER_DESC.ASO_QTY - AGENCYSALEORDER_DESC.ASO_RECDQTY),0)/AGENCYSALEORDER_DESC.ASO_QTY)*100,2)) AS BALPER, AGENCYSALEORDER.ASO_YEARID AS YEARID , ISNULL(AGENCYSALEORDER.ASO_REFNO,'') AS REFNO FROM AGENCYSALEORDER_DESC INNER JOIN AGENCYSALEORDER ON AGENCYSALEORDER_DESC.ASO_NO = AGENCYSALEORDER.ASO_no AND AGENCYSALEORDER_DESC.ASO_YEARID = AGENCYSALEORDER.ASO_YEARID INNER JOIN LEDGERS ON AGENCYSALEORDER.ASO_ledgerid = LEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS DISPATCHLEDGERS ON AGENCYSALEORDER.ASO_PACKINGID = DISPATCHLEDGERS.ACC_ID INNER JOIN ITEMMASTER ON AGENCYSALEORDER_DESC.ASO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN COLORMASTER ON AGENCYSALEORDER_DESC.ASO_COLORID = COLORMASTER.COLOR_id LEFT OUTER JOIN DESIGNMASTER ON AGENCYSALEORDER_DESC.ASO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON AGENCYSALEORDER.ASO_Agentid = AGENTLEDGERS.Acc_id LEFT OUTER JOIN QUALITYMASTER ON AGENCYSALEORDER_DESC.ASO_QUALITYID = QUALITYMASTER.QUALITY_id LEFT OUTER JOIN CITYMASTER ON LEDGERS.Acc_cityid = CITYMASTER.city_id WHERE AGENCYSALEORDER_DESC.ASO_CLOSED = 'FALSE' and (AGENCYSALEORDER_DESC.ASO_QTY-AGENCYSALEORDER_DESC.ASO_RECDQTY)>0 AND dbo.AGENCYSALEORDER.ASO_yearid=" & YearId & " UNION ALL  SELECT OPENINGAGENCYSALEORDER.OPASO_no AS SONO, OPENINGAGENCYSALEORDER_DESC.OPASO_GRIDSRNO AS GRIDSRNO, OPENINGAGENCYSALEORDER.OPASO_date AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.Acc_cmpname,'') AS AGENTNAME, ISNULL(DISPATCHLEDGERS.Acc_cmpname,'') AS DISPATCHTO, OPENINGAGENCYSALEORDER.OPASO_pono AS PARTYPONO, OPENINGAGENCYSALEORDER.OPASO_DUEDATE AS DELDATE, ITEMMASTER.item_name AS ITEMNAME, ISNULL(DESIGNMASTER.DESIGN_NO,'') AS DESIGNNO, ISNULL(COLORMASTER.COLOR_name,'') AS COLOR, ISNULL(OPENINGAGENCYSALEORDER_DESC.OPASO_PARTYPONO,'') AS GRIDPARTYPONO, OPENINGAGENCYSALEORDER_DESC.OPASO_QTY AS PCS, OPENINGAGENCYSALEORDER_DESC.OPASO_CUT AS CUT, OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS AS MTRS, OPENINGAGENCYSALEORDER_DESC.OPASO_RATE AS RATE, OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY AS OUTPCS, OPENINGAGENCYSALEORDER_DESC.OPASO_RECDMTRS AS OUTMTRS, (OPENINGAGENCYSALEORDER_DESC.OPASO_QTY - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY) AS BALPCS, ISNULL((OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDMTRS),0) AS BALMTRS, OPASO_REMARKS AS REMARKS, ISNULL(OPASO_CLOSED,0) AS CLOSED ,ISNULL(CITYMASTER.city_name, '') AS CITY, ISNULL(QUALITYMASTER.QUALITY_name, '') AS QUALITY, 'OPENING' AS TYPE, ISNULL(OPASO_FORWARD,'') AS FORWARD, (ROUND((ISNULL((OPENINGAGENCYSALEORDER_DESC.OPASO_QTY - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY),0)/OPENINGAGENCYSALEORDER_DESC.OPASO_QTY)*100,2)) AS BALPER, OPENINGAGENCYSALEORDER.OPASO_YEARID AS YEARID , ISNULL(OPENINGAGENCYSALEORDER.OPASO_REFNO,'') AS REFNO FROM OPENINGAGENCYSALEORDER_DESC INNER JOIN OPENINGAGENCYSALEORDER ON OPENINGAGENCYSALEORDER_DESC.OPASO_NO = OPENINGAGENCYSALEORDER.OPASO_no AND OPENINGAGENCYSALEORDER_DESC.OPASO_YEARID = OPENINGAGENCYSALEORDER.OPASO_YEARID INNER JOIN LEDGERS ON OPENINGAGENCYSALEORDER.OPASO_ledgerid = LEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS DISPATCHLEDGERS ON OPENINGAGENCYSALEORDER.OPASO_PACKINGID = DISPATCHLEDGERS.ACC_ID  INNER JOIN ITEMMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN COLORMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_COLORID = COLORMASTER.COLOR_id LEFT OUTER JOIN DESIGNMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON OPENINGAGENCYSALEORDER.OPASO_Agentid = AGENTLEDGERS.Acc_id LEFT OUTER JOIN QUALITYMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_QUALITYID = QUALITYMASTER.QUALITY_id LEFT OUTER JOIN CITYMASTER ON LEDGERS.Acc_cityid = CITYMASTER.city_id WHERE OPENINGAGENCYSALEORDER_DESC.OPASO_CLOSED = 'FALSE' and (OPENINGAGENCYSALEORDER_DESC.OPASO_QTY-OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY)>0 AND dbo.OPENINGAGENCYSALEORDER.OPASO_yearid=" & YearId & ") AS T LEFT OUTER JOIN (SELECT * FROM BARCODESTOCK " & TEMPCONDITION & ") AS BARCODESTOCK ON T.ITEMNAME = BARCODESTOCK.ITEMNAME AND T.DESIGNNO = BARCODESTOCK.DESIGNNO AND T.COLOR = BARCODESTOCK.COLOR AND T.YEARID = BARCODESTOCK.YEARID ", " GROUP BY  T.SONO, T.REFNO , T.GRIDSRNO, T.SODATE, T.NAME, T.AGENTNAME, T.DISPATCHTO, T.PARTYPONO, T.DELDATE, T.ITEMNAME, T.DESIGNNO, T.COLOR, T.GRIDPARTYPONO, T.PCS, T.CUT, T.MTRS, T.RATE, T.OUTPCS, T.OUTMTRS, T.BALPCS, T.BALMTRS, T.REMARKS, T.CLOSED, T.CITY, T.QUALITY, T.TYPE, T.FORWARD, T.BALPER, T.YEARID ORDER BY SONO, GRIDSRNO")
                End If
            Else
                If SALEORDERONMTRS = True Then
                    dt = OBJCMN.search("*", "", " (SELECT AGENCYSALEORDER.ASO_no AS SONO, AGENCYSALEORDER_DESC.ASO_GRIDSRNO AS GRIDSRNO, AGENCYSALEORDER.ASO_date AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.Acc_cmpname,'') AS AGENTNAME, ISNULL(DISPATCHLEDGERS.Acc_cmpname,'') AS DISPATCHTO, AGENCYSALEORDER.ASO_pono AS PARTYPONO, AGENCYSALEORDER.ASO_DUEDATE AS DELDATE, ITEMMASTER.item_name AS ITEMNAME, ISNULL(DESIGNMASTER.DESIGN_NO,'') AS DESIGNNO, ISNULL(COLORMASTER.COLOR_name,'') AS COLOR, ISNULL(AGENCYSALEORDER_DESC.ASO_PARTYPONO,'') AS GRIDPARTYPONO, AGENCYSALEORDER_DESC.ASO_QTY AS PCS, AGENCYSALEORDER_DESC.ASO_CUT AS CUT, AGENCYSALEORDER_DESC.ASO_MTRS AS MTRS, AGENCYSALEORDER_DESC.ASO_RATE AS RATE, AGENCYSALEORDER_DESC.ASO_RECDQTY AS OUTPCS, AGENCYSALEORDER_DESC.ASO_RECDMTRS AS OUTMTRS, (AGENCYSALEORDER_DESC.ASO_QTY - AGENCYSALEORDER_DESC.ASO_RECDQTY) AS BALPCS, ISNULL((AGENCYSALEORDER_DESC.ASO_MTRS - AGENCYSALEORDER_DESC.ASO_RECDMTRS),0) AS BALMTRS, ASO_REMARKS AS REMARKS, cast(0 as BIT) AS CLOSED ,ISNULL(CITYMASTER.city_name, '') AS CITY, ISNULL(QUALITYMASTER.QUALITY_name, '') AS QUALITY, 'AGENCYSALEORDER' AS TYPE, ISNULL(ASO_FORWARD,'') AS FORWARD, (ROUND((ISNULL((AGENCYSALEORDER_DESC.ASO_MTRS - AGENCYSALEORDER_DESC.ASO_RECDMTRS),0)/AGENCYSALEORDER_DESC.ASO_MTRS)*100,2)) AS BALPER , ISNULL(AGENCYSALEORDER.ASO_REFNO,'') AS REFNO, ISNULL(AGENCYSALEORDER_DESC.ASO_CLOSEDDATE,'') AS CLOSEDDATE, ISNULL(AGENCYSALEORDER_DESC.ASO_CLOSEDREASON,'') AS REASON FROM AGENCYSALEORDER_DESC INNER JOIN AGENCYSALEORDER ON AGENCYSALEORDER_DESC.ASO_NO = AGENCYSALEORDER.ASO_no AND AGENCYSALEORDER_DESC.ASO_YEARID = AGENCYSALEORDER.ASO_YEARID INNER JOIN LEDGERS ON AGENCYSALEORDER.ASO_ledgerid = LEDGERS.Acc_id  LEFT OUTER JOIN LEDGERS AS DISPATCHLEDGERS ON AGENCYSALEORDER.ASO_PACKINGID = DISPATCHLEDGERS.ACC_ID INNER JOIN ITEMMASTER ON AGENCYSALEORDER_DESC.ASO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN COLORMASTER ON AGENCYSALEORDER_DESC.ASO_COLORID = COLORMASTER.COLOR_id LEFT OUTER JOIN DESIGNMASTER ON AGENCYSALEORDER_DESC.ASO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON AGENCYSALEORDER.ASO_Agentid = AGENTLEDGERS.Acc_id LEFT OUTER JOIN QUALITYMASTER ON AGENCYSALEORDER_DESC.ASO_QUALITYID = QUALITYMASTER.QUALITY_id LEFT OUTER JOIN CITYMASTER ON LEDGERS.Acc_cityid = CITYMASTER.city_id WHERE AGENCYSALEORDER_DESC.ASO_CLOSED = 'TRUE' and (AGENCYSALEORDER_DESC.ASO_MTRS-AGENCYSALEORDER_DESC.ASO_RECDMTRS)>0 AND dbo.AGENCYSALEORDER.ASO_yearid=" & YearId & " UNION ALL  SELECT OPENINGAGENCYSALEORDER.OPASO_no AS SONO, OPENINGAGENCYSALEORDER_DESC.OPASO_GRIDSRNO AS GRIDSRNO, OPENINGAGENCYSALEORDER.OPASO_date AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.Acc_cmpname,'') AS AGENTNAME, ISNULL(DISPATCHLEDGERS.Acc_cmpname,'') AS DISPATCHTO, OPENINGAGENCYSALEORDER.OPASO_pono AS PARTYPONO, OPENINGAGENCYSALEORDER.OPASO_DUEDATE AS DELDATE, ITEMMASTER.item_name AS ITEMNAME, ISNULL(DESIGNMASTER.DESIGN_NO,'') AS DESIGNNO, ISNULL(COLORMASTER.COLOR_name,'') AS COLOR, ISNULL(OPENINGAGENCYSALEORDER_DESC.OPASO_PARTYPONO,'') AS GRIDPARTYPONO, OPENINGAGENCYSALEORDER_DESC.OPASO_QTY AS PCS, OPENINGAGENCYSALEORDER_DESC.OPASO_CUT AS CUT, OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS AS MTRS, OPENINGAGENCYSALEORDER_DESC.OPASO_RATE AS RATE, OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY AS OUTPCS, OPENINGAGENCYSALEORDER_DESC.OPASO_RECDMTRS AS OUTMTRS, (OPENINGAGENCYSALEORDER_DESC.OPASO_QTY - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY) AS BALPCS, ISNULL((OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDMTRS),0) AS BALMTRS, OPASO_REMARKS AS REMARKS, cast(0 as BIT) AS CLOSED ,ISNULL(CITYMASTER.city_name, '') AS CITY, ISNULL(QUALITYMASTER.QUALITY_name, '') AS QUALITY, 'OPENING' AS TYPE, ISNULL(OPASO_FORWARD,'') AS FORWARD, (ROUND((ISNULL((OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDMTRS),0)/OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS)*100,2)) AS BALPER , ISNULL(OPENINGAGENCYSALEORDER.OPASO_REFNO,'') AS REFNO, ISNULL(OPENINGAGENCYSALEORDER_DESC.OPASO_CLOSEDDATE,'') AS CLOSEDDATE, ISNULL(OPENINGAGENCYSALEORDER_DESC.OPASO_CLOSEDREASON,'') AS REASON FROM OPENINGAGENCYSALEORDER_DESC INNER JOIN OPENINGAGENCYSALEORDER ON OPENINGAGENCYSALEORDER_DESC.OPASO_NO = OPENINGAGENCYSALEORDER.OPASO_no AND OPENINGAGENCYSALEORDER_DESC.OPASO_YEARID = OPENINGAGENCYSALEORDER.OPASO_YEARID INNER JOIN LEDGERS ON OPENINGAGENCYSALEORDER.OPASO_ledgerid = LEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS DISPATCHLEDGERS ON OPENINGAGENCYSALEORDER.OPASO_PACKINGID = DISPATCHLEDGERS.ACC_ID  INNER JOIN ITEMMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN COLORMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_COLORID = COLORMASTER.COLOR_id LEFT OUTER JOIN DESIGNMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON OPENINGAGENCYSALEORDER.OPASO_Agentid = AGENTLEDGERS.Acc_id LEFT OUTER JOIN QUALITYMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_QUALITYID = QUALITYMASTER.QUALITY_id LEFT OUTER JOIN CITYMASTER ON LEDGERS.Acc_cityid = CITYMASTER.city_id WHERE OPENINGAGENCYSALEORDER_DESC.OPASO_CLOSED = 'TRUE' and (OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS-OPENINGAGENCYSALEORDER_DESC.OPASO_RECDMTRS)>0 AND dbo.OPENINGAGENCYSALEORDER.OPASO_yearid=" & YearId & ") AS T", " ORDER BY SONO, GRIDSRNO")
                Else
                    dt = OBJCMN.search("*", "", " (SELECT AGENCYSALEORDER.ASO_no AS SONO, AGENCYSALEORDER_DESC.ASO_GRIDSRNO AS GRIDSRNO, AGENCYSALEORDER.ASO_date AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.Acc_cmpname,'') AS AGENTNAME, ISNULL(DISPATCHLEDGERS.Acc_cmpname,'') AS DISPATCHTO, AGENCYSALEORDER.ASO_pono AS PARTYPONO, AGENCYSALEORDER.ASO_DUEDATE AS DELDATE, ITEMMASTER.item_name AS ITEMNAME, ISNULL(DESIGNMASTER.DESIGN_NO,'') AS DESIGNNO, ISNULL(COLORMASTER.COLOR_name,'') AS COLOR, ISNULL(AGENCYSALEORDER_DESC.ASO_PARTYPONO,'') AS GRIDPARTYPONO, AGENCYSALEORDER_DESC.ASO_QTY AS PCS, AGENCYSALEORDER_DESC.ASO_CUT AS CUT, AGENCYSALEORDER_DESC.ASO_MTRS AS MTRS, AGENCYSALEORDER_DESC.ASO_RATE AS RATE, AGENCYSALEORDER_DESC.ASO_RECDQTY AS OUTPCS, AGENCYSALEORDER_DESC.ASO_RECDMTRS AS OUTMTRS, (AGENCYSALEORDER_DESC.ASO_QTY - AGENCYSALEORDER_DESC.ASO_RECDQTY) AS BALPCS, ISNULL((AGENCYSALEORDER_DESC.ASO_MTRS - AGENCYSALEORDER_DESC.ASO_RECDMTRS),0) AS BALMTRS, ASO_REMARKS AS REMARKS, cast(0 as BIT) AS CLOSED ,ISNULL(CITYMASTER.city_name, '') AS CITY, ISNULL(QUALITYMASTER.QUALITY_name, '') AS QUALITY, 'AGENCYSALEORDER' AS TYPE, ISNULL(ASO_FORWARD,'') AS FORWARD, (ROUND((ISNULL((AGENCYSALEORDER_DESC.ASO_QTY - AGENCYSALEORDER_DESC.ASO_RECDQTY),0)/AGENCYSALEORDER_DESC.ASO_QTY)*100,2)) AS BALPER , ISNULL(AGENCYSALEORDER.ASO_REFNO,'') AS REFNO, ISNULL(AGENCYSALEORDER_DESC.ASO_CLOSEDDATE,'') AS CLOSEDDATE, ISNULL(AGENCYSALEORDER_DESC.ASO_CLOSEDREASON,'') AS REASON FROM AGENCYSALEORDER_DESC INNER JOIN AGENCYSALEORDER ON AGENCYSALEORDER_DESC.ASO_NO = AGENCYSALEORDER.ASO_no AND AGENCYSALEORDER_DESC.ASO_YEARID = AGENCYSALEORDER.ASO_YEARID INNER JOIN LEDGERS ON AGENCYSALEORDER.ASO_ledgerid = LEDGERS.Acc_id  LEFT OUTER JOIN LEDGERS AS DISPATCHLEDGERS ON AGENCYSALEORDER.ASO_PACKINGID = DISPATCHLEDGERS.ACC_ID INNER JOIN ITEMMASTER ON AGENCYSALEORDER_DESC.ASO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN COLORMASTER ON AGENCYSALEORDER_DESC.ASO_COLORID = COLORMASTER.COLOR_id LEFT OUTER JOIN DESIGNMASTER ON AGENCYSALEORDER_DESC.ASO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON AGENCYSALEORDER.ASO_Agentid = AGENTLEDGERS.Acc_id LEFT OUTER JOIN QUALITYMASTER ON AGENCYSALEORDER_DESC.ASO_QUALITYID = QUALITYMASTER.QUALITY_id LEFT OUTER JOIN CITYMASTER ON LEDGERS.Acc_cityid = CITYMASTER.city_id WHERE AGENCYSALEORDER_DESC.ASO_CLOSED = 'TRUE' and (AGENCYSALEORDER_DESC.ASO_QTY-AGENCYSALEORDER_DESC.ASO_RECDQTY)>0 AND dbo.AGENCYSALEORDER.ASO_yearid=" & YearId & " UNION ALL  SELECT OPENINGAGENCYSALEORDER.OPASO_no AS SONO, OPENINGAGENCYSALEORDER_DESC.OPASO_GRIDSRNO AS GRIDSRNO, OPENINGAGENCYSALEORDER.OPASO_date AS SODATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(AGENTLEDGERS.Acc_cmpname,'') AS AGENTNAME, ISNULL(DISPATCHLEDGERS.Acc_cmpname,'') AS DISPATCHTO, OPENINGAGENCYSALEORDER.OPASO_pono AS PARTYPONO, OPENINGAGENCYSALEORDER.OPASO_DUEDATE AS DELDATE, ITEMMASTER.item_name AS ITEMNAME, ISNULL(DESIGNMASTER.DESIGN_NO,'') AS DESIGNNO, ISNULL(COLORMASTER.COLOR_name,'') AS COLOR, ISNULL(OPENINGAGENCYSALEORDER_DESC.OPASO_PARTYPONO,'') AS GRIDPARTYPONO, OPENINGAGENCYSALEORDER_DESC.OPASO_QTY AS PCS, OPENINGAGENCYSALEORDER_DESC.OPASO_CUT AS CUT, OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS AS MTRS, OPENINGAGENCYSALEORDER_DESC.OPASO_RATE AS RATE, OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY AS OUTPCS, OPENINGAGENCYSALEORDER_DESC.OPASO_RECDMTRS AS OUTMTRS, (OPENINGAGENCYSALEORDER_DESC.OPASO_QTY - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY) AS BALPCS, ISNULL((OPENINGAGENCYSALEORDER_DESC.OPASO_MTRS - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDMTRS),0) AS BALMTRS, OPASO_REMARKS AS REMARKS, cast(0 as BIT) AS CLOSED ,ISNULL(CITYMASTER.city_name, '') AS CITY, ISNULL(QUALITYMASTER.QUALITY_name, '') AS QUALITY, 'OPENING' AS TYPE, ISNULL(OPASO_FORWARD,'') AS FORWARD, (ROUND((ISNULL((OPENINGAGENCYSALEORDER_DESC.OPASO_QTY - OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY),0)/OPENINGAGENCYSALEORDER_DESC.OPASO_QTY)*100,2)) AS BALPER , ISNULL(OPENINGAGENCYSALEORDER.OPASO_REFNO,'') AS REFNO, ISNULL(OPENINGAGENCYSALEORDER_DESC.OPASO_CLOSEDDATE,'') AS CLOSEDDATE, ISNULL(OPENINGAGENCYSALEORDER_DESC.OPASO_CLOSEDREASON,'') AS REASON  FROM OPENINGAGENCYSALEORDER_DESC INNER JOIN OPENINGAGENCYSALEORDER ON OPENINGAGENCYSALEORDER_DESC.OPASO_NO = OPENINGAGENCYSALEORDER.OPASO_no AND OPENINGAGENCYSALEORDER_DESC.OPASO_YEARID = OPENINGAGENCYSALEORDER.OPASO_YEARID INNER JOIN LEDGERS ON OPENINGAGENCYSALEORDER.OPASO_ledgerid = LEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS DISPATCHLEDGERS ON OPENINGAGENCYSALEORDER.OPASO_PACKINGID = DISPATCHLEDGERS.ACC_ID  INNER JOIN ITEMMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN COLORMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_COLORID = COLORMASTER.COLOR_id LEFT OUTER JOIN DESIGNMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN LEDGERS AS AGENTLEDGERS ON OPENINGAGENCYSALEORDER.OPASO_Agentid = AGENTLEDGERS.Acc_id LEFT OUTER JOIN QUALITYMASTER ON OPENINGAGENCYSALEORDER_DESC.OPASO_QUALITYID = QUALITYMASTER.QUALITY_id LEFT OUTER JOIN CITYMASTER ON LEDGERS.Acc_cityid = CITYMASTER.city_id WHERE OPENINGAGENCYSALEORDER_DESC.OPASO_CLOSED = 'TRUE' and (OPENINGAGENCYSALEORDER_DESC.OPASO_QTY-OPENINGAGENCYSALEORDER_DESC.OPASO_RECDQTY)>0 AND dbo.OPENINGAGENCYSALEORDER.OPASO_yearid=" & YearId & ") AS T", " ORDER BY SONO, GRIDSRNO")
                End If
            End If

            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try
            If RBPENDING.Checked = True Then
                For I As Integer = 0 To gridbill.RowCount - 1
                    Dim DTROW As DataRow = gridbill.GetDataRow(I)
                    If Convert.ToBoolean(DTROW("CLOSED")) = True Then
                        If IsDBNull(DTROW("CLOSEDDATE")) = False AndAlso DTROW("CLOSEDDATE") = "" Then
                            MsgBox("Enter Closed Date", MsgBoxStyle.Critical)
                            Exit Sub
                        End If
                    End If
                Next
            Else
                If MsgBox("You have trying to Re-Open Closed Orders, Wish to Proceed?", MsgBoxStyle.YesNo) = MsgBoxResult.No Then Exit Sub
            End If



            Dim OBJCMN As New ClsCommon
            For I As Integer = 0 To gridbill.RowCount - 1
                Dim DTROW As DataRow = gridbill.GetDataRow(I)
                If RBPENDING.Checked = True Then
                    If Convert.ToBoolean(DTROW("CLOSED")) = True AndAlso IsDBNull(DTROW("CLOSEDDATE")) = False AndAlso DTROW("CLOSEDDATE") <> "" Then
                        Dim TEMP As DateTime
                        DateTime.TryParse(DTROW("CLOSEDDATE"), TEMP)
                        If DTROW("TYPE") = "AGENCYSALEORDER" Then Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE AGENCYSALEORDER_DESC SET ASO_CLOSED = 1, ASO_CLOSEDDATE = '" & Format(TEMP, "MM/dd/yyyy") & "', ASO_CLOSEDREASON = '" & DTROW("REASON") & "' WHERE ASO_NO = " & Val(DTROW("SONO")) & " AND ASO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND ASO_YEARID = " & YearId, "", "") Else Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE OPENINGAGENCYSALEORDER_DESC SET OPASO_CLOSED = 1, OPASO_CLOSEDDATE = '" & Format(TEMP, "MM/dd/yyyy") & "', OPASO_CLOSEDREASON = '" & DTROW("REASON") & "' WHERE OPASO_NO = " & Val(DTROW("SONO")) & " AND OPASO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND OPASO_YEARID = " & YearId, "", "")
                    End If
                Else
                    If Convert.ToBoolean(DTROW("CLOSED")) = True Then
                        If DTROW("TYPE") = "AGENCYSALEORDER" Then Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE AGENCYSALEORDER_DESC SET ASO_CLOSED = 0, ASO_CLOSEDREASON = '' WHERE ASO_NO = " & Val(DTROW("SONO")) & " AND ASO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND ASO_YEARID = " & YearId, "", "") Else Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE OPENINGAGENCYSALEORDER_DESC SET OPASO_CLOSED = 0, OPASO_CLOSEDREASON = '' WHERE OPASO_NO = " & Val(DTROW("SONO")) & " AND OPASO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND OPASO_YEARID = " & YearId, "", "")
                    End If
                End If
            Next
            FILLGRID()
            gridbill.Focus()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CMDREFRESH_Click(sender As Object, e As EventArgs) Handles CMDREFRESH.Click
        Try
            FILLGRID()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_RowStyle(ByVal sender As Object, ByVal e As DevExpress.XtraGrid.Views.Grid.RowStyleEventArgs) Handles gridbill.RowStyle
        Try
            If e.RowHandle >= 0 Then
                Dim View As GridView = sender
                If View.GetRowCellDisplayText(e.RowHandle, View.Columns("CLOSED")) = "Checked" Then
                    e.Appearance.Font = New System.Drawing.Font("CALIBRI", 9.0F, System.Drawing.FontStyle.Bold)
                    e.Appearance.BackColor = Color.Yellow
                End If
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CMDAPPLY_Click(sender As Object, e As EventArgs) Handles CMDAPPLY.Click
        Try
            For I As Integer = 0 To gridbill.RowCount - 1
                Dim DTROW As DataRow = gridbill.GetDataRow(I)
                If Convert.ToBoolean(DTROW("CLOSED")) = True Then
                    If IsDBNull(DTROW("CLOSEDDATE")) = False AndAlso DTROW("CLOSEDDATE") = "" Then
                        DTROW("CLOSEDDATE") = DTCLOSEDATE.Value.Date.ToString
                        DTROW("REASON") = CMBMAINREASON.Text.Trim
                    End If
                End If
            Next
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_ValidateRow(ByVal sender As Object, ByVal e As DevExpress.XtraGrid.Views.Base.ValidateRowEventArgs) Handles gridbill.ValidateRow
        Try
            If IsDBNull(gridbill.GetRowCellValue(e.RowHandle, "CLOSEDDATE")) = False Then

                If gridbill.GetRowCellValue(e.RowHandle, "CLOSEDDATE").ToString <> "" Then
                    'PARSING DATE FORMATS WHETHER THEY ARE CLOSEDDATE OR NOT
                    Dim TEMP As DateTime
                    If Not DateTime.TryParse(gridbill.GetRowCellValue(e.RowHandle, "CLOSEDDATE"), TEMP) Then
                        e.Valid = False
                        gridbill.SetColumnError(GCLOSEDDATE, "Invalid Date")
                        Exit Sub
                    Else
                        If gridbill.GetRowCellValue(e.RowHandle, "CLOSEDDATE") < Convert.ToDateTime(gridbill.GetRowCellValue(e.RowHandle, "DATE")).Date Then
                            e.Valid = False
                            gridbill.SetColumnError(GCLOSEDDATE, "Date must be After Order Date")
                            Exit Sub
                        End If
                    End If
                End If

            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub PrintToolStripButton_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles PrintToolStripButton.Click
        Try

            Dim PATH As String = Application.StartupPath & "\Sale Order Details.XLS"
            Dim opti As New DevExpress.XtraPrinting.XlsExportOptions
            opti.ShowGridLines = True
            opti.SheetName = "Sale Order Details"
            gridbill.ExportToXls(PATH, opti)
            EXCELCMPHEADER(PATH, "Sale Order Details", gridbill.VisibleColumns.Count + gridbill.GroupCount)
        Catch ex As Exception
            MsgBox("Sale Order Details Excel File is Open, Please Close the File first then try to Export", MsgBoxStyle.Critical)
        End Try
    End Sub

    Private Sub CHKSELECTALL_CheckedChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CHKSELECTALL.CheckedChanged
        Try
            If gridbilldetails.Visible = True Then
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    dtrow("CLOSED") = CHKSELECTALL.Checked
                Next
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub AgencySaleOrderClose_Shown(sender As Object, e As EventArgs) Handles Me.Shown
        Try
            If ClientName = "INDRANI" Then
                GSONO.Caption = "Sr No."
                GREFNO.Caption = "SO No"
            End If


            If ClientName = "SOFTAS" Then
                GAGENTNAME.Visible = False
                GCITY.Visible = False
                GDESIGNNO.Visible = False
                GQUALITY.Visible = False
                GBALMTRS.VisibleIndex = GCOLOR.VisibleIndex + 1
            End If

        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_KeyDown(sender As Object, e As KeyEventArgs) Handles gridbill.KeyDown
        Try
            If e.KeyCode = Keys.Space Then
                Dim dtrow As DataRow = gridbill.GetFocusedDataRow()
                dtrow("CLOSED") = Not dtrow("CLOSED")
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub
End Class



