
Imports BL

Public Class TDSDeductedReport

    Private Sub TDSDeductedReport_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode = Windows.Forms.Keys.Escape Then
                Me.Close()
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub fillgrid()
        Try
            Dim OBJCMN As New ClsCommon
            Dim dt As DataTable
            Dim WHERECLAUSE As String = ""
            If cmbregister.Text.Trim <> "" Then WHERECLAUSE = WHERECLAUSE & " AND REGNAME = '" & cmbregister.Text.Trim & "'"
            If CMBCOMPANYTYPE.Text.Trim <> "" Then WHERECLAUSE = WHERECLAUSE & " AND TDSCOMPANY = '" & CMBCOMPANYTYPE.Text.Trim & "'"
            If chkdate.CheckState = CheckState.Checked Then WHERECLAUSE = WHERECLAUSE & " AND PARTYBILLDATE >= '" & Format(dtfrom.Value.Date, "MM/dd/yyyy") & "' AND PARTYBILLDATE <= '" & Format(dtto.Value.Date, "MM/dd/yyyy") & "'"
            'If CMBCOMPANYTYPE.Text = "COMPANY" Then WHERECLAUSE = " AND DEDUCTEETYPEMASTER.DEDUCTEETYPE_NAME = '" & CMBCOMPANYTYPE.Text.Trim & "'" Else WHERECLAUSE = " AND DEDUCTEETYPEMASTER.DEDUCTEETYPE_NAME <> 'COMPANY'"
            'If CMBCOMPANYTYPE.Text = "COMPANY" Then Else WHERECLAUSE = " AND DEDUCTEETYPEMASTER.DEDUCTEETYPE_NAME <> 'COMPANY'"
            'End If

            If RBNOTDEDUCTED.Checked = True Then
                'THIS IS WITHOUT NONPURCHASE
                'dt = OBJCMN.search(" BILL_NO AS BILLNO, BILL_PARTYBILLNO AS PARTYBILLNO, BILL_PARTYBILLDATE AS PARTYBILLDATE, LEDGERS.Acc_cmpname AS NAME, BILL_GRANDTOTAL AS GRANDTOTAL, ISNULL(TDSCHALLANVIEW.TDSAMT,0) AS TDSAMT ", "", "DEDUCTEETYPEMASTER RIGHT OUTER JOIN ACCOUNTSMASTER_TDS ON DEDUCTEETYPEMASTER.DEDUCTEETYPE_ID = ACCOUNTSMASTER_TDS.ACC_DEDUCTEETYPEID RIGHT OUTER JOIN PURCHASEMASTER INNER JOIN LEDGERS ON LEDGERS.Acc_id = PURCHASEMASTER.BILL_LEDGERID LEFT OUTER JOIN TDSCHALLANVIEW ON TDSCHALLANVIEW.BILLINITIALS = PURCHASEMASTER.BILL_INITIALS AND TDSCHALLANVIEW.YEARID = PURCHASEMASTER.BILL_YEARID INNER JOIN REGISTERMASTER ON REGISTERMASTER.register_id = PURCHASEMASTER.BILL_REGISTERID ON ACCOUNTSMASTER_TDS.ACC_ID = LEDGERS.Acc_id", " AND BILL_INITIALS NOT IN (SELECT DISTINCT BILL_INITIALS FROM PURCHASEMASTER INNER JOIN JOURNALMASTER ON BILL_INITIALS = journal_refno AND BILL_YEARID = journal_yearid INNER JOIN LEDGERS ON journal_ledgerid = LEDGERS.ACC_ID WHERE LEDGERS.ACC_TDSAC = 'TRUE' AND BILL_YEARID = " & YearId & ") AND BILL_YEARID = " & YearId & WHERECLAUSE & " ORDER BY BILL_NO ")
                dt = OBJCMN.search("*", "", " (SELECT BILL_NO AS BILLNO, BILL_PARTYBILLNO AS PARTYBILLNO, BILL_PARTYBILLDATE AS PARTYBILLDATE, LEDGERS.Acc_cmpname AS NAME, BILL_SUBTOTAL As TAXABLEAMT, BILL_GRANDTOTAL AS GRANDTOTAL, ISNULL(TDSCHALLANVIEW.TDSAMT,0) AS TDSAMT , REGISTER_NAME AS REGNAME, ISNULL(LEDGERS.ACC_TDSCOMPANY,'') AS TDSCOMPANY
                FROM DEDUCTEETYPEMASTER RIGHT OUTER JOIN ACCOUNTSMASTER_TDS ON DEDUCTEETYPEMASTER.DEDUCTEETYPE_ID = ACCOUNTSMASTER_TDS.ACC_DEDUCTEETYPEID RIGHT OUTER JOIN PURCHASEMASTER INNER JOIN LEDGERS ON LEDGERS.Acc_id = PURCHASEMASTER.BILL_LEDGERID LEFT OUTER JOIN TDSCHALLANVIEW ON TDSCHALLANVIEW.BILLINITIALS = PURCHASEMASTER.BILL_INITIALS AND TDSCHALLANVIEW.YEARID = PURCHASEMASTER.BILL_YEARID INNER JOIN REGISTERMASTER ON REGISTERMASTER.register_id = PURCHASEMASTER.BILL_REGISTERID ON ACCOUNTSMASTER_TDS.ACC_ID = LEDGERS.Acc_id
                WHERE BILL_INITIALS NOT IN (SELECT DISTINCT BILL_INITIALS FROM PURCHASEMASTER INNER JOIN JOURNALMASTER ON BILL_INITIALS = journal_refno AND BILL_YEARID = journal_yearid INNER JOIN LEDGERS ON journal_ledgerid = LEDGERS.ACC_ID 
                WHERE LEDGERS.ACC_TDSAC = 'TRUE' AND BILL_YEARID = " & YearId & ") AND BILL_YEARID = " & YearId & " UNION ALL  SELECT NP_NO AS BILLNO, NP_REFNO AS PARTYBILLNO, NP_PARTYBILLDATE AS PARTYBILLDATE, LEDGERS.Acc_cmpname AS NAME, NP_TOTALTAXABLEAMT AS TAXABLEAMT, NP_GRANDTOTAL AS GRANDTOTAL, ISNULL(TDSCHALLANVIEW.TDSAMT,0) AS TDSAMT , REGISTER_NAME AS REGNAME, ISNULL(LEDGERS.ACC_TDSCOMPANY,'') AS TDSCOMPANY
                FROM DEDUCTEETYPEMASTER RIGHT OUTER JOIN ACCOUNTSMASTER_TDS ON DEDUCTEETYPEMASTER.DEDUCTEETYPE_ID = ACCOUNTSMASTER_TDS.ACC_DEDUCTEETYPEID RIGHT OUTER JOIN NONPURCHASE INNER JOIN LEDGERS ON LEDGERS.Acc_id = NONPURCHASE.NP_LEDGERID LEFT OUTER JOIN TDSCHALLANVIEW ON TDSCHALLANVIEW.BILLINITIALS = NONPURCHASE.NP_INITIALS AND TDSCHALLANVIEW.YEARID = NONPURCHASE.NP_YEARID INNER JOIN REGISTERMASTER ON REGISTERMASTER.register_id = NONPURCHASE.NP_REGISTERID ON ACCOUNTSMASTER_TDS.ACC_ID = LEDGERS.Acc_id
                WHERE NP_INITIALS NOT IN (SELECT DISTINCT NP_INITIALS FROM NONPURCHASE INNER JOIN JOURNALMASTER ON NP_INITIALS = journal_refno AND NP_YEARID = journal_yearid INNER JOIN LEDGERS ON journal_ledgerid = LEDGERS.ACC_ID 
                WHERE LEDGERS.ACC_TDSAC = 'TRUE' AND NP_YEARID = " & YearId & " ) AND NP_YEARID = " & YearId & " ) AS T", WHERECLAUSE & " ORDER BY T.BILLNO")
            Else
                'THIS IS WITHOUT NONPURCHASE
                'dt = OBJCMN.search(" DISTINCT BILL_NO As BILLNO, BILL_PARTYBILLNO As PARTYBILLNO, BILL_PARTYBILLDATE As PARTYBILLDATE, LEDGERS.Acc_cmpname As NAME, BILL_GRANDTOTAL As GRANDTOTAL, ISNULL(TDSCHALLANVIEW.TDSAMT, 0) AS TDSAMT ", "", "DEDUCTEETYPEMASTER RIGHT OUTER JOIN ACCOUNTSMASTER_TDS ON DEDUCTEETYPEMASTER.DEDUCTEETYPE_ID = ACCOUNTSMASTER_TDS.ACC_DEDUCTEETYPEID RIGHT OUTER JOIN PURCHASEMASTER INNER JOIN JOURNALMASTER ON PURCHASEMASTER.BILL_INITIALS = JOURNALMASTER.journal_refno And  PURCHASEMASTER.BILL_YEARID = JOURNALMASTER.journal_yearid INNER JOIN LEDGERS AS JOURNALLEDGERS ON JOURNALMASTER.journal_ledgerid = JOURNALLEDGERS.Acc_id INNER JOIN LEDGERS ON LEDGERS.Acc_id = PURCHASEMASTER.BILL_LEDGERID LEFT OUTER JOIN  TDSCHALLANVIEW ON TDSCHALLANVIEW.BILLINITIALS = PURCHASEMASTER.BILL_INITIALS And TDSCHALLANVIEW.YEARID = PURCHASEMASTER.BILL_YEARID INNER JOIN REGISTERMASTER ON REGISTERMASTER.register_id = PURCHASEMASTER.BILL_REGISTERID ON ACCOUNTSMASTER_TDS.ACC_ID = LEDGERS.Acc_id ", " And JOURNALLEDGERS.ACC_TDSAC = 'TRUE' AND BILL_YEARID = " & YearId & WHERECLAUSE & " AND TDSLEDGER <> LEDGERS.ACC_CMPNAME ORDER BY BILL_NO ")
                dt = OBJCMN.search("*", "", "(SELECT DISTINCT BILL_NO As BILLNO, BILL_PARTYBILLNO As PARTYBILLNO, BILL_PARTYBILLDATE As PARTYBILLDATE, LEDGERS.Acc_cmpname As NAME, BILL_SUBTOTAL As TAXABLEAMT, BILL_GRANDTOTAL As GRANDTOTAL, ISNULL(TDSCHALLANVIEW.TDSAMT, 0) AS TDSAMT, REGISTER_NAME AS REGNAME, ISNULL(LEDGERS.ACC_TDSCOMPANY,'') AS TDSCOMPANY
                FROM DEDUCTEETYPEMASTER RIGHT OUTER JOIN ACCOUNTSMASTER_TDS ON DEDUCTEETYPEMASTER.DEDUCTEETYPE_ID = ACCOUNTSMASTER_TDS.ACC_DEDUCTEETYPEID RIGHT OUTER JOIN PURCHASEMASTER INNER JOIN JOURNALMASTER ON PURCHASEMASTER.BILL_INITIALS = JOURNALMASTER.journal_refno And  PURCHASEMASTER.BILL_YEARID = JOURNALMASTER.journal_yearid INNER JOIN LEDGERS AS JOURNALLEDGERS ON JOURNALMASTER.journal_ledgerid = JOURNALLEDGERS.Acc_id INNER JOIN LEDGERS ON LEDGERS.Acc_id = PURCHASEMASTER.BILL_LEDGERID LEFT OUTER JOIN  TDSCHALLANVIEW ON TDSCHALLANVIEW.BILLINITIALS = PURCHASEMASTER.BILL_INITIALS And TDSCHALLANVIEW.YEARID = PURCHASEMASTER.BILL_YEARID INNER JOIN REGISTERMASTER ON REGISTERMASTER.register_id = PURCHASEMASTER.BILL_REGISTERID ON ACCOUNTSMASTER_TDS.ACC_ID = LEDGERS.Acc_id
                WHERE JOURNALLEDGERS.ACC_TDSAC = 'TRUE' AND BILL_YEARID = " & YearId & " AND TDSLEDGER <> LEDGERS.ACC_CMPNAME

                UNION ALL
                SELECT DISTINCT NP_NO As BILLNO, NP_REFNO As PARTYBILLNO, NP_PARTYBILLDATE As PARTYBILLDATE, LEDGERS.Acc_cmpname As NAME, NP_TOTALTAXABLEAMT AS TAXABLEAMT, NP_GRANDTOTAL As GRANDTOTAL, ISNULL(TDSCHALLANVIEW.TDSAMT, 0) AS TDSAMT, REGISTER_NAME AS REGNAME, ISNULL(LEDGERS.ACC_TDSCOMPANY,'') AS TDSCOMPANY
                FROM DEDUCTEETYPEMASTER RIGHT OUTER JOIN ACCOUNTSMASTER_TDS ON DEDUCTEETYPEMASTER.DEDUCTEETYPE_ID = ACCOUNTSMASTER_TDS.ACC_DEDUCTEETYPEID RIGHT OUTER JOIN NONPURCHASE INNER JOIN JOURNALMASTER ON NONPURCHASE.NP_INITIALS = JOURNALMASTER.journal_refno And  NONPURCHASE.NP_YEARID = JOURNALMASTER.journal_yearid INNER JOIN LEDGERS AS JOURNALLEDGERS ON JOURNALMASTER.journal_ledgerid = JOURNALLEDGERS.Acc_id INNER JOIN LEDGERS ON LEDGERS.Acc_id = NONPURCHASE.NP_LEDGERID LEFT OUTER JOIN  TDSCHALLANVIEW ON TDSCHALLANVIEW.BILLINITIALS = NONPURCHASE.NP_INITIALS And TDSCHALLANVIEW.YEARID = NONPURCHASE.NP_YEARID INNER JOIN REGISTERMASTER ON REGISTERMASTER.register_id = NONPURCHASE.NP_REGISTERID ON ACCOUNTSMASTER_TDS.ACC_ID = LEDGERS.Acc_id
                WHERE JOURNALLEDGERS.ACC_TDSAC = 'TRUE' AND NP_YEARID = " & YearId & " AND TDSLEDGER <> LEDGERS.ACC_CMPNAME
                ) AS T  ", WHERECLAUSE & " ORDER BY T.BILLNO")
            End If
            'If RBNOTDEDUCTED.Checked = True Then
            '    dt = OBJCMN.search(" BILL_NO AS BILLNO, BILL_PARTYBILLNO AS PARTYBILLNO, BILL_PARTYBILLDATE AS PARTYBILLDATE, LEDGERS.Acc_cmpname AS NAME, BILL_GRANDTOTAL AS GRANDTOTAL, ISNULL(TDSCHALLANVIEW.TDSAMT,0) AS TDSAMT ", "", " PURCHASEMASTER INNER JOIN LEDGERS ON Acc_id = BILL_LEDGERID LEFT OUTER JOIN TDSCHALLANVIEW ON TDSCHALLANVIEW.BILLINITIALS = BILL_INITIALS AND TDSCHALLANVIEW.YEARID = BILL_YEARID INNER JOIN REGISTERMASTER ON REGISTER_ID = BILL_REGISTERID", " AND BILL_INITIALS NOT IN (SELECT DISTINCT BILL_INITIALS FROM PURCHASEMASTER INNER JOIN JOURNALMASTER ON BILL_INITIALS = journal_refno AND BILL_YEARID = journal_yearid INNER JOIN LEDGERS ON journal_ledgerid = LEDGERS.ACC_ID WHERE LEDGERS.ACC_TDSAC = 'TRUE' AND BILL_YEARID = " & YearId & ") AND BILL_YEARID = " & YearId & WHERECLAUSE & " ORDER BY BILL_NO ")
            'Else
            '    dt = OBJCMN.search(" DISTINCT BILL_NO AS BILLNO, BILL_PARTYBILLNO AS PARTYBILLNO, BILL_PARTYBILLDATE AS PARTYBILLDATE, LEDGERS.Acc_cmpname AS NAME, BILL_GRANDTOTAL AS GRANDTOTAL, ISNULL(TDSCHALLANVIEW.TDSAMT,0) AS TDSAMT ", "", " PURCHASEMASTER INNER JOIN JOURNALMASTER ON BILL_INITIALS = journal_refno AND BILL_YEARID = journal_yearid INNER JOIN LEDGERS AS JOURNALLEDGERS ON journal_ledgerid = JOURNALLEDGERS.ACC_ID INNER JOIN LEDGERS ON LEDGERS.Acc_id = BILL_LEDGERID LEFT OUTER JOIN TDSCHALLANVIEW ON TDSCHALLANVIEW.BILLINITIALS = BILL_INITIALS AND TDSCHALLANVIEW.YEARID = BILL_YEARID INNER JOIN REGISTERMASTER ON REGISTER_ID = BILL_REGISTERID", " AND JOURNALLEDGERS.ACC_TDSAC = 'TRUE' AND BILL_YEARID = " & YearId & WHERECLAUSE & " AND TDSLEDGER <> LEDGERS.ACC_CMPNAME ORDER BY BILL_NO ")
            'End If
            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then gridbill.FocusedRowHandle = gridbill.RowCount - 1
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdcancel_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdcancel.Click
        Me.Close()
    End Sub

    Private Sub CMDPRINT_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CMDPRINT.Click
        Try
            Dim PATH As String = "" = ""
            If FileIO.FileSystem.FileExists(PATH) = True Then FileIO.FileSystem.DeleteFile(PATH)
            PATH = Application.StartupPath & "\TDS Deducted Details.XLS"

            Dim opti As New DevExpress.XtraPrinting.XlsExportOptions
            opti.ShowGridLines = True

            Dim PERIOD As String = AccFrom & " - " & AccTo

            opti.SheetName = "TDS Deducted Details"
            gridbill.ExportToXls(PATH, opti)
            EXCELCMPHEADER(PATH, "TDS Deducted Details", gridbill.VisibleColumns.Count + gridbill.GroupCount, "", PERIOD)

        Catch ex As Exception
            MsgBox("TDS Deducted Details Excel File is Open, Please Close the File first then try to Export", MsgBoxStyle.Critical)
        End Try
    End Sub

    Private Sub TDSDeductedReport_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            fillregister(cmbregister, " and (register_type = 'PURCHASE' OR REGISTER_TYPE = 'EXPENSE')")
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmbregister_Validating(ByVal sender As Object, ByVal e As System.ComponentModel.CancelEventArgs) Handles cmbregister.Validating
        Try
            If cmbregister.Text.Trim.Length > 0 Then
                cmbregister.Text = UCase(cmbregister.Text)
                Dim clscommon As New ClsCommon
                Dim dt As DataTable
                dt = clscommon.search(" register_abbr, register_initials, register_id", "", " RegisterMaster", " and register_name ='" & cmbregister.Text.Trim & "' and (register_type = 'PURCHASE' OR register_type = 'EXPENSE') and register_cmpid = " & CmpId & " AND REGISTER_LOCATIONID = " & Locationid & " AND REGISTER_YEARID = " & YearId)
                If dt.Rows.Count <= 0 Then
                    MsgBox("Register Not Present, Add New from Master Module")
                    e.Cancel = True
                End If
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub CMDREFRESH_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CMDREFRESH.Click
        Try
            fillgrid()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub
End Class