DECLARE @SUBJECT VARCHAR(100), @ENTRYBODY VARCHAR(MAX), @TOTALMTRS DECIMAL(18,2), @TOTALPCS DECIMAL(18,2), @CMPNAME VARCHAR(100), @YEARID INT, @BODY VARCHAR(MAX)
SET @SUBJECT = 'DAILY JOBBER ITEM-DESIGN WISE RECEIPT REPORT FOR ' + CAST(DAY(GETDATE()) AS VARCHAR(2)) + '-' + CAST(MONTH(GETDATE()) AS VARCHAR(2)) + '-' + CAST(YEAR(GETDATE()) AS VARCHAR(4))
SET @CMPNAME = 'YASHVI CREATION'
SET @YEARID=(SELECT TOP 1 YEAR_ID FROM YEARMASTER inner join CMPMASTER ON YEAR_CMPID = CMP_ID WHERE CMP_DISPLAYEDNAME = @CMPNAME  and year_startdate= CASE WHEN MONTH(GETDATE()) > 3 THEN CAST(YEAR(GETDATE()) AS VARCHAR(4)) + '-04-01' ELSE CAST(YEAR(GETDATE())-1 AS VARCHAR(4)) + '-04-01' END ORDER BY YEAR_STARTDATE DESC)

SET @TOTALMTRS = 0
SET @TOTALPCS = 0

SELECT @TOTALMTRS =  ISNULL(SUM(MATREC_TOTALRECDMTR),0), @TOTALPCS = ISNULL(SUM(MATREC_TOTALQTY),0) FROM MATERIALRECEIPT WHERE MATERIALRECEIPT.MATREC_YEARID = @YEARID  AND CAST(MATREC_DATE AS DATE) = CAST(GETDATE() AS DATE) 
SELECT @TOTALMTRS = @TOTALMTRS + ISNULL(SUM(JOBIN.JI_TOTALMTRS),0), @TOTALPCS = @TOTALPCS + ISNULL(SUM(JOBIN.JI_TOTALQTY),0) FROM JOBIN WHERE JOBIN.JI_YEARID = @YEARID AND CAST(JI_DATE AS DATE)  = CAST(GETDATE() AS DATE)


SET @ENTRYBODY = (SELECT
			[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@width]='250px', TD= T.JOBBERNAME,'', 
			[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@width]='250px', TD= T.ITEMNAME,'', 
			[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@width]='250px', TD= T.DESIGNNO,'', 
			[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@align]='right',[TD/@width]='100px', TD=CAST(T.RECDPCS AS DECIMAL(18,2)) ,'',
			[TD/@style]='font-family:Tahoma; font-size:11px;', [TD/@align]='right',[TD/@width]='100px', TD=CAST(T.RECDMTRS AS DECIMAL(18,2)),''
			FROM
			(
			SELECT   LEDGERS.Acc_cmpname AS JOBBERNAME,ITEMMASTER.item_name AS ITEMNAME, ISNULL(DESIGNMASTER.DESIGN_NO,'') AS DESIGNNO, SUM(MATERIALRECEIPT_DESC.MATREC_QTY) AS RECDPCS, SUM(MATERIALRECEIPT_DESC.MATREC_RECDMTRS) AS RECDMTRS
			FROM            MATERIALRECEIPT INNER JOIN
                         LEDGERS ON MATERIALRECEIPT.MATREC_ledgerid = LEDGERS.Acc_id INNER JOIN
                         MATERIALRECEIPT_DESC ON MATERIALRECEIPT.MATREC_NO = MATERIALRECEIPT_DESC.MATREC_NO AND MATERIALRECEIPT.MATREC_yearid = MATERIALRECEIPT_DESC.MATREC_YEARID INNER JOIN
                         ITEMMASTER ON MATERIALRECEIPT_DESC.MATREC_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN
						 DESIGNMASTER ON MATERIALRECEIPT_DESC.MATREC_DESIGNID = DESIGNMASTER.DESIGN_ID
			WHERE        (MATERIALRECEIPT.MATREC_yearid = @YEARID) AND CAST(MATERIALRECEIPT.MATREC_DATE  AS DATE) = CAST(GETDATE() AS DATE)
			GROUP BY LEDGERS.Acc_cmpname, ITEMMASTER.item_name, ISNULL(DESIGNMASTER.DESIGN_NO,'') 

			UNION ALL
			SELECT    LEDGERS.Acc_cmpname AS JOBBERNAME, ITEMMASTER.item_name AS ITEMNAME,  ISNULL(DESIGNMASTER.DESIGN_NO,'') AS DESIGNNO,SUM(JOBIN_DESC.JI_QTY) AS RECDPCS, SUM(JOBIN_DESC.JI_MTRS) AS RECDMTRS
			FROM            JOBIN INNER JOIN
                         LEDGERS ON JOBIN.JI_ledgerid = LEDGERS.Acc_id INNER JOIN
                         JOBIN_DESC ON JOBIN.JI_no = JOBIN_DESC.JI_NO AND JOBIN.JI_yearid = JOBIN_DESC.JI_YEARID INNER JOIN
                         ITEMMASTER ON JOBIN_DESC.JI_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN
						 DESIGNMASTER ON JOBIN_DESC.JI_DESIGNID = DESIGNMASTER.DESIGN_ID
			WHERE        (JOBIN.JI_yearid = @YEARID) AND CAST(JOBIN.JI_DATE  AS DATE) = CAST(GETDATE() AS DATE)
			GROUP BY LEDGERS.Acc_cmpname, ITEMMASTER.item_name, ISNULL(DESIGNMASTER.DESIGN_NO,'') 
			) AS T
			ORDER BY ITEMNAME, DESIGNNO, JOBBERNAME
			FOR XML PATH ('tr'))

			
SET @BODY = ISNULL(@BODY,'') + N'<H1 style="font-family:Tahoma; font-size:11px;">DAILY JOBBER ITEM-DESIGN WISE RECEIPT REPORT FOR</H1>' +
							N'<Table Border = "1">' + 
							N'<Tr style="font-family:Tahoma; font-size:11px;"><Th>Jobber Name</Th><Th>Item Name</Th><Th>Design No</Th><Th>Recd Pcs</Th><Th>Recd Mtrs</Th></Tr>'+
							+ISNULL(@ENTRYBODY,'')+ N'<tfoot><tr><td colspan="3"; style="font-family:Tahoma; font-size:11px; font-weight:bold; color:black;" bgcolor="yellow">TOTAL:</td>
							<td style="font-family:Tahoma; font-size:11px; font-weight:bold; color:black;" align="right" bgcolor="yellow">' + CAST(@TOTALPCS AS VARCHAR) + N'</td>
							<td style="font-family:Tahoma; font-size:11px; font-weight:bold; color:black;" align="right" bgcolor="yellow">' + CAST(@TOTALMTRS AS VARCHAR) + N'</td>
							</tr></tfoot></Table></html>'

			

DECLARE @FINALBODY VARCHAR(MAX)
SET @FINALBODY = @BODY 


EXEC msdb.dbo.sp_send_dbmail
@profile_name='TEXTRADE',
@recipients='gulkitjain@gmail.com;',
@subject=@SUBJECT,
@body=@FINALBODY,
@body_format = 'HTML'








