
Imports BL

Public Class EmbIncentiveDetails

    Dim USERADD, USEREDIT, USERVIEW, USERDELETE As Boolean      'USED FOR RIGHT MANAGEMAENT

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub TOOLREFRESH_Click(sender As Object, e As EventArgs) Handles TOOLREFRESH.Click
        Try
            fillgrid()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub JOBINDetails_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode = Windows.Forms.Keys.Escape Then
                Me.Close()
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub JOBINDetails_LOAD(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Dim DTROW() As DataRow
        DTROW = USERRIGHTS.Select("FormName = 'JOB IN'")
        USERADD = DTROW(0).Item(1)
        USEREDIT = DTROW(0).Item(2)
        USERVIEW = DTROW(0).Item(3)
        USERDELETE = DTROW(0).Item(4)

        If USEREDIT = False And USERVIEW = False Then
            MsgBox("Insufficient Rights")
            Exit Sub
        End If

        fillgrid()
    End Sub

    Sub fillgrid()
        Try
            If USEREDIT = False And USERVIEW = False Then
                MsgBox("Insufficient Rights")
                Exit Sub
            End If

            Dim objclsCMST As New ClsCommon
            Dim DT As New DataTable
            If ClientName = "KARAN" Then
                DT = objclsCMST.Execute_Any_String("SELECT EMBPRODUCTION.PROD_NO AS PRODNO, EMBPRODUCTION.PROD_DATE AS DATE, ISNULL(CONTRACTMASTER.CONTRACT_NAME, '') AS LABOUR, EMBPRODUCTION.PROD_SHIFT AS SHIFT, ISNULL(MACHINEMASTER.MACHINE_NAME, '') AS MACHINENO, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, ISNULL(COLORMASTER.COLOR_name, '') AS SHADE, EMBPRODUCTION.PROD_MTRS AS MTRS, EMBPRODUCTION.PROD_STITCHES AS STITCHES, EMBPRODUCTION.PROD_FRAMES AS FRAMES, EMBPRODUCTION.PROD_RUNFRAMES AS RUNFRAMES, EMBPRODUCTION.PROD_TOTALPROD AS TOTALPROD, EMBPRODUCTION.PROD_ACTUALPROD AS ACTUALPROD, EMBPRODUCTION.PROD_DIFF AS DIFF, EMBPRODUCTION.PROD_CHALLANNO AS CHALLANNO, EMBPRODUCTION.PROD_CHALLANDATE AS CHALLANDATE, EMBPRODUCTION.PROD_JONO AS JONO, EMBPRODUCTION.PROD_JOSRNO AS JOSRNO, EMBPRODUCTION.PROD_TOTALMTRS AS TOTALMTRS, EMBPRODUCTION.PROD_TOTALCONES AS TOTALCONES, EMBPRODUCTION.PROD_REMARKS AS REMARKS, ISNULL(EMBPRODUCTION_THREAD.PROD_GRIDSRNO, 0) AS GRIDSRNO, ISNULL(STOREITEMMASTER.STOREITEM_NAME, '') AS THREAD, ISNULL(EMBPRODUCTION_THREAD.PROD_CONES, 0) AS CONES, ISNULL(EMBPRODUCTION_THREAD.PROD_THREADMTRS, 0) AS THREADMTRS, EMBPRODUCTION.PROD_YEARID AS YEARID FROM STOREITEMMASTER RIGHT OUTER JOIN EMBPRODUCTION_THREAD ON STOREITEMMASTER.STOREITEM_ID = EMBPRODUCTION_THREAD.PROD_STOREITEMID RIGHT OUTER JOIN EMBPRODUCTION INNER JOIN CONTRACTMASTER ON EMBPRODUCTION.PROD_CONTRACTID = CONTRACTMASTER.CONTRACT_ID INNER JOIN MACHINEMASTER ON EMBPRODUCTION.PROD_MACHINEID = MACHINEMASTER.MACHINE_ID INNER JOIN ITEMMASTER ON EMBPRODUCTION.PROD_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN COLORMASTER ON EMBPRODUCTION.PROD_SHADEID = COLORMASTER.COLOR_id ON EMBPRODUCTION_THREAD.PROD_YEARID = EMBPRODUCTION.PROD_YEARID AND EMBPRODUCTION_THREAD.PROD_NO = EMBPRODUCTION.PROD_NO INNER JOIN (SELECT  EMBPRODUCTION.PROD_DATE AS DATE, ISNULL(CONTRACTMASTER.CONTRACT_NAME, '') AS LABOUR, CONTRACT_ID AS LABOURID , EMBPRODUCTION.PROD_SHIFT AS SHIFT, EMBPRODUCTION.PROD_YEARID AS YEARID FROM STOREITEMMASTER RIGHT OUTER JOIN EMBPRODUCTION_THREAD ON STOREITEMMASTER.STOREITEM_ID = EMBPRODUCTION_THREAD.PROD_STOREITEMID RIGHT OUTER JOIN EMBPRODUCTION INNER JOIN CONTRACTMASTER ON EMBPRODUCTION.PROD_CONTRACTID = CONTRACTMASTER.CONTRACT_ID INNER JOIN MACHINEMASTER ON EMBPRODUCTION.PROD_MACHINEID = MACHINEMASTER.MACHINE_ID INNER JOIN ITEMMASTER ON EMBPRODUCTION.PROD_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN COLORMASTER ON EMBPRODUCTION.PROD_SHADEID = COLORMASTER.COLOR_id ON EMBPRODUCTION_THREAD.PROD_YEARID = EMBPRODUCTION.PROD_YEARID AND EMBPRODUCTION_THREAD.PROD_NO = EMBPRODUCTION.PROD_NO WHERE (EMBPRODUCTION.PROD_YEARID = '" & YearId & "') GROUP BY  EMBPRODUCTION.PROD_DATE ,ISNULL(CONTRACTMASTER.CONTRACT_NAME, ''),CONTRACT_ID , EMBPRODUCTION.PROD_SHIFT, EMBPRODUCTION.PROD_YEARID HAVING COUNT(ISNULL(CONTRACTMASTER.CONTRACT_NAME, '')) > 1) AS T ON T.DATE = EMBPRODUCTION.PROD_DATE AND T.LABOUR = ISNULL(CONTRACTMASTER.CONTRACT_NAME, '') AND T.SHIFT = EMBPRODUCTION.PROD_SHIFT AND T.YEARID = EMBPRODUCTION.PROD_YEARID AND PROD_ACTUALPROD = (SELECT MIN(PROD_ACTUALPROD) FROM EMBPRODUCTION AS EE WHERE T.DATE = EE.PROD_DATE AND T.LABOURID = EE.PROD_CONTRACTID AND T.SHIFT = EE.PROD_SHIFT AND T.YEARID = EE.PROD_YEARID) ORDER BY EMBPRODUCTION.PROD_NO ", "", "")
            Else
                DT = objclsCMST.Execute_Any_String("SELECT EMBPRODUCTION.PROD_NO AS PRODNO, EMBPRODUCTION.PROD_DATE AS DATE, ISNULL(CONTRACTMASTER.CONTRACT_NAME, '') AS LABOUR, EMBPRODUCTION.PROD_SHIFT AS SHIFT, ISNULL(MACHINEMASTER.MACHINE_NAME, '') AS MACHINENO, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, ISNULL(COLORMASTER.COLOR_name, '') AS SHADE, EMBPRODUCTION.PROD_MTRS AS MTRS, EMBPRODUCTION.PROD_STITCHES AS STITCHES, EMBPRODUCTION.PROD_FRAMES AS FRAMES, EMBPRODUCTION.PROD_RUNFRAMES AS RUNFRAMES, EMBPRODUCTION.PROD_TOTALPROD AS TOTALPROD, EMBPRODUCTION.PROD_ACTUALPROD AS ACTUALPROD, EMBPRODUCTION.PROD_DIFF AS DIFF, EMBPRODUCTION.PROD_CHALLANNO AS CHALLANNO, EMBPRODUCTION.PROD_CHALLANDATE AS CHALLANDATE, EMBPRODUCTION.PROD_JONO AS JONO, EMBPRODUCTION.PROD_JOSRNO AS JOSRNO, EMBPRODUCTION.PROD_TOTALMTRS AS TOTALMTRS, EMBPRODUCTION.PROD_TOTALCONES AS TOTALCONES, EMBPRODUCTION.PROD_REMARKS AS REMARKS, ISNULL(EMBPRODUCTION_THREAD.PROD_GRIDSRNO, 0) AS GRIDSRNO, ISNULL(STOREITEMMASTER.STOREITEM_NAME, '') AS THREAD, ISNULL(EMBPRODUCTION_THREAD.PROD_CONES, 0) AS CONES, ISNULL(EMBPRODUCTION_THREAD.PROD_THREADMTRS, 0) AS THREADMTRS, EMBPRODUCTION.PROD_YEARID AS YEARID FROM STOREITEMMASTER RIGHT OUTER JOIN EMBPRODUCTION_THREAD ON STOREITEMMASTER.STOREITEM_ID = EMBPRODUCTION_THREAD.PROD_STOREITEMID RIGHT OUTER JOIN EMBPRODUCTION INNER JOIN CONTRACTMASTER ON EMBPRODUCTION.PROD_CONTRACTID = CONTRACTMASTER.CONTRACT_ID INNER JOIN MACHINEMASTER ON EMBPRODUCTION.PROD_MACHINEID = MACHINEMASTER.MACHINE_ID INNER JOIN ITEMMASTER ON EMBPRODUCTION.PROD_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN COLORMASTER ON EMBPRODUCTION.PROD_SHADEID = COLORMASTER.COLOR_id ON EMBPRODUCTION_THREAD.PROD_YEARID = EMBPRODUCTION.PROD_YEARID AND EMBPRODUCTION_THREAD.PROD_NO = EMBPRODUCTION.PROD_NO ", "", "")
            End If
            gridbilldetails.DataSource = DT
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

End Class