
Imports BL
Imports DevExpress.XtraGrid.Views.Grid

Public Class YarnSaleOrderClose

    Dim USERADD, USEREDIT, USERVIEW, USERDELETE As Boolean      'USED FOR RIGHT MANAGEMAENT

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub YarnSaleOrderClose_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode = Windows.Forms.Keys.Escape Then
                Me.Close()
            ElseIf e.KeyCode = Keys.Space And e.Control = True Then
                'SELECT ALL DATA
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    dtrow("CLOSED") = Not Convert.ToBoolean(dtrow("CLOSED"))
                Next
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub YarnSaleOrderClose_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            Dim DTROW() As DataRow
            DTROW = USERRIGHTS.Select("FormName = 'SALE ORDER'")
            USERADD = DTROW(0).Item(1)
            USEREDIT = DTROW(0).Item(2)
            USERVIEW = DTROW(0).Item(3)
            USERDELETE = DTROW(0).Item(4)

            If USEREDIT = False And USERVIEW = False Then
                MsgBox("Insufficient Rights")
                Exit Sub
            End If


            fillgrid()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub fillgrid()
        Try
            Dim objclsCMST As New ClsCommonMaster
            Dim dt As DataTable
            If RBPENDING.Checked = True Then
                dt = objclsCMST.search("*", "", " (SELECT ISNULL(YARNSALEORDER.YSO_NO, 0) AS SONO, YARNSALEORDER.YSO_DATE AS SODATE, YARNSALEORDER.YSO_DUEDATE AS DUEDATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(YARNSALEORDER.YSO_CRDAYS, 0) AS CRDAYS, ISNULL(YARNSALEORDER.YSO_DELDAYS, 0) AS DELDAYS, ISNULL(YARNSALEORDER.YSO_REFNO, '') AS REFNO, ISNULL(YARNSALEORDER.YSO_DISCOUNT, 0) AS DISCOUNT, ISNULL(YARNSALEORDER.YSO_REMARKS, '') AS REMARKS, ISNULL(YARNSALEORDER.YSO_LBLTOTALAMT, 0) AS LBLTOTALPCS, ISNULL(YARNSALEORDER.YSO_INWORDS, '') AS INWORDS, ISNULL(BROKERLEDGERS.Acc_cmpname, '') AS BROKER, ISNULL(DESIGNMASTER.DESIGN_NO, '') AS DESIGN, ISNULL(YARNSALEORDER_DESC.YSO_GRIDSRNO, 0) AS GRIDSRNO, ISNULL(YARNSALEORDER_DESC.YSO_DESC, '') AS [DESC], ISNULL(UNITMASTER.unit_name, '') AS UNIT, ISNULL(COLORMASTER.COLOR_name, '') AS SHADE, ISNULL(YARNSALEORDER_DESC.YSO_BAGS, 0) AS BAGS, ISNULL(YARNSALEORDER_DESC.YSO_WT, 0) AS WT, YARNQUALITYMASTER.YARN_NAME AS YARNQUALITY, ISNULL(LEDGERS.Acc_mobile, '') AS MOBILENO, ISNULL(TRANSLEDGERS.Acc_cmpname, '') AS TRANSNAME, ISNULL(YARNSALEORDER_DESC.YSO_RATE, 0) AS RATE, ISNULL(YARNSALEORDER_DESC.YSO_AMT, 0) AS AMT, ISNULL(YARNSALEORDER_DESC.YSO_RECDBAGS, 0) AS RECDBAGS, ISNULL(YARNSALEORDER_DESC.YSO_RECDWT, 0) AS RECDWT, ISNULL(YARNSALEORDER_DESC.YSO_DONE, 0) AS DONE, ISNULL(YARNSALEORDER_DESC.YSO_CLOSED, 0) AS CLOSED, (ISNULL(YARNSALEORDER_DESC.YSO_BAGS, 0) - ISNULL(YARNSALEORDER_DESC.YSO_RECDBAGS, 0)) AS BALBAGS, (ISNULL(YARNSALEORDER_DESC.YSO_WT, 0) - ISNULL(YARNSALEORDER_DESC.YSO_RECDWT, 0)) AS BALWT ,'YARNSALEORDER' AS TYPE FROM YARNSALEORDER INNER JOIN YARNSALEORDER_DESC ON YARNSALEORDER.YSO_NO = YARNSALEORDER_DESC.YSO_NO AND YARNSALEORDER.YSO_YEARID = YARNSALEORDER_DESC.YSO_YEARID LEFT OUTER JOIN DESIGNMASTER ON YARNSALEORDER_DESC.YSO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN COLORMASTER ON YARNSALEORDER_DESC.YSO_SHADEID = COLORMASTER.COLOR_id LEFT OUTER JOIN YARNQUALITYMASTER ON YARNSALEORDER_DESC.YSO_YARNQUALITYID = YARNQUALITYMASTER.YARN_ID LEFT OUTER JOIN LEDGERS AS BROKERLEDGERS ON YARNSALEORDER.YSO_BROKERID = BROKERLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON YARNSALEORDER.YSO_TRANSID = TRANSLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS ON YARNSALEORDER.YSO_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN UNITMASTER ON YARNSALEORDER_DESC.YSO_UNITID = UNITMASTER.unit_id WHERE  ISNULL(YARNSALEORDER_DESC.YSO_CLOSED, 0) = 'FALSE' AND dbo.YARNSALEORDER.YSO_yearid=" & YearId & " UNION ALL  SELECT ISNULL(OPENINGYARNSALEORDER.OYSO_NO, 0) AS SONO, OPENINGYARNSALEORDER.OYSO_DATE AS SODATE, OPENINGYARNSALEORDER.OYSO_DUEDATE AS DUEDATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(OPENINGYARNSALEORDER.OYSO_CRDAYS, 0) AS CRDAYS, ISNULL(OPENINGYARNSALEORDER.OYSO_DELDAYS, 0) AS DELDAYS, ISNULL(OPENINGYARNSALEORDER.OYSO_REFNO, '') AS REFNO, ISNULL(OPENINGYARNSALEORDER.OYSO_DISCOUNT, 0) AS DISCOUNT, ISNULL(OPENINGYARNSALEORDER.OYSO_REMARKS, '') AS REMARKS, ISNULL(OPENINGYARNSALEORDER.OYSO_LBLTOTALAMT, 0) AS LBLTOTALPCS, ISNULL(OPENINGYARNSALEORDER.OYSO_INWORDS, '') AS INWORDS, ISNULL(BROKERLEDGERS.Acc_cmpname, '') AS BROKER, ISNULL(DESIGNMASTER.DESIGN_NO, '') AS DESIGN, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_GRIDSRNO, 0) AS GRIDSRNO, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_DESC, '') AS [DESC], ISNULL(UNITMASTER.unit_name, '') AS UNIT, ISNULL(COLORMASTER.COLOR_name, '') AS SHADE, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_BAGS, 0) AS BAGS, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_WT, 0) AS WT, YARNQUALITYMASTER.YARN_NAME AS YARNQUALITY, ISNULL(LEDGERS.Acc_mobile, '') AS MOBILENO, ISNULL(TRANSLEDGERS.Acc_cmpname, '') AS TRANSNAME, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_RATE, 0) AS RATE, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_AMT, 0) AS AMT, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_RECDBAGS, 0) AS RECDBAGS, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_RECDWT, 0) AS RECDWT, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_DONE, 0) AS DONE, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_CLOSED, 0) AS CLOSED, (ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_BAGS, 0) - ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_RECDBAGS, 0)) AS BALBAGS, (ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_WT, 0) - ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_RECDWT, 0)) AS BALWT , 'OPENINGYARNSALEORDER' AS TYPE  FROM OPENINGYARNSALEORDER INNER JOIN OPENINGYARNSALEORDER_DESC ON OPENINGYARNSALEORDER.OYSO_NO = OPENINGYARNSALEORDER_DESC.OYSO_NO AND OPENINGYARNSALEORDER.OYSO_YEARID = OPENINGYARNSALEORDER_DESC.OYSO_YEARID LEFT OUTER JOIN DESIGNMASTER ON OPENINGYARNSALEORDER_DESC.OYSO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN COLORMASTER ON OPENINGYARNSALEORDER_DESC.OYSO_SHADEID = COLORMASTER.COLOR_id LEFT OUTER JOIN YARNQUALITYMASTER ON OPENINGYARNSALEORDER_DESC.OYSO_YARNQUALITYID = YARNQUALITYMASTER.YARN_ID LEFT OUTER JOIN LEDGERS AS BROKERLEDGERS ON OPENINGYARNSALEORDER.OYSO_BROKERID = BROKERLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON OPENINGYARNSALEORDER.OYSO_TRANSID = TRANSLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS ON OPENINGYARNSALEORDER.OYSO_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN UNITMASTER ON OPENINGYARNSALEORDER_DESC.OYSO_UNITID = UNITMASTER.unit_id WHERE  ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_CLOSED, 0) = 'FALSE' AND dbo.OPENINGYARNSALEORDER.OYSO_yearid=" & YearId & ") AS T", " ORDER BY SONO, GRIDSRNO")
            Else
                dt = objclsCMST.search("*", "", " (SELECT ISNULL(YARNSALEORDER.YSO_NO, 0) AS SONO, YARNSALEORDER.YSO_DATE AS SODATE, YARNSALEORDER.YSO_DUEDATE AS DUEDATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(YARNSALEORDER.YSO_CRDAYS, 0) AS CRDAYS, ISNULL(YARNSALEORDER.YSO_DELDAYS, 0) AS DELDAYS, ISNULL(YARNSALEORDER.YSO_REFNO, '') AS REFNO, ISNULL(YARNSALEORDER.YSO_DISCOUNT, 0) AS DISCOUNT, ISNULL(YARNSALEORDER.YSO_REMARKS, '') AS REMARKS, ISNULL(YARNSALEORDER.YSO_LBLTOTALAMT, 0) AS LBLTOTALPCS, ISNULL(YARNSALEORDER.YSO_INWORDS, '') AS INWORDS, ISNULL(BROKERLEDGERS.Acc_cmpname, '') AS BROKER, ISNULL(DESIGNMASTER.DESIGN_NO, '') AS DESIGN, ISNULL(YARNSALEORDER_DESC.YSO_GRIDSRNO, 0) AS GRIDSRNO, ISNULL(YARNSALEORDER_DESC.YSO_DESC, '') AS [DESC], ISNULL(UNITMASTER.unit_name, '') AS UNIT, ISNULL(COLORMASTER.COLOR_name, '') AS SHADE, ISNULL(YARNSALEORDER_DESC.YSO_BAGS, 0) AS BAGS, ISNULL(YARNSALEORDER_DESC.YSO_WT, 0) AS WT, YARNQUALITYMASTER.YARN_NAME AS YARNQUALITY, ISNULL(LEDGERS.Acc_mobile, '') AS MOBILENO, ISNULL(TRANSLEDGERS.Acc_cmpname, '') AS TRANSNAME, ISNULL(YARNSALEORDER_DESC.YSO_RATE, 0) AS RATE, ISNULL(YARNSALEORDER_DESC.YSO_AMT, 0) AS AMT, ISNULL(YARNSALEORDER_DESC.YSO_RECDBAGS, 0) AS RECDBAGS, ISNULL(YARNSALEORDER_DESC.YSO_RECDWT, 0) AS RECDWT, ISNULL(YARNSALEORDER_DESC.YSO_DONE, 0) AS DONE, ISNULL(YARNSALEORDER_DESC.YSO_CLOSED, 0) AS CLOSED, (ISNULL(YARNSALEORDER_DESC.YSO_BAGS, 0) - ISNULL(YARNSALEORDER_DESC.YSO_RECDBAGS, 0)) AS BALBAGS, (ISNULL(YARNSALEORDER_DESC.YSO_WT, 0) - ISNULL(YARNSALEORDER_DESC.YSO_RECDWT, 0)) AS BALWT , 'YARNSALEORDER' AS TYPE  FROM YARNSALEORDER INNER JOIN YARNSALEORDER_DESC ON YARNSALEORDER.YSO_NO = YARNSALEORDER_DESC.YSO_NO AND YARNSALEORDER.YSO_YEARID = YARNSALEORDER_DESC.YSO_YEARID LEFT OUTER JOIN DESIGNMASTER ON YARNSALEORDER_DESC.YSO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN COLORMASTER ON YARNSALEORDER_DESC.YSO_SHADEID = COLORMASTER.COLOR_id LEFT OUTER JOIN YARNQUALITYMASTER ON YARNSALEORDER_DESC.YSO_YARNQUALITYID = YARNQUALITYMASTER.YARN_ID LEFT OUTER JOIN LEDGERS AS BROKERLEDGERS ON YARNSALEORDER.YSO_BROKERID = BROKERLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON YARNSALEORDER.YSO_TRANSID = TRANSLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS ON YARNSALEORDER.YSO_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN UNITMASTER ON YARNSALEORDER_DESC.YSO_UNITID = UNITMASTER.unit_id WHERE (ISNULL(YARNSALEORDER_DESC.YSO_WT, 0) - ISNULL(YARNSALEORDER_DESC.YSO_RECDWT, 0)) > 0 AND ISNULL(YARNSALEORDER_DESC.YSO_CLOSED, 0) = 'TRUE' AND dbo.YARNSALEORDER.YSO_yearid=" & YearId & " UNION ALL  SELECT ISNULL(OPENINGYARNSALEORDER.OYSO_NO, 0) AS SONO, OPENINGYARNSALEORDER.OYSO_DATE AS SODATE, OPENINGYARNSALEORDER.OYSO_DUEDATE AS DUEDATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(OPENINGYARNSALEORDER.OYSO_CRDAYS, 0) AS CRDAYS, ISNULL(OPENINGYARNSALEORDER.OYSO_DELDAYS, 0) AS DELDAYS, ISNULL(OPENINGYARNSALEORDER.OYSO_REFNO, '') AS REFNO, ISNULL(OPENINGYARNSALEORDER.OYSO_DISCOUNT, 0) AS DISCOUNT, ISNULL(OPENINGYARNSALEORDER.OYSO_REMARKS, '') AS REMARKS, ISNULL(OPENINGYARNSALEORDER.OYSO_LBLTOTALAMT, 0) AS LBLTOTALPCS, ISNULL(OPENINGYARNSALEORDER.OYSO_INWORDS, '') AS INWORDS, ISNULL(BROKERLEDGERS.Acc_cmpname, '') AS BROKER, ISNULL(DESIGNMASTER.DESIGN_NO, '') AS DESIGN, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_GRIDSRNO, 0) AS GRIDSRNO, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_DESC, '') AS [DESC], ISNULL(UNITMASTER.unit_name, '') AS UNIT, ISNULL(COLORMASTER.COLOR_name, '') AS SHADE, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_BAGS, 0) AS BAGS, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_WT, 0) AS WT, YARNQUALITYMASTER.YARN_NAME AS YARNQUALITY, ISNULL(LEDGERS.Acc_mobile, '') AS MOBILENO, ISNULL(TRANSLEDGERS.Acc_cmpname, '') AS TRANSNAME, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_RATE, 0) AS RATE, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_AMT, 0) AS AMT, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_RECDBAGS, 0) AS RECDBAGS, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_RECDWT, 0) AS RECDWT, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_DONE, 0) AS DONE, ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_CLOSED, 0) AS CLOSED, (ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_BAGS, 0) - ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_RECDBAGS, 0)) AS BALBAGS, (ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_WT, 0) - ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_RECDWT, 0)) AS BALWT , 'OPENINGYARNSALEORDER' AS TYPE  FROM OPENINGYARNSALEORDER INNER JOIN OPENINGYARNSALEORDER_DESC ON OPENINGYARNSALEORDER.OYSO_NO = OPENINGYARNSALEORDER_DESC.OYSO_NO AND OPENINGYARNSALEORDER.OYSO_YEARID = OPENINGYARNSALEORDER_DESC.OYSO_YEARID LEFT OUTER JOIN DESIGNMASTER ON OPENINGYARNSALEORDER_DESC.OYSO_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN COLORMASTER ON OPENINGYARNSALEORDER_DESC.OYSO_SHADEID = COLORMASTER.COLOR_id LEFT OUTER JOIN YARNQUALITYMASTER ON OPENINGYARNSALEORDER_DESC.OYSO_YARNQUALITYID = YARNQUALITYMASTER.YARN_ID LEFT OUTER JOIN LEDGERS AS BROKERLEDGERS ON OPENINGYARNSALEORDER.OYSO_BROKERID = BROKERLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS AS TRANSLEDGERS ON OPENINGYARNSALEORDER.OYSO_TRANSID = TRANSLEDGERS.Acc_id LEFT OUTER JOIN LEDGERS ON OPENINGYARNSALEORDER.OYSO_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN UNITMASTER ON OPENINGYARNSALEORDER_DESC.OYSO_UNITID = UNITMASTER.unit_id WHERE (ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_WT, 0) - ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_RECDWT, 0)) > 0 AND ISNULL(OPENINGYARNSALEORDER_DESC.OYSO_CLOSED, 0) = 'TRUE' AND dbo.OPENINGYARNSALEORDER.OYSO_yearid=" & YearId & ") AS T", " ORDER BY SONO, GRIDSRNO")
            End If
            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try

            Dim OBJCMN As New ClsCommon
            For I As Integer = 0 To gridbill.RowCount - 1
                Dim DTROW As DataRow = gridbill.GetDataRow(I)
                If RBPENDING.Checked = True AndAlso Convert.ToBoolean(DTROW("CLOSED")) = True Then
                    If DTROW("TYPE") = "YARNSALEORDER" Then
                        Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE YARNSALEORDER_DESC SET YSO_CLOSED = 1 WHERE YSO_NO = " & Val(DTROW("SONO")) & " AND YSO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND YSO_YEARID = " & YearId, "", "")
                    ElseIf DTROW("TYPE") = "OPENINGYARNSALEORDER" Then
                        Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE OPENINGYARNSALEORDER_DESC SET OYSO_CLOSED = 1 WHERE OYSO_NO = " & Val(DTROW("SONO")) & " AND OYSO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND OYSO_YEARID = " & YearId, "", "")
                    End If
                ElseIf RBPENDING.Checked = False AndAlso Convert.ToBoolean(DTROW("CLOSED")) = True Then
                    If DTROW("TYPE") = "YARNSALEORDER" Then
                        Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE YARNSALEORDER_DESC SET YSO_CLOSED = 0 WHERE YSO_NO = " & Val(DTROW("SONO")) & " AND YSO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND YSO_YEARID = " & YearId, "", "")
                    ElseIf DTROW("TYPE") = "OPENINGYARNSALEORDER" Then
                        Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE OPENINGYARNSALEORDER_DESC SET OYSO_CLOSED = 0 WHERE OYSO_NO = " & Val(DTROW("SONO")) & " AND OYSO_GRIDSRNO = " & Val(DTROW("GRIDSRNO")) & " AND OYSO_YEARID = " & YearId, "", "")
                    End If
                End If

            Next
            fillgrid()
            gridbill.Focus()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CMDREFRESH_Click(sender As Object, e As EventArgs) Handles CMDREFRESH.Click
        Try
            fillgrid()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_RowStyle(ByVal sender As Object, ByVal e As DevExpress.XtraGrid.Views.Grid.RowStyleEventArgs) Handles gridbill.RowStyle
        Try
            If e.RowHandle >= 0 Then
                Dim View As GridView = sender
                If View.GetRowCellDisplayText(e.RowHandle, View.Columns("CLOSED")) = "Checked" Then
                    e.Appearance.Font = New System.Drawing.Font("CALIBRI", 9.0F, System.Drawing.FontStyle.Bold)
                    e.Appearance.BackColor = Color.Yellow
                End If
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub PrintToolStripButton_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles PrintToolStripButton.Click
        Try

            Dim PATH As String = Application.StartupPath & "\Sale Order Details.XLS"
            Dim opti As New DevExpress.XtraPrinting.XlsExportOptions
            opti.ShowGridLines = True
            opti.SheetName = "Sale Order Details"
            gridbill.ExportToXls(PATH, opti)
            EXCELCMPHEADER(PATH, "Sale Order Details", gridbill.VisibleColumns.Count + gridbill.GroupCount)
        Catch ex As Exception
            MsgBox("Sale Order Details Excel File is Open, Please Close the File first then try to Export", MsgBoxStyle.Critical)
        End Try
    End Sub

    Private Sub CHKSELECTALL_CheckedChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CHKSELECTALL.CheckedChanged
        Try
            If gridbilldetails.Visible = True Then
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    dtrow("CLOSED") = CHKSELECTALL.Checked
                Next
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

End Class